### PR TITLE
fix: hover state on compact messages

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
That's fucking amazing! I blame QT for having bad docs and never showing us that this existed.

Can you do the same for text links also?

**Comment by richard-ramos** [comment]
Yes

**Comment by simonricoo** [comment]
What a hero @richard-ramos 🚀

**Comment by simonricoo** [comment]
@jrainville @richard-ramos Maybe its a right time to do the hover states on mentions and pin messages 🙈🙏?
Screenshot 2021-02-10 at 09 51 45
Mentions: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4024%3A0


Screenshot 2021-02-10 at 09 53 55
Pinn messages: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4140%3A40238

**Comment by jrainville** [comment]
> Maybe its a right time to do the hover states on mentions and pin messages 🙈🙏?

Yeah mentions should work with this new component. Pinned messages still don't exist but when they do, we'll know what to do

**Pull request merged**
