### PR TITLE
chore: update for StoreNodeRequestManager

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-desktop/issues/12537
status-go PR: https://github.com/status-im/status-go/pull/4446

This status-go update contains refactoring of fetching communities.
I made quick tests of where we fetch communities in status-desltop:
- Import community (with public key)
- Link previews

Would be nice to test other places if we have any. E.g. community directory, but I couldn't get any curated communities.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@lukaszso @glitchminer pls take a look

**Review by lukaszso — APPROVED** [review]
I've tested fetching communities today quite extensively, it works fine. I've focuses mainly on macOS version but tried on Windows as well. LGTM.

**Comment by igor-sirotin** [comment]
It seems that requesting contact info got broken in desktop.
It shouldn't be related to this PR, but could be. Will check later.

`https://status.app/u/iwaACgwKCkFuYXN0YXNpeWED#zQ3shUXHvwL91dmgCzhZGMbTsSaW35B8u16Avq9aJaBSRjNua`


image


```nim
DBG 2023-12-20 23:08:31.555+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=817276 file=core.nim:27 rpc_method=wakuext_requestContactInfoFromMailserver
DBG 2023-12-20 23:08:31.674+00:00 asyncContactInfoLoaded                     topics="contacts-service" tid=817253 file=service.nim:790 pubkeyAndRpcResponse="{\"publicKey\":\"0x0469ac47d3e00e3563b5c09ff25f6d4f07cbea91ae71aa50c3f782b2dfce05548d8ab888d82f142cc4e8369474af043512d9caf6f62355be13176776ed36c13856\",\"response\":{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":0,\"error\":null},\"error\":null}"
ERR 2023-12-20 23:08:31.674+00:00 error colorIdOf:                           tid=817253 file=service.nim:39 errDescription="invalid pubkey: "
ERR 2023-12-20 23:08:31.674+00:00 error colorHashOf:                         tid=817253 file=service.nim:26 errDescription="invalid pubkey: "

```

**Review by caybro — APPROVED** [review]
LGTM for all I can judge :)

**Comment by igor-sirotin** [comment]
> It seems that requesting contact info got broken in desktop.

ok it doesn't matter. status-go is updated anyway already, and I'm not even sure if it's related.
Will not hold these fixes.

**Pull request merged**
