### PR TITLE
[#2813] Updating chat layout

### LINKED ISSUE #2813: implement design for user list
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=2431%3A28468

### PR DESCRIPTION
**Pull request by alexandraB99**
Switched to StatusAppThreePanelLayout as per new
design for members list

Depends on https://github.com/status-im/StatusQ/pull/283

Closes #2813

### CODE REVIEW

**Comment by alexandraB99** [comment]
Please consider also merging this [this](https://github.com/status-im/StatusQ/pull/293)

**Review by iurimatias — CHANGES_REQUESTED** [review]
Hi @alexandraB99 ,

I see a bunch of issues in this branch with the layout, note that I did locally rebase and point to the latest statusQ etc.. but still I see these issues so I assume it's specific to this branch:

issue 1 - the content in the main chat in window is out of bounds

Screen Shot 2021-07-23 at 4 20 08 PM

issue 2 - the sidebar should have a limit on how much it can be resized

Screen Shot 2021-07-23 at 4 20 29 PM

Screen Shot 2021-07-23 at 4 21 01 PM

issue 3 - the user list needs to either have a minimum width or have some nice fallback

Screen Shot 2021-07-23 at 4 21 50 PM

for e.g it would be cool if we resized to the minimum it would 'snap' and look something like this

Screen Shot 2021-07-01 at 4 49 27 PM

**Comment by alexandraB99** [comment]
Tnanks @iurimatias for your findings! All issues should be fixed now, please re-check. Depends on https://github.com/status-im/StatusQ/pull/296.

**Review by iurimatias — CHANGES_REQUESTED** [review]
in the latest, the sidebar has min and max width issues, see screenshots

Screen Shot 2021-07-26 at 12 43 55 PM
Screen Shot 2021-07-26 at 12 43 48 PM

**Comment by alexandraB99** [comment]
> in the latest, the sidebar has min and max width issues, see screenshots
> 
> Screen Shot 2021-07-26 at 12 43 55 PM
> Screen Shot 2021-07-26 at 12 43 48 PM

@iurimatias this is fixed [here](https://github.com/status-im/StatusQ/pull/297), could you make sure you have the latest StatusQ?

**Comment by iurimatias** [comment]
@alexandraB99 the min width is now fixed, however we should also enforce a lower max-width or not allow it at all in a different PR/change

**Pull request merged**
