### PR TITLE
chore: Consolidate date/time formatting

### LINKED ISSUE #7230: Consolidate date/time formatting
# Bug Report

## Description

Currently, in a lot of places, datetime  formatting is broken. 

Most of the formatting functions reside in `ui/imports/utils/Utils.qml`. Introduce a new module, `LocaleUtils.qml`, extract the relevant methods from `Utils.qml` and fix them, taking into account default values coming from QML `Locale` and `Date` objects. Options like short/long date formats and 12/24 hour format should be preserved.

- Status desktop version: All
- Operating System: All

### PR DESCRIPTION
**Pull request by caybro**
- simplify locale settings
- extract/fix datetime related functions into LocaleUtils
- port code to the new LocaleUtils, move it to StatusQ.Core
- cleanup dead code (separate commit)

Closes #7230

### What does the PR do

Fixes incorrect/inconsistent date/time formatting

### TODO
- ~~enforce 12/24hr time format~~
- ~~move from Utils to StatusQ.DateTimeUtils? (to be able to format stuff in StatusQ)~~
- ~~figure out the performance penalty between calls to `Date().toLocale(Date/Time)String()` and `Qt.formatDate(Time)`~~ (after Qt 5.15)
  - the former is preferred, API stable but seems slower
  - the latter is faster but its API changed in Qt 5.15 and completely removed in Qt 6 :/

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Formatting timestamps:
image

Locale settings panel:
image

Wallet/token chart (with properly formatted date in x axis):
image

Correct search results timestamps:
image

Fixed gaps/fetch more timestamps:
image

### CODE REVIEW

**Comment by caybro** [comment]
Still a WIP/draft but I'd like to hear some early opinions on this, esp. the points that I outlined in the `TODO` section of the PR description. TIA :)

**Comment by caybro** [comment]
> Actually I have a question here, which always bothered me. We have 2 settings in the app:
> 
> * Language
> * Time format
> 
> But time format is never corresponding to the chosen language, instead it's synced with OS locale. It's easily seen in your screenshots. Timestamps are in Czech (I guess), but the app is in English.
> 
> And Discord does it the right way slightly_smiling_face

That is desired; locale is not the same as (translation) language.

**Comment by alexjba** [comment]
Looks like a good direction to me! Great work!
Having the date/time formatting consolidated in a single place will enable us to easily improve it even more if needed. 👍

> figure out the performance penalty between calls to Date().toLocale(Date/Time)String() and Qt.formatDate(Time)
the former is preferred, API stable but seems slower
the latter is faster but its API changed in Qt 5.15 and completely removed in Qt 6 :/

I guess we can use it once we migrate to Qt5.15 and in Qt6 we could look into the c++ API.

**Comment by caybro** [comment]
This is good to go from my POV :) Please review

@dlipicar just a heads up, I have moved LocaleUtils to StatusQ.Core (to be able to apply the datetime formats in StatusQ itself too)

**Review by osmaczko — APPROVED** [review]
Looks good :watch: :date:

**Review by alexjba — APPROVED** [review]
LGTM!

**Review by dlipicar — APPROVED** [review]

**Pull request merged**
