### PR TITLE
fix(Wallet): prevent signing phrase from leaking out of modal

### PR DESCRIPTION
**Pull request by PascalPrecht**
This is what it looks like right now:
Screenshot 2021-03-25 at 10 23 08

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good. 

Could you next time either add a screenshot of the final result also (or just the final result)? I got confused because it seemed like you screenshot was for your fix, which was obviously bad haha.
It also helps for QA. For simple fixes like this, we can see in a screenshot that it's ok now and not have to download the build

**Comment by iurimatias** [comment]
I can't replicate this in master, is there a specific situation that causes this?

**Comment by PascalPrecht** [comment]
@iurimatias no specific scenario, just head over to the wallet and have it render the signing phrase modal.
I just checked, it's still reproducible on latest `master`

**Comment by jrainville** [comment]
I assume it depends on the resolution and the size of the App window

**Pull request merged**
