### PR TITLE
fleets.json: drop decomissioned eth.test fleet

### PR DESCRIPTION
**Pull request by jakubgs**
The fleet wasn't being used so it has been liquidated: https://github.com/status-im/infra-eth-cluster/commit/de986014
This will also drop the earlier decomissiond `waku.connect` fleet.

Also I've unified keys for connection types to be `*/p2p/waku`: https://github.com/status-im/infra-misc/commit/66e1dabb

### CODE REVIEW

**Review by mprakhov — APPROVED** [review]
LGTM

**Comment by jakubgs** [comment]
@richard-ramos oh you're right, I missed that. Fixed. Also turns out the `Makefile` was updating `fleets.json` but what was being used was `resources/fleets.json`. Someone moved it there but didn't update the `Makefile`.

**Comment by jakubgs** [comment]
Wait, what the hell is happening here?
https://github.com/status-im/status-desktop/blob/1b81490c552154d49272c63119f4bf532aecf7c8/src/nim_status_client.nim#L23-L24
What is this supposed to be?

**Comment by caybro** [comment]
> Wait, what the hell is happening here?
> 
> https://github.com/status-im/status-desktop/blob/1b81490c552154d49272c63119f4bf532aecf7c8/src/nim_status_client.nim#L23-L24
> 
> 
> What is this supposed to be?

Ugh :D This should use "qrc:/"

**Review by richard-ramos — APPROVED** [review]

**Comment by jakubgs** [comment]
This probably isn't the right way to do this, but whatever, someone can fix that later:
https://github.com/status-im/status-desktop/blob/84c68a3224865165c66a6877a612c32adbd06253/src/nim_status_client.nim#L23-L24
Or suggest how to do it better in this PR.

**Comment by caybro** [comment]
> This probably isn't the right way to do this, but whatever, someone can fix that later:
> 
> https://github.com/status-im/status-desktop/blob/84c68a3224865165c66a6877a612c32adbd06253/src/nim_status_client.nim#L23-L24
> 
> 
> Or suggest how to do it better in this PR.

As I said, I _think_ this should use the "qrc:/" system (also elsewhere in this file where we make a fishy distinction between a "windows release build" and "otherwise"; wdyt @jrainville ?

**Comment by jakubgs** [comment]
I have no clue what `qrc:/` is and how it works.

**Comment by jakubgs** [comment]
My "fix" doesn't work:
```
StatusIm-Desktop-221209-133558-84c68a-pr8705.AppImage is now installed in /home/jakubgs/.cache/appimage-run/80a6eb5b21f88620857ca1952c6efb67782476c3c705dc3c4c9038b7a546dd6e
/home/jenkins/workspace/s-desktop_branches_linux_PR-8705/src/nim_status_client.nim(181) nim_status_client
/home/jenkins/workspace/s-desktop_branches_linux_PR-8705/src/nim_status_client.nim(93) mainProc
/home/jenkins/workspace/s-desktop_branches_linux_PR-8705/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(693) readFile
Error: unhandled exception: cannot open: /home/jakubgs/.cache/appimage-run/80a6eb5b21f88620857ca1952c6efb67782476c3c705dc3c4c9038b7a546dd6e/usr/resources/fleets.json [IOError]
```
It's looking under `usr/resources/fleets.json`...

**Comment by jakubgs** [comment]
Honestly, I don't get why there's so many code changes necessary when we are parsing a JSON file. This should just work without any code changes.

**Comment by caybro** [comment]
> Honestly, I don't get why there's so many code changes necessary when we are parsing a JSON file. This should just work without any code changes.

We have `${SRCDIR}/fleets.json` but also `${SRCDIR}/resources/fleets.json`... dunno why it's duplicated

**Comment by jakubgs** [comment]
My understanding is that CPP was using the one under `resources`, but now I'm not so sure. It's quite messy.

I might not the time to finish this today. So either someone could fix this for me, which I'd appreciate, or it will wait till January.

**Comment by caybro** [comment]
> My "fix" doesn't work:
> 
> ```
> StatusIm-Desktop-221209-133558-84c68a-pr8705.AppImage is now installed in /home/jakubgs/.cache/appimage-run/80a6eb5b21f88620857ca1952c6efb67782476c3c705dc3c4c9038b7a546dd6e
> /home/jenkins/workspace/s-desktop_branches_linux_PR-8705/src/nim_status_client.nim(181) nim_status_client
> /home/jenkins/workspace/s-desktop_branches_linux_PR-8705/src/nim_status_client.nim(93) mainProc
> /home/jenkins/workspace/s-desktop_branches_linux_PR-8705/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(693) readFile
> Error: unhandled exception: cannot open: /home/jakubgs/.cache/appimage-run/80a6eb5b21f88620857ca1952c6efb67782476c3c705dc3c4c9038b7a546dd6e/usr/resources/fleets.json [IOError]
> ```
> 
> It's looking under `usr/resources/fleets.json`...

Makefile:
cp -R $(FLEETS) tmp/linux/dist/usr/.

**Comment by caybro** [comment]
> proc determineFleetsPath(): string = 
>    result = if defined(windows) and defined(production): "/../resources/fleets.json" else: "/../fleets.json"

As a result of:
```nim
proc determineFleetsPath(): string = 
   result = if defined(windows) and defined(production): "/../resources/fleets.json" else: "/../fleets.json"
```

But how could it ever have worked under Linux/AppImage... no idea :) @jrainville

**Comment by jakubgs** [comment]
Yes, I've seen that:
https://github.com/status-im/status-desktop/blob/1b81490c552154d49272c63119f4bf532aecf7c8/Makefile#L432
But the thing is if the file is under `resources` then it has to be under `resources` in the AppImage too, or you have to have some logic, because otherwise the nim binary by itself won't work.

**Pull request merged**
