### PR TITLE
fix: `LinkPreview` to json conversion

### PR DESCRIPTION
**Pull request by osmaczko**
fixes: #14731

https://github.com/status-im/status-desktop/assets/33099791/d363e969-a9e2-4f5d-973e-57786308a99c

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by osmaczko** [comment]
@anastasiyaig e2e tests seems to be failing but I can't see any correlation with my changes, cold you please take a look?

**Comment by anastasiyaig** [comment]
@antdanchenko @Valentina1133 please

**Comment by jrainville** [comment]
@osmaczko I now realize you pushed those in 2.28. It wasn't fully necessary, but I guess, might as well.

The e2e fails all the time on this branch because it's very off from the current tests. We can just ignore

**Comment by anastasiyaig** [comment]
ah yeah, the base branch is release, okay, we cant make tests work in prs this way just now. We gonna move tests to main repo back that should solve this. For now - force merge to release branch

**Comment by jrainville** [comment]
> Are we planning to release a 2.28.2?

We were thinking about it, because Iuri was stuck on some operations. I guess fixing such a crash is a good candidate to make it in

**Pull request merged**
