### PR TITLE
feat(deeplinks): Open user profile or chat if user is contact

### PR DESCRIPTION
**Pull request by borismelnik**
Fixes: #10892

### What does the PR do

Open user profile or chat if user is contact

### Affected areas

Deeplinks

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks goo.d Why is it marked as do not merge?

**Comment by borismelnik** [comment]
> Looks goo.d Why is it marked as do not merge?

I was planning to test build from CI :)

**Review by endulab — CHANGES_REQUESTED** [review]

**Review by MishkaRogachev — APPROVED** [review]
Looks good!

**Review by jrainville — APPROVED** [review]

**Comment by glitchminer** [comment]
@borismelnik, is it expected to behave as if user is non-mutual contact when the contact is blocked?

**Comment by borismelnik** [comment]
> @borismelnik, is it expected to behave as if user is non-mutual contact when the contact is blocked?

I don't remember any special instructions about this case, but I think yes :)

**Comment by glitchminer** [comment]
OK, thanks. I just wondered because it's not useful if a user is trying to reach a chat with a previously blocked user. Otherwise it's OK, checked regular key & ENS.

**Comment by borismelnik** [comment]
@endulab by some reasons, I can't request your review :)

**Review by endulab — APPROVED** [review]

**Pull request merged**
