### PR TITLE
feat: Change optimism network short name

### PR DESCRIPTION
**Pull request by Cuteivist**
Closes https://github.com/status-im/status-desktop/issues/14720

Status-go PR: https://github.com/status-im/status-go/pull/5163

### What does the PR do

* Changed Mainnet and Sepolia Optimism short name from `opt` to `oeth`
* Changed Mainnet and Sepolia Arbritrum short name from `arb` to `arb1`

### Affected areas

Wallet

#### Mainnet

image

#### Testnet

image

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]
👍

**Comment by saledjenic** [comment]
On this link https://chainid.network/chains_mini.json I see that apart from the change `opt` to `oeth` we should make the following changes if we want to align:
for mainnet: 
`arb` -> `arb1`

for sepolia: 
`opt` -> `opsep` 
`arb` -> `arb-sep`

@xAlisher could you confirm this?

**Comment by xAlisher** [comment]
> On this link https://chainid.network/chains_mini.json I see that apart from the change `opt` to `oeth` we should make the following changes if we want to align: for mainnet: `arb` -> `arb1`
> 
> for sepolia: `opt` -> `opsep` `arb` -> `arb-sep`
> 
> @xAlisher could you confirm this?

Thanks @saledjenic for bringing this up.

I can confirm about arb1.  We aware of it, and already using this prefix on mobile thanks to @mariocnovoa. I believe @benjthayer also has it  to-do list.

But I'm not sure about testnets. Should we change our QRs and addresses prefixes when user switches to testnets? We never discussed that. I need to check it with team.

**Comment by benjthayer** [comment]
> I can confirm about arb1. We aware of it, and already using this prefix on mobile thanks to @mariocnovoa. I believe @benjthayer has it on his to-do list too.


Yes - on my to do list both opt -> oeth and arb -> arb1
Agree we need to maybe discuss testnet changes further before rolling out

**Comment by xAlisher** [comment]
@saledjenic @benjthayer I'm going to design options to handle address QRs and router behavior for testnets and let you know!

**Review by saledjenic — CHANGES_REQUESTED** [review]
@Cuteivist could you please handle `arb` to `arb1` within this issue as well?
At the end to be:
`opt` -> `oeth`
`arb` -> `arb1` 

for both mainnet and testnet mode (don't change it for the testnet mode).

Once designers prepare the design for the testnet mode we will do the similar change to handle that.

**Review by saledjenic — APPROVED** [review]

**Comment by xAlisher** [comment]
@saledjenic 

Confirmed with John, we'll not support testnets in QRs

**Pull request merged**
