### PR TITLE
Various token minting UI fixes

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

Three tiny commits covering:
- Fixes: https://github.com/status-im/status-desktop/issues/11122
- Fixes: https://github.com/status-im/status-desktop/issues/11190
- Fixes: https://github.com/status-im/status-desktop/issues/11187

### Affected areas

CommunityNewTokenView

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

[Záznam obrazovky z 2023-06-22 10-41-23.webm](https://github.com/status-im/status-desktop/assets/5377645/c8e791cb-2eab-4a7f-bbfe-1c88674ac615)

### CODE REVIEW

**Review by noeliaSD — COMMENTED** [review]
Tested!! Everything looks good but there is still a small detail:

- In total finite supply field, when entering long values it still switches to `-2147483648`:

https://github.com/status-im/status-desktop/assets/97019400/54dd1977-83ac-4578-815d-a8771f745f22

**Comment by caybro** [comment]
> Tested!! Everything looks good but there is still a small detail:
> 
> * In total finite supply field, when entering long values it still switches to `-2147483648`:
> 
>  Screen.Recording.2023-06-22.at.11.17.55.mov

I see; will have a look, thanks!

**Comment by caybro** [comment]
> > Tested!! Everything looks good but there is still a small detail:
> > 
> > * In total finite supply field, when entering long values it still switches to `-2147483648`:
> > 
> 
> I see; will have a look, thanks!

@noeliaSD fixed, pls have a second look

**Review by noeliaSD — APPROVED** [review]
Tested! It works fine now :partying_face: !!

**Review by alexandraB99 — APPROVED** [review]

**Pull request merged**
