### PR TITLE
feat(utils): Adding Tracer component

### PR DESCRIPTION
**Pull request by alexandraB99**
### What does the PR do
Adding Tracer component: Used to help determine UI components position and dimensions. Example photo attached

### Affected areas
utilities

### Screenshot of functionality (including design for comparison)
e

### CODE REVIEW

**Review by caybro — APPROVED** [review]
Cool stuff but I think this could go to StatusQ so that we could use it already in the Sandbox app for quick testing

**Comment by alexandraB99** [comment]
> Cool stuff but I think this could go to StatusQ so that we could use it already in the Sandbox app for quick testing

hmm yes! however in that case to use in desktop we'd need to import StatusQ Utils, meanwhile dekstop's utils is imported in almost every file already.  So we can:
1) add it in StatusQ as well
2) add it only in StatusQ and import StatusQ utils wherever we want to use it
3) add it only in desktop

**Review by micieslak — APPROVED** [review]
cool&simple :)

**Comment by noeliaSD** [comment]
> > Cool stuff but I think this could go to StatusQ so that we could use it already in the Sandbox app for quick testing
> 
> hmm yes! however in that case to use in desktop we'd need to import StatusQ Utils, meanwhile dekstop's utils is imported in almost every file already. So we can:
> 
> 1. add it in StatusQ as well
> 2. add it only in StatusQ and import StatusQ utils wherever we want to use it
> 3. add it only in desktop

Thanks for this addition :)
I'd suggest your second option, to add only in `StatusQ` an import it wherever needed.

**Review by noeliaSD — APPROVED** [review]

**Pull request merged**
