### PR TITLE
Tmp: bump status-go and logs and members fix

### PR DESCRIPTION
**Pull request by MishkaRogachev**
For #12114

status-go PR: https://github.com/status-im/status-go/pull/4026

### CODE REVIEW

**Comment by caybro** [comment]
FWIW, tried this and it doesn't fix the problem for me in master

**Comment by caybro** [comment]
```
------> fixupChannelMembers for community:  Test w/o icon
------> populateChatWithAllMembers:: general , members:  0
------> fixupChannelMembers for community:  Wednesday
------> populateChatWithAllMembers:: astral , members:  0
------> populateChatWithAllMembers:: test-paste , members:  0
------> populateChatWithAllMembers:: plus-sign-in-filename , members:  0
------> populateChatWithAllMembers:: syntax-highlighter-test , members:  0
------> populateChatWithAllMembers:: test2 , members:  0
------> populateChatWithAllMembers:: general , members:  0
------> populateChatWithAllMembers:: test-inline-emojis , members:  0
------> populateChatWithAllMembers:: emoji-test , members:  0
------> populateChatWithAllMembers:: chat-reactions , members:  0
------> populateChatWithAllMembers:: deep-link-test-fooo , members:  0
------> populateChatWithAllMembers:: test-channel , members:  0
------> fixupChannelMembers for community:  Test without icon
------> populateChatWithAllMembers:: general , members:  0
------> fixupChannelMembers for community:  Test com
------> populateChatWithAllMembers:: general , members:  0
------> fixupChannelMembers for community:  caytest
------> populateChatWithAllMembers:: test-channel , members:  1
------> populateChatWithAllMembers:: general , members:  1
```

@richard-ramos @MishkaRogachev  what's interesting is that it doesn't print _anything_ for the Status CC

**Comment by caybro** [comment]
This channel

image

yields:
```
------> toAPIChat:: random , members:  5
...
------> handleCommunityDescription:: random , members:  5
```

**Comment by MishkaRogachev** [comment]
> @richard-ramos @MishkaRogachev what's interesting is that it doesn't print _anything_ for the Status CC

Yes, the current issue we can't receive CommunityDescription from Status CCs. Probably it's being cased by [this](https://github.com/status-im/status-desktop/issues/12114#issuecomment-1721030001), however we should check message's size on the control node side. 

> FWIW, tried this and it doesn't fix the problem for me in master

And most likely when we fix the issue, clients will receive valid community description after the control node will get updated. We are also waiting for @osmaczko  from vacation, do discuss how we can decompose CommunityDescription message (or just leave chat members empty if channel has no permissions)

**Pull request closed without merging**
