### PR TITLE
fix(@desktop/activity-center): mentions and replies in the activity centre does not display community icon

### LINKED ISSUE #5302: Mentions & Replies in the Activity Centre does not display community icon
# Bug Report

## Description

- Mentions tab in the Activity Centre _does not_ display community icon.

image

- Replies tab in the Activity Centre _does not_ display what community the replies are in.

image

#### Expected behavior
The community icon and community must visible on all notifications

### Additional Information

- Status desktop version: Master : e26befb6c26141529a5c4263bc8b26aa7c27e042

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #5302

### CODE REVIEW

**Review by borismelnik — APPROVED** [review]

**Review by stefandunca — APPROVED** [review]
It looks good. Didn't test it, though.

**Comment by abhi-status** [comment]
@saledjenic I am not able to see the community/channel icons. 
The icons in the Activity centre are currently all black and shown with the text "Channel name"

image

**Comment by saledjenic** [comment]
> @saledjenic I am not able to see the community/channel icons.
The icons in the Activity centre are currently all black and shown with the text "Channel name"

@abhi-status good catch, that's only happening if you have the activity center opened when new mention comes. Fixed. Thank you.

**Comment by abhi-status** [comment]
The display of Community badges (on `@` mentions) work on Ubuntu and based on talks with Sale, this works as expected on Mac as well.

On Windows, the Community badges display correctly only after a reboot. [This will be handled separately on another ticket]
Currently, Replies dont have a badge. [This will be handled on another ticket]

**Review by abhi-status — APPROVED** [review]

**Comment by saledjenic** [comment]
> On Windows, the Community badges display correctly only after a reboot. 

@abhi-status changes done here shouldn't be platform dependant. In this [video](https://drive.google.com/file/d/1Hq6NY-Ie4A81JPQ8e9nXhA3-Mp7cS_q8/view?usp=sharing) you can see behavior on my side, though recorded on Mac.

**Pull request merged**
