### PR TITLE
feat(community): add notification setting to community

### LINKED ISSUE #2421: Notifications option is not implemented for Communities
Снимок экрана 2021-04-23 в 17 14 47

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #2421

When the Notification setting is unchecked, you don't receive OS notifications for new messages

~~Do not merge until the status go is merged: https://github.com/status-im/status-go/pull/2271~~ Merged

### CODE REVIEW

**Comment by iurimatias** [comment]
@jrainville is this branch pointing to status-go master?

**Comment by anastasiyaig** [comment]
@jrainville seems that switching off the setting does not switch off the notifications , could u please help to check?


https://user-images.githubusercontent.com/82375995/124473139-9e4c2780-dda7-11eb-8d9c-858d40243258.mov

**Comment by jrainville** [comment]
> @jrainville is this branch pointing to status-go master?

Yes. The commit hash is: 11c46edd8b25bb6b313b71378f1b3ac842ad1908

**Comment by jrainville** [comment]
> @jrainville seems that switching off the setting does not switch off the notifications , could u please help to check?

Ah weird, I will for sure take a look

**Comment by jrainville** [comment]
@anastasiyaig I fixed it. The issue was that I didn't update the muted state in the community list, so the change only took effect once you closed and reopened the app. It now updates live.

**Review by richard-ramos — APPROVED** [review]

**Comment by anastasiyaig** [comment]
thank you for fixing this!

**Pull request merged**
