### PR TITLE
[#2650] Fixed pasting rich text in text box

### LINKED ISSUE #2650: copy pasting from another app results in a blank input in the text box
1. go to another app (for e.g discord) select multiple lines and copy
2. go to the app and paste in the input box

result:

### PR DESCRIPTION
**Pull request by alexandraB99**
[#2650] Fixed pasting rich text in text box

    * Text copied from clipboard that included images
      and other rich content was not visible in text
      box when pasted, modified to keep only plain
      text instead and removed unnecessary funtions
    * Also removed unecessary Rectangle in Input

    Closes #2650

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
Hi @alexandraB99 

I see two issues in this branch

The first issue is that the input boxes seem to have lost their style

Screen Shot 2021-07-15 at 11 31 14 AM


The second issue is that after pasting the text and sending the message, that message is not rendered in the client

Screen Shot 2021-07-15 at 10 36 52 AM

**Comment by alexandraB99** [comment]
> Hi @alexandraB99
> 
> I see two issues in this branch
> 
> The first issue is that the input boxes seem to have lost their style
> 
> Screen Shot 2021-07-15 at 11 31 14 AM
> 
> The second issue is that after pasting the text and sending the message, that message is not rendered in the client
> 
> Screen Shot 2021-07-15 at 10 36 52 AM

Thanks @iurimatias, brought back the style, I'll have a further look in the text not rendering issue

**Comment by alexandraB99** [comment]
@jrainville what is this function supposed to do: 
    ```
function getPlainText() {
        const textWithoutMention = messageInputField.text.replace(/<span style="[ :#0-9a-z;\-\.,\(\)]+">(@([a-z\.]+(\ ?[a-z]+\ ?[a-z]+)?))<\/span>/ig, "\[\[mention\]\]$1\[\[mention\]\]")
        const deparsedEmoji = Emoji.deparse(textWithoutMention);
        return chatsModel.plainText(deparsedEmoji);
    }
```

It is the one currently that breaks things when the copied text includes rich content (eg, image, emoji) etc. If I replace line 321:
`const plainText = getPlainText()`
with:
`const plainText = messageInputField.getFormattedText(0, messageInputField.length);`
it works. However I don't get the images rendered but I can see the text.

**Comment by jrainville** [comment]
> what is the use case of this function:

That was used back in the day to get the text back to the plain text, so that we could modify it and then parse it back again. 

When I did the code formation refactor, I removed the use of that function in multiple places, but it hasn't been done for the paste yet. If you change the paste to no longer use it anymore, it's great because doing that is not very good.

**Pull request merged**
