### PR TITLE
use new wallet api to receive wallet signals

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by jakubgs** [comment]
Looks like something with `DOtherSide` is broken:
```
09:03:32  cd /home/jenkins/workspace/s-desktop_branches_linux_PR-2315/vendor/DOtherSide/build/lib && /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -I/home/jenkins/workspace/s-desktop_branches_linux_PR-2315/vendor/DOtherSide/lib/include -I/home/jenkins/workspace/s-desktop_branches_linux_PR-2315/vendor/DOtherSide/lib/include/Qt -isystem /opt/qt/5.14.0/gcc_64/include -isystem /opt/qt/5.14.0/gcc_64/include/QtCore -isystem /opt/qt/5.14.0/gcc_64/./mkspecs/linux-g++ -isystem /opt/qt/5.14.0/gcc_64/include/QtGui -isystem /opt/qt/5.14.0/gcc_64/include/QtWidgets -isystem /opt/qt/5.14.0/gcc_64/include/QtQml -isystem /opt/qt/5.14.0/gcc_64/include/QtNetwork -isystem /opt/qt/5.14.0/gcc_64/include/QtQuick -isystem /opt/qt/5.14.0/gcc_64/include/QtQmlModels -isystem /opt/qt/5.14.0/gcc_64/include/QtQuickControls2  -O3 -DNDEBUG   -Wall -Wno-long-long -pedantic -fPIC -std=gnu++11 -o CMakeFiles/DOtherSideStatic.dir/src/DosQMetaObject.cpp.o -c /home/jenkins/workspace/s-desktop_branches_linux_PR-2315/vendor/DOtherSide/lib/src/DosQMetaObject.cpp
09:03:33  /home/jenkins/workspace/s-desktop_branches_linux_PR-2315/vendor/DOtherSide/lib/src/DOtherSide.cpp:1322:26: fatal error: DOtherSide.moc: No such file or directory
```

**Comment by anastasiyaig** [comment]
the PR looks good apart the known issue with sending transactions in chat https://github.com/status-im/status-desktop/issues/2533, however i tested this with simple dapp and assume no harm done to transactioning.

Not sure about the Linux artefact failure though @richard-ramos

**Comment by jakubgs** [comment]
Why was this merged while the CI builds were failing? @iurimatias ?

**Comment by richard-ramos** [comment]
Looks like all linux builds are failing

**Comment by richard-ramos** [comment]
(not only on this PR)

**Comment by jakubgs** [comment]
Well, isn't that fun.

**Comment by jakubgs** [comment]
https://github.com/status-im/status-desktop/issues/2579

**Pull request merged**
