### PR TITLE
Fetch community info from link

### LINKED ISSUE #2290: Call fetch on communities when getting a community link in chat
I added link unfurling for communities in this PR https://github.com/status-im/status-desktop/pull/2015, but it was missing the fact that if you don't know the community, it couldn't show anything.

So to remedy this, you just have to call the fetch function that was added in the Import PR https://github.com/status-im/status-desktop/pull/2208 and then you can display the unfurling

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #2290

When we find link in the chat and the community is not part of our list, we fetch it from the mailserver.
Since sometimes the mailserver is not ready at first, we use the event to fetch at the right time.

Then we get the signal from QML and show the unfurled data.

We might want a design for what do show during the loading.

Steps to test:
1. Login in account 1
2. Create a community
3. Click Invite and copy the invite link
4. Paste invite link in a chat where the second account can see it
5. Logout and login with account 2
6. Go in the channel where you can see the link
7. Wait a couple of seconds for the fetch to finish (will need a design)
8. Unfurling appears

### CODE REVIEW

**Comment by anastasiyaig** [comment]
Jakub is looking into failed Windows artifact

**Comment by anastasiyaig** [comment]
preview of communities is now shown when posted as a link:




@jrainville is it something broken in the PR? Send message button is not working now from user profile (but it was fixed in master some time ago by Eric and still works there):



`qrc:/app/AppLayouts/Chat/components/ProfilePopup.qml:341: Error: Cannot assign to non-existent property "currentIndex"`

**Comment by jakubgs** [comment]
By adding `V=5` I found this error:
```
C:\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.10240.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\jenkins\workspace\desktop_branches_windows_PR-2469\vendor\DOtherSide\build\CMakeFiles\3.18.4\VCTargetsPath.vcxproj]
```
Which might be related to me adding `Microsoft.VisualStudio.Component.Windows10SDK.10240` to the PS script:
https://github.com/status-im/status-desktop/blob/010b617da69ecf98a70b758bfca459573eb417dd/scripts/windows_build_setup.ps1#L45-L46

But I tried installing VisualStudio without `Microsoft.VisualStudio.Component.Windows10SDK.14393` but the same error happened.

**Comment by jakubgs** [comment]
Took the liberty of rebasing this branch.

**Comment by jakubgs** [comment]
This makes no sense, because `10.0.10240.0` is clearly installed:
```
PS C:\Users\admin> (Get-VSSetupInstance | Select-VSSetupInstance -Product *).packages | Where-Object {$_.Id -like "*Component*"} | Select-Object Id,Version | Sort-Object Id
                                                                                                                                                                            
Id                                                        Version
--                                                        -------
Microsoft.Component.MSBuild                               15.7.27520.0
Microsoft.Component.VC.Runtime.UCRTSDK                    15.6.27309.0
Microsoft.VisualStudio.Component.CoreBuildTools           15.6.27309.0
Microsoft.VisualStudio.Component.Roslyn.Compiler          15.6.27309.0
Microsoft.VisualStudio.Component.Static.Analysis.Tools    15.0.26208.0
Microsoft.VisualStudio.Component.VC.CoreBuildTools        15.8.27729.1
Microsoft.VisualStudio.Component.VC.Redist.14.Latest      15.6.27406.0
Microsoft.VisualStudio.Component.VC.Tools.x86.x64         15.8.27825.0
Microsoft.VisualStudio.Component.Windows10SDK             15.6.27406.0
Microsoft.VisualStudio.Component.Windows10SDK.10240       15.6.27406.0
Microsoft.VisualStudio.Component.Windows81SDK             15.6.27406.0
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 15.6.27406.0
```

**Comment by jrainville** [comment]
> @jrainville is it something broken in the PR? Send message button is not working now from user profile (but it was fixed in master some time ago by Eric and still works there):

The PR was based on a commit that was before the fix Eric landed. Now that Jakub rebased, the Send message should work as expected

**Comment by anastasiyaig** [comment]
Right, i did not realize that since the build was quite fresh so did not require rebase. Thank you for looking into it @jrainville , lets merge it

**Pull request merged**
