### PR TITLE
feat(@wallet): add pokt network + fallbak

### LINKED ISSUE #9137: Switch from Infura to Pokt
Ensure that all network we supports are also supported by pokt and change the URL

### PR DESCRIPTION
**Pull request by alaibe**
Status-go: https://github.com/status-im/status-go/pull/3204

fixes #9137

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
it works to me: 
- i was able to build the app with POKT_TOKEN flag locally
- balances are fine
- transactioning is fine

**Review by anastasiyaig — APPROVED** [review]

**Comment by jakubgs** [comment]
There you go. You can try using the branch name instead of the version tag in Jenkinsfiles:

* https://github.com/status-im/status-jenkins-lib/pull/58

**Comment by alaibe** [comment]
@jakubgs  did i do something wrong:
```
[2023-02-26T09:18:18.420Z] Using POKT token: devel

Could not find credentials entry with ID 'pokt-devel-token'
```

**Comment by jakubgs** [comment]
Ah no, that's my mistake. I created the credentials only on the release CI instance, and not on the develop one.

Should work now.

**Comment by alaibe** [comment]
It worked, you can merge yours, I ll update mine

**Comment by jakubgs** [comment]
I have merged the PR and tagged the commit with `v1.6.8`, please use it.

**Comment by jakubgs** [comment]
Pretty sure "fallbark" isn't a word :D.

**Pull request merged**
