### PR TITLE
fix(@desktop/community) adjust Image Upload popup

### LINKED ISSUE #6835: Image upload slider differs from the Design
# Bug Report

## Steps to reproduce
1. Go to change profile image or community image, or group chat image
2. Check the image upload slider according to the [Design](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2563%3A524846)

#### Expected behavior
image

#### Actual behavior
1. The space between the image and slider differs from the Design
2. The space between the slider and zoom buttons is different
3. The zoom buttons differ from the Design by size and color
4. The text of the button for Community logo modal differs from the Design
image

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/6811
- Operating System: macOS Monterey

### PR DESCRIPTION
**Pull request by faust4exe**
Fixes #6835

Requires https://github.com/status-im/StatusQ/pull/839
Requires https://github.com/status-im/StatusQ/pull/848

### What does the PR do

Adjust ImageUpload popup and use updated StatusQ version

### Affected areas

Desktop Community

### Screenshot of functionality (including design for comparison)

- [X] I've checked the design and this PR matches it

Screenshot from 2022-08-10 13-01-25

### CODE REVIEW

**Review by caybro — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Review by elina2015 — CHANGES_REQUESTED** [review]
@faust4exe hey, I tested adding a new Profile image and Community image and it doesn't work. Could you kindly check?

https://user-images.githubusercontent.com/14942081/183559286-6a8580ca-54b0-4bc9-acf2-f86c072aad6d.mov
https://user-images.githubusercontent.com/14942081/183559335-f28a18ea-49eb-4831-8397-e729cdb37c16.mov

**Comment by faust4exe** [comment]
> @faust4exe hey, I tested adding a new Profile image and Community image and it doesn't work. Could you kindly check?
> 
> https://user-images.githubusercontent.com/14942081/183559286-6a8580ca-54b0-4bc9-acf2-f86c072aad6d.mov https://user-images.githubusercontent.com/14942081/183559335-f28a18ea-49eb-4831-8397-e729cdb37c16.mov

It was related to a regression in used FileDialog version - you should see some errors in logs.

@elina2015 Please retest - now should be working as expected.

**Review by elina2015 — CHANGES_REQUESTED** [review]
@faust4exe thank you very much for the fixes! There are just a few issues:
1. New user added a profile pic, but it's not saved and it's not shown on the profile modal
2. The zoom buttons are placed wrongly
3. The text of the button for the Community logo is a little bit different from the Design:
image
Could you kindly check?

**Comment by faust4exe** [comment]
> @faust4exe thank you very much for the fixes! There are just a few issues:
> 
>     1. The zoom buttons are placed wrongly
> 
>     2. The text of the button for the Community logo is a little bit different from the Design:
> 
> 
> image
> Could you kindly check?

Regarding text of the button
Please check your original image from Issue and my image from PR where we have the Design image.
Also looking here one of screen is wrong.
Screenshot from 2022-08-10 10-46-42

**Review by richard-ramos — APPROVED** [review]

**Review by elina2015 — APPROVED** [review]
Tested and approved

**Pull request merged**
