### PR TITLE
fix(Utils): Sanitize string representing amount

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

Fixes displaying fee amounts by sanitizing amount string.

Closes: #11929

### Affected areas
`LocaleUtils`

### Screenshot of functionality (including design for comparison)

Screenshot from 2023-08-17 17-26-15

### CODE REVIEW

**Review by caybro — COMMENTED** [review]
Hmm no, not sure at all this is the right place to fix it as it will not work when the Label/Text element is set to PlainText

**Comment by caybro** [comment]
I suggest using `Utils.escapeHtml(possibleRichText)` instead

**Comment by micieslak** [comment]
> I suggest using `Utils.escapeHtml(possibleRichText)` instead at the place where the function is used

For default `textFormat` (`AutoText`) both versions will work. But yeah, for `PlainText` it won't work properly and I agree that the ideal solution is to escape whenever we know that we are using rich/styled text. On the other hand it hurts to introduce dependency on nim backend (which just calls `QString::toHtmlEscaped()` into pure UI component like `FeeRow` and break all storybook pages where it's used...

To do it better, my proposition is to create a task for moving method `escapeHtml` (and some other similar functions) from nim to `StatusQ` as direct C++ implementation, skipping unnecessary nim layer, leaving `currencyAmountToLocaleString` unescaped as you suggest, and for now use local, backend-independent version of `escapeHtml` defined in `FeeRow` as implementation detail, e.g.:

```
function escapeHtml(unsafe) {
    return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
}
```
Wdyt?

**Comment by caybro** [comment]
> > I suggest using `Utils.escapeHtml(possibleRichText)` instead at the place where the function is used
> 
> For default `textFormat` (`AutoText`) both versions will work. But yeah, for `PlainText` it won't work properly and I agree that the ideal solution is to escape whenever we know that we are using rich/styled text. On the other hand it hurts to introduce dependency on nim backend (which just calls `QString::toHtmlEscaped()` into pure UI component like `FeeRow` and break all storybook pages where it's used...
> 
> To do it better, my proposition is to create a task for moving method `escapeHtml` (and some other similar functions) from nim to `StatusQ` as direct C++ implementation, skipping unnecessary nim layer, leaving `currencyAmountToLocaleString` unescaped as you suggest, and for now use local, backend-independent version of `escapeHtml` defined in `FeeRow` as implementation detail, e.g.:
> 
> ```
> function escapeHtml(unsafe) {
>     return unsafe
>          .replace(/&/g, "&amp;")
>          .replace(/</g, "&lt;")
>          .replace(/>/g, "&gt;")
>          .replace(/"/g, "&quot;")
> }
> ```
> 
> @caybro , wdyt?

Yup, I agree and it's as simple as `QString::toHtmlEscaped()` :)

**Comment by caybro** [comment]
You don't even have to create a separate task for this; just do the C++ impl here and use it imo

**Review by caybro — APPROVED** [review]
LGTM

**Review by endulab — APPROVED** [review]

**Review by alexjba — APPROVED** [review]
LGTM!

**Pull request merged**
