### PR TITLE
fix(Albums): Fix extra count of messages for image albums

### PR DESCRIPTION
**Pull request by borismelnik**
Fixes: #9958

[status-go pr](https://github.com/status-im/status-go/pull/3345)

### What does the PR do

Skip extra count of new messages for image albums

### Affected areas

Chat

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

Снимок экрана 2023-03-24 в 20 41 36

### CODE REVIEW

**Review by MishkaRogachev — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@borismelnik it seems i cant create an account in this branch

Screenshot 2023-03-29 at 17 28 32

```
ERR 2023-03-29 17:28:26.124+03:00 login error                                topics="app-controller" tid=6661357 file=module.nim:419 methodName=onNodeLogin errDesription="failed to apply migrations: failed to apply status-go/protocol migrations: failed to migrate: no such column: album_id in line 0: CREATE TABLE IF NOT EXISTS chats (\n  id VARCHAR PRIMARY KEY ON CONFLICT REPLACE,\n  name VARCHAR NOT NULL,\n  color VARCHAR NOT NULL DEFAULT \'#a187d5\',\n  type INT NOT NULL,\n  active BOOLEAN NOT NULL DEFAULT TRUE,\n  timestamp INT NOT NULL,\n  deleted_at_clock_value INT NOT NULL DEFAULT 0,\n  public_key BLOB,\n  unviewed_message_count INT NOT NULL DEFAULT 0,\n  last_clock_value INT NOT NULL DEFAULT 0,\n  last_message BLOB,\n  members BLOB,\n  membership_updates BLOB\n);\n\nCREATE TABLE contacts (\n  id TEXT PRIMARY KEY ON CONFLICT REPLACE,\n  address TEXT NOT NULL,\n  name TEXT NOT NULL,\n  ens_verified BOOLEAN DEFAULT FALSE,\n  ens_verified_at INT NOT NULL DEFAULT 0,\n  alias TEXT NOT NULL,\n  identicon TEXT NOT NULL,\n  photo TEXT NOT NULL,\n  last_updated INT NOT NULL DEFAULT 0,\n  system_tags BLOB,\n  device_info BLOB,\n  tribute_to_talk TEXT NOT NULL\n);\n\n-- It\'s important that this table has rowid as we rely on it\n-- when implementing infinite-scroll.\nCREATE TABLE IF NOT EXISTS user_messages (\n    id VARCHAR PRIMARY KEY ON CONFLICT REPLACE,\n    whisper_timestamp INTEGER NOT NULL,\n    source TEXT NOT NULL,\n    destination BLOB,\n    text VARCHAR NOT NULL,\n    content_type INT NOT NULL,\n    username VARCHAR,\n    timestamp INT NOT NULL,\n    chat_id VARCHAR NOT NULL,\n    local_chat_id VARCHAR NOT NULL,\n    hide BOOLEAN DEFAULT FALSE,\n    response_to VARCHAR,\n    message_type INT,\n    clock_value INT NOT NULL,\n    seen BOOLEAN NOT NULL DEFAULT FALSE,\n    outgoing_status VARCHAR,\n    parsed_text BLOB,\n    raw_payload BLOB,\n    sticker_pack INT,\n    sticker_hash VARCHAR,\n    command_id VARCHAR,\n    command_value VARCHAR,\n    command_address VARCHAR,\n    command_from VARCHAR,\n    command_contract VARCHAR,\n    command_transaction_hash VARCHAR,\n    command_signature BLOB,\n    command_state INT\n);\n\nCREATE INDEX idx_album_id on user_messages(local_chat_id, album_id);\nCREATE INDEX idx_source ON user_messages(source);\nCREATE INDEX idx_search_by_chat_id ON  user_messages(\n    substr(\'0000000000000000000000000000000000000000000000000000000000000000\' || clock_value, -64, 64) || id, chat_id, hide\n);\n\nCREATE TABLE IF NOT EXISTS raw_messages (\n  id VARCHAR PRIMARY KEY ON CONFLICT REPLACE,\n  local_chat_id VARCHAR NOT NULL,\n  last_sent INT NOT NULL,\n  send_count INT NOT NULL,\n  sent BOOLEAN DEFAULT FALSE,\n  resend_automatically BOOLEAN DEFAULT FALSE,\n  message_type INT,\n  recipients BLOB,\n  payload BLOB);\n\nCREATE TABLE IF NOT EXISTS messenger_transactions_to_validate (\n  message_id VARCHAR,\n  command_id VARCHAR NOT NULL,\n  transaction_hash VARCHAR PRIMARY KEY,\n  retry_count INT,\n  first_seen INT,\n  signature BLOB NOT NULL,\n  to_validate BOOLEAN DEFAULT TRUE,\n  public_key BLOB);\n\nCREATE INDEX idx_messenger_transaction_to_validate ON  messenger_transactions_to_validate(to_validate);\n"
```
the same in autotests here: https://ci.status.im/job/status-desktop/job/branches/job/e2e/job/PR-10023/3/squishResults_230327_184231.764/server_230327_185137.649.log

**Comment by anastasiyaig** [comment]
oh my bad, i saw 2 approvals and assumed it is ready to be tested. If it is not the case - please lemme know so i can test it when it is time :)

**Comment by glitchminer** [comment]
Hi @borismelnik , what's the scope of this please? I'm seeing a message count of 1 in chat navigation, group chat badge, and system notification but still a count of 5 in activity centre.

image

**Comment by borismelnik** [comment]
@glitchminer try this version, I add the correct last unseen message detection if message include in album. It works for me.

**Review by jrainville — APPROVED** [review]

**Review by glitchminer — APPROVED** [review]
Thanks for the fixes @borismelnik. 
Tested, approved.

**Review by alaibe — APPROVED** [review]

**Pull request merged**
