### PR TITLE
fix: Increase keycard popup width

### PR DESCRIPTION
**Pull request by alexjba**
### What does the PR do
Closing #11335 

Increase the keycard popup with to predefined value.

### Affected areas
Keycard popup

### Screenshot of functionality (including design for comparison)
Screenshot 2023-07-06 at 16 56 44

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

**Review by caybro — APPROVED** [review]

**Comment by caybro** [comment]
Although... with a translated app, the individual buttons widths might be much wider and so we'd probably overflow again :/ This needs a more generic solution in the long run

**Comment by alexjba** [comment]
> Although... with a translated app, the individual buttons widths might be much wider and so we'd probably overflow again :/ This needs a more generic solution in the long run

You're right!

Screenshot 2023-07-07 at 13 30 16

**Comment by alexjba** [comment]
> Although... with a translated app, the individual buttons widths might be much wider and so we'd probably overflow again :/ This needs a more generic solution in the long run

I guess there's two options for this: Review the problematic translations and/or review StatusModal to support either dynamic width or a dynamic max width for buttons to prevent overflow. I'll add a task for the latter since it should never overflow.

**Comment by caybro** [comment]
> > Although... with a translated app, the individual buttons widths might be much wider and so we'd probably overflow again :/ This needs a more generic solution in the long run
> 
> I guess there's two options for this: Review the problematic translations and/or review StatusModal to support either dynamic width or a dynamic max width for buttons to prevent overflow. I'll add a task for the latter since it should never overflow.

Cool yeah, the former is not an option though 🙂

**Pull request merged**
