### PR TITLE
feat(@desktop/wallet): Add emoji to Wallet accounts.

### LINKED ISSUE #4926: Support assigning emojis to wallet acounts
### Description

note: this is related to https://github.com/status-im/status-desktop/issues/4809 as both require work in status-go and similar UI work to use the emoji picker. might be worth it to sync up.

designs: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=350%3A83030

Screen Shot 2022-02-28 at 1 14 24 PM

goal: support assigning an emoji to a wallet account

* [ ] support in status-go assigning an emoji to a wallet account
* [ ] display emoji for a wallet account
* [ ] assign an emoji when creating/importing a new wallet account
* [ ] assign an emoji when editing a wallet account

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4926

StatusQ PR : https://github.com/status-im/StatusQ/pull/575
Status-go PR: https://github.com/status-im/status-go/pull/2582

### What does the PR do

Added support  for emojis to:
1. Wallet list
2. Adding a new account
3. Editing an account

### Affected areas

Wallet , Community

### Screenshot of functionality
image

### CODE REVIEW

**Comment by anastasiyaig** [comment]
the Settings part will be done in another task

**Review by alaibe — APPROVED** [review]
LGTM

**Review by anastasiyaig — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Very nice job!

I see you improved the Input component to contain the emoji picker. Can you also replace the one in the community or maybe just add a small issue to remember to replace what is currently there with that.

**Comment by Khushboo-dev-cpp** [comment]
> Very nice job!
> 
> I see you improved the Input component to contain the emoji picker. Can you also replace the one in the community or maybe just add a small issue to remember to replace what is currently there with that.

Hey @jrainville doing it here https://github.com/status-im/status-desktop/issues/5026 :)

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp I get this (I did rebase / update statusq)
> 
> ```
> QQmlApplicationEngine failed to load component
> qrc:/main.qml:311:9: Type AppMain unavailable
> qrc:/app/mainui/AppMain.qml:493:17: Type WalletLayout unavailable
> qrc:/app/AppLayouts/Wallet/WalletLayout.qml:53:9: Type RightTabView unavailable
> qrc:/app/AppLayouts/Wallet/views/RightTabView.qml:24:5: Type WalletHeader unavailable
> qrc:/app/AppLayouts/Wallet/panels/WalletHeader.qml:121:9: Type AccountSettingsModal unavailable
> qrc:/app/AppLayouts/Wallet/popups/AccountSettingsModal.qml:63:13: Cannot assign to non-existent property "onEmojiClicked
> ```

Hey I fixed that. Merging it now

**Pull request merged**
