### PR TITLE
fix(@dekstop/chat): mentioning oneself display the full key instead of username

### LINKED ISSUE #4897: mentioning oneself display the full key instead of username
# Bug Report

## Steps to reproduce

1. go to a channel
2. type `@` and select yourself
3. send a message

Screen Shot 2022-02-25 at 2 38 30 PM

#### Expected behavior

should display the message as `@your username`

#### Actual behavior

displays the message as `@the public key (You)`

Screen Shot 2022-02-25 at 2 38 37 PM

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #4897

### CODE REVIEW

**Comment by saledjenic** [comment]
@iurimatias please advice how do you want to see if logged in user mentions himself. This is how it looks now:
mentionning

Do we need that "(You)" or not?

**Comment by iurimatias** [comment]
> @iurimatias please advice how do you want to see if logged in user mentions himself. This is how it looks now: mentionning
> 
> Do we need that "(You)" or not?

the you is not necessary

**Review by jrainville — COMMENTED** [review]
I'm confused why that code change fixes the issue. It seems like the code change only adds a space. 
Was the issue already fixed in master?

**Comment by saledjenic** [comment]
@iurimatias `(You)` removed, issue fixed.

**Comment by saledjenic** [comment]
> I'm confused why that code change fixes the issue. It seems like the code change only adds a space. Was the issue already fixed in master?

@jrainville I was wondering the same when I was investigating, but seems that the parser on the `status-go` side doesn't find mention if there is no space after the PK of the mentioned user.  As you know before calling `sendChatMessage` API point we're replacing "alias" with "public key", and if there is no a "space" after "public key" a message is not parsed well and response we're getting after that doesn't contain `mention` for the `type` of parsed `children` in `parsedText` array.

**Review by jrainville — APPROVED** [review]
I get it now. Looks good!

**Review by borismelnik — APPROVED** [review]

**Review by anastasiyaig — APPROVED** [review]

**Comment by iurimatias** [comment]
@saledjenic could you rebase and merge please

**Pull request merged**
