### PR TITLE
fix(Messaging/Contacts): The titles of folders in Settings-Messaging are shown very close to the search field

### LINKED ISSUE #5288: The titles of folders in Settings-Messaging are shown very close to the search field
# Bug Report

## Steps to reproduce
1. Sign in and go to Settings - Messaging - Contacts, Requests, and Blocked users
2. Check the titles of Contacts, Pending Requests, Rejected Requests, Blocked

#### Expected behavior
The titles are shown not very close to the search contacts field
#### Actual behavior
The titles are shown very close to the field
image

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/5171
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

### PR DESCRIPTION
**Pull request by noeliaSD**
Fixes #5288

### What does the PR do

Added more top margin in tab component.

### Affected areas

Messaging/Contacts

### Screenshot of functionality
Screenshot 2022-04-06 at 11 22 42

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Comment by noeliaSD** [comment]
kindly reminder to @elina2015 !! Thankss! :)

**Comment by elina2015** [comment]
Hi @noeliaSD, there is an error on the last onboarding page. So, it's impossible to register a new account and check the fixes. Could you kindly check?
image
image

**Comment by noeliaSD** [comment]
> Hi @noeliaSD, there is an error on the last onboarding page. So, it's impossible to register a new account and check the fixes. Could you kindly check? image image

Rebased! Please @elina2015 try again!

**Comment by elina2015** [comment]
@noeliaSD thank you so much for rebase, but it didn't help (for macOS) and the error is still shown and it's not possible to register a new user. Could you kindly check?

**Comment by noeliaSD** [comment]
> @noeliaSD thank you so much for rebase, but it didn't help (for macOS) and the error is still shown and it's not possible to register a new user. Could you kindly check?

I also have a mac M1 and it works fine to me after the rebase.. Could @alaibe and @jrainville verify if you also have the same issue? Thanks!

**Comment by jrainville** [comment]
@noeliaSD your branch works for me

@elina2015 I think your accounts DB was corrupted. I'm not sure how that happened, but I remember one discussion where status-go had a mis-ordered migration, so that might be it.
So you'll need to delete your data folder. This PR doesn't have anything to do with login anyway, so I'm guessing you'll have that issue on master as well.

**Pull request merged**
