### PR TITLE
fix(StatusQ) scrolling on macOS if mouse pointer is over StatusBaseInput

### LINKED ISSUE #5355: Can't scroll when having focus in seed phrase grid in wallet
### Description

1. enable wallet
2. click Add account
3. click Advanced
4. click Use 24 words
5. hover any cell of the grid
6. try to scroll

https://user-images.githubusercontent.com/82375995/161717924-0fb2ba6e-51bc-46e6-8fcc-43a1130a053d.mov

**Version:** MacOS, master commit https://github.com/status-im/status-desktop/commit/b54111f82ac0bdbecdace09358080f53891a5505 , april 5 2021

### PR DESCRIPTION
**Pull request by stefandunca**
### Fixes #5355

This commit fixes scrolling on macOS using trackpad in the context of Add Wallet Account using seed-phrase.

#### Considerations:

The scrolling of advanced input with seed-phrase selected was failing when mouse pointer was moving over a word phrase.

Scrolling of the popup content in `AddAccountModal` would not work when the mouse pointer was over the `StatusSeedPhraseInput` form the `ImportSeedPhrasePanel`

The identified root cause is `StatusBaseInput`'s `Flickable` which captures the specially generated mouse wheel event. It seems the trackpad wheel events are handled differently on `macOS` by the `Flickable` and are not propagated to the parent.

The fix disables user interactions for single-line items where there should be no need

### Affected areas

Add Account Wallet and all the panels and views that might rely on the StatusQ custom input controls that rely on the base input to stop mouse scroll events.

### Debugging Review

The issue was hard to find due to `StatusBaseInput` having too many responsibilities: it provides the specific text input, additional decorations and scrolling the view inside its container. I found this approach unintuitive. A StatusDecoratedScrollableBaseInput would have been a more appropriate name.

### StatusQ checklist

- [x] add documentation if necessary (new component, new feature)
- [x] ~~update sandbox app~~
  - I looked to add it to the corner cases for the input panel but none was found and no time left to build it

### CODE REVIEW

**Comment by stefandunca** [comment]
@endulab please try it on your side. @anastasiyaig there is a slight chance of new behaviour while scrolling using the trackpad on scrollable areas containing text input after fixing this issue.  Please let me know if you see something similar I described having a look.

**Comment by endulab** [comment]
@stefandunca after your fix, trackpad works correctly.

**Review by endulab — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]
LGTM, just simple suggestion: If you can, pls, propagate `wheelEvent` when content in multiline text at the end. Sometimes if you have bunch of inputs in ui with `ScrollView` its impossible to scroll it correctly.

**Comment by stefandunca** [comment]
> LGTM, just simple suggestion: If you can, pls, propagate `wheelEvent` when content in multiline text at the end. Sometimes if you have bunch of inputs in ui with `ScrollView` its impossible to scroll it correctly.

I added this as a bug to this related issue: https://github.com/status-im/status-desktop/issues/7557

**Pull request merged**
