### PR TITLE
multiple issues running the app

### PR DESCRIPTION
**Pull request by saledjenic**
Changes done in `dotherside`:
- https://github.com/status-im/dotherside/pull/55

Fixed issues:
- `setAppWidth` issue - fixed
- `signal connection` issue - fixed

Test script `app-run-test.sh` added to `test-scripts` folder.

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
I'll test this to see if I can reproduce the bug

**Comment by jrainville** [comment]
Sadly, I was still able to reproduce the error after like 20 tries. But then, I could reproduce after 2 tries

**Review by jrainville — COMMENTED** [review]
Looks good. I'll test it out

**Comment by jrainville** [comment]
I tested and the bug still happens to me. It might still be good to merge since it seems to delay the initiation of some modules when they were not needed.

**Pull request merged**
