### PR TITLE
chore: trim down PNG size with optipng

### PR DESCRIPTION
**Pull request by caybro**
- reduce the file size by about 5%-20% w/o any change in visual quality
- profile_fetching_* images replaced by the resolution we need; originally it was 1700x1700 and about 4MB each(!)

### What does the PR do

Optimizes/reduces PNG file size

### Affected areas

PNG assets

### Screenshot of functionality (including design for comparison)

- [N/A] I've checked the design and this PR matches it

### CODE REVIEW

**Review by micieslak — APPROVED** [review]
Look good. The only thing (not directly related) is that some files have 2x and 3x versions and other not. Do you maybe know why we have inconsistency like that?

**Comment by caybro** [comment]
> Look good. The only thing (not directly related) is that some files have 2x and 3x versions and other not. Do you maybe know why we have inconsistency like that?

These are meant for highres displays (3x for 5k displays, aka 300% scaling). I'd say we don't really need such highres images in general

**Comment by micieslak** [comment]
> > Look good. The only thing (not directly related) is that some files have 2x and 3x versions and other not. Do you maybe know why we have inconsistency like that?
> 
> These are meant for highres displays (3x for 5k displays, aka 300% scaling). I'd say we don't really need such highres images in general

Yeah, I know what's the purpose. I would just expected that all pgns have at least x2 for retina displays.

**Comment by caybro** [comment]
> > > Look good. The only thing (not directly related) is that some files have 2x and 3x versions and other not. Do you maybe know why we have inconsistency like that?
> > 
> > 
> > These are meant for highres displays (3x for 5k displays, aka 300% scaling). I'd say we don't really need such highres images in general
> 
> Yeah, I know what's the purpose. I would just expected that all pgns have at least x2 for retina displays.

Right... we don't have that; nothing that I could influence here :)

**Review by jrainville — APPROVED** [review]
Ah yes, I reviewed every file and checked everything and it's all fine, without a doubt

**Pull request merged**
