### PR TITLE
fix(community): Skip requests to join for public communities

### PR DESCRIPTION
**Pull request by borismelnik**
Fixes: #7949

### What does the PR do

Skip adding request to my pending requests if community is public

### Affected areas

Communities

### CODE REVIEW

**Comment by jrainville** [comment]
My bad for not noticing it when assigning, but I'm not sure if the issue and PR are necessary. Isn't it the new wanted behaviour that even "public" communities (should be called open) need the request access? I think the approval should be immediate only if the Owner is online, but we can't be sure since the signal for online is only every 5 minutes and you can set as "always online". Only when the signal comes back from the owner are we part of the community.

cc'ing @pedro-et to get the up to date wanted behaviour for the open community. Should we always show "pending" even if it might only be for a second?

**Comment by du64** [comment]
> My bad for not noticing it when assigning, but I'm not sure if the issue and PR are necessary. Isn't it the new wanted behaviour that even "public" communities (should be called open) need the request access? I think the approval should be immediate only if the Owner is online, but we can't be sure since the signal for online is only every 5 minutes and you can set as "always online". Only when the signal comes back from the owner are we part of the community.
> 
> cc'ing @pedro-et to get the up to date wanted behaviour for the open community. Should we always show "pending" even if it might only be for a second?

I think this would be bad, especially since I don't want people knowing when I am online, so I always keep it set to inactive.

**Comment by PascalPrecht** [comment]
> My bad for not noticing it when assigning, but I'm not sure if the issue and PR are necessary. Isn't it the new wanted behaviour that even "public" communities (should be called open) need the request access? I think the approval should be immediate only if the Owner is online, but we can't be sure since the signal for online is only every 5 minutes and you can set as "always online". Only when the signal comes back from the owner are we part of the community.

Open communities indeed require a request to join by design. This is because we need the community owner to process every request to join so that we get a deterministic and up-to-date community member list.

However, the online **status** of the community owner is irrelevant here. From the owner's perspective, it's just a message signal that needs to be processed. So as soon as a community owner starts Status and receives the request to join from store nodes, the request will be accepted (with an ACK).

> I think this would be bad, especially since I don't want people knowing when I am online, so I always keep it set to inactive.

@du64 as mentioned above, this is irrespective of your set online status. "online" here means, the community owner node receives the message signal and processes it (which can only happen when she is connected to the network)

**Comment by John-44** [comment]
> Isn't it the new wanted behaviour that even "public" communities (should be called open) need the request access? I think the approval should be immediate only if the Owner is online, but we can't be sure since the signal for online is only every 5 minutes and you can set as "always online". Only when the signal comes back from the owner are we part of the community.

@jrainville @PascalPrecht @borismelnik @elina2015 what @jrainville says here is 100% correct.  For "Public" communities (e.g. communities that don't have any token permissions that need to be met before a user can join the community), access still has to be requested from the Owner.  

If the Owner of a "Public" community has 'auto accept requests to join' switched on, then the request to join will be immediately automatically responded to in the Owner Node is online.  If the Owner Node is offline, then the request to join remains in the pending state until the Owner Node comes online.

If the Owner of a "Public" community has 'manually accept requests to join' switched on, then the request to join remains in the pending state until it's manually accepted.

For "Private" communities (e.g. communities that have one or more token permissions that need to be met before a user can join the community), access also has to be requested from the owner, in exactly the same two ways as for Public communities (e.g. the Owner of a "Private" community has the same two 'auto accept requests to join' and 'manually accept requests to join' options available to them ).

I think there is come confusion in the wording of the original issue, because currently Status Desktop *only* supports "Public" communities (e.g. we don't have token based permissions working at the community level yet), and it makes no difference if the Community owner has  'auto accept requests to join' or 'manually accept requests to join' switched on, these are both applicable for "Public" communities.

**Pull request closed without merging**
