### PR TITLE
fix(@wallet): receive modal

### LINKED ISSUE #4534: [base_bc] receive modal is empty in wallet
### Description

Screenshot 2022-01-24 at 14 21 12

### PR DESCRIPTION
**Pull request by alaibe**
fixes #4534

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by Khushboo-dev-cpp — CHANGES_REQUESTED** [review]
Hey can we please use the store again? instead of calling the module directly from the UI?

**Review by Khushboo-dev-cpp — APPROVED** [review]
Ignore my last comment :D

**Review by iurimatias — CHANGES_REQUESTED** [review]
Screen Shot 2022-01-25 at 1 44 17 PM

the `copy to clipboard` button isn't working. the address feels off somewhat

**Comment by alaibe** [comment]
@iurimatias button should work now and looks a better!

**Comment by anastasiyaig** [comment]
@alaibe the address is slightly overlapped for generated account. Besides that works great

Screenshot 2022-01-26 at 15 21 17

**Pull request merged**
