### PR TITLE
feat(wallet) extract json blobs and add custom migration support

### PR DESCRIPTION
**Pull request by stefandunca**
Update #10746

Bump status-go with the required changes [#3540](https://github.com/status-im/status-go/pull/3540)

### What does the PR do

Improves the migration for high-risk GO lang run data migration.
Extracts transaction information for future use (in activity filtering)

### Affected areas

Migration process
Migration from an older version of user data (ens)
Wallet

### CODE REVIEW

**Comment by stefandunca** [comment]
@anastasiyaig This PR improves the migration process and implements the migration of transaction data from BLOBs to a more structured approach. Could the testing team please execute migration regressions of already-fetched transactions to ensure we cover as many corner cases as possible?

**Review by alaibe — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@stefandunca i tested that with my local build and faced with the following error:

Screenshot 2023-06-05 at 16 28 33

```
DBG 2023-06-05 16:28:23.685+03:00 Account logged in                          topics="accounts-service" tid=6964868 file=service.nim:616
ERROR[06-05|16:28:25.074] failed to initialize db                  package=status-go/api.GethStatusBackend err="failed to migrate up: file does not exist"
ERROR[06-05|16:28:25.074] failed to start a node                   key-uid=0x1292e6b5d6cf15e13ca1ddb448316b3fa26706033f7b419bbfab3252c1ee3176 error="failed to migrate up: file does not exist"
ERR 2023-06-05 16:28:25.074+03:00 node.login                                 topics="signals-manager" tid=6964868 file=signals_manager.nim:53 error="failed to migrate up: file does not exist"
ERR 2023-06-05 16:28:25.077+03:00 login error                                topics="app-controller" tid=6964868 file=module.nim:434 methodName=onNodeLogin errDesription="failed to migrate up: file does not exist"
```

perhaps it is because of the PR is a bit behind of master, also would be nice to have an ability to retest within CI builds (mac builds are now available). Sorry about that, i will retest it first priority once it is rebased!

**Comment by stefandunca** [comment]
> perhaps it is because of the PR is a bit behind of master, also would be nice to have an ability to retest within CI builds (mac builds are now available). Sorry about that, i will retest it first priority once it is rebased!

Indeed, it seems there were some migration and transaction changes. I update all the migrations and solved merge conflicts, @anastasiyaig please give it another try.

**Comment by anastasiyaig** [comment]
> > perhaps it is because of the PR is a bit behind of master, also would be nice to have an ability to retest within CI builds (mac builds are now available). Sorry about that, i will retest it first priority once it is rebased!
> 
> Indeed, it seems there were some migration and transaction changes. I update all the migrations and solved merge conflicts, @anastasiyaig please give it another try.

on it!

**Comment by anastasiyaig** [comment]
I've tested the accounts migration with all possible creativity i have. iIsaw the issue with signal 16 when updating release version to this PR but i dont think it is related to these changes (same issue that happens to me from time to time when adding accounts)

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
