### PR TITLE
Chore(general/nimqml): Merge `nimqml` into status-desktop

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

It merges the `nimqml` (https://github.com/status-im/nimqml) repository into `status-desktop`. The upstream commits are squashed into single commit, the rest of history specific for Status is rewritten to status-desktop, similarly as it was done for StatusQ (https://github.com/status-im/status-desktop/pull/7462) and DOtherSide (https://github.com/status-im/status-desktop/pull/9411)

`nimqml` merge is based on branch https://github.com/status-im/nimqml/tree/master-with-original-nimqml-squashed where the upstream history has been squashed.

Closing this ticket should result in setting https://github.com/status-im/nimqml in read-only mode (@iurimatias your action will be needed).

Closes: https://github.com/status-im/status-desktop/issues/9843

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

once it builds ;)

**Review by alexjba — APPROVED** [review]

**Comment by caybro** [comment]
@micieslak when you re-run the script, pls make sure to include https://github.com/status-im/nimqml/pull/49 as well, thanks

**Comment by iurimatias** [comment]
@micieslak could you rebase this PR please

**Comment by iurimatias** [comment]
cc: @alexandraB99

**Comment by micieslak** [comment]
The problem with merging that `nimqml` stuff into status-desktop is the fact that this change breaks nim build system (which relies on listing git sumbodules :/) and requires some further workarounds to work properly. So I would opt for leaving it as it is (submodule). We do not tackle nimqml frequently and nim days are counted so the agreed solution is to not waste time on digging into nim build and close this PR.

**Pull request closed without merging**
