### PR TITLE
Keycard tests fixed, improved and other tests fixed accordingly

### PR DESCRIPTION
**Pull request by Valentina1133**
### What does the PR do

- Fixed keycard tests
- Fixed opening some of settings screens, added wait_until_appears (because we need to wait while verifying that screen was opened), also I added separate more precise wait_until_appears for each screen (now we wait for unique object on screens, so it works correctly)
- Had to rework authenticate popup class to make it work for keycard tests too
- Improved keycard tests a bit

CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2360/allure/#suites

From that run - 2 fails tried to fix here , all green, will see in nightly - https://github.com/status-im/status-desktop/pull/15654
1 fail was skipped and will be investigated here later - https://github.com/status-im/status-desktop/issues/15655

### CODE REVIEW

**Comment by anastasiyaig** [comment]
thanks @Valentina1133 , great job, thats what we needed for a long time. Just one comment - maybe we can mark keycard tests with some mark? To have an ability to run them separately, like `pytest -m keycard`

**Comment by Valentina1133** [comment]
> thanks @Valentina1133 , great job, thats what we needed for a long time. Just one comment - maybe we can mark keycard tests with some mark? To have an ability to run them separately, like `pytest -m keycard`

Mark is already there :)

**Comment by anastasiyaig** [comment]
yes, i was blind sorry

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@Valentina1133 i gave it one more try and 1 test failed because of window was not fully loaded (i guess)
maybe add more time to wait for this window? 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2363/allure/#suites/65453af30b6e126e5bcaf22acb6d5769/cf3b0a951109dcf7/

**Comment by Valentina1133** [comment]
> @Valentina1133 i gave it one more try and 1 test failed because of window was not fully loaded (i guess)
> maybe add more time to wait for this window?
> https://ci.status.im/job/status-desktop/job/e2e/job/manual/2363/allure/#suites/65453af30b6e126e5bcaf22acb6d5769/cf3b0a951109dcf7/

I increased timeout and ran keycard tests separately -  https://ci.status.im/job/status-desktop/job/e2e/job/manual/2365/  and also full run - https://ci.status.im/job/status-desktop/job/e2e/job/manual/2364/allure/, all good

**Comment by anastasiyaig** [comment]
perfect, pls merge, keycard lib mock is enabled for builds already

**Pull request merged**
