### PR TITLE
Add contact requests

### LINKED ISSUE #2345: Support mutual contact requests
https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=19780%3A321

desktop designs https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=5224%3A2707

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #2345

Adds contacts requests. When someone adds you as a contact, it sends you a request that appears with a notification in the contact column. 

You can then accept (adds as contact), decline (pretty much an ignore) or block.

The design couldn't be replicated 100%, because the backend doesn't support all the features seen in the design. eg:
- no message when sending a request
- no way to know if someone blocked receiving contact requests
- I also didn't put the request bubble, because it's too much work for what it does. We can always add it later if we want

I'll update the docs in another commit today or tomorrow

### CODE REVIEW

**Review by iurimatias — CHANGES_REQUESTED** [review]
test

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias 

the provided functionality does not match the designs attached to the initial issue. If the functionality was split to small parts, would you mind please describe what specifically is done in this particular PR and when (which issues) will be done the rest. In case full designed functionality is expected here, then this PR needs to be adjusted. 

1. No request bubble, no request button (at the bottom left)  - i see the comment in the PR , but please see my initial comment above
2. Able to send messages even the request is not initiated / is pending
3. Contact requests pop-up -> three dots / right click is not working, supposed to show additional actions with View profile + decline and block
4. Decline all / Accept all buttons are present on Contact requests screen when having it empty
5. No contact request message in 1x1 chat when accepted, also 1x1 chat is not opened
6. No notification when sending the add to contacts request
7. Counter on Chat badge is not updated when having incoming Contact Request
8. Since the request bubble is missing - i cant test it

Also , please see https://github.com/status-im/status-desktop/issues/2595 - we need to remove Add Contact button (ideally in this PR).

**Comment by jrainville** [comment]
@anastasiyaig I fixed the issues you mentionned. The ones I couldn't fix, I added another issue for them to be fixed later

1. I added 2 new issues for this. The first one blocks the other: 
  - https://github.com/status-im/status-desktop/issues/2604
  - https://github.com/status-im/status-desktop/issues/2605
3. Again, I think this is the issue you only have. For me, clicking those buttons works perfectly fine
5. You now join the chat with the person when you accept a single person, but clicking "Accept all" doesn't do it. Let me know if I should change the behavior to join the chat even for accept all

**Comment by anastasiyaig** [comment]
thank you for logging additional issues @jrainville ! Let's merge the PR and will continue working on this in master.

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
