### PR TITLE
fix: extend/fix DND and clipboard image operations

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

Fixes several issues/deficiencies we had with handling image data (paste, drag'n'drop, resizing); pls see the individual commits for explanation; namely: 
- fix crash when dropping a remote URL (non-Chrome browsers)
- fix DND checks for URLs containing a query
- missing support for dropping URLs
- fixup support for dropping URLs from Chrome (uses a non standard MIME type)
- fix missing support for dropping a bunch of files (e.g. from a file manager)
- more efficient `image_resizer` C++ code, more robust file size/extension checks

### Affected areas

StatusChatInput, `sendImages`

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

TODO: video

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

**Comment by jrainville** [comment]
I tried this PR and drag and drop works fine (though it did work for me anyway before).

Pasting from Brave still doesn't work though. So https://github.com/status-im/status-desktop/issues/10926 is not fixed by this.

I feel like this is a Brave/Qt Bug that we can't really fix

**Comment by caybro** [comment]
> I tried this PR and drag and drop works fine (though it did work for me anyway before).
> 
> Pasting from Brave still doesn't work though. So #10926 is not fixed by this.
> 
> I feel like this is a Brave/Qt Bug that we can't really fix

Ah, too bad. Most likely it is a Qt bug, fancy updating your Qt version? :) I'll install Brave myself anyway and will give it a try

**Comment by caybro** [comment]
> I tried this PR and drag and drop works fine (though it did work for me anyway before).
> 
> Pasting from Brave still doesn't work though. So #10926 is not fixed by this.
> 
> I feel like this is a Brave/Qt Bug that we can't really fix

@jrainville works for me :/

Copy & paste:
image

**Comment by caybro** [comment]
@jakubgs the `e2e` build fails here repeatedly with at least some meaningful error message:

```
[2023-06-07T22:32:04.913Z] /usr/bin/ld: nimcache/release/nim_status_client/@m..@svendor@snimbus-build-system@svendor@sNim@slib@spure@snet.nim.c.o: in function `checkCertName__pureZnet_1309':
[2023-06-07T22:32:04.913Z] /home/jenkins/workspace/_linux_x86_64_tests-e2e_PR-10975/vendor/nimbus-build-system/vendor/Nim/lib/pure/net.nim:831: undefined reference to `SSL_get_peer_certificate'
[2023-06-07T22:32:04.913Z] collect2: error: ld returned 1 exit status
[2023-06-07T22:32:04.913Z] Error: execution of an external program failed: 'g++  @nim_status_client_linkerArgs.txt'
[2023-06-07T22:32:04.913Z] make: *** [Makefile:476: bin/nim_status_client] Error 1
script returned exit code 2
```

Some stale nimcache? OpenSSL upgraded?

**Comment by alexjba** [comment]
> > I tried this PR and drag and drop works fine (though it did work for me anyway before).
> > Pasting from Brave still doesn't work though. So #10926 is not fixed by this.
> > I feel like this is a Brave/Qt Bug that we can't really fix
> 
> @jrainville works for me :/
> 
> Copy & paste: image

Works on MacOs with Safari and Chrome

**Comment by caybro** [comment]
> > 
> > @jrainville works for me :/
> 
> Works on MacOs with Safari and Chrome

@alexjba Qt version?

**Comment by alexjba** [comment]
> > > @jrainville works for me :/
> > 
> > 
> > Works on MacOs with Safari and Chrome
> 
> @alexjba Qt version?

The same version used on CI, 5.15.8.

**Review by alexjba — APPROVED** [review]
LGTM!

**Comment by jrainville** [comment]
> The same version used on CI, 5.15.8.

If I use 0.12, I can still reproduce the issue. Is there any chance that we updated the QT version since then on CI?

**Comment by alexjba** [comment]
> > The same version used on CI, 5.15.8.
> 
> If I use 0.12, I can still reproduce the issue. Is there any chance that we updated the QT version since then on CI?

AFAIK only MacOs is using 5.15.8 since 0.11. Linux is still stuck to 5.15.2 (https://github.com/status-im/status-desktop/issues/9350)
Not sure about Windows tho..

**Comment by jrainville** [comment]
Interesting. I'm using 5.15.2 locally too, so that might explain why I also see the issue reproducing. I'll try updating to 5.15.8

**Comment by jrainville** [comment]
Dumb question, how did you install 5.15.8 @lukaszso ? The online installer only gives access to 5.15.2 and 6.x

**Comment by caybro** [comment]
> Dumb question, how did you install 5.15.8 @lukaszso ? The online installer only gives access to 5.15.2 and 6.x

Comes with my Linux distro :)

**Comment by caybro** [comment]
> > Dumb question, how did you install 5.15.8 @lukaszso ? The online installer only gives access to 5.15.2 and 6.x
> 
> Comes with my Linux distro :)

Otherwise there are just source packages to download

**Comment by alexjba** [comment]
> Dumb question, how did you install 5.15.8 @caybro ? The online installer only gives access to 5.15.2 and 6.x

On MacOs we're using Homebrew to install it. It's also available on linux, so you could try with `brew install qt@5`. I remember it was working fine on Docker. But I see the package is now upgraded to 5.15.9.

**Pull request merged**
