### PR TITLE
feat(Profile): Profile showcase backend

### LINKED ISSUE #11081: Profile showcase backend
### Description

The UI for this feature is ready but we need to implement the backend part

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #11081
Waits https://github.com/status-im/status-go/pull/4005

### What does the PR do

Add display with profile showcase settings applied:
- [x] Communities
- [x] Wallet Accounts
- [ ] Collectibles
- [x] Assets

### Affected areas

Profile, Contacts

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/2522130/3c1830f8-13b8-4209-abe2-f079157b0651

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
Suggestion: maybe it would be a bit better to keep one model in QML (per category) and use ProxyModel for `In Showcase` and `Hidden`. Then I could store every change in one model and when saving I would just convert back to DTO.

Or can we temporarily leave it as it is and implement profile protocol & client side ui first?

@caybro @jrainville

**Comment by caybro** [comment]
> Suggestion: maybe it would be a bit better to keep one model in QML (per category) and use ProxyModel for `In Showcase` and `Hidden`. Then I could store every change in one model and when saving I would just convert back to DTO.
> 
> Or can we temporarily leave it as it is and implement profile protocol & client side ui first?
> 
> @caybro @jrainville

I don't think you'll be able to use the SortProxyModel in QML, as that would break the drag'n'drop :/ But you might want to experiment with it a bit first

**Comment by MishkaRogachev** [comment]
Moving to draft, review [this PR](https://github.com/status-im/status-desktop/pull/12510) instead

**Comment by MishkaRogachev** [comment]
Closed, due to [this one](https://github.com/status-im/status-desktop/pull/12510)

**Pull request closed without merging**
