### PR TITLE
uiux(StatusChatInput): toggle markdown from selection

### LINKED ISSUE #1930: dismiss the bold formation when pressing CMD+B
I want to hit CMD+B (or any other shortcut) to dismiss the bold formation.

Watch video + audio recording...

https://user-images.githubusercontent.com/52249767/109282871-65f77400-781e-11eb-9227-d032082d944a.mov

### PR DESCRIPTION
**Pull request by PascalPrecht**
Closes #1930

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
the keyboard shortcuts don't work on this branch, for e.g I select text and press cmd + B and nothing happens

**Comment by PascalPrecht** [comment]
They do work when the text is selected via keyboard instead of the mouse.
This is an issue that existed before and is unrelated to this PR.

The reason this happens is because when we select with the mouse, we open the text formatting menu on mouse release, which then puts the focus on the formatting menu, disabling the shortcut.

Will look into this

**Comment by PascalPrecht** [comment]
> The reason this happens is because when we select with the mouse, we open the text formatting menu on mouse release, which then puts the focus on the formatting menu, disabling the shortcut.

It's funny, even though the `messageFieldInput` gets `activeFocus`, the keyboard shortcut isn't activated. I tried many different things now, but can't get the shortcut to activate when the text formatting menu is open...

**Comment by jrainville** [comment]
@PascalPrecht have you tried move the `Action`s higher up in the component chain? Maybe they would keep the "focus"

**Comment by PascalPrecht** [comment]
Hmm no I haven't because the actions are transcluded into the text formatting menu component. Moving them out, removes the buttons in the menu...

**Comment by jrainville** [comment]
Ah right that makes sense. You can still cheat I guess and just duplicate the Actions and the ones out of teh menu would have no icon or physical appearance.

**Comment by PascalPrecht** [comment]
I might be missing something here... so the keyboard shortcuts are coming from the `Shortcut` components used in the chat input, not the `Action` components. The actions are merely there to pass menu items to the menu, could as well have been `MenuItem` components instead, but I think I stole this pattern from somewhere else and I believe this was done so that `MenuItem` could be fully customized.

Now.. Moving up those `Shortcut` components doesn't make a difference. In face, they are already higher up in the component tree because they live inside the `TextArea`, while the `Action` items live inside the `StatusFormatTextMenu` (which also lives inside the `TextArea`

**Comment by jrainville** [comment]
Ok my bad, I was used to having shortcuts in Actions. I didn't look well enough, disregard all I said 🙈

**Comment by PascalPrecht** [comment]
No worries, thanks for giving it a try man

**Comment by PascalPrecht** [comment]
Updated this PR once more with following changes:

- formatting from one style to another is now supported (e.g. from italic to bold, without unformatting first)
- md formats can no longer be nested

The shortcuts work only when the text was selected with the keyboard. Otherwise, the functionality is the same

**Comment by anastasiyaig** [comment]
@PascalPrecht should the formatting work with hot keys , for example command + b (makes text **bold**)? If so - it is not working on my machine

**Comment by PascalPrecht** [comment]
https://github.com/status-im/status-desktop/pull/1966#issuecomment-819499401

> The shortcuts work only when the text was selected with the keyboard. Otherwise, the functionality is the same

**Comment by anastasiyaig** [comment]
@PascalPrecht This is correct, i was not doing the selection via mouse. The problem is that "select all" with `command + a` then does not allow formatting as described in this ticket. 
selection of the text with shift + arrow keys works just fine with formatting using keyboard.

Could u please take a look and advise if fixing command+a is something we can achieve easily in this PR? If not - i can track this particular scenario in separate ticket in order not to hold current PR.

**Comment by PascalPrecht** [comment]
> The problem is that "select all" with command + a then does not allow formatting as described in this ticket.

I just gave that a spin and doing CMD+A to select the entire message and then doing e.g. CMD+B works perfectly fine for me

**Comment by anastasiyaig** [comment]
dunno whats happened but it is working now indeed

**Pull request merged**
