### PR TITLE
feat: cache data related to token price and market data locally for GetWalletToken

### PR DESCRIPTION
**Pull request by seanstrom**
related to: https://github.com/status-im/status-mobile/issues/20975
related status-go pr: https://github.com/status-im/status-go/pull/5832
related status-mobile pr: https://github.com/status-im/status-mobile/pull/21272
and a continuation of [the "balance zero" work group](https://www.notion.so/Working-group-for-0-balances-and-provider-being-down-blocker-7125b05e3a3d4247b09378d3b50120e6?pvs=4)

### What does the PR do

* This PR attempts to update the status-go version to the latest commit in this PR: https://github.com/status-im/status-go/pull/5832
  * The changes in the related status-go pr are for resolving some issues with status-mobile reporting a wallet balance of zero.

### Affected areas

* `GetWalletToken` is the function that is affected the most by the status-go changes, and it seems that status-desktop to use this function internally. So most of the benefits will be for status-mobile, but a regression check for the app could be necessary
* Router Transaction Estimates
  * When providing estimates from router, we request token pricing data, and this code has been slightly modified.
  * The changes should not have affected anything, but it's probably best to test this portion of the app.

### How to test

This PR is mostly for created for QA to test if the related status-go changes have caused any regressions in the status-desktop app. There are no intended changed for status-desktop, but it's worth double-checking the way estimates for the router transactions are still working. This is because some of the code related to fetching the prices for the router estimates has been refactored, so it could have regressed.

### Risk 

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]
@seanstrom thanks for updating statusgo for the desktop app, but you will need to update it again after you merge your statusgo changes.

**Comment by anastasiyaig** [comment]
@seanstrom please rebase to current fresh fresh master, as we fixed recently a bug that was preventing to send

Screenshot 2024-09-17 at 11 24 56

you need this commit https://github.com/status-im/status-desktop/pull/16350

**Comment by anastasiyaig** [comment]
The following things were tested on mainnet and transactions were just fine:

Send:

- [ ] eth
- [ ] erc20
- [ ] erc721
- [ ] erc1155

Bridge:

- [ ] eth -> eth
- [ ] erc20 -> erc20

Swap:
- [ ] eth -> erc20
- [ ] erc20 -> eth
- [ ] erc20 -> erc20

Community:

- [ ] mint tokens (community tokens and NFT / Assets)
- [ ] get prices for all networks
- [ ] airdrop
- [ ] transfer ownerhip
- [ ] remote destruct

**Comment by seanstrom** [comment]
I've updated the commit in this PR to update status-go to version `v2.1.0`.
Let me know if there's anything else to do before merging please 🙏 

cc @saledjenic @anastasiyaig

**Comment by saledjenic** [comment]
@seanstrom all good then, feel free to merge this pr. Thanks.

**Review by alaibe — APPROVED** [review]

**Comment by seanstrom** [comment]
Since this PR only updates status-go to v2.1.0, and this PR has merged that updates to latest status-go on the develop branch (which includes v2.1.0), I think it's safe to close this PR. 🚀

**Pull request closed without merging**
