### PR TITLE
chore: remove old router logic

### LINKED ISSUE #16201: Remove "old" router logic
Under this issue, we should
- remove the old router logic (cause it's not in use anymore)
- improve file organization for the new router

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/5778

Closes #16201

### CODE REVIEW

**Review by dlipicar — CHANGES_REQUESTED** [review]
image

image


uses of the old error codes not updated

**Comment by dlipicar** [comment]
@saledjenic couple other places that use the old `swap.errorCodes`
image

**Comment by saledjenic** [comment]
SwapModalAdaptor is already handled, I missed storybook pages

**Review by dlipicar — APPROVED** [review]
Cool, thanks for the changes.
This now also closes https://github.com/status-im/status-desktop/issues/15874

**Review by alexjba — APPROVED** [review]
LGTM!

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM! also tested it locally on my side, Send , Bridge Swap work okay :)

**Pull request merged**
