### PR TITLE
chore: bump status-go

### PR DESCRIPTION
**Pull request by igor-sirotin**
update status go to get https://github.com/status-im/status-go/pull/4821

Closes https://github.com/status-im/status-desktop/issues/13756

### CODE REVIEW

**Review by endulab — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@igor-sirotin change password test fails in this build...

**Comment by igor-sirotin** [comment]
> @igor-sirotin change password test fails in this build...

tested locally, "works on my machine" 😄 

https://github.com/status-im/status-desktop/assets/25482501/fb4bb04d-303f-403d-a95f-314a95a9275a

**Comment by anastasiyaig** [comment]
sure, i texted you in DM about the root cause. I am restarting tests now

**Comment by igor-sirotin** [comment]
> sure, i texted you in DM about the root cause. I am restarting tests now

yeah, just logging things here for future clarity 😄

**Comment by anastasiyaig** [comment]
its green @igor-sirotin

**Pull request merged**
