### PR TITLE
Fix duplicated chats

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/7167

This is a weird issue. It only happens in packaged builds (PRs and release builds). Local dev builds work correctly.
I ended up finding that the issue happens because of the DelegateChooser. I don't have a reason, but using just a condition doesn't have that issue.
I also cleaned up some old code and typos while doing my testing. The actual changes are only on StatusAppNavBar.

The only thing that I did that's not 100% clean is I have to pass the model to the created component. Let me know if there is a cleaner way to do that.

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]
Super cool that you could fix this. 
I'll defer to the QML experts whether this change is feasible as a fix.

Must've been hard to figure this one out

**Review by caybro — APPROVED** [review]
LGTM although I'd definitely like to see more declarative way here

**Review by osmaczko — CHANGES_REQUESTED** [review]
Thanks for finding the fix. When reviewing it I realized `StatusAppNavBar` is way too imperative and so error-prone. I decided to refactor it: https://github.com/status-im/status-desktop/pull/8477

**Comment by jrainville** [comment]
Closing in favor of https://github.com/status-im/status-desktop/pull/8477

**Pull request closed without merging**
