### PR TITLE
fix(@desktop): crash when handling messages.new signal

### LINKED ISSUE #3527: Application is crashing after stay idle for a while
It is not crashing to me, but @flexsurfer and @pinebit saw them 

`signal_controller.nim:51
self.status.events.emit(signal.signalType.event, signal)`

Probably related to group chats management (join / leave) but i am not clear yet.

### PR DESCRIPTION
**Pull request by pinebit**
Probably closes #3527 

I was able to reproduce the crash described in #3527 
However, I still barely understand what led to incorrect Args type.
This fix is probably just masking another issue, but some people complains they cannot run their app for a while, hence I am suggesting this workaround.

### CODE REVIEW

**Comment by flexsurfer** [comment]
this PR doesn't crash for me, and i can see in logs 
```
signal:messages.new event args is not of MessageSignal
signal:messages.new event args is not of MessageSignal
```

**Comment by richard-ramos** [comment]
@flexsurfer, @pinebit 
Can you try this PR? https://github.com/status-im/status-desktop/pull/3588
I missed setting the signalType when I did a refactor to move the signal logic to status-lib

**Comment by flexsurfer** [comment]
@richard-ramos it doesn't crash in your build, but dunno what if it was fixed by this PR ? i mean what if there are no such signals anymore ?

**Comment by richard-ramos** [comment]
> @richard-ramos it doesn't crash in your build, but dunno what if it was fixed by this PR ? i mean what if there are no such signals anymore ?

@pinebit is able to reproduce the problem consistently. Let's wait for him to see if my PR stops the issue from happening

**Comment by pinebit** [comment]
@richard-ramos 's fix is working and it is proper fix. So closing this PR.

**Pull request closed without merging**
