### PR TITLE
fix: Send Message button not working in profile popup

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2364

The Send Message button click event was erroring due to a refactor that had been done to allow for changing app sections.

This has been updated to follow the current way to change app sections.

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@emizzle 

same scenario crashes the app when sending a message in community, can we fix it as well here? 

`/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/src/nim_status_client.nim(216) nim_status_client
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/src/nim_status_client.nim(213) mainProc
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/vendor/nimqml/src/nimqml/private/qapplication.nim(8) exec
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(595) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/src/app/chat/view.nim(583) joinChat
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/src/app/chat/view.nim(410) setActiveChannel
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2426/src/app/chat/views/chat_item.nim(34) setChatItem
SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

**Steps:** 

1. create community
2. create a channel 
3. send something in channel
4. click profile -> send message (or click profile -> view profile -> send message)

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
looks great now thanks for fixing communities part!

**Comment by emizzle** [comment]
@jrainville could you please re-review? Specifically, I would like to make sure this change https://github.com/status-im/status-desktop/pull/2426/files#diff-7ee7cfb8be5fc9d26148a2e6de49c5d2579ed3e7a0e88bf5743f29f752f415e9 doesn't have any side effects that I'm not aware of.

**Review by jrainville — APPROVED** [review]
It looks good. I think setting the community active to false shouldn't introduce any side effect.

**Pull request merged**
