### PR TITLE
Nim library upgrades, pt1

### PR DESCRIPTION
**Pull request by arnetheduck**
This PR upgrades a number of libraries as well as nim itself, to address security issues and crashes that we've worked to solve over the past few months on the nimbus-eth2 side leading up to its 1.6 migration - they include changes that are safe to use in both 1.2 and 1.6 without requiring 1.6, making the code compatible with both versions.

In particular, 1.6 becomes more strict in several ways including exception handling, style and certain langauge constructs related to memory safety - as a result, we've cleaned up said libraries and improved their stability overall, including fixing several crashes.

* nim 1.2.18 - this is the last release in the 1.2 series we produced together with upstream based on nimbus' needs - between the version Desktop is using today and v1.2.18, changes are predominantly backports from newer Nim versions that we asked for while working on stability in Nimbus itself.
* chronicles - cleanups
* confutils - cleanups
* faststreams - cleanups & crash fixes
* nim-json-serialization - several important crash fixes for json parsing edge cases
* metrics - cleanups & threading fixes
* secp256k1 - upstream updates (including security fixes)
* serialization - cleanups
* stew - many convenience fixes and updates to common low-level utilities, such as Result and hex / base64 / etc parsing
* stint - cleanups
* zlib - cleanups
* nimPNG - cleanups
* nimcrypto - cleanups

This is part 1 of library upgrades and focuses on the low-level libraries - part 2 will upgrade the network stack (chronos, json-rpc, web3, etc), keeping the two separate so as to limit the potential impact of this PR.

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by caybro — APPROVED** [review]
LGTM

**Review by osmaczko — APPROVED** [review]
LGTM (the app runs just fine)

**Comment by arnetheduck** [comment]
I count 3 approvals here - are we good to go? 

I have pt.2 ready as well which upgrades the rest of the libraries, focusing on the web / socket stuff, json-rpc above all - works fine locally.

**Comment by caybro** [comment]
> I count 3 approvals here - are we good to go?
> 
> I have pt.2 ready as well which upgrades the rest of the libraries, focusing on the web / socket stuff, json-rpc above all - works fine locally.

I'd say go ahead :shrug:

**Review by borismelnik — APPROVED** [review]

**Pull request merged**
