### PR TITLE
fix: appimage freezes on login

### LINKED ISSUE #4189: Appimage does not work
Using 0.4.0 App freezes on login
Nothing of interest is shown in the logs
Attaching gdb to the running process displays the following stacktrace. It's possible these are not related at all to the login error
image
image

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #4189

### CODE REVIEW

**Comment by jakubgs** [comment]
I seriously need to get hetzner hardware hosts for windows because the Google Cloud ones have performance which depends on alignment of planets.

**Comment by PascalPrecht** [comment]
Was this creating some infinite loop or something due to expression scoping going sideways? Trying to understand how those changes could unblock an app freeze..

**Review by alaibe — APPROVED** [review]

**Comment by jakubgs** [comment]
Doesn't seem to fix it for me, the PR build freezes the same way on my NixOS machine. Spinning in place:

image

**Comment by richard-ramos** [comment]
> Was this creating some infinite loop or something due to expression scoping going sideways? Trying to understand how those changes could unblock an app freeze..

Yeah, I don't know what's going on. I just noticed that if I assigned a value to `activeMailserverTxt.text` within the signal handler, it ended up freezing the app. However @jakubgs still has the problem with this PR :man_facepalming:

**Comment by jakubgs** [comment]
Could we maybe use [pprof](https://github.com/google/pprof) to figure out what's spinning in place?

**Comment by jakubgs** [comment]
There's [nimprof](https://nim-lang.org/docs/nimprof.html) equivalent to `pprof`: https://nim-lang.org/docs/estp.html

**Review by jakubgs — APPROVED** [review]
The build nr 6 works for me. Great work @richard-ramos ! Now I fan finally see all the spam I want:

image

**Review by jrainville — COMMENTED** [review]
@richard-ramos do you plan on working on this more or we are good with removing the Active Mailserver section?

**Comment by richard-ramos** [comment]
> @richard-ramos do you plan on working on this more or we are good with removing the Active Mailserver section?

I wasn't thinking in working in this anymore, since the mailserver can be seen in the Mailserver section of the Sync Settings, and identifying the issue and 'fix' took an absurd amount of time :(

**Review by jrainville — APPROVED** [review]

**Pull request merged**
