### PR TITLE
feat: channels encryption backend

### PR DESCRIPTION
**Pull request by osmaczko**
### What does the PR do

This brings channels encryption backend. Now every token-gated channel should be encrypted behind the scenes. It also includes improved community rekeying.

### Affected areas

- communities messaging
    - on encrypted community
    - on encrypted channels
    
#### Test community-level encryption
1) Create token-gated community
1) Join with MemberA who satisfies the criteria
1) Send message "X" to general channel
1) MemberA should see the "X" message
1) Change token permissions so that MemberA no longer satisfies the criteria
1) MemberA should be kicked from the community
1) Send message "Y" to general channel
1) Change token permissions so that MemberA once again meets the criteria
1) MemberA should be re-added to the community
1) MemberA should see both "X" and "Y" messages
1) Send message "Z" to general channel
1) MemberA should see "X", "Y" and "Z" messages

#### Test channel-level encryption
1) Create open community
1) Create token-gated test channel
1) Join with MemberA who satisfies test channel's criteria
1) Send message "X" to general and test channels
1) MemberA should see the "X" message both in general and test channels
1) Change test channel's token permissions so that MemberA no longer satisfies the criteria
1) Send message "Y" to general and test channels
1) Member should see the "X" and "Y" messages in general channel but not in the test channel
1) Change token permissions so that MemberA once again meets the criteria
1) MemberA should see both "X" and "Y" messages in the test channel
1) Send message "Z" to general and test channels
1) MemberA should see "X", "Y" and "Z" messages in both the general and test channels

@glitchminer please consider adding above scenarios to regressions tests

### CODE REVIEW

**Comment by glitchminer** [comment]
Hi @osmaczko , I'll be afk for a while so won't be able to pick this up, sorry. @anastasiyaig or @lukaszso may be able to help though.

**Comment by osmaczko** [comment]
@glitchminer thanks for info! @anastasiyaig could you please take over?

**Comment by anastasiyaig** [comment]
@osmaczko yes, @lukaszso is already on it

**Comment by lukaszso** [comment]
@osmaczko I've checked both scenarios and here are the results:

Community-level encryption:
1. Create token-gated community - ✓
2. Join with MemberA who satisfies the criteria - ✓
3. Send message "X" to general channel - ✓
4. MemberA should see the "X" message - ✓
5. Change token permissions so that MemberA no longer satisfies the criteria - ✓
6. MemberA should be kicked from the community - ✓ 
7. Send message "Y" to general channel - ✓
8. Change token permissions so that MemberA once again meets the criteria - ✓
9. MemberA should be re-added to the community - X (user has to manually re-join)
10. MemberA should see both "X" and "Y" messages - X (only sees "X")
11. Send message "Z" to general channel - ✓
12. MemberA should see "X", "Y" and "Z" messages - X (only sees "X" and "Z")


For channel-level encryption it seems to be working as described, i think it's because while they are on the user is still a part of the community so all the messages are still fetched but not visible maybe?

**Comment by osmaczko** [comment]
Hi @lukaszso, thanks for testing :pray: 

> MemberA should be re-added to the community - X (user has to manually re-join)

Right, that's my mistake. This is expected behavior, user has to manually re-join.

> MemberA should see both "X" and "Y" messages - X (only sees "X")

That's an issue. I double-checked and this can be reproduced on master without my changes, so it is not a regression from this PR. I created a separate issue for that: https://github.com/status-im/status-desktop/issues/11686

@lukaszso could you please add these scenarios to TestRail?

**Comment by osmaczko** [comment]
Closing, channels re-keying works fine. I'll bump status-go with another PR.

**Comment by lukaszso** [comment]
> @lukaszso could you please add these scenarios to TestRail?

Added [here](https://ethstatus.testrail.net/index.php?/suites/view/5280&group_by=cases:section_id&group_id=51162&group_order=asc&display_deleted_cases=0)

**Pull request closed without merging**
