### PR TITLE
Enable deep links in Windows

### PR DESCRIPTION
**Pull request by jrainville**
This enabled deep links for Windows by running a bat file that sets the correct Registry entries.

To do this:
1. Go in Profile > Advanced
2. Press "Setup deep links" (this will change with designs)
3. You're ready to try a deep link

You can then enter a public chat deep link like so `status-im://CHANEL_NAME`

It will join that channel in the opened app or open Status and join it once logged in

We will support more deep links once the Status-Go PR is done and merged.

Re-running the bat file will work and it is also necessary for when the user moves the app to a different directory.

Later, we can try to do a Query on the registry to see if the setup folder for the app is the same as what we have right now, if now, we can encourage the user to re-run the script.

Edit: This only works for packaged builds, so if you want to test it out, just do `make pkg` or use one of the Jenkins builds

### CODE REVIEW

**Review by michaelsbradleyjr — COMMENTED** [review]
Do we know if this is actually gcsafe?

https://github.com/jrainville/asynctools/blob/fix/missing-gcsafe/asynctools/asyncsync.nim#L154-L159

Added in https://github.com/jrainville/asynctools/commit/f166a3db60bbac9bda9dd1059b6c15bc3fee51e5.

**Comment by jrainville** [comment]
> Do we know if this is actually gcsafe?

I'm not sure, see full answer here https://github.com/cheatfate/asynctools/pull/29#discussion_r595176894

**Comment by iurimatias** [comment]
adding `do not merge` tag for now, since we should do this in an installer

**Comment by iurimatias** [comment]
closing because this needs to be done through the installer

**Pull request closed without merging**
