### PR TITLE
fix(desktop/chat) online/offline selector not changing color/state

### LINKED ISSUE #4049: [refactoring/base_02] online/offline selector not changing color/state
in the latest refactor branch:

Screen Shot 2021-11-04 at 12 20 20 PM

select offline, the state color is still green

### PR DESCRIPTION
**Pull request by alexandraB99**
Selecting online/offline state was not updating the color
in the profile image badge

Closes #4049  

https://user-images.githubusercontent.com/176720/140383074-c8e5833c-9f32-44db-a67f-16b4fc249407.png

### CODE REVIEW

**Review by saledjenic — CHANGES_REQUESTED** [review]
@alexandraB99 within this `base_02` branch a new global instance `userProfile` is introduced, it should be used across all qml files for reading/accessing any logged in user related info. 

Needed changes:
1. Having that all places here in this PR where is used `appMain.rootStore.profileModelInst.profile.sendUserStatus` need to be updated to be like `userProfile.sendUserStatus`.

2. Since `profileModelInst` from the `RootStore` refers to the old "profileModel" which we want to get rid of, another necessary change is actually using  `profileModule.setSendUserStatus` instead of `root.store.profileModelInst.profile.setSendUserStatus` and that change requires slight update of profile module, where is enough to have only `setSendUserStatus` which is a slot which _will update global `userProfile` instance_, and remove `QtProperty[bool] sendUserStatus` from there.

**Comment by alexandraB99** [comment]
> @alexandraB99 within this `base_02` branch a new global instance `userProfile` is introduced, it should be used across all qml files for reading/accessing any logged in user related info.
> 
> Needed changes:
> 
> 1. Having that all places here in this PR where is used `appMain.rootStore.profileModelInst.profile.sendUserStatus` need to be updated to be like `userProfile.sendUserStatus`.
> 2. Since `profileModelInst` from the `RootStore` refers to the old "profileModel" which we want to get rid of, another necessary change is actually using  `profileModule.setSendUserStatus` instead of `root.store.profileModelInst.profile.setSendUserStatus` and that change requires slight update of profile module, where is enough to have only `setSendUserStatus` which is a slot which _will update global `userProfile` instance_, and remove `QtProperty[bool] sendUserStatus` from there.

@saledjenic `profileModule.setSendUserStatus` seems not working, I get `UserStatusContextMenu.qml:104: TypeError: Property 'setSendUserStatus' of object View(0x7fea1bc2f0c0) is not a function`

**Comment by saledjenic** [comment]
> @saledjenic profileModule.setSendUserStatus seems not working, I get UserStatusContextMenu.qml:104: TypeError: Property 'setSendUserStatus' of object View(0x7fea1bc2f0c0) is not a function

@alexandraB99 I added that as a general guide how it should be, but I was not working on that part. I've thought it's directly accessible for the `profileModule` but having a look into `profileModule` seems it's not accessible using  `profileModule.setSendUserStatus` but since it's in a model of that module it's accessible like `profileModule.model.setSendUserStatus`.  

Now it's accessible but that still doesn't solve the issue, in order to solve it properly we need to apply complete suggested change from my previous message.

**Comment by alexandraB99** [comment]
> > @saledjenic profileModule.setSendUserStatus seems not working, I get UserStatusContextMenu.qml:104: TypeError: Property 'setSendUserStatus' of object View(0x7fea1bc2f0c0) is not a function
> 
> @alexandraB99 I added that as a general guide how it should be, but I was not working on that part. I've thought it's directly accessible for the `profileModule` but having a look into `profileModule` seems it's not accessible using `profileModule.setSendUserStatus` but since it's in a model of that module it's accessible like `profileModule.model.setSendUserStatus`.
> 
> Calling `setSendUserStatus` from the `model` of the `profileModule` it's accessible, but that still doesn't solve the issue, in order to solve it properly we need to apply complete suggested change from my previous message.

Ah, so you basically want me to update profile module? Is this like a missing change? Because I see these parts where updated in `ba09fb47b refactor(@desktop/general): qml updated according to the new `userProfile` instance` but at the end was 'half' implemented because `setSendUserStatus` is not there yet?

**Comment by saledjenic** [comment]
@alexandraB99 changes in commit `ba09fb47b` are caused because of changes introduced in the commit before `5464ab40f` and that's all. The point of exposed `userProfile` is the have global instance on the both qml and Nim side for reading/accessing a details about logged in user. Function `setSendUserStatus` is not part of the `userProfile`, it is currentlly part of the `profileModule` (but it should be part of the `mainModule` at the end).

> so you basically want me to update profile module? Is this like a missing change?

That should be done as a part of this ticket in order to have feature fully completed. Ideally would be if we would move that part to the `mainModule`, but even it's like it's now then profile module needs some update where we need only `setSendUserStatus` which is a slot which will update global userProfile instance, and we don't need `QtProperty[bool] sendUserStatus` there at all.

**Comment by alexandraB99** [comment]
> @alexandraB99 changes in commit `ba09fb47b` are caused because of changes introduced in the commit before `5464ab40f` and that's all. The point of exposed `userProfile` is the have global instance on the both qml and Nim side for reading/accessing a details about logged in user. Function `setSendUserStatus` is not part of the `userProfile`, it is currentlly part of the `profileModule` (but it should be part of the `mainModule` at the end).
> 
> > so you basically want me to update profile module? Is this like a missing change?
> 
> That should be done as a part of this ticket in order to have feature fully completed. Ideally would be if we would move that part to the `mainModule`, but even it's like it's now then profile module needs some update where we need only `setSendUserStatus` which is a slot which will update global userProfile instance, and we don't need `QtProperty[bool] sendUserStatus` there at all.

@saledjenic this ticket is a bug in QML caused by `ba09fb47b` which turns out to be an incomplete feature in nim side and it's currently confusing. so I either fix the bug with currently proposed changes and then when the feature is completed in nim we update the respective parts or I really work to finish the feature. Do you have any task for this leftovers? @iurimatias how should we move on here?

**Comment by saledjenic** [comment]
@al

> > @alexandraB99 changes in commit `ba09fb47b` are caused because of changes introduced in the commit before `5464ab40f` and that's all. The point of exposed `userProfile` is the have global instance on the both qml and Nim side for reading/accessing a details about logged in user. Function `setSendUserStatus` is not part of the `userProfile`, it is currentlly part of the `profileModule` (but it should be part of the `mainModule` at the end).
> > > so you basically want me to update profile module? Is this like a missing change?
> > 
> > 
> > That should be done as a part of this ticket in order to have feature fully completed. Ideally would be if we would move that part to the `mainModule`, but even it's like it's now then profile module needs some update where we need only `setSendUserStatus` which is a slot which will update global userProfile instance, and we don't need `QtProperty[bool] sendUserStatus` there at all.
> 
> @saledjenic this ticket is a bug in QML caused by `ba09fb47b` which turns out to be an incomplete feature in nim side and it's currently confusing. so I either fix the bug with currently proposed changes and then when the feature is completed in nim we update the respective parts or I really work to finish the feature. Do you have any task for this leftovers? @iurimatias how should we move on here?

@alexandraB99 yes, in the commit `ba09fb47b` we introduced new global instance `userProfile` and it is used on many places on the qml side, but since this is just a single commit during refactoring phase we cannot do everything in a single go. 

Not all issues a qml only issues, so this ticket is an issue we need to fix, in order to fix this issue we need to deal with qml and nim also in a proper way. I don't get what's the problem?

**Comment by alexandraB99** [comment]
> > > @alexandraB99 changes in commit `ba09fb47b` are caused because of changes introduced in the commit before `5464ab40f` and that's all. The point of exposed `userProfile` is the have global instance on the both qml and Nim side for reading/accessing a details about logged in user. Function `setSendUserStatus` is not part of the `userProfile`, it is currentlly part of the `profileModule` (but it should be part of the `mainModule` at the end).
> > > > so you basically want me to update profile module? Is this like a missing change?
> > > 
> > > 
> > > That should be done as a part of this ticket in order to have feature fully completed. Ideally would be if we would move that part to the `mainModule`, but even it's like it's now then profile module needs some update where we need only `setSendUserStatus` which is a slot which will update global userProfile instance, and we don't need `QtProperty[bool] sendUserStatus` there at all.
> > 
> > 
> > @saledjenic this ticket is a bug in QML caused by `ba09fb47b` which turns out to be an incomplete feature in nim side and it's currently confusing. so I either fix the bug with currently proposed changes and then when the feature is completed in nim we update the respective parts or I really work to finish the feature. Do you have any task for this leftovers? @iurimatias how should we move on here?
> 
> @alexandraB99 yes, in the commit `ba09fb47b` we introduced new global instance `userProfile` and it is used on many places on the qml side, but since this is just a single commit during refactoring phase we cannot do everything in a single go.
> 
> The flow there was:
> 
> * commit `5464ab40f` introduced a new global instance `userProfile`
> * commit `ba09fb47b` updated qml files according the the instance introduce in the previous commit
> * now the rest of the code need to be aware of that change and that's a `profileModule`, so within this issue we need to update profile module properly (or at least property/methods related to send user status)
> 
> Not all issues a qml only issues, so this ticket is an issue we need to fix, in order to fix this issue we need to deal with qml and nim also in a proper way. I don't get what's the problem?

No, no. No problem, it is just confusing as it's not really a bug but a feature to be completed. Anyway, I did some changes as you suggested, so please have a look. However I can't find `saveSetting(Setting.SendUserStatus, status)` that you're mentioned in our chat as well as I'm getting an error when trying to build
`type mismatch: got <AccessInterface, bool>
but expected one of:
proc setUserStatus(self: View; status: bool)
  first type mismatch at position: 1
  required type for self: View
  but expression 'self.delegate' is of type: AccessInterface`

Please let me know either in comments or if you want to commit something please create a different commit so that I'm aware of what's going on.

**Comment by saledjenic** [comment]
I am closing this one since the issue is fixed in 
 - https://github.com/status-im/status-desktop/pull/4145

**Comment by saledjenic** [comment]
I am closing this one since the issue is fixed in 
 - https://github.com/status-im/status-desktop/pull/4145

**Pull request closed without merging**
