### PR TITLE
fix: Airdrop section of deployed NFT doesn't seem to apply darkmode

### LINKED ISSUE #11289: Airdrop section of deployed NFT doesn't seem to apply darkmode
After trying to deploy an NFT and viewing it in Desktop, I've noticed the "Airdrop" section doesn't seem to look well in darkmode:

Screenshot from 2023-06-28 11-50-39

Also, when clicking that "Airdrop" button, I see a green that look slike this:

Screenshot from 2023-06-28 11-51-02

That "fee" section looks a bit too black to my eyes, so looks like this is not using the correct color either.

### PR DESCRIPTION
**Pull request by caybro**
- fix some colors to look correct in dark mode too
- update/unbreak the corresponding storybook pages

Fixes #11289

### Affected areas

EditAirdropView

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Airdrop view:
image
image

image
image

Empty holders panel:
image
image

### CODE REVIEW

**Review by 0x-r4bbit — APPROVED** [review]
So much better

**Review by noeliaSD — APPROVED** [review]
Code LGTM! Tested!

Could you also check what's wrong with `HoldingsDropdwonPage`? The assets model and collectibles one are not displayed as it happend inside `EditAirdropViewPage`.

**Comment by caybro** [comment]
> Code LGTM! Tested!
> 
> Could you also check what's wrong with `HoldingsDropdwonPage`? The assets model and collectibles one are not displayed as it happend inside `EditAirdropViewPage`.

Done :)

**Comment by noeliaSD** [comment]
> > Code LGTM! Tested!
> > Could you also check what's wrong with `HoldingsDropdwonPage`? The assets model and collectibles one are not displayed as it happend inside `EditAirdropViewPage`.
> 
> Done :)

Tested! Thanks for the fix!

**Pull request merged**
