### PR TITLE
chore: bump nimqml and dotherside libs

### PR DESCRIPTION
**Pull request by emizzle**

### CODE REVIEW

**Comment by jrainville** [comment]
Hmm, there seems to be a bug compiling:
```
home/jenkins/workspace/nim-status-client_linux_PR-1691/src/app/node/core.nim(15, 27) Error: undeclared identifier: 'QNetworkAccessManager'
```
I remember seeing this in the past. I don't know why we're having it again

**Review by richard-ramos — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
there is something going on jenkins that this PR is not passing

**Comment by michaelsbradleyjr** [comment]
The error for all the builds is the same: `Error: undeclared identifier: 'QNetworkAccessManager'`.

I don't understand that, yet, because `QNetworkAccessManager` is part of the `QtNetwork` module and I would think it should be in a standard Qt install.

**Comment by emizzle** [comment]
Close in favour of https://github.com/status-im/status-desktop/pull/2277.

**Pull request closed without merging**
