### PR TITLE
chore: sign the flow only once if approval and transaction need to be placed once after another (swap flow)

### LINKED ISSUE #16337: Make a signing approval and transaction a single UI flow
Make signing approval/s and transaction/s as a single click action, without the need for a user to go explicitly through the authentication/signing flow more than once.

An example:
- At this moment swap tx cannot be placed if an approval is needed before that approval gets confirmed. That's currently done as a two-step process, firstly the user signs an approval, then waits for it to be confirmed then signs sending swap tx.
- The idea is to let the user do the signing only once and the backend should take care of the TXS order and if needed wait for their execution before placing other txs.

### PR DESCRIPTION
**Pull request by saledjenic**
The Swap flow now:
1. if approval not needed (swapping ETH)
  - run swap flow
  - click "Swap" button
  - review "Sign Swap" popup
  - click "Sign"
  - authenticate
2. if approval needed (swapping any ERC20 token)
  - run swap flow
  - click "Approve TOKEN" button
  - review "Approve spending cap" popup
  - click "Sign"
  - authenticate
  - button is in the "Approving TOKEN" state
  - when approval is executed, and "Swap" button becomes available, click it
  - review "Swap" popup
  - click "Swap" button **(no need to sign again here)**

Updated the following User Stories:
- SD-28
- SD-36
- SD-89

Closes #16337

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

**Comment by caybro** [comment]
@saledjenic these ui-tests failures look legit though:

```
13:26:34  3: FAIL!  : QmlTests::SwapSignModal::test_fromToProps(ETH) Compared values are not the same
13:26:34  3:    Actual   (): 
13:26:34  3:    Expected (): Sign Swap
13:26:34  3:    Loc: [/home/jenkins/workspace/s_linux_x86_64_tests-ui_PR-16484@2/storybook/qmlTests/tests/tst_SwapSignModal.qml(103)]
13:26:34  3: FAIL!  : QmlTests::SwapSignModal::test_fromToProps(DAI) Compared values are not the same
13:26:34  3:    Actual   (): 
13:26:34  3:    Expected (): Sign Swap
13:26:34  3:    Loc: [/home/jenkins/workspace/s_linux_x86_64_tests-ui_PR-16484@2/storybook/qmlTests/tests/tst_SwapSignModal.qml(103)]
```

**Review by alexjba — APPROVED** [review]
LGTM! 👍

**Review by alaibe — APPROVED** [review]

**Comment by saledjenic** [comment]
@anastasiyaig @virginiabalducci for this PR, in order to be fully sure about swap (not just because of these changes, but to ensure correctness for all cases) we should conduct the following tests on each chain separately (mainnet, optimism, arbitrum):
  - swap ETH for any ERC20 token
  - swap ERC20 token, where approval will be placed from the app, for ETH
  - swap ERC20 token, where approval will be placed from the app, for ERC20 token
  - swap ERC20 token, with  approval will be set beforehand, for ETH
  - swap ERC20 token, with  approval will be set beforehand, for ERC20 token

**Comment by virginiabalducci** [comment]
> * swap ETH for any ERC20 token
> * swap ERC20 token, where approval will be placed from the app, for ETH
> * swap ERC20 token, where approval will be placed from the app, for ERC20 token
> * swap ERC20 token, with  approval will be set beforehand, for ETH
> * swap ERC20 token, with  approval will be set beforehand, for ERC20 token

the following scenarios were tested for Arbitrum and Optimism and look good. 
Mainnet testing is in progress

**Comment by virginiabalducci** [comment]
Testing of scenarios on Mainnet have been tested and passed @saledjenic

**Review by virginiabalducci — APPROVED** [review]

**Pull request merged**
