### PR TITLE
Move community specific functions to chat_section

### LINKED ISSUE #4489: Move remaining community specific functions to chat_section

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4489

This moves the remaining community functions that are not general to the chat_section. It also fixes some small missing hooks (for members for example) 

There are other functions that will need to be moved, like the category ones and some others, but they are not yet fully implemented on the front-end, and in the case of categories, are being worked on by @borismelnik so I don't want to conflict with his work.

### CODE REVIEW

**Comment by Khushboo-dev-cpp** [comment]
hey @jrainville  I found an issue that if you have joined a community, and the admin of the community adds/deletes a channel, its is not updated in base_bc? are you aware if someone is already working on this? 
Also I think I've members part in my PR too. If I understood the description right!

**Comment by jrainville** [comment]
> Question: Let's say the maps and compounds were "perfect", would you still do some changes from time to time just to keep things fresh?

I know it's not implemented yet. I don't think anyone is working on it yet

> Also I think I've members part in my PR too. If I understood the description right!

Do you have a link?

**Comment by Khushboo-dev-cpp** [comment]
https://github.com/status-im/status-desktop/pull/4487

And what was the Question you asked ? I am not sure I follow.

**Comment by jrainville** [comment]
> And what was the Question you asked ?

I was just looking for the PR you were talking about to see if there was a conflict. You said there was a members part, though I don't see it.
Anyway, I checked your changes and it seems good. There doesn't seem to be a conflict and you don't have code that needs moving as far as I see it.

**Comment by Khushboo-dev-cpp** [comment]
alrighty :)
Sorry about the confusion

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
