### PR TITLE
refactor: replace `StatusSettingsLineButton` with StatusQ components

### PR DESCRIPTION
**Pull request by PascalPrecht**

### CODE REVIEW

**Review by iurimatias — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
@PascalPrecht I get this error with this branch

```
qrc:/main.qml:458:9: Type AppMain unavailable
qrc:/app/AppMain.qml:477:13: Type ProfileLayout unavailable
qrc:/app/AppLayouts/Profile/ProfileLayout.qml:88:9: Type AdvancedView unavailable
qrc:/app/AppLayouts/Profile/views/AdvancedView.qml:563:13: Type StatusSettingsLineButton unavailable
qrc:/imports/shared/status/StatusSettingsLineButton.qml: No such file or directory
```

**Comment by PascalPrecht** [comment]
@iurimatias I can't reproduce what you're running into. That line in `AdvancedView` doesn't even use `StatusSettingsLineButton` anymore as of this commit.

**Comment by PascalPrecht** [comment]
This is rebased but needs your approval @iurimatias

**Comment by iurimatias** [comment]
closing due to massive changes since then

**Pull request closed without merging**
