### PR TITLE
fix(@onboarding): back button on seed phrase

### LINKED ISSUE #5614: [Onboarding] Fix back key behavior when importing Seed Input Phrase
# Bug Report

## Description
Pressing back from “Enter Display Name” in the “Import Seed Phrase” flow, we go back to onboarding screen 1 and not the page where the Seed phrase was entered

## Steps to reproduce
1. Choose to create new keys
2. Choose to import seed phrase
4. Follow all steps and you reach Enter Display name view
5. Press the back button

#### Expected behavior
The flow returns to import seed phrase view

#### Actual behavior
The flow returns to onboarding screen

### Additional Information

- Status desktop version:
master
- Operating System:
macOS

### PR DESCRIPTION
**Pull request by alaibe**
fixes #5614

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by alexandraB99 — APPROVED** [review]
lgtm

**Review by iurimatias — CHANGES_REQUESTED** [review]
I couldn't get past the seed phrase step, the finalize button is not enabled

steps:
1. go to https://iancoleman.io/bip39/ and generate a random seed phrase
2. remote Status folder and run app
3. select already using status and import seed phrase

Screen Shot 2022-05-10 at 2 33 22 PM

**Comment by iurimatias** [comment]
another example, the button activates but says invalid seed phrase, this should be valid though

Screen Shot 2022-05-10 at 2 36 27 PM

**Comment by jrainville** [comment]
FYI, I revamped the whole importing a seed phrase flow in my PR https://github.com/status-im/status-desktop/pull/5632

So it's possible that your issue is fixed in my PR. I feel like this was a "user issue", because the UX was pretty bad.

**Comment by alaibe** [comment]
> I couldn't get past the seed phrase step, the finalize button is not enabled

This is a UI issue, I think Jo might have fixed that, you need to select the word or use the auto complete

> another example, the button activates but says invalid seed phrase, this should be valid though

Are all the combination of word valid?

**Pull request merged**
