### PR TITLE
fix(@desktop/chat): after reaching the top of chat history, unable to scroll down again

### PR DESCRIPTION
**Pull request by saledjenic**
InvitationBubble binding loop on height fixed.
Scroll down if you reach the top of the chat is not blocked any more.

Fixes: #3320

### CODE REVIEW

**Comment by saledjenic** [comment]
@Khushboo-dev-cpp please check this out as you managed to reproduce it, I am not able to reproduce this issue anymore using your `Status` data folder.

**Review by alaibe — APPROVED** [review]

**Comment by Khushboo-dev-cpp** [comment]
Hey @saledjenic Still doesn't work for me :(
Does it work with my data folder for you?

**Review by pinebit — APPROVED** [review]

**Comment by saledjenic** [comment]
> Hey @saledjenic Still doesn't work for me :(
> Does it work with my data folder for you?
> So after the apps launched and scroll right up I see the issue again. In case I jump to latest and start over it isn't reproduced

@Khushboo-dev-cpp [here](https://drive.google.com/file/d/1pLsVlqCauavXWwKJYKwp-GnDjNuiQbir/view?usp=sharing) is how it works for me within this branch (with changes I added). Before these changes I had the same issue as you recorded.

**Comment by Khushboo-dev-cpp** [comment]
> > Hey @saledjenic Still doesn't work for me :(
> > Does it work with my data folder for you?
> > So after the apps launched and scroll right up I see the issue again. In case I jump to latest and start over it isn't reproduced
> 
> @Khushboo-dev-cpp [here](https://drive.google.com/file/d/1pLsVlqCauavXWwKJYKwp-GnDjNuiQbir/view?usp=sharing) is how it works for me within this branch (with changes I added). Before these changes I had the same issue as you recorded.

Hey Sale! I tried it on machine again today. With no luck. The issue still exists but I wasn't able to find a solution so far ! As discussed, lets merge this and close it for now?

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Pull request merged**
