### PR TITLE
feat(wallet): add support for proxy basic auth for market providers

### PR DESCRIPTION
**Pull request by dlipicar**
### What does the PR do

Cherrypicks https://github.com/status-im/status-desktop/pull/15913 to properly get Proxy credentials from env variables.
Cherrypicks https://github.com/status-im/status-desktop/pull/16093#issuecomment-2288491868 to get API keys injected by CI.

Implemented changes to get env variable `STATUS_BUILD_PROXY_STAGE_NAME`

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Comment by dlipicar** [comment]
@siddarthkay cherrypicked the jenkins lib version change to release. You see any problem with that?

**Comment by siddarthkay** [comment]
> @siddarthkay cherrypicked the jenkins lib version change to release. You see any problem with that?

Hmm let me verify..

**Comment by siddarthkay** [comment]
@dlipicar : looks good. safe to proceed.

**Review by Samyoul — APPROVED** [review]
It'll be great to see these changes in the next RC

**Comment by dlipicar** [comment]
Ran some tests. The PR build is trying to hit the prod endpoint, while the test endpoint should be used. Mobile has the same problem, we'll probably need to introduce some status-go changes

**Review by virginiabalducci — APPROVED** [review]

**Pull request merged**
