### PR TITLE
fix(onboarding): Hide context menu for password fields

### PR DESCRIPTION
**Pull request by borismelnik**
Closes: #5547

### What does the PR do

Hide context menu for password fields

### Affected areas

Input.qml

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
I don 't think this is the correct solution, the paste should work instead

**Comment by borismelnik** [comment]
> I don 't think this is the correct solution, the paste should work instead

As you wish, but I'm based on
```
Expected behavior

Nothing appeared, it's impossible to paste any text in the Password field
```

And I agreed. Most of app not support it cos copy/paste passwords isn't secure. @iurimatias

**Comment by elina2015** [comment]
@iurimatias cc @borismelnik So, what do we decided about copy/paste? Should we show the Paste menu and provide the Ctrl+V option in the passwords fields?

**Comment by PascalPrecht** [comment]
> As you wish, but I'm based on

I believe there's a misunderstanding here. What is stated under `Expected behaviour` seems to be the description of what is happening at the moment.

#5547 even says in the title that pasting via CTRL-V or context menu doesn't work (which should be fixed).

**Comment by borismelnik** [comment]
Base on last discussion, I close the PR cos its paste working already in master.

**Comment by PascalPrecht** [comment]
According to https://github.com/status-im/status-desktop/issues/5547#issuecomment-1125381791 it's not

**Comment by elina2015** [comment]
Tested on the latest [master ](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220518-122121-8eff1b.dmg/*view*/) - the Paste button now works correctly and the copied text appears in the Password fields.

**Pull request closed without merging**
