### PR TITLE
fix(@desktop/community): When selecting top communities channel, they all appear selected

### LINKED ISSUE #4166: When selecting top communities channel, they all appear selected
# Bug Report

## Description

image

Only Desktop channel should appear selected

## Steps to reproduce

Go to a community with multiple channel, select a random one, then select the top one of the list

#### Expected behavior

Only top channel should appear selected

#### Actual behavior

Most channel appear selected

### Additional Information

- Status desktop version: release/0.4.0
- Operating System: Linux

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fix(@desktop/community): When selecting top communities channel, they all appear selected

Usage of HoverHandler instead of containsMouse property of MouseArea, solves the issue

fixes #4166

### What does the PR do

This PR points to the correct version of StatusQ that contains fix for this issue - https://github.com/status-im/StatusQ/pull/496

Fixes the issue of the chat list getting a highlight even when they are not really hovered

The issue is caused by the fact that the MouseArea returns containsMouse as true even when the item is not hovered.
The issue is reproduced when the model changes dynamically in the StatusChatList, thus causing the StatusChatListItem to be recreated and
this is when the containsMouse remains true even though the item is not hovered.
I see a bunch of issues in the QT bug list with regards to the containsMouse property but are still open.
A solution to this is to use HoverHandler which is a more reliable way getting hovered events for an item.

### Affected areas

Community

### Screenshot of functionality

https://user-images.githubusercontent.com/60327365/144488893-409e5d5a-2191-489b-b398-54cd553d6285.mov

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]
Love it when updates in 3rd party libs fix bugs! 
Great great work @Khushboo-dev-cpp !

**Review by borismelnik — COMMENTED** [review]
Just one think - remove `hoverEnabled: true` from `MouseArea` to avoid potential conflicts pls :)

**Comment by Khushboo-dev-cpp** [comment]
> Just one think - remove `hoverEnabled: true` from `MouseArea` to avoid potential conflicts pls :)

Hey Boris I have updated the statusQ PR with your comment :)

**Review by borismelnik — APPROVED** [review]
Great!

**Pull request merged**
