### PR TITLE
fix(chatMessages): line breaks in message were not respected when pasting text

### LINKED ISSUE #3510: Pasting text in Chat Box Doubling the line breaks and final message removing all empty lines
**Version:** StatusIm-Desktop-v0.3.0-beta-a8c37d.tar.gz
**System:** Arch Linux

Line breaks in software behaving a little weird.

Whenever I paste something into the chatbox. It is doubling all the line breaks. So chat box becomes very confusing. But final message doesn't have any empty lines.

https://drive.google.com/file/d/1J0rAAVSXHUR8Fs3_LFRxvu6BXFk_z9fl/view?usp=sharing

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #3510 
Depends on https://github.com/status-im/status-desktop/pull/4889

### What does the PR do
When pasting 
A
B

C

D

in text input ,
A
B
C
D
was received

### Affected areas
Chat messages

### Screenshot of functionality
https://user-images.githubusercontent.com/31625338/156405606-e9517525-9ba1-4a66-9b54-ff3135c24200.mov

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Good job.

Just a tip/request for next time, can you make the base the other branch, that way we only review the new commits. In this case it was easy since it was only two commits, but just in case.

**Comment by alexandraB99** [comment]
> Good job.
> 
> Just a tip/request for next time, can you make the base the other branch, that way we only review the new commits. In this case it was easy since it was only two commits, but just in case.

You're totally right, I missed that part. Updated, thanks!

**Review by richard-ramos — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
this scenario still removes lines

```
A
B

C




D

```

https://user-images.githubusercontent.com/176720/156649319-9d2b97f2-2777-4608-9730-721b394d6d04.mov

**Comment by alexandraB99** [comment]
> this scenario still removes lines
> 
> ```
> A
> B
> 
> C
> 
> 
> 
> 
> D
> ```
> 
>  Screen.Recording.2022-03-03.at.3.40.08.PM.mov

After discussing with @richard-ramos , this might be because of https://github.com/status-im/markdown parsing issues as it seems it might not support many empty paragraphs as  we send ["a\n\n\n\nb"] and receive  ["<p>a</p>\n\n<p>b</p>\n"].

**Pull request merged**
