### PR TITLE
feat: use new pending transfer API

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes: #2323 and https://github.com/status-im/status-desktop/issues/2222
Depends on: https://github.com/status-im/status-go/pull/2197 being merged first

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-go/pull/2197 is merged

**Comment by richard-ramos** [comment]
> Depends on: status-im/status-go#2197 being merged first

We can merge this PR now

**Comment by richard-ramos** [comment]
Can you consistently reproduce the issue?
I think it might be something else, as the code to generate accounts was not modified.
Here's my attempt at generating an account:
https://user-images.githubusercontent.com/1106587/116125678-ccb8d280-a693-11eb-8a9b-c6019f8d3038.mp4

**Comment by anastasiyaig** [comment]
@richard-ramos i missed the details: i was able to reproduce the issue with newly created account and first you need to enter wrong password when adding new wallet, this crashes with `cannot retrieve a valid key for a given account: could not decrypt key with given password
ERR 2021-04-26 22:59:03+03:00 TODO: if user is logged in, logout         topics="main" tid=3446599 file=nim_status_client.nim:155
Object 0x7fc46fe29630 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/app/AppLayouts/Wallet/components/GenerateAccountModal.qml:95: function() { [native code] }
Traceback (most recent call last)
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2331/src/nim_status_client.nim(215) nim_status_client
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2331/src/nim_status_client.nim(157) mainProc
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2331/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGABRT: Abnormal termination.
`

**Comment by anastasiyaig** [comment]
please merge it to master

**Pull request merged**
