### PR TITLE
fix(Community): Updated create new channel popup

### LINKED ISSUE #5636: [New channel] Adjust text color based on dark/light theme
### Description
Implement a function to determine if the text color should be white or black depending on the contrast of the background color. See `StatusLetterIdenticon.qml` as reference, and move this function somewhere accessible from both sides.

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #5636
Depends on https://github.com/status-im/StatusQ/pull/671

### What does the PR do
Updates create new chat popup based on designs

### Affected areas
Create new chat popup

### Screenshot of functionality
https://user-images.githubusercontent.com/31625338/168133941-ef51de86-3b55-43ec-b862-4839afeae310.mov

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Looks good. The only thing is what was the final consensus on the `#`. Did we decide to remove it, or just not make it part of the placeholder, but just outside the input?

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Comment by alexandraB99** [comment]
> Looks good. The only thing is what was the final consensus on the `#`. Did we decide to remove it, or just not make it part of the placeholder, but just outside the input?

@jrainville based on this https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2975%3A489237 I guess just keep it as placeholder? or you mean something else?

**Comment by jrainville** [comment]
Ah ignore my comments, Anthony already has a PR to remove it https://github.com/status-im/status-desktop/pull/5728

**Pull request merged**
