### PR TITLE
fix: invalid variable being used for identicons in transaction commands

### LINKED ISSUE #2533: Send / receive chat commands are outdated
**steps**

1. start a 1 on 1 chat
2. click send transaction and/or request transaction

Result: it display a send dialog, with the to/from field needing to be specified, also TO field can't be specified 

`hod=wakuext_getContactByID
qrc:/app/AppLayouts/Chat/ChatColumn.qml:413: ReferenceError: activeChatIdenticon is not defined`

Screenshot 2021-05-11 at 12 16 44

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #2533

https://user-images.githubusercontent.com/1106587/121940982-b4247a80-cd1c-11eb-911c-8159e2345c49.mp4

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
1. Sign and send crashes the app

`Traceback (most recent call last)
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2704/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2704/src/nim_status_client.nim(162) mainProc
/Users/jenkins/workspace/s-desktop_branches_macos_PR-2704/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGBUS: Illegal storage access. (Attempt to read from nil?)
`



2. Sign and send appears both for sender and receiver - not sure if this is expected but might be existing functionality

**Comment by anastasiyaig** [comment]
however, if this fix only fixes the possibility to correctly call request / send (might be so) - then it is okay, i will handle the issues separately @richard-ramos , just let me know

**Comment by richard-ramos** [comment]
I'd prefer to handle these as a separate issue, as this PR only fixes the issue described in #2533

**Comment by anastasiyaig** [comment]
this PR will be rebased on top of https://github.com/status-im/status-desktop/pull/2711 to let me test chat commands (sending / requesting funds) too

**Comment by anastasiyaig** [comment]
@iurimatias  in terms of interaction with simple dapp: 

- cant request tokens . sign messages and etc -> it works in Master

Screenshot 2021-06-17 at 12 41 03


`DBG 2021-06-17 12:39:55+03:00 Verifying mailserver connection state...   topics="mailserver model" tid=6621794 file=model.nim:186
qrc:/app/AppLayouts/Browser/BrowserLayout.qml:170: TypeError: Cannot read property 'name' of undefined
`

Can we fix that please? It basically blocks any dapps usage

**Comment by iurimatias** [comment]
@anastasiyaig I'm merging this into 2711, so I can rebase everything there

**Pull request merged**
