### PR TITLE
chore: Update status-go on permitted channel removal fix

### LINKED ISSUE #15008: When a channel is removed, update or remove the associated permisisons
### Description

Currently, when a channel is deleted, the permissions stays as is.

What should happen is the permissions that link to this channel should be updated to no longer contain that channel.
As a side-effect, the permissions that no longer contain any channels should be deleted.

Do note that this should **not** trigger a re-evaluation, since we there is nothing to re-evaluate, the channel is gone.

### Acceptance criteria

- When a channel is deleted, all permissions that had this channel in their list are updated to no longer have that channel
- If a permission had only that channel in its list, the permission is also deleted

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #15008
Waits https://github.com/status-im/status-go/pull/5297

### What does the PR do

update status-go

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/2522130/c2e47ba3-66fb-463d-bb21-9f7747607ccb

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
is the status-go PR already merged?

**Review by mprakhov — APPROVED** [review]
Please, add a link to status-go PR in commit description

**Comment by MishkaRogachev** [comment]
@jrainville @mprakhov , i've added a link to status-go PR

**Comment by MishkaRogachev** [comment]
latest master already contains my changes

**Pull request closed without merging**
