### PR TITLE
fix: update community invite text in push notification

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2505.

Changes the community invitation text notifications from

“Upgrade to see a community invitation”

to

**InviteUsersToCommunity**
```golang
fmt.Sprintf("You have been invited to the community %s", community.Name())
```

**ShareCommunity**
```golang
fmt.Sprintf("Community %s has been shared with you", community.Name())
```

### NOTE
This PR relies on [a status-go PR](https://github.com/status-im/status-go/pull/2263) which needs to be merged before first, then the commit hash updated in this PR, before this PR is merged.

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@emizzle 

when i share the community, i still see the old notification:



to reproduce it: 

1. install any mobile status build 
2. create a community on mobile device
3. create account on desktop build as well
4. add them both to contacts (user created on mobile and user created on desktop)
5. as user created on mobile, navigate to community -> three dots -> community info -> click Share icon at the top right -> select a contact to share community with
6. check desktop notification

Is it possible to fix?

**Comment by emizzle** [comment]
@anastasiyaig As this change was done in Status-go, the device doing the sharing/inviting needs to have the updated changes in status-go. Until we get the underlying PR merged in to develop, we won't be able to see this fixed in mobile. However, if you repeat the test above with the same build of desktop from this PR, you should see the results you're after. This is because this build from CI will have the status-go changes.

**Comment by anastasiyaig** [comment]
basically i tried this, i used the windows build as second one instead:

Screenshot 2021-06-25 at 22 15 00

**Comment by anastasiyaig** [comment]
I suggest to merge it (when the appropriate status-go PR is merged and so on) , so I will retest it in master and see. 

Missing **share** functionality on desktop should be discussed separately

**Pull request merged**
