### PR TITLE
fix: Move gif to status-go

### LINKED ISSUE #4355: Move gif to status-go
Currently, call to tenor api is done in the client, move the call to status-go

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
### What does the PR do

Move the calls to Tenor to status_go

### Affected areas

chat

fixes #4355

### CODE REVIEW

**Review by alaibe — COMMENTED** [review]
Favorites/recent should also be managed by status-go itself I believe.

**Review by noeliaSD — APPROVED** [review]

**Comment by Khushboo-dev-cpp** [comment]
> Favorites/recent should also be managed by status-go itself I believe.

Hey anthony for recents and favourites we simply save them to settings db. Should we still do them in status_go?

I think the point here is to have a reusable service between mobile and desktop and in that case it definitely makes more sense to move it over to status_go

**Comment by Khushboo-dev-cpp** [comment]
@alaibe Have moved it to status_go. Please check :)

**Review by alaibe — APPROVED** [review]

**Review by abhi-status — APPROVED** [review]

**Comment by iurimatias** [comment]
https://github.com/status-im/status-lib/pull/172

**Comment by iurimatias** [comment]
https://github.com/status-im/status-go/pull/2505

**Pull request merged**
