### PR TITLE
tests: reduce timeout for saved address test

### PR DESCRIPTION
**Pull request by anastasiyaig**
### What does the PR do

Reduce timeout when adding saved address, because it seems https://github.com/status-im/status-desktop/issues/16121 is not happening anymore

### CODE REVIEW

**Comment by saledjenic** [comment]
@anastasiyaig please check the comment here https://github.com/status-im/status-desktop/issues/16121#issuecomment-2295868841

It's much better to do a repetitive check if saved addresses got added up to the max waiting time which should be set to some high value, like 20 seconds, then wait for some hardcoded time and then check if the address was added. We should update tests in that way.

**Comment by anastasiyaig** [comment]
@saledjenic this is the check

```
driver.waitFor(
            lambda: name in settings_saved_addresses.get_saved_address_names_list(),
            configs.timeouts.UI_LOAD_TIMEOUT_MSEC),
```
it waits for 5 seconds

**Comment by saledjenic** [comment]
> it waits for 5 seconds, checking the list all the time within these 5 seconds

If so, then it doesn't matter if it's 5 or 20 seconds, even better to be 20, cause that will fail only if the network is really congested a lot, otherwise it will never wait that long, but just a necessary amount of time.

**Comment by anastasiyaig** [comment]
> > it waits for 5 seconds, checking the list all the time within these 5 seconds
> 
> If so, then it doesn't matter if it's 5 or 20 seconds, even better to be 20, cause that will fail only if the network is really congested a lot, otherwise it will never wait that long, but just a necessary amount of time.

alright, replaced with 20 seconds timeout

**Review by saledjenic — APPROVED** [review]

**Review by antdanchenko — APPROVED** [review]

**Pull request merged**
