### PR TITLE
[BackupSeedPopup]: Fixed warning message size based on text size

### LINKED ISSUE #8402: Settings -> Backup seed phrase: warning text background is not resized when using large text size
# Bug Report

After setting XXL text size from Appearance settings, the red warning background from Backup seed phrase popup is not resized based on the new text size

Screenshot 2022-11-23 at 12 06 44

## Steps to reproduce
1. Go to Settings -> Appearance
2. Set font size to XXL
3. Go to Settings -> Back up seed phrase

#### Expected behavior
The textbox with red background should be resized to cover the new text size
#### Actual behavior
The textbox with red background is not resized and the text is overflowing
### Additional Information

- Status desktop version:
- Operating System: MacOs

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #8402

### What does the PR do
Backup Seed Phrase Popup: Fixed warning message size based on text size

### Affected areas
Backup Seed Phrase Popup

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/31625338/eaec85bd-ec00-43e3-ad6c-bc8bafea4daf

### CODE REVIEW

**Review by caybro — COMMENTED** [review]
Looks good but would be nice to also fix the width/margins, so that the text doesn't go over the scrollbar

**Comment by alexandraB99** [comment]
> Looks good but would be nice to also fix the width/margins, so that the text doesn't go over the scrollbar

@caybro done

pu

**Review by caybro — APPROVED** [review]
LGTM :+1:

**Review by alexjba — APPROVED** [review]
LGTM! Looks very nice now 👍

**Pull request merged**
