### PR TITLE
fix(StatusImageCrop): fix artefacts while editing a cropped image

### PR DESCRIPTION
**Pull request by stefandunca**
### Fixes: #6640

This PR bumps the StatusQ to include the fix: https://github.com/status-im/StatusQ/pull/835

### CODE REVIEW

**Comment by stefandunca** [comment]
@endulab please test changes. 🍀

**Comment by endulab** [comment]
@stefandunca can you fix ui tests ?

**Comment by stefandunca** [comment]
> @stefandunca can you fix ui tests?

Done, thanks for the heads up. Please have another look.

**Comment by endulab** [comment]
Tested and approved:

image

**Review by endulab — APPROVED** [review]

**Pull request merged**
