### PR TITLE
fix(@desktop/profile): Fix loading the correct settings

### LINKED ISSUE #3624: settings lost on new install
on master, running a new version is reseting the settings. e.g if a community is joined, certain tabs are enabled etc.. they all disapear

### PR DESCRIPTION
**Pull request by alaibe**
Since https://github.com/status-im/status-desktop/commit/e0c53b7012354023e367c33093598f7523063aa6 settings where loaded
according to the username while they should be loaded after the public
key

As the public key is only available once the login happened, it needs
to be set when the profile is being initialized

fixes #3624

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Review by saledjenic — CHANGES_REQUESTED** [review]
@alaibe you cannot just like that delete the changes done in the e0c53b7 as they are part of the OS Keychain feature done here 8af104a1 Since user's public key is not accessible before we login a user, but only his username, in that commit we switched to storing settings in a local file named by username. As I see here this issue should be present only if user tries to login with `Status` data folder created before we introduced OS Keychain login feature, for new accounts it works well.

So what you need to do here, is just to add a procedure which will make the app backward compatible. 

When user starts new app for the first time only once and login button is clicked local file with new three words username will be created, in that moment you will know user's public key also and you just need to copy properties from the local file named by the public key to the new local file named by the username.

**Comment by saledjenic** [comment]
> @saledjenic sadly it is not that simple, there is slight concern of security when changing the settings filename to be the alias. 

What is an issue with coping properties from the ini file named by user's public key to the new file named by user's username? We should do that only once for users who are logging in a new app version with an old Status folder, to ensure that the app is backward compatible, and delete file named by user's public key after that.

Also I am not sure what security we're talking about? None of the properties stored in either global or user specific local ini file don't contain any important info. They just store values about app settings for specific user, like... is wallet section enabled or disabled, what language is the default one for the app and so.

> Also an improvement would be to encrypt the profile settings (see new issue: #3660)

According to my answer above, this is absolutely unnecessary. There are no any important info in local .ini files which may be used for any hack and compromising a user's personal info/accounts. Maybe the most exposed meaningful info is actually the name of the file which is a user's public key actually, that's one more reason to use user's username instead.

> Please see second commit of this PR where I keep 2 files, the account settings which are being accessed pre-login and the profile settings which are accessed after login and ideally should be encrypted

I am against having one more user specific local .ini file, it is unneeded and redundant.

> Please let me know what you think know. What really mislead me is that fact that we access the profile view while it is not really loaded, maybe we could create an account view?

If you start the app form an empty state, file named by user's username won't be created until you login the app. In that moment local .ini file will be created containing appropriate properties. Naming is the thing of preference... it could be named either account or profile, but maybe account is better because we're storing there settings per account. But no need to change that in this moment.

> Also I am not on Mac OS so I cannot test the keychain feature.

Np, I will test when it's done.

**Comment by saledjenic** [comment]
I added this new issue [here](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/3661), which can be done even before this fix, cause I think that coping properties from a local file named by user's public key to a file named by user's username may be easier after that.

One thing more, maybe you can even just rename that file named by user's public key to new name by user's username, and add `storeToKeychain` property to that renamed file.

**Comment by alaibe** [comment]
I am not saying that out of the blue, I shared the settings file to the security team and it was their recommendation. A property of having the file name after the chat key is that before login, you don't know which file is associated with which alias. Indeed the alias is derived from the public key. There is a similar things for the accounts db, In this db, there is no mapping information for the alias <=> chat key, there is another id which is also derived from the chat key. I only did it that way based on recommendation I received.

**Comment by saledjenic** [comment]
> I am not saying that out of the blue, I shared the settings file to the security team and it was their recommendation.

As I said in the ticket you logged #3660 _we can do that_ but not sure if that is really needed since we don't keep there any important info.

Yes, the only info which identifies a user, before he logs in, is 3 words username. Public key is available once he is logged in. That is why I suggested to keep only user specific local file named by username instead of public key.

**Review by saledjenic — APPROVED** [review]
We are going to proceed with encrypting locally stored file named by user's public key.

**Pull request merged**
