### PR TITLE
fix(nim-tests): split tests into individual targets

### PR DESCRIPTION
**Pull request by jakubgs**
Otherwise combining separate `nim` calls with `;` results in only the last one informing `make` call what exit code the whole target had.

Resolves:
- https://github.com/status-im/status-desktop/issues/16545

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
The tests will fail, I'll ping people to add commits to this so we can fix the tests and get this merged

**Comment by jrainville** [comment]
Seems like it fails, but for a different reason:
```
[2024-10-17T17:26:50.167Z] + make tests-nim-linux

[2024-10-17T17:26:50.167Z] bash: nim: command not found

[2024-10-17T17:26:50.167Z] Makefile:857: recipe for target 'nim-test-run/test/nim/collectibles_model_test.nim' failed
```

**Comment by jakubgs** [comment]
Yeah, that's just a simple fix, I removed `| dotherside` dependency while testing.

**Comment by jakubgs** [comment]
For some reason it refuses to run the tests in parallel:
```
Makefile:857: recipe for target 'nim-test-run/test/nim/message_model_test.nim' failed
```
Need to figure that one out.

**Comment by jakubgs** [comment]
It seems that indeed it is running in parallel, we just can't tell because `nimbus-build-system` is hiding a lot of logs.

**Comment by jakubgs** [comment]
I don't think current failures are related to my fixes, it's the tests failing.

**Comment by siddarthkay** [comment]
975bep

**Comment by jrainville** [comment]
> I don't think current failures are related to my fixes, it's the tests failing.

Yeah I think you're right. I know the message_model_test was broken already and it seems to be shown in the logs.

I can fix that one. @dlipicar can you check the activity and collections test failures please :pray: 

We can push in this branch

**Comment by dlipicar** [comment]
@jrainville Activity tests weren't failing as far as I could see. Fixed the collectibles ones

**Comment by jrainville** [comment]
@jakubgs we fixed the tests that were failing locally and it's still failing. I think there is some sort of compilation or linking error?

**Comment by caybro** [comment]
Yes, a link problem:
```
16:58:18  CC: message_model_test.nim
16:58:22  Hint:  [Link]
16:58:22  g++: error: vendor/DOtherSide/build/lib/libDOtherSideStatic.a: No such file or directory
16:58:22  Error: execution of an external program failed: 'g++  @collectibles_model_test_linkerArgs.txt'
16:58:22  Makefile:857: recipe for target 'nim-test-run/test/nim/collectibles_model_test.nim' failed
16:58:22  make: *** [nim-test-run/test/nim/collectibles_model_test.nim] Error 1
16:58:31  Hint:  [Link]
16:58:31  g++: error: vendor/DOtherSide/build/lib/libDOtherSideStatic.a: No such file or directory
16:58:31  Error: execution of an external program failed: 'g++  @message_model_test_linkerArgs.txt'
16:58:31  Makefile:857: recipe for target 'nim-test-run/test/nim/message_model_test.nim' failed
16:58:31  make: *** [nim-test-run/test/nim/message_model_test.nim] Error 1
```

**Pull request merged**
