### PR TITLE
fix(Chat): align emojis within chat inputs properly

### LINKED ISSUE #1944: Chat input field & emoji issue
### Chat inpput field's hight increase when I insert an emoji.
Input field should have a fixed hight

https://user-images.githubusercontent.com/52249767/109635413-9dca2880-7b4a-11eb-864f-2da663b033f4.mov

### Align emojis with text
Screenshot_2021-03-02_at_11_27_37

### PR DESCRIPTION
**Pull request by PascalPrecht**
Fixes #1944

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
there is still a change with the input height, see video

https://user-images.githubusercontent.com/176720/112162107-1fe5c400-8bc2-11eb-96d0-717d21cca919.mov

**Comment by PascalPrecht** [comment]
Very sorry to disappoint here but... as soon as I adjust the default height of the input field so that it doesn't have this little jump anymore, we're running into the same issue we're having in #2018 

As mentioned there, I've wrestled with this for many hours. Twice actually, once for the chat input, once for the timeline input and I can't get rid off this weird behaviour that that text area is out of the scrollview's viewport by default **until** it gains focus.

Also, forcing active focus doesn't fix it either, you have to *click* to make the text adjust to it's proper position.

**Comment by iurimatias** [comment]
so given what was discussed, this is acceptable

**Comment by PascalPrecht** [comment]
> Very sorry to disappoint here but... as soon as I adjust the default height of the input field so that it doesn't have this little jump anymore, we're running into the same issue we're having in #2018
> 
> As mentioned there, I've wrestled with this for many hours. Twice actually, once for the chat input, once for the timeline input and I can't get rid off this weird behaviour that that text area is out of the scrollview's viewport by default **until** it gains focus.
> 
> Also, forcing active focus doesn't fix it either, you have to _click_ to make the text adjust to it's proper position.

^ This whole comment was actually related to #2018

**Pull request merged**
