### PR TITLE
fix(Communities): ensure app remembers hidden community intro banners

### LINKED ISSUE #1960: Remember my decision when I close the intro container in community
https://user-images.githubusercontent.com/52249767/109809863-17d0df00-7c29-11eb-866d-c5b2b172ac13.mov

### PR DESCRIPTION
**Pull request by PascalPrecht**
Fixes #1960

### CODE REVIEW

**Review by iurimatias — CHANGES_REQUESTED** [review]
it doesn't fully work with the following steps:

1. go to a community and click the X
2. go to the public chats
3. go back to the community

result: the banner is back there again

also, we would be nice if this show/hide behaviour was done per community (i.e if I go to community A and hide it, then go community B I should still see the banner)

**Review by jrainville — COMMENTED** [review]
Ah I know why it doesn't work. There is no signal being emitted when we push to an array, because the setting itself doesn't change; the setting is the array and the ref is the same.

You'd need to call a function that manually calls a signal when you change a setting and listen to that signal in the community column.

**Comment by PascalPrecht** [comment]
>  it doesn't fully work with the following steps:

Actually, that's what I've tested and I can't reproduce this bug. I'm reassigning the appsettings, which made it work.

**Comment by iurimatias** [comment]
it works for me now, maybe I was in the wrong branch or something

**Pull request merged**
