### PR TITLE
uiux: ajdust app tab icons to have the correct size

### LINKED ISSUE #1843: Update tab bar icons
Somehow the browser icon is smaller and I have updated the Status Updates logo. Best way to make sure everything is consistent and right update all icons with icons that you can find here: https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1968%3A13644

Screenshot_2021-02-15_at_10_38_01

 **Design** (Dont mind the icons order...)
Screenshot_2021-02-15_at_10_37_56

Also please fix the outline of the dot indicator is adjusting when its color also on hover state on both dark and light mode.
Screenshot 2021-02-15 at 10 44 30

### PR DESCRIPTION
**Pull request by PascalPrecht**
Closes #1843

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by iurimatias** [comment]
@PascalPrecht is this being applied to community icons as well?

**Comment by PascalPrecht** [comment]
@iurimatias not sure which ones you're referring to, but this PR tackles the ones mentioned in https://github.com/status-im/status-desktop/issues/1843

**Comment by iurimatias** [comment]
I mean these ones:

Screen Shot 2021-04-20 at 1 27 19 PM

**Comment by PascalPrecht** [comment]
As discussed offline: Iuri was referring to the community image identicons (or letter identicons for that matter).

These are not actually icons and were/are not updated as part of this PR (also don't need update as far as I'm aware).

**Pull request merged**
