### PR TITLE
fix(Chat): Reuse chat root store connections and fix chat quick actions when blocked

### LINKED ISSUE #10570: Reuse connections to 1to1 chat contact details defined in RootStore for: PinnedMessages.qml, ChatColumnView.qml
It may not be in the scope of an issue, but if you move those connections to the store, you can reuse them elsewhere: PinnedMessages.qml, ChatColumnView.qml and etc. 
Or you can just open an issue and assign it on me :)

_Originally posted by @MishkaRogachev in https://github.com/status-im/status-desktop/pull/10477#discussion_r1186128313_

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #10570

### What does the PR do

* Reuse chat root store connections
* Fix quick actions for blocked chat

### Affected areas

Chat

### Screenshot of functionality

Screenshot 2023-05-08 at 17 44 02

### CODE REVIEW

**Review by alexjba — APPROVED** [review]
LGTM! Thanks for this! 🍻

**Review by igor-sirotin — APPROVED** [review]
👍

**Review by igor-sirotin — APPROVED** [review]
👍

**Comment by igor-sirotin** [comment]
lol, double approval! 😄

**Pull request merged**
