### PR TITLE
fix(@desktop/notifications): nothing happens after clicking on any notification

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `StatusQ` PR:
- https://github.com/status-im/StatusQ/pull/737

Fixes: #5935

### CODE REVIEW

**Review by alexandraB99 — APPROVED** [review]
looks good, didn't test though

**Comment by iurimatias** [comment]
I can't trigger the notifications, perhaps i'm doing somethign wrong? I tried one one chats, another tab selected and sending a mention. I get a normal notification but not the ephemeral one

**Review by elina2015 — APPROVED** [review]
Tested and Approved

**Comment by saledjenic** [comment]
> I can't trigger the notifications, perhaps i'm doing somethign wrong? I tried one one chats, another tab selected and sending a mention. I get a normal notification but not the ephemeral one

@iurimatias if you were using 2 apps on the same machine that's normal, cause clicking send message on the other app makes that other app the top most, and that means the app receiving a message and displaying notification is not the top most app since ephemeral notifications will be displayed only while your app is active, otherwise you will receive OS notification. Bast thing is to ask somebody to send you a mention message on the chat which is not the active one while the app receiving a message is the top most app or to use mobile app to send a message.

**Review by borismelnik — APPROVED** [review]

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
