### PR TITLE
chores(@desktop/chat): add guard when buying stickers

### PR DESCRIPTION
**Pull request by alaibe**
Call the same function as to when we do a transaction to validate
the argument. From there we validate that the gas in an int.

sister PR of #3071

@anastasiyaig if you could double check that buying sticker pack still work?

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Review by pinebit — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@alaibe can the issue be related to the changes made in this PR?

```
`/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(566) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/status/signals/core.nim(74) receiveSignal
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/status/signals/core.nim(69) processSignal
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/eventemitter.nim(38) emit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/app/login/core.nim(47) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/app/login/core.nim(31) handleNodeLogin
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/eventemitter.nim(38) emit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/eventemitter.nim(32) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/nim_status_client.nim(173) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/app/wallet/core.nim(85) checkPendingTransactions
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/status/wallet.nim(115) checkPendingTransactions
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/status/wallet.nim(99) confirmTransactionStatus
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/eventemitter.nim(38) emit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/src/app/chat/event_handling.nim(169) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-3076/vendor/nimbus-build-system/vendor/Nim/lib/pure/strutils.nim(1087) parseInt
Error: unhandled exception: invalid integer:  [ValueError]`

**Comment by alaibe** [comment]
@anastasiyaig it seems it is a different code path. This is PR is not merged yet, did you get this issue on this specific branch? or on master?

**Comment by anastasiyaig** [comment]
originally i received it in 307 PR branch , i will try in master

**Comment by alaibe** [comment]
I'll investigate too

**Comment by anastasiyaig** [comment]
i was able to reproduce the issue in beta11 as well

**Pull request merged**
