### PR TITLE
fix(@desktop/wallet): Fix for market values not displayed on Asset details view

### LINKED ISSUE #9055: Market values missing on AssetDetailsView
### Description

Market values missing on AssetDetailsView

Seems like the data coming form status-go is updated but corresponding nim side is not

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
closes #9055 

### What does the PR do

Market values not displayed on wallets asset view

the statusgo structure has changes but the nim side update was missing

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Screenshot 2023-01-11 at 4 04 30 PM

### CODE REVIEW

**Comment by caybro** [comment]
@dlipicar doesn't this conflict with your number formatting fixes?

**Comment by dlipicar** [comment]
> 

It does...
@Khushboo-dev-cpp I'm doing similar changes here https://github.com/status-im/status-desktop/pull/8911/files#diff-6eab90137e892ecb8e060c536dc726ffc2883e9661b087f5c8159d192115c55e, so I don't think this PR will be needed when I merge my changes (which will happen as soon as the e2e tests stop failing :D)

**Comment by Khushboo-dev-cpp** [comment]
> > 
> 
> It does... @Khushboo-dev-cpp I'm doing similar changes here https://github.com/status-im/status-desktop/pull/8911/files#diff-6eab90137e892ecb8e060c536dc726ffc2883e9661b087f5c8159d192115c55e, so I don't think this PR will be needed when I merge my changes (which will happen as soon as the e2e tests stop failing :D)

aaah then my bad, I thought this was somehow missed, but I think status-go was merged before its equivalent on desktop side

**Comment by dlipicar** [comment]
> > > 
> > 
> > 
> > It does... @Khushboo-dev-cpp I'm doing similar changes here https://github.com/status-im/status-desktop/pull/8911/files#diff-6eab90137e892ecb8e060c536dc726ffc2883e9661b087f5c8159d192115c55e, so I don't think this PR will be needed when I merge my changes (which will happen as soon as the e2e tests stop failing :D)
> 
> aaah then my bad, I thought this was somehow missed, but I think status-go was merged before its equivalent on desktop side

I did merge them originally, which broke some stuff, but then I reverted those changes here https://github.com/status-im/status-go/pull/3046
So the current `master` version of status-go should have the old structure/data types

**Comment by Khushboo-dev-cpp** [comment]
closing this PR as it already covered by Dario.

**Pull request closed without merging**
