### PR TITLE
feat(@settings): Add feature flag for multi network

### PR DESCRIPTION
**Pull request by alaibe**
Add a new feature flag for multi network

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good.
What is multi network BTW? 
Also, should it be a status-go setting at one point?

**Comment by alaibe** [comment]
@jrainville multi network is for the new wallet, in this new wallet you can view tokens across multiple network. But when you do a tx you can also choose which network to use.

As a concrete example, in the wallet view where you see your token, you will see token across multiple network.
And balance as well.

The status-go part as already been done, this is why you can see function now with chainId. (before it was using the one you configured but now you can pass whatever the one you want)

**Comment by anastasiyaig** [comment]
@alaibe do we want to have a message when enabling something under Advanced for this new toggle? Like we have for others:

**Comment by alaibe** [comment]
@anastasiyaig you're it is better to have it, just in case. PR updated

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
