### PR TITLE
Feat/spectate community

### PR DESCRIPTION
**Pull request by osmaczko**
- user is able to see community without being a member
- invitation bubble always display "Go to Community"
- join community buttons are displayed in community view

main part of: https://github.com/status-im/status-desktop/issues/7072
status-go: https://github.com/status-im/status-go/pull/2877

https://user-images.githubusercontent.com/33099791/191797599-a70ffc3b-2209-4d59-9104-e1cd243d34b3.mp4

### CODE REVIEW

**Comment by osmaczko** [comment]
@glitchminer, there is one outstanding issue: the members list is empty before we join the community. I am not sure if I will be able to fix it with this PR.

**Comment by du64** [comment]
> @glitchminer, there is one outstanding issue: the members list is empty before we join the community. I am not sure if I will be able to fix it with this PR.

I think this is a feature not a bug: it prevents people from scraping servers to build relationship maps based on who is in the server

**Comment by anastasiyaig** [comment]
okay i tested it against figma and i confirm the described ACs work fine:

-  Should be possible to view a community without being a member (but not send messages)
-  Button to join community if community doesn't require membership approval
-  Button to request to join community if community requires membership approval
-  Modify welcome modal to be as in the design (note buttons are different depending if it's to join a community or to request joining one)
-  User should see an ephermeral notification that a request has been made
-  User should see an ephermeral notification that a request has been accepted or rejected

Sorry it took too long @osmaczko

**Review by anastasiyaig — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]
LGTM :)

**Pull request merged**
