### PR TITLE
feat(@desktop/wallet): Add chain id to internal API

### PR DESCRIPTION
**Pull request by alaibe**
Adjust desktop to status lib and status go new API

https://github.com/status-im/status-lib/pull/29
https://github.com/status-im/status-go/pull/2359

@anastasiyaig when you have a few minutes to spare, if you help have a go at this one, *nothing* should change. (only requesting you to have a look cause there is a lot of change in status-lib)

### CODE REVIEW

**Review by pinebit — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
I get a crash when signing in or creating a new account with this branch:

```
/Users/iurimatias/Projects/Status/nim-status-client/vendor/status-lib/status/wallet.nim(263) initAccounts
/Users/iurimatias/Projects/Status/nim-status-client/vendor/status-lib/status/eth/tokens.nim(61) getVisibleTokens
/Users/iurimatias/Projects/Status/nim-status-client/vendor/status-lib/status/eth/tokens.nim(19) visibleTokensSNTDefault
/Users/iurimatias/Projects/Status/nim-status-client/vendor/status-lib/status/types/network.nim(40) sntSymbol
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by alaibe** [comment]
@iurimatias updated, let me know if you still see the problem

**Comment by anastasiyaig** [comment]
@alaibe i am not sure about gas fee - in master it is different

**Master**
Screenshot 2021-09-21 at 17 41 31


**PR**

Screenshot 2021-09-21 at 17 39 44

**Comment by alaibe** [comment]
@anastasiyaig which field for you is different? The gas amount limit, or the per-gas overall limit?

**Comment by anastasiyaig** [comment]
@alaibe i wonder why `Current Base fee ` is that different

**Pull request merged**
