### PR TITLE
Revert "fix(StatusMessage): stickers were not aligned correctly"

### PR DESCRIPTION
**Pull request by jrainville**
This reverts commit 0fb954b640f7645e9e9947bacc9340b5285a6b1d.

There is a regression

### CODE REVIEW

**Review by caybro — APPROVED** [review]

**Comment by 0x-r4bbit** [comment]
The original commit also broke discord messages as this change puts a contenttype constraint on StatusMessage

**Review by 0x-r4bbit — APPROVED** [review]

**Comment by 0x-r4bbit** [comment]
Restarted CI a bunch of times now. Can't get past it

**Comment by caybro** [comment]
> Restarted CI a bunch of times now. Can't get past it

Tried one more time; rebuilding w/o debug

**Comment by 0x-r4bbit** [comment]
It seems to be failing because of:

Screenshot from 2023-01-27 14-34-01

Which I don't think is related to any of the changes here

**Comment by caybro** [comment]
> It seems to be failing because of:
> 
> Screenshot from 2023-01-27 14-34-01
> 
> Which I don't think is related to any of the changes here

It's failing on something else every different; totally random imho

**Comment by jrainville** [comment]
I looked at the e2e and this one is actually green. It probably had to retry but the result was still sent as a failure. Merging 
https://ci.status.im/job/status-desktop/job/branches/job/e2e/job/PR-9294/6/squishResults_230127_121247.028/webreport_230127_121247.028_linux-04/index.html

**Pull request merged**
