### PR TITLE
fix(chat): make category bold if chats have unread messages

### LINKED ISSUE #8604: group is not highlighted in a community, when there is new message in one of the chats in the group
image

whatever should be highlighted

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
Closes #8604

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Nice! Good work

**Comment by 0x-r4bbit** [comment]
@mprakhov done

**Comment by mprakhov** [comment]
category became bold if you'll send a mention to the opened category channel

https://user-images.githubusercontent.com/117639195/211863748-1ddee32c-21f1-4dc8-9971-85381dba959d.mov

**Comment by 0x-r4bbit** [comment]
Nice @mprakhov good catch! I thought the hasMention flag is only referring to mentions of the logged-in user.

**Comment by 0x-r4bbit** [comment]
@mprakhov updated!
Checking only for unviewed messages now

**Comment by mprakhov** [comment]
Found another issue:

https://user-images.githubusercontent.com/117639195/212045485-f5de50a2-4be0-4020-ade7-0efbb600339a.mov

**Comment by mprakhov** [comment]
Found another issue:

https://user-images.githubusercontent.com/117639195/212045485-f5de50a2-4be0-4020-ade7-0efbb600339a.mov

**Comment by 0x-r4bbit** [comment]
@mprakhov thanks for staying resistant here. Can you elaborate what the issue is? The video alone doesn't make it clear to me.

**Comment by mprakhov** [comment]
> @mprakhov thanks for staying resistant here. Can you elaborate what the issue is? The video alone doesn't make it clear to me.

1. Sender sends mention and simple message to the Receiver last category channel
2. Receiver launches the application
3. Receiver receives unread messages
4. Receiver sees unread messages and scroll to the unread messages
5. Badge icon dissapears, that channel has unread message, but category stay bold

**Comment by 0x-r4bbit** [comment]
> that channel has unread message, but category stay bold

The category is marked as "hasUnreadMessages" if any of its channels has unread messages.
So this sounds correct.

**Comment by 0x-r4bbit** [comment]
Ohhh, I see now!  Will look into this.

**Review by mprakhov — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Pull request merged**
