### PR TITLE
fix(CreateChatView): updated layout spacing and sizes

### LINKED ISSUE #6452: New DM page differs from the Design
# Bug Report

## Steps to reproduce
1. Sign up for a new account
2. Click on the icon for a new message

#### Actual behavior
1. The placeholder text in the field 'To:' is smaller than it should be
2. The 'Confirm' button is very close to the 'To:' field
3. The space between lines of text is bigger than it should be:
image
image

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2319/
- Operating System: macOS

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #6452

### What does the PR do
CreateChatView updated layout spacing and sizes

### Affected areas
CreateChatView

### Screenshot of functionality (including design for comparison)
da

*Figma at top, app at the bottom
*Screenshot is taken in combination with this https://github.com/status-im/StatusQ/pull/780 change

TEXT
txt

### CODE REVIEW

**Review by caybro — CHANGES_REQUESTED** [review]
Code looks good but... something I noticed recently, and it's quite obvious from the actual screenshot, the "Confirm" button vertical alignment is off... slightly shifted up

**Comment by alexandraB99** [comment]
> Code looks good but... something I noticed recently, and it's quite obvious from the actual screenshot, the "Confirm" button vertical alignment is off... slightly shifted up

It's aligned at the top `Layout.alignment: Qt.AlignTop`

**Comment by caybro** [comment]
> 

And should it really be that way?

**Comment by alexandraB99** [comment]
> And should it really be that way?

Yeah, so the header is taller than 44px because of the TagSelector having different height, so everything is aligned on top, both the tag selector's input and the button have 44px height
tr

**Comment by PascalPrecht** [comment]
It's weird though that the confirm button's label is affected by that.

**Comment by alexandraB99** [comment]
> It's weird though that the confirm button's label is affected by that.

how come it is affected?

**Comment by PascalPrecht** [comment]
Well, maybe I'm misunderstanding but... I get that the controls are being aligned top, but why is that causing the **label** of the confirm button to be slightly offset (vertically)?

It should be vertically centered inside the button.

**Comment by alexandraB99** [comment]
> Well, maybe I'm misunderstanding but... I get that the controls are being aligned top, but why is that causing the **label** of the confirm button to be slightly offset (vertically)?
> 
> It should be vertically centered inside the button.

I didn't change anything in the button neither it's height. this is from master:
bg

it looks the same to me

**Comment by PascalPrecht** [comment]
Yea I don't think it's something you've introduced, it's been like that for a while I think, but it should be fixed nonetheless. 
I guess it'd make sense to be fixed in this PR as well.

**Comment by alexandraB99** [comment]
> Yea I don't think it's something you've introduced, it's been like that for a while I think, but it should be fixed nonetheless.
> I guess it'd make sense to be fixed in this PR as well.

I see this as a more general button problem than a create chat view, but as I already mentioned there's already a fix on the button here https://github.com/status-im/StatusQ/commit/f19f208b3c74a395d8315ba1462c92cfcd73ebd8 which is already in master statusq.

This is how it looks with this in:
ol

so as soon as desktop updates StatusQ this will be fixed

**Review by caybro — APPROVED** [review]
Ship it!

**Review by anastasiyaig — APPROVED** [review]

**Review by PascalPrecht — APPROVED** [review]

**Pull request merged**
