### PR TITLE
fix(@desktop/groups): view group modal member list is missing identicon for self

### LINKED ISSUE #5466: view group modal member list is missing emoji for self
# Bug Report

## Steps to reproduce

1 .click view group
2. see member list

#### Expected behavior

own user should display identicon

#### Actual behavior

identicon is missing

Screen Shot 2022-04-08 at 5 25 01 PM

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #5466

### CODE REVIEW

**Review by endulab — APPROVED** [review]

**Review by stefandunca — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
getting an error running this:

`qrc:/app/AppLayouts/Chat/popups/GroupInfoPopup.qml:223:22: Cannot assign to non-existent property "textColor"`

**Review by osmaczko — APPROVED** [review]

**Comment by saledjenic** [comment]
> getting an error running this:
> 
> `qrc:/app/AppLayouts/Chat/popups/GroupInfoPopup.qml:223:22: Cannot assign to non-existent property "textColor"`

@iurimatias I didn't have that error (otherwise I couldn't check the fix), after checking what's the issue of that error I found that in commit `1e5d389b53cf21cd07a5b41b199b1f34e04c5fa7` in `StatusQ` property `textColor` was removed in meantime, and that's why you see it.

All in all code here is rebased and updated to the latest `StatusQ` changes.

**Review by iurimatias — APPROVED** [review]
Screen Shot 2022-04-12 at 6 05 40 PM

**Comment by abhi-status** [comment]
https://ethstatus.testrail.net/index.php?/runs/view/8957&group_by=cases:section_id&group_order=asc

**Pull request merged**
