### PR TITLE
fix(desktop/wallet): Swap Modal doesn't have cursor visible when launched

### LINKED ISSUE #15417: Swap Modal doesn't have cursor visible when launched
### Description

On launching swap -> the Pay side should be highlighted and focussed and it is not currentlu

https://github.com/status-im/status-desktop/assets/60327365/b10d8c77-72c1-40df-8cef-829d084e5660

Issue 2: 
After editing modal once and relaunching it the pay side is highlighted in red which is wrong

image

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #15417, #15525

### What does the PR do

1. Show cursor on Pay amount when SwapModal in launched
2. Reset values correctly so that the form is not pre-filled with wrong data

### Affected areas

SwapModal.qml

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://github.com/user-attachments/assets/2c81a32e-3576-478a-8a63-36d54befc699

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]
👌

**Comment by dlipicar** [comment]
Hmm the entered amount became a lighter shade of gray when hovering the Max Amount button. That's not expected, is it?
image

**Review by dlipicar — APPROVED** [review]
We seem to lose active focus in a couple other scenarios (selecting account, chain, asset). We need to check with design if that's expected behavior, but that's outside the scope of this task.

**Comment by caybro** [comment]
> Hmm the entered amount became a lighter shade of gray when hovering the Max Amount button. That's not expected, is it?
> image
> 

Yeah, it's in Figma ☺️

**Review by caybro — APPROVED** [review]

**Comment by Khushboo-dev-cpp** [comment]
> > Hmm the entered amount became a lighter shade of gray when hovering the Max Amount button. That's not expected, is it?
> > image
> 
> Yeah, it's in Figma ☺️

yes https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3422-324162&m=dev here it is!

**Comment by Khushboo-dev-cpp** [comment]
> We seem to lose active focus in a couple other scenarios (selecting account, chain, asset). We need to check with design if that's expected behavior, but that's outside the scope of this task.

yes we need to think about what the behaviour should be on those cases as it is not currently defined?

as per current design it should not https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3430-335244&m=dev

**Comment by Khushboo-dev-cpp** [comment]
https://github.com/user-attachments/assets/e32c4bdc-a64a-4f8a-b2aa-81704af939ce

added behaviour for switching focus back to pay amount on account selected or network as well and also added tests for them

**Comment by virginiabalducci** [comment]
@Khushboo-dev-cpp looks good! QA passed

**Pull request merged**
