### PR TITLE
Chore(WalletConnect): Upgrade Wallet connect version and migrate to WalletKit

### PR DESCRIPTION
**Pull request by alexjba**
### What does the PR do

Closes [#15916](https://github.com/status-im/status-desktop/issues/15916)

The `web3Wallet` is now `WalletKit` and `WalletConnect` is being rebranded to `Reown`.

Updated the packages based on docs https://docs.reown.com/walletkit/upgrade/from-web3wallet-web

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

**Comment by virginiabalducci** [comment]
Hi @alexjba 
I tested the build from this PR and the connection is not working as expected. 
1. Go go a dApp page, for example Rarible
2. Connect via Browser connect

Actual result: the pop up to sign the connection request shows up on the desktop app, user accepts it and app seems to be connected, however on the dApps end, Status app is not connecting. 

URL: https://appkit-lab.reown.com/library/wagmi-siwe/
Console log:
[app_20241007_220608.log](https://github.com/user-attachments/files/17286046/app_20241007_220608.log)

https://github.com/user-attachments/assets/5582ed3f-d216-4f00-b34c-e595144e0c1c

dApp: Rarible

https://github.com/user-attachments/assets/8e14fd6b-916b-4788-9edd-b01527b3e353


```
WRN 2024-10-08 01:21:28.362Z qt warning                                 topics="qt" tid=54837088 text="Warning: Multi-selection is disabled, but multiple items are selected. Automatically selecting the first inserted item." file=qrc:/app/AppLayouts/Wallet/views/NetworkSelectorView.qml:43 category=qml
WRN 2024-10-08 01:21:28.420Z qt warning                                 topics="qt" tid=54837088 text="QML Binding: Binding loop detected for property \"value\"" file=qrc:/imports/shared/controls/AccountSelector.qml:136 category=default
DBG 2024-10-08 01:21:33.560Z NewBE_callPrivateRPC                       topics="rpc" tid=54837088 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-10-08 01:21:33.646Z NewBE_callPrivateRPC                       topics="rpc" tid=54837088 file=core.nim:27 rpc_method=connector_requestAccountsAccepted
ERR 2024-10-08 01:21:33.650Z qt error                                   topics="qt" tid=54837088 text="addSession: missing required parameters" file=qrc:/app/AppLayouts/Wallet/services/dapps/ConnectorDAppsListProvider.qml:17 category=qml
DBG 2024-10-08 01:21:35.442Z NewBE_callPrivateRPC                       topics="rpc" tid=54837088 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
```
Console log: 
[app_20241007_220608.log](https://github.com/user-attachments/files/17286055/app_20241007_220608.log)

[geth.log.zip](https://github.com/user-attachments/files/17286054/geth.log.zip)

Let me know in case I can provide any other information, thanks!

**Comment by virginiabalducci** [comment]
Hey @alexjba  thanks for the clarification

It seems WC is also presenting issues. On the build app of this PR, I'm unable to connect to any dApp. I tested with 3 test users with the same results.
I also deleted my browsing history and tried again with the same results.

Tested in https://lido.fi/, https://react-app.walletconnect.com/, https://app.uniswap.org/, https://rarible.com/

https://github.com/user-attachments/assets/56b0eabe-d9f9-4d7f-8cca-6105e1463413

https://github.com/user-attachments/assets/42d8ee14-64a3-466f-9cb4-5fad81972c5e



```
WRN 2024-10-08 11:28:46.641Z qt warning                                 topics="qt" tid=55267654 text="QML Connections: Detected function \"onContactRenamed\" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name." file=qrc:/app/mainui/activitycenter/views/ActivityNotificationMessage.qml:72 category=default
DBG 2024-10-08 11:28:47.373Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_markAsSeenActivityCenterNotifications
DBG 2024-10-08 11:28:51.373Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
DBG 2024-10-08 11:29:35.077Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-10-08 11:29:38.192Z qt message                                 topics="qt" tid=55267654 text="WC WalletConnectSDK.wcCall.getActiveSessions;" file=qrc:/app/AppLayouts/Wallet/services/dapps/WalletConnectSDK.qml:112 category=qml
ERR 2024-10-08 11:29:38.198Z qt error                                   topics="qt" tid=55267654 text="Uncaught TypeError: Cannot read property 'getActiveSessions' of null" file=qrc:/app/AppLayouts/Wallet/services/dapps/sdk/generated/bundle.js:2 category=js
DBG 2024-10-08 11:29:40.293Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
DBG 2024-10-08 11:29:45.070Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-10-08 11:29:48.102Z NewBE_callPrivateRPC                       topics="rpc" tid=55267654 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
```

**Comment by alexjba** [comment]
Thanks @virginiabalducci! Will have a look. It looks like a code error somewhere. Probably in the parent PRs

**Comment by alexjba** [comment]
@virginiabalducci Fixed! There's been an issue on the upgrade

**Comment by caybro** [comment]
@alexjba conflicts :)

**Review by caybro — APPROVED** [review]
LGTM

**Review by virginiabalducci — APPROVED** [review]
tested a couple of dApps and looks good!

**Pull request merged**
