### PR TITLE
fix: Timeline view crash with SIGSEGV when loaded

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2618.

The main culprit was that `self.pinnedMessagesList` did not contain the `self.activeChannel.id` because it was incorrectly upserted in `upsertChannel`.

To fix this, `upsertChannel` was split between upserting a channel in `self.messagesList` (in `upsertChannel`) and upserting a channel in `self.pinnedMessagesList` (in `upsertPinnedChannel`).

Nil checks were added to parsing the messages RPC response in case specific fields were not returned in the response.

In addition, a copy/paste error was fixed in `asyncMessageLoadTask`.

The bad commit was https://github.com/status-im/status-desktop/commit/b52dceb984b3bb1a15173cac925408bd11dbeb8b.

### CODE REVIEW

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
the crash is no more reproducible in this branch

**Review by jrainville — APPROVED** [review]
Nice find. Sorry about the issue 😬

**Review by iurimatias — CHANGES_REQUESTED** [review]
Screen Shot 2021-06-01 at 11 17 57 AM

in this build when loading the app, the chat is blank

**Comment by emizzle** [comment]
@iurimatias this has been fixed.

**Comment by anastasiyaig** [comment]
I've tested this once again:

1. Timeline is not crashing, also can add pictures reactions and etc
2. Public chat is operational, can join, leave, join again and still see messages
3. 1x1 chat is receiving messages as well, can leave, join, send messages
4. Group chat is looking great
5. Communities are not great, but it is broken in master https://github.com/status-im/status-desktop/issues/2628

Sorry for missing this chat issue, somehow i was distracted and not reported it, thanks @iurimatias for spotting it

**Pull request merged**
