### PR TITLE
feat(MessageContextMenu): add option to verify identity in context menu

### LINKED ISSUE #6252: In Profile menu show options for Identity Verification

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #6252

This branch is on top of https://github.com/status-im/status-desktop/pull/6375 because it needs the mutual contact fixes

image

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Review by caybro — APPROVED** [review]

**Comment by jrainville** [comment]
Updated to use `isContact` instead of `isMutualContact`

**Review by caybro — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Review by osmaczko — APPROVED** [review]

**Comment by Hbouaz** [comment]
@jrainville It is not clear if the feature works only on chat context/community context or both? There are no community labels on the issue, so I guess it's the profile context on chat. 

what I am seeing is:


0A0C8999-7B75-482E-AD06-B33BBFE08983

9DA30FA1-1306-4D92-984B-569DEFED3A33

**Comment by jrainville** [comment]
@Hbouaz Yeah sorry it wasn't clear from the issue. It was supposed to be added to the Profile section (Messenger/Contacts) as seen in the design https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1657%3A184714

I added it to the Message context menu because I thought it was there I was supposed to.

Anyway, I added it to the profile and left it in the Message context menu because I feel like it's easier to use for a user to have it in multiple places.
I can add it to the community member list as well, but I'd prefer doing it in another PR at this point.

For the reviewers: I remove the old Profile context menu and reused the MessageContextMenu, that way we reduce duplication of code.

**Comment by jrainville** [comment]
Rebased

**Comment by elina2015** [comment]
@jrainville hey, thank you for the updates! there is only one small issue: 
'Verify Identity' should be above the 'Rename' option. Could you kindly check?
image

**Review by elina2015 — CHANGES_REQUESTED** [review]
Need to update according to the Design

**Comment by jrainville** [comment]
On it, I think I inverted during the rebase

**Comment by jrainville** [comment]
@elina2015 I fixed the order. I also rebased.

Do note that sending contact requests on this version of the app is difficult, if not impossible, because popups are messed up. Someone is fixing that (Alex I think).

If you ever need to test this, you can use an older version or mobile to send the contact request.

**Comment by jrainville** [comment]
@elina2015 I rebased again, the bug with contact request was fixed, so it should be good now

**Review by elina2015 — APPROVED** [review]
Tested and approved

**Pull request merged**
