### PR TITLE
fix(@wallet/desktop): No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled

### LINKED ISSUE #16569: No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled
# Bug Report

## Description

No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled (a really subtile change there in the modal. Maybe obvious for people that worked on it. But it tricked me to think it's broken until @Khushboo-dev-cpp explained the difference 😄). IMO that's not very clear for the user. Ideally the user knows in advance that we'll request 2 actions and once the Swap flow started, the maybe the input data cannot be changed until user reject or error. E.g. IIRC Uniswap uses two checkboxes in the modal. Once the approval is completed, the approval checkbox is green and the Swap checkbox is pending.
cc @benjthayer @alexjba @benjthayer for visibility. This issue was created to track separately issue #1 described in https://github.com/status-im/status-desktop/issues/16563

No feedback after token approval. Once the approval is confirmed the Swap dialog becomes editable again, with the Swap button enabled
This is confusing because the user has approved a certain balance of spending cap, and then they can still go ahead and modify the Swap amount, and the Sign button is still enabled.

## Steps to reproduce

Case 1: User modifies the balance amount to a lower amount after the approval has been made
1. Start a Swap transaction for example USDT 0.30 to USDC
Image
2. Approve the USDT spending cap
Image
3. The 'Swap' button is enabled but user can still modify the Swap conditions (in this case the amount to swap has been lowered)
Image
4. User is able to Sign without any warning
Image

Case 2: User modifies the balance amount to a higher amount after an approval of a lower spending cap has been made and signed
In this case, the 'Sign' Button turns back to 'Approve', if user either:
- modifies the balance for a higher amount
- modifies the asset pair
https://github.com/user-attachments/assets/354fc528-dbc3-45c1-8879-43c6cb1b0a43

#### Actual behavior

https://github.com/user-attachments/assets/1e889be9-fff7-4f0c-b3f6-9f1b64be95a5

### Additional Information

- Status desktop version:
- Operating System:

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #16569, #16564

Go PR - https://github.com/status-im/status-go/pull/5995

### What does the PR do

his PR adds back missing Setting Spending Cap and Swapping... toasts with the correct token amounts.

The Spending cap set and Swapped... toasts are missing currently and perhaps should be addressed with new notifications design https://www.figma.com/design/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=25111-368170&node-type=instance&m=dev here.

### Affected areas

Swap notifications

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://github.com/user-attachments/assets/1ec2fcd3-899c-4771-9dc0-45b7ed5fa18c

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

**Review by alexjba — APPROVED** [review]

**Comment by saledjenic** [comment]
Agreed with @Khushboo-dev-cpp that since we are working on fixing ephemeral notifications in the desktop app, globally, these changes should go only to the release branch, and not land on the master branch.

**Comment by caybro** [comment]
> Agreed with @Khushboo-dev-cpp that since we are working on fixing ephemeral notifications in the desktop app, globally, these changes should go only to the release branch, and not land on the master branch.

Why, we don't want them in master or next release(s)?

**Comment by anastasiyaig** [comment]
@caybro because there is a bigger task that refactors and fixes all the toasts for the app , @saledjenic is on it. We will land it in 2.32 hopefully

**Review by virginiabalducci — APPROVED** [review]
Looks good on my end! 

Screenshot 2024-10-31 at 9 52 39 AM

Screenshot 2024-10-31 at 9 52 59 AM

**Comment by jrainville** [comment]
Force merging with Nastya's blessing

**Pull request merged**
