### PR TITLE
fix: profile preview doesn't show entire profile

### LINKED ISSUE #9519: Profile preview doesn't show entire profile
Screenshot from 2023-02-10 10-57-25

This was the only way for us to access chatkeys via UI.

### PR DESCRIPTION
**Pull request by caybro**
rectifies one of the StatusScrollView behavior changes done recently

Fixes #9519

### Affected areas

ProfileDialogView

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

### CODE REVIEW

**Review by alexandraB99 — APPROVED** [review]
exactly what I was mentioning to @noeliaSD the other time. we're nowhere setting height in Layouts, we're based on the ColumnLayout calculating it's own height based on it's children, so Layout.fillHeight: true will never work D:

**Comment by caybro** [comment]
> exactly what I was mentioning to @noeliaSD the other time. we're nowhere setting height in Layouts, we're based on the ColumnLayout calculating it's own height based on it's children, so Layout.fillHeight: true will never work D:

Yeah... but it's a behavior change, this used to work before thx to the implicitHeight in the scrollview :/

**Review by alexjba — APPROVED** [review]

**Comment by alexandraB99** [comment]
> > exactly what I was mentioning to @noeliaSD the other time. we're nowhere setting height in Layouts, we're based on the ColumnLayout calculating it's own height based on it's children, so Layout.fillHeight: true will never work D:
> 
> Yeah... but it's a behavior change, this used to work before thx to the implicitHeight in the scrollview :/

Sure, we can always revert to what it was if you think it's better :D

**Review by 0x-r4bbit — APPROVED** [review]

**Review by micieslak — COMMENTED** [review]
lgtm

**Review by micieslak — APPROVED** [review]
lgtm

**Pull request merged**
