### PR TITLE
chore: statusgo changes to remove default pubsubtopic (not to merge)

### PR DESCRIPTION
**Pull request by chaitanyaprem**
### What does the PR do

Includes changes from https://github.com/status-im/status-go/pull/5474 which changes statusgo to only use shards and no defaultpubsubTopic.
This is only for dogfooding.

### Affected areas

Communities and messaging.
1. Better to test community creation and shard assignment.  Try asssigning a community to shard 128 or 256.
2. Send and receive of messages should work before and after assignment of the community.
3. Join community and send/receive messages.
4. All messaging send and receive i.e communities, groups and 1:1 chat.

Anything else comes to mind that should be explicitly verified @igor-sirotin @richard-ramos ?

### Risk 

Described potential risks and worst case scenarios.

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

-->

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
I have done manual testing of the following and did not face any issues where 1 user is using this build and another one is using nightly build: 
1. Create a new community and add users. User joins community 
2. Send messages in default community channel. 
3. Add new channel, send and receive messages 
4. Group chat and 1:1 chat send and receive message with 1 user in this build and another user in regular nightly build.

**Comment by igor-sirotin** [comment]
@chaitanyaprem I guess we can open for review?

**Comment by igor-sirotin** [comment]
@anastasiyaig I think we need QA eyes on this

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem I guess we can open for review?

Well, nothing much from desktop point of view, mainly this PR is for testing..hence did not open for review.

**Comment by igor-sirotin** [comment]
> > @chaitanyaprem I guess we can open for review?
> 
> Well, nothing much from desktop point of view, mainly this PR is for testing..hence did not open for review.

You'll need at least 2 approvals anyway, so better open in sooner than later 😄

**Comment by chaitanyaprem** [comment]
Closing this PR as dogfooding is done and underlying status-go PR is ready to merge.

**Pull request closed without merging**
