### PR TITLE
fix: browser connect - send transaction command

### LINKED ISSUE #16063: Browser plugin - transaction via Uniswap doesn't go through
# Bug Report

## Description

When connected to Uniswap via Browser plug in, transaction gets stuck

## Steps to reproduce

1. Have the Status browser extension installed
2. Open the desktop app and use an account that has some funds
3. Go to Uniswap and connect the wallet to Status browser
4. On Uniswap, make a swap for example 1 usdt to 1 usdc
5. On the Status desktop app, Sign the transaction.

#### Expected behavior
Sign transaction details to show correct data 
Sign transaction to go through correctly

#### Actual behavior
Sign transaction details are ilegible
Screenshot 2024-08-09 at 11 00 34 AM
Transaction on Uniswap's end remains Pending
Status app shows a successful toast but nothing else happens
I re-tried the transaction and the Status Sign modal showed up 1 or 2 times but nothing happens on Uniswap's end.

https://github.com/user-attachments/assets/85e096ab-079d-4a78-bad3-b49e04652a8a
https://github.com/user-attachments/assets/3bae0ed9-44ec-48ab-8d0f-b5cd8fc42533
Screenshot 2024-08-09 at 10 26 35 AM
Screenshot 2024-08-09 at 10 25 52 AM
Screenshot 2024-08-09 at 10 18 50 AM

### Additional Information
[app.uniswap.org-1723211704025.log](https://github.com/user-attachments/files/16562115/app.uniswap.org-1723211704025.log)

- Status desktop version: 2.30 rc-5
- Operating System: Mac OS Sonoma, Chrome Version 127.0.6533.89 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/5855

Fixes #16063 

**Important** 
- while working on this I've noticed many holes in the browser connect implementation that @alexjba and I will work on
- with changes here and on the statusgo side I wanted just to make the sending flow working anyhow, but the real work is yet to come

Executed swap tx:
- https://arbiscan.io/tx/0x1c98c0e57341a99f6041a401d3f8639629e81512ea0b6df9e1298dc72016c9df

Screenshot from the app, where you can see the displayed content in a readable form instead of weird symbols that we had before:
_a2

### CODE REVIEW

**Review by alexjba — APPROVED** [review]
LGTM! Tested

The e2e tests keep failing. I hope a rebase would help

**Comment by anastasiyaig** [comment]
is this PR changing sync code length / UI representation at any point? Sync devices test is failing

https://ci.status.im/job/status-desktop/job/e2e/job/prs/2274/allure/#suites/9a2e8e86a4e9b0acc74a47650c6a3271/ca5758a0660f46d4/

**Comment by anastasiyaig** [comment]
i ran the test in the master build commit 894a5f19c952cb3e03ebc7f16170290a2db9efbb and it passes there

**Comment by alexjba** [comment]
> is this PR changing sync code length / UI representation at any point? Sync devices test is failing
> 
> https://ci.status.im/job/status-desktop/job/e2e/job/prs/2274/allure/#suites/9a2e8e86a4e9b0acc74a47650c6a3271/ca5758a0660f46d4/

No, had the same failure here https://github.com/status-im/status-desktop/pull/16353

**Comment by anastasiyaig** [comment]
wonder what's that because i cant reproduce locally 

there is some change in go https://github.com/status-im/status-desktop/pull/16358 (in this PR tests were passing), maybe it impacts?

**Review by alaibe — APPROVED** [review]

**Pull request merged**
