### PR TITLE
fix(@refactoring/base_01): button `I have a Keycard` displayed when it's not enabled

### PR DESCRIPTION
**Pull request by saledjenic**
@iurimatias @anastasiyaig I have tested the issue #3944 but I cannot reproduce it. If there are any certain steps for that, let me know. Will try it on win now maybe it's a win only issue.

Also I noticed, while I was checking this, that "I have a Keycard" button is displayed on the main screen even it's not enabled in the settings for new accounts, so I fixed that. The point is that "isKeycardEnabled" property was added to the local settings which is exposed once the user is logged in, so I just moved it to the other user's local file which is ready before from the app start.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
these crashes might be specific to the windows only,  checking now

**Comment by saledjenic** [comment]
> these crashes might be specific to the windows only, checking now

@anastasiyaig the crash is happening only if you're testing installed app, and the crash is fixed through the #4012 there is a comment also why that crash was happening.

@anastasiyaig as you suggested within this ticket I updated the image displayed on login screen, it was most likely unintentionally changed in commit `426c116bac61003462ad33da966a9b77eaccf5a7` during the qml refactor.

**Comment by anastasiyaig** [comment]
thanks for bringing the screen back @saledjenic 

Screenshot 2021-11-02 at 17 35 39

**Comment by anastasiyaig** [comment]
i cant reproduce the crash in this branch, thanks @saledjenic

**Comment by anastasiyaig** [comment]
thanks for fixing the crash :) @saledjenic

**Pull request merged**
