### PR TITLE
Update StatusWindowsTitleBar.qml

### PR DESCRIPTION
**Pull request by JesseGuoX**
signal should be closed

### What does the PR do

bug fix

### Affected areas

statusq platform qml

### CODE REVIEW

**Comment by caybro** [comment]
What problem is this trying to fix?

**Comment by JesseGuoX** [comment]
When I use StatusQ as a third-party library, if I use `StatusWindowsTitleBar`, it will not trigger the 'close' signal. Obviously, this is a syntax error. The 'closed' signal is triggered on line 114 of `StatusWindowsTitleBar.qml` instead of the 'close' signal."

**Review by caybro — CHANGES_REQUESTED** [review]
I see... the problem here is that even though we actually don't use this component in our app so there's indeed a typo there. But the other window decoration that we _do_ use on Mac has the same signals; so I'd ask you to rather fix the signal invokation typo on line 114 instead.

Thanks for the contribution!

**Review by caybro — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
