### PR TITLE
fix(@desktop/chat): Modal on the Pinned Messages Popup isnt seen

### LINKED ISSUE #4002: [refactoring/base_01] unpinned messages menu is not visible
upload_cca89ad391c55776c1ea28ec00ae2d13

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4002

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp thanks for fixing this. May i ask u to fix the action itself too? Or it should be another issue? I can see the options, but 'unpin` is not doing anything on this modal

Screenshot 2021-11-03 at 14 19 56

**Comment by Khushboo-dev-cpp** [comment]
Hey I can fix it under this itself. Let me check.

**Comment by Khushboo-dev-cpp** [comment]
Hey @anastasiyaig I have fixed that issue now too. Please check :)

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
thank you @Khushboo-dev-cpp lets merge it, works fine

**Review by iurimatias — CHANGES_REQUESTED** [review]
clicking on `add reaction` doesn't work and the console says `qrc:/app/AppLayouts/Chat/panels/ChatButtonsPanel.qml:80: Error: Insufficient arguments`

**Comment by Khushboo-dev-cpp** [comment]
> clicking on `add reaction` doesn't work and the console says `qrc:/app/AppLayouts/Chat/panels/ChatButtonsPanel.qml:80: Error: Insufficient arguments`

Made changes to fix this :)

**Comment by anastasiyaig** [comment]
it should be fine now


https://user-images.githubusercontent.com/82375995/140732379-09e83a06-a0d1-450f-b110-3b6ea44ddcc7.mov

**Review by iurimatias — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Pull request merged**
