### PR TITLE
fix: use correct pubkey during account generation

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by alexandraB99** [comment]
@richard-ramos in Figma we have:
f

What is that?

**Comment by richard-ramos** [comment]
The key being shown in figma, while it looks like a public key, it is not a valid value, and ends up causing confusion.
The change i made is to show a valid public key whose value matches what is being shown on the profile. Before it was displaying an incorrect address.

With https://github.com/status-im/status-desktop/pull/5269 this gigantic 65bytes address will be compressed to a shorter value and will look closer to the figma design (but with a correct value)

**Review by osmaczko — APPROVED** [review]

**Comment by abhi-status** [comment]
Hey @richard-ramos 

The chat key, emoji hash and identicon ring being generated on the onboarding screen is not correct.

I have a few test accounts whose chat keys and seed phrases I have noted down.
When I use their seed phrases to restore the accounts, the onboarding page shows me an entirely different chat key.

**eg:** One of the profiles I use is -  Scaly Prize Jackal 
whose public chat key is : **0x04a7870af8171cbd4bde3b0b7e571fb0cef115212a1415633f7ba299b3deb82aa152f1a6255935186b012ff5bf5938609baf7e438cbd0c6a21ffb63eb884d49027** 

The seed phrase I use to restore this profile is -> **badge damp click unaware worry agent critic clay bundle balcony injury pencil**

Using the existing user flow, I use the above seed phrase to get 👇 (I am not sure what the key displayed here is)
image



On hitting the `Re-encrypt` key button and setting a profile name, I get this 👇 
image

This chat key is different to what I have saved before.

Although, after on-boarding, my key is displayed correctly in the profile : 
**0x04a7870af8171cbd4bde3b0b7e571fb0cef115212a1415633f7ba299b3deb82aa152f1a6255935186b012ff5bf5938609baf7e438cbd0c6a21ffb63eb884d49027**

image

The emoji hash and identicon ring are different to the ones on the boarding screen as well.

**Comment by richard-ramos** [comment]
The changes I did only dealt with the New Account generation (which i just confirmed is working correctly), but i did not modify importing existing accounts because I assumed those worked correctyl, but I can see wrong account is being displayed. I have a general idea of what could be wrong there and will attempt a fix.

**Comment by richard-ramos** [comment]
> Using the existing user flow, I use the above seed phrase to get  (I am not sure what the key displayed here is)

This screen is displaying an incorrect value too. Looks like it's an address and not a chat key

**Comment by richard-ramos** [comment]
@abhi-status , please try again. I fixed the flow for existing users, including the key shown below the identicon when you recover a seed phrase

**Comment by abhi-status** [comment]
Thanks Richard !

I can confirm, onboarding screens on both flows (new & existing users) now work as desired.

**Comment by abhi-status** [comment]
https://ethstatus.testrail.net/index.php?/runs/view/8883&group_by=cases:section_id&group_order=asc

**Review by abhi-status — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Pull request merged**
