### PR TITLE
refactor(@desktop/chat): loading messages on join public chat

### PR DESCRIPTION
**Pull request by saledjenic**
@iurimatias faced 2 issues:
1. initial messages have not been loaded when user joins a public chat
2. messages sent to a certain chat are visible into other chats as well

The second issue is fixed here and received new messages are now filtered by the chat id they belong to.

The first issue is something we need to figure out why it's happening, we have mailserver signals added to the log so we can follow easier what's happening. Added logging refers to the following signals:
- `SignalType.HistoryRequestStarted`
- `SignalType.HistoryRequestBatchProcessed`
- `SignalType.HistoryRequestCompleted`
- `SignalType.HistoryRequestFailed`

Out of 10 tries (starting from an empty Status data and joining public chat) I didn't get initial messages loaded in ~30% cases. If you receive initial history messages for the first joined public chat on the app start you may join more chats and all of them will receive initial history messages, but if history messages are not received for the first chat they won't be received for other chats you are joining as well. In that case the following will be received:
- info that history request started: `jsonSignal: {"type":"history.request.started","event":{"requestId":"2c6379ca-9d4c-4fa8-a115-73953dc22a51","batchIndex":0,"numBatches":1}}`
- and then that it failed: `{"type":"history.request.failed","event":{"requestId":"2c6379ca-9d4c-4fa8-a115-73953dc22a51","batchIndex":0,"errorMessage":"could not find peer with ID: 2721ca3e5c87d73ce892bd0710f9a78eef4c800f92aeaa7feec8b9b86b62c131"}}`

On the side of `status-desktop` all should be good in terms of requesting data/handling response, so maybe @richard-ramos may help somehow?

Actually when user joins new public chat we do `wakuext_createPublicChat` first and after that do `wakuext_chatMessages` call which returns `{"messages":null,"cursor":""}` always, what is ok (the same as `master` branch work) and we expect to received messages via `messages.new` signal sent from `status-go` but that missed due to we couldn't find a peer with ID appropriate id.

That, most likely, means if initial history messages are not loaded when you joined a chat they won't be loaded later as well   since we don't have them in the DB.

Maybe we should think about trying to fetch data from other peer/s in that case?

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@saledjenic macOs is not built

**Comment by saledjenic** [comment]
This pr also fixed issue where reply to a message was added as 2 messages in the message list, and now messages are added to a model respecting their timestamp.

**Comment by saledjenic** [comment]
> @saledjenic macOs is not built

Should be good now.

**Review by jrainville — APPROVED** [review]
Code looks good. I'm not sure why the history fails to load sometimes, but I know it's been a recurring issue even on master. Maybe like you said, we need to look at multiple mailservers, or maybe we need to take another look at how mobile does it, in case something changed there

**Pull request merged**
