### PR TITLE
chore: bump status-go to include DB re-encryption fix

### PR DESCRIPTION
**Pull request by alexjba**
### What does the PR do
Closing: https://github.com/status-im/status-desktop/issues/10353

Bump status-go to include https://github.com/status-im/status-go/pull/3607. This fix is changing the re-encryption process to avoid DB corruption.

Testing tips:
The DB re-encryption happens whenever the DB password is changed. Closing the app or manually updating the DB (using sqlite client) while the re-encryption process is ongoing should not corrupt the DB and the account should remain usable.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@alexjba any hint what to test here?

**Review by caybro — APPROVED** [review]

**Comment by alexjba** [comment]
> @alexjba any hint what to test here?

Killing the app while the password change is running. 

Changing the password for a decently large account takes up to 1 minute. If anything happens (crash, app force close, DB updates via sqlclient) the account should still be usable (probably with the old password if the process was not completed).

**Comment by alexjba** [comment]
> > @alexjba any hint what to test here?
> 
> Killing the app while the password change is running.
> 
> Changing the password for a decently large account takes up to 1 minute. If anything happens (crash, app force close, DB updates via sqlclient) the account should still be usable (probably with the old password if the process was not completed).

There's also the process of password hash upgrade (from upper case to lower case  - https://github.com/status-im/status-desktop/issues/9492). This is also a password change under the hood, but it happens automatically on login. So another test could be this: Setup an account with 0.10 and migrate to this version.

**Review by jrainville — APPROVED** [review]

**Comment by alexjba** [comment]
Not needed. Already bumped

**Pull request closed without merging**
