### PR TITLE
feat(SendModal): add a spinner when resolving an ENS name

### LINKED ISSUE #16355: SendModal: Improvements: Missing loading state when ENS name is being resolved
https://github.com/user-attachments/assets/d65a5ceb-ad51-4461-9e84-beacf9e614b9

As seen in the screenshot when the sendModal is prefilled with an ens name, we can see the recipient selector while the ens name is being resolved.
As soon as the ens name is resolved we replace it with the wallet address
There is not loading state during this time and its not clear that the ens name is being validated in the background. 

Need some designs to handle this usecase.

### Description

[comment]: # (Describe the feature you would like and include designs and Figma links if available.)
[comment]: # (Describe the use cases the implementation should cover. E.g. New users, existing users, public chat, group chat, etc)
*Summary*: ...

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

@benjthayer fyi

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do

- update the SB page with the toggle too

Fixes #16355

### Affected areas

SendRecipientInput -> RecipientView -> SendModal

### Architecture compliance

- [x] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Architecture guidelines](../architecture-guide.md)

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://github.com/user-attachments/assets/dc319497-8c9f-4eb4-a353-ea5c66a4dc59

### CODE REVIEW

**Comment by Khushboo-dev-cpp** [comment]
Hey awesome work. Just some issues some things missed
1. No QMl Unit tests either in SendMdal or SendRecipientInput for the loading state
2.  as per design it should look like this when the ens name is resolved 
image
but in current implementation it looks like this 
https://github.com/user-attachments/assets/afa09644-4a9a-47cb-9b59-2b491dcb8756
3. When pasting an address 0x16437e05858c1a34f0ae63c9ca960d61a5583d5e I dont see any loading animation at all.  I think it supposed to be same for ens and wallet address @benjthayer can you please confrim?
4. On the storybook, the tests are not running for SendModal.qml, broken perhaps?

**Review by Khushboo-dev-cpp — CHANGES_REQUESTED** [review]
reviewed. add some changes

**Comment by caybro** [comment]
> Hey awesome work. Just some issues some things missed
> 
> 1. No QMl Unit tests either in SendMdal or SendRecipientInput for the loading state

Yeah, will add some tests to SendRecipientInput

> 2. as per design it should look like this when the ens name is resolved

Right, I guess this was never implemented? (the title + subtitle UI when ENS is resolved)

> 3. When pasting an address 0x16437e05858c1a34f0ae63c9ca960d61a5583d5e I dont see any loading animation at all.  I think it supposed to be same for ens and wallet address @benjthayer can you please confirm?

No idea, but in this case, when directly pasting an address, no resolution is taking place, so no loading state

> 4. On the storybook, the tests are not running for SendModal.qml, broken perhaps?

Hmm indeed, weird. Most likely unrelated but I'll check this

**Comment by caybro** [comment]
> > 7\. On the storybook, the tests are not running for SendModal.qml, broken perhaps?
> 
> Hmm indeed, weird. Most likely unrelated but I'll check this

Ha, SendModal doesn't have any tests at all :)

**Comment by benjthayer** [comment]
> > 2. as per design it should look like this when the ens name is resolved
> 
> Right, I guess this was never implemented? (the title + subtitle UI when ENS is resolved)

Yeah this is a new presentation for the ENS which borrows the dual line (title/subtitle) presentation that we have for contacts and accounts: 
Screenshot 2024-09-18 at 12 54 01

> > 3. When pasting an address 0x16437e05858c1a34f0ae63c9ca960d61a5583d5e I dont see any loading animation at all.  I think it supposed to be same for ens and wallet address @benjthayer can you please confirm?
> 
> No idea, but in this case, when directly pasting an address, no resolution is taking place, so no loading state

I believe this is because we are only validating the format of the address which is done instantaneously? So while the spinner is in the designs, it might not be needed if the check is instant

**Comment by Khushboo-dev-cpp** [comment]
> > > 2. as per design it should look like this when the ens name is resolved
> > 
> > 
> > Right, I guess this was never implemented? (the title + subtitle UI when ENS is resolved)
> 
> Yeah this is a new presentation for the ENS which borrows the dual line (title/subtitle) presentation that we have for contacts and accounts: Screenshot 2024-09-18 at 12 54 01
> 
> > > 3. When pasting an address 0x16437e05858c1a34f0ae63c9ca960d61a5583d5e I dont see any loading animation at all.  I think it supposed to be same for ens and wallet address @benjthayer can you please confirm?
> > 
> > 
> > No idea, but in this case, when directly pasting an address, no resolution is taking place, so no loading state
> 
> I believe this is because we are only validating the format of the address which is done instantaneously? So while the spinner is in the designs, it might not be needed if the check is instant

I did see some delay before I noticed the blue tick for the address

**Comment by caybro** [comment]
> > > 2. as per design it should look like this when the ens name is resolved
> > 
> > 
> > Right, I guess this was never implemented? (the title + subtitle UI when ENS is resolved)
> 
> Yeah this is a new presentation for the ENS which borrows the dual line (title/subtitle) presentation that we have for contacts and accounts: 

This we haven't implemented at all; so I'd postpone the ENS delegate changes to a later issue/PR

> 
> > > 3. When pasting an address 0x16437e05858c1a34f0ae63c9ca960d61a5583d5e I dont see any loading animation at all.  I think it supposed to be same for ens and wallet address @benjthayer can you please confirm?
> > 
> > 
> > No idea, but in this case, when directly pasting an address, no resolution is taking place, so no loading state
> 
> I believe this is because we are only validating the format of the address which is done instantaneously? So while the spinner is in the designs, it might not be needed if the check is instant

Yeah there is a 1.5s debounce delay, so I'll add the spinner to that too

**Review by saledjenic — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]
Lgtm!

**Review by alaibe — APPROVED** [review]

**Pull request merged**
