### PR TITLE
8001 compressed community key2

### PR DESCRIPTION
**Pull request by endulab**
### What does the PR do

Join community links contains compressed key: "https://join.status.im/c/zQ3sh...."
Links should work normally: via chat or via web browser as deep links (internal - status-im://c/zQ3.....)

Technical details:
zQ3.. format is a multiformat compression.
Community id is propagated in the system as a compressed 33-bytes string.
Utility function "changeCommunityKeyCompression" was added to change compressions 33-bytes <-> multiformat.
This function is used to create a share link or before opening link which uses zQ3 format.

Required prs:
https://github.com/status-im/status-go/pull/2924
https://github.com/status-im/nim-status-go/pull/17

### Affected areas

Chat/Community/ Deep links

### Screenshot of functionality (including design for comparison)

image

image

image

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good

**Comment by elina2015** [comment]
For QA: the pr is fixing the task https://github.com/status-im/status-desktop/issues/8001

**Review by borismelnik — APPROVED** [review]
LGTM 👍

**Comment by caybro** [comment]
@alexandraB99 isn't this first popup going away?

**Comment by elina2015** [comment]
Hi @endulab, thank you, everything works, just have a question about the Status browser and the regular browser. The link https://join.status.im/c/zQ3shhYsCe8ucxHFFctu3T8L56FQ5qe7Ep2h9DYZZyu5Wcmvt in these browsers leads to our status.im main page. 
So, it looks like the compressed links don't work correctly in the browsers. I'd like to add this to a separated task and close the current one. Are you agree?

**Review by elina2015 — APPROVED** [review]
Tested and approved. The found issues will be separated to another task

**Comment by elina2015** [comment]
Added the issue: https://github.com/status-im/status-desktop/issues/8102

**Comment by endulab** [comment]
> Hi @endulab, thank you, everything works, just have a question about the Status browser and the regular browser. The link https://join.status.im/c/zQ3shhYsCe8ucxHFFctu3T8L56FQ5qe7Ep2h9DYZZyu5Wcmvt in these browsers leads to our status.im main page. So, it looks like the compressed links don't work correctly in the browsers. I'd like to add this to a separate task and close the current one. Do you agree?

@elina2015 this may be related to https://github.com/status-im/status-desktop/issues/7957.
Our current website does not handle links correctly (only /u/ afaik). The new website from Pavel will handle them. So we need to wait for a new website.

**Pull request merged**
