### PR TITLE
chore: merge qa automation repo as subfolder

### PR DESCRIPTION
**Pull request by jakubgs**
Because as far as we know there's no good reason why Volodimir insisted on it being a separate repository.

The merging of `desktop-qa-automation` was one using [`git-filter-repo`](https://github.com/newren/git-filter-repo) tool and these instructions:
https://gist.github.com/x-yuri/9890ab1079cf4357d6f269d073fd9731

Steps:
```sh
git clone git@github.com:status-im/status-desktop
git clone git@github.com:status-im/desktop-qa-automation
cd desktop-qa-automation
git filter-repo --to-subdirectory-filter test/e2e
cd ../status-desktop
git remote add test-e2e ../desktop-qa-automation
git fetch test-e2e --no-tags
git merge --no-edit --allow-unrelated-histories test-e2e/master
```

Here's proof that it can work for a nightly, but will definitely need more adjustments:
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e/3/

And here's and example PR E2E run:
https://ci.status.im/job/status-desktop/job/e2e/job/prs-merged/2/

### CODE REVIEW

**Comment by jakubgs** [comment]
Windows Git has some REALLY weird issues with this branch:
```
Checking out Revision b17a35c058e2e51b9385beb48dab183f79df89a8 (PR-14548)
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git checkout -f b17a35c058e2e51b9385beb48dab183f79df89a8" returned status code 128:
stdout: 
stderr: error: invalid path 'test/e2e/tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py'
```
Maybe it's time to upgrade Git on windows.

**Comment by jakubgs** [comment]
What I don't understand is this error from `windows-03` host:
```
stderr: error: invalid path 'test/e2e/tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py'
```
https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-14548/7/console

It happens on `windows-02` so it's not host-specific.

**Comment by anastasiyaig** [comment]
> What I don't understand is this error from `windows-03` host:
> 
> ```
> stderr: error: invalid path 'test/e2e/tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py'
> ```
> 
> https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-14548/7/console
> 
> It happens on `windows-02` so it's not host-specific.

@jakubgs what i am seeing is that there are spaces in test name which windows normally hates. I can rename that quickly if it is resonable

**Comment by jakubgs** [comment]
The issue isn't spaces, it's the colons in filenames:
```
~/temp/status-desktop tests/merge-qa-automation
 > ls -l test/e2e/tests/wallet_main_screen
total 24
-rw-r--r-- 1 jakubgs jakubgs 42 Jun  3 09:47  __init__.py
drwxr-xr-x 2 jakubgs jakubgs  3 Jun  3 09:47 'wallet: assets tab'
drwxr-xr-x 2 jakubgs jakubgs  5 Jun  3 09:47 'wallet: footer actions'
drwxr-xr-x 2 jakubgs jakubgs 11 Jun  3 09:47 'wallet: plus button'
drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: right click on account'
drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: right click out of account area'
drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: saved addresses
```
What a terrible idea.

**Comment by anastasiyaig** [comment]
> The issue isn't spaces, it's the colons in filenames:
> 
> ```
> ~/temp/status-desktop tests/merge-qa-automation
>  > ls -l test/e2e/tests/wallet_main_screen
> total 24
> -rw-r--r-- 1 jakubgs jakubgs 42 Jun  3 09:47  __init__.py
> drwxr-xr-x 2 jakubgs jakubgs  3 Jun  3 09:47 'wallet: assets tab'
> drwxr-xr-x 2 jakubgs jakubgs  5 Jun  3 09:47 'wallet: footer actions'
> drwxr-xr-x 2 jakubgs jakubgs 11 Jun  3 09:47 'wallet: plus button'
> drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: right click on account'
> drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: right click out of account area'
> drwxr-xr-x 2 jakubgs jakubgs  4 Jun  3 09:47 'wallet: saved addresses
> ```
> 
> What a terrible idea. Fixed:
> 
> * [`status-desktop#862a1400`](https://github.com/status-im/status-desktop/commit/862a1400) - fix(e2e): remove colons from test filenames

Agree, i did that on the fly some time ago and forgot to fix :(

**Pull request merged**
