### PR TITLE
Fix some mint token UI issues

### PR DESCRIPTION
**Pull request by noeliaSD**
There are 5 fixes here solved in different commits:
https://github.com/status-im/status-desktop/issues/11149
https://github.com/status-im/status-desktop/issues/11147
https://github.com/status-im/status-desktop/issues/11199
https://github.com/status-im/status-desktop/issues/11198
https://github.com/status-im/status-desktop/issues/11208

### What does the PR do

The fixes are mainly issues created after a rebase so, just some property names or signal params changed incorrectly.

- Remotely destruct tokens flow should work correctly (I cannot test it in the app bc of the frozen app with accounts that have some minted and airdroped tokens)
- Airdrop item inserted correctly when there is navigation between minting view and airdrop.
- Minting footer options disabled logic.
- A label changed in a minting view box as per new design requirement.
- Updated remaining supply information when token is deployed with infinite supply.
- Storybook updates.

### Affected areas

Mint token / Airdrop token

### Screenshot of functionality 
- Airdrop navigation:

https://github.com/status-im/status-desktop/assets/97019400/cabb42cf-fc2e-43a0-80af-43d171350f21

- New label:
Screenshot 2023-06-21 at 18 26 07

- Footer disabled bc of minting in progress:

https://github.com/status-im/status-desktop/assets/97019400/f40f3e69-f32c-4e90-8784-4a77b597bc5e

- Airdrop disabled bc no remaining tokens:
Screenshot 2023-06-22 at 07 48 52

- Airdrop disabled bc no remaining tokens AND remotely destruct enabled bc of there are hodlers:
Screenshot 2023-06-22 at 07 59 20

- Remotely destruct disabled bc no hodlers:

Screenshot 2023-06-22 at 07 47 49

- Remaining tokens info when infinite supply set:
Screenshot 2023-06-22 at 07 23 36

### CODE REVIEW

**Review by endulab — APPROVED** [review]
I tested all operations:
- minting (deployment)
- airdrops (minting)
- burning
- remote burning

All worked correctly.

**Review by micieslak — APPROVED** [review]
Nice!

**Review by caybro — APPROVED** [review]
LGTM

**Comment by noeliaSD** [comment]
Just changed last commit bc of last minute design change: https://github.com/status-im/status-desktop/issues/11208#issuecomment-1602242824

Screenshot 2023-06-22 at 10 56 20

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@noeliaSD i tested it and it works like a charm! Please merge it asap :)

**Pull request merged**
