### PR TITLE
Nim library updates, pt 2

### PR DESCRIPTION
**Pull request by arnetheduck**
This is part 2 of the nim library updates targeting networking and ETH libraries:

* bearssl: upstream security updates, refactoring
* chronos: significant stability updates across the board - ie better connection management, async fixes, updates, refactoring etc
* eth: updates across the board, including EIP support, discv5, etc
* http-utils: fixes
* json-rpc: replaced websocket engine with in-house nim-websock (vs news which is no longer supported)
* libp2p: lots of updates, but not relevant to status-desktop as of yet
* web3: new API and conformance updates based on execution API spec
* semver: crash fix, branch name
* news: removed in favour of nim-websock

### CODE REVIEW

**Comment by arnetheduck** [comment]
@jrainville thoughts on moving forward with this?

**Comment by jrainville** [comment]
Sorry, I missed it. Next time, you can assign `desktop-devs` as reviewer, it's gonna auto assign two devs to review.

**Review by jrainville — APPROVED** [review]
LGTM. I tested quickly and basic functionality works

**Review by igor-sirotin — APPROVED** [review]
Nice! Didn't test, but have no concerns about the changes 🙂

**Pull request merged**
