### PR TITLE
[CHERRY-PICK] checksum validation

### PR DESCRIPTION
**Pull request by saledjenic**
Depends on `status-go` PR:
- https://github.com/status-im/status-go/pull/5632

Cherry-picked PR:
- https://github.com/status-im/status-desktop/pull/15893

### CODE REVIEW

**Comment by jrainville** [comment]
@saledjenic something is messed up here (wrong base or something)

**Comment by saledjenic** [comment]
@jrainville sorry, I see it was `master` instead of `release/2.30.x` set for the base branch.

**Comment by jrainville** [comment]
@saledjenic thanks it looks better. Can you just update the status-go vendor please.

**Comment by saledjenic** [comment]
> @saledjenic thanks it looks better. Can you just update the status-go vendor please.

@jrainville updated to point to related statusgo change from the statusgo PR, cause that one is not merged yet on the statusgo side.

**Comment by saledjenic** [comment]
@jrainville I've rebased this, just now, could you please merge it (statusgo part is already merged in statusgo release branch)?

**Comment by jrainville** [comment]
@saledjenic I rebased your commits and they don't launch anymore. Can you look at it. 

```RN 2024-08-09 13:48:03.605-04:00 qt warning                                 topics="qt" tid=461222 text="QQmlApplicationEngine failed to load component" file=:0 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Type AppMain unavailable" file=qrc:/main.qml:338 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Type WalletLayout unavailable" file=qrc:/app/mainui/AppMain.qml:1391 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Type LeftTabView unavailable" file=qrc:/app/AppLayouts/Wallet/WalletLayout.qml:239 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Type AddAccountPopup unavailable" file=qrc:/app/AppLayouts/Wallet/views/LeftTabView.qml:52 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Type AddAccountStore unavailable" file=qrc:/imports/shared/popups/addaccount/AddAccountPopup.qml:20 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Unexpected token `('" file=qrc:/imports/shared/popups/addaccount/stores/AddAccountStore.qml:185 category=default
WRN 2024-08-09 13:48:03.606-04:00 qt warning                                 topics="qt" tid=461222 text="Expected token `('" file=qrc:/imports/shared/popups/addaccount/stores/AddAccountStore.qml:185 category=default
INF 2024-08-09 13:48:03.606-04:00 starting application...                    topics="status-app" tid=461222 file=nim_status_client.nim:250
WRN 2024-08-09 13:48:03.609-04:00 Error decoding signal                      topics="signals-manager" tid=461222 file=signals_manager.nim:49 err="Unknown signal received: mediaserver.started"
WRN 2024-08-09 13:48:03.610-04:00 qt warning                                 topics="qt" tid=461222 text="Error while loading QML: QUrl(\"qrc:/main.qml\")" file=:0 category=default
INF 2024-08-09 13:48:03.610-04:00 shutting down...                           topics="status-app" tid=461222 file=nim_status_client.nim:221
INF 2024-08-09 13:48:03.610-04:00 logging out...                             topics="app-controller" tid=461222 file=app_controller.nim:300
```

**Comment by saledjenic** [comment]
@jrainville yes, it was a rebase issue, a closing bracket was missing, thanks, it should be good now.

**Pull request merged**
