### PR TITLE
don't allow username change for own user

### LINKED ISSUE #2374: it shouldnt be possible to set a nickname for yourself
https://user-images.githubusercontent.com/1106587/115769103-27db8400-a379-11eb-8c7f-897bff839b94.mp4

### PR DESCRIPTION
**Pull request by iurimatias**
fixes #2374

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@iurimatias how do we want to handle the update (when user set this nickname for some reason and then updated to the version where it is not possible) -> i see this nickname set at the top of my profile

**Comment by iurimatias** [comment]
@anastasiyaig I can add a check for that, although it would be kinda unfortunate because it would mean a check that is probably not needed for 99.9% of users (since they cannot set the nickname anymore anyway)

**Review by jrainville — APPROVED** [review]

**Comment by jrainville** [comment]
> although it would be kinda unfortunate because it would mean a check that is probably not needed for 99.9% of users (since they cannot set the nickname anymore anyway)

IMO, we can ignore that, since like you said, it affects almost no one. Also, we are in beta  and removing the data folder and re-importing the seed phrase would fix the issue.

**Comment by anastasiyaig** [comment]
> > although it would be kinda unfortunate because it would mean a check that is probably not needed for 99.9% of users (since they cannot set the nickname anymore anyway)
> 
> IMO, we can ignore that, since like you said, it affects almost no one. Also, we are in beta and removing the data folder and re-importing the seed phrase would fix the issue.

lets ignore it then and merge it

**Pull request merged**
