### PR TITLE
update status/wakuv2 fleets DNS discovery enrtree

### PR DESCRIPTION
**Pull request by yakimant**
### What does the PR do

Enrtrees are updated, please test the DNS discovery.

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Comment by yakimant** [comment]
@richard-ramos, @jrainville, is testing needed here?

**Comment by jrainville** [comment]
> @richard-ramos, @jrainville, is testing needed here?

Better safe than sorry I guess.

@anastasiyaig can you have someone test this PR please. 
@yakimant anything special to test? Mostly message reliability I guess?

**Comment by richard-ramos** [comment]
The success criteria for the test would be to create a new account, and see that desktop connects to peers.

**Comment by anastasiyaig** [comment]
Should be fine! 
Screenshot 2023-09-28 at 09 21 55

**Review by anastasiyaig — APPROVED** [review]

**Comment by jakubgs** [comment]
I'm not sure this actually works without also including these changes:

* https://github.com/status-im/status-go/pull/4063

**Comment by yakimant** [comment]
@anastasiyaig, I updated status-go submodule to https://github.com/status-im/status-go/pull/4063, can you plesae test what Richard suggested again?

**Comment by anastasiyaig** [comment]
@yakimant ya, still looks okay to me

**Comment by yakimant** [comment]
Removed `status-go` update from this PR, as https://github.com/status-im/status-go/pull/4070 is already merged and submodule updated in master.

**Pull request merged**
