### PR TITLE
fix: make contact related APIs working again

### LINKED ISSUE #4147: Add to contacts is not working because of status-go change
# Bug Report

## Description

Add to contacts is not working because of status-go change https://github.com/status-im/status-go/pull/2413

## Steps to reproduce

1. open a 1x1 chat with a user that u havent added to contacts yet
2. click Add to contacts button

Screenshot 2021-11-22 at 15 28 32

#### Expected behavior

Can send a contact request

#### Actual behavior

```
ERR 2021-11-22 15:24:46.979+03:00 rpc response error                         topics="rpc" tid=3072585 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32601,\"message\":\"the method wakuext_saveContact does not exist/is not available\"}}" payload="[{\"id\":\"0x045efbcc044e5ae21ac3cf111ea6df6186e0cc50a2cd747f52a56d19ce516e683c66cb47f4b0a21110859aea9592dfba1e0bf4af11ff3eab995f844b3673643bf1\",\"name\":\"\",\"ensVerified\":false,\"alias\":\"Thoughtful Stupendous Graywolf\",\"identicon\":\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAgElEQVR4nOzWsQmAQBAFURV7sTI7sAw7sDKr0VwMVvC44TMvlEuGD4vTEMIQGkNoDKExhMYQGkNoDKGJCZmrD49zv96+r8s29nj/FLOIITSGqJGYRQyhMYTGfy0aQ2gMoSlfra+q1+YvMYsYQmOIGolZxBAaQ2gMoTGE5g4AAP//I/YZaHdYNaEAAAAASUVORK5CYII=\",\"images\":{\"thumbnail\":{\"Payload\":\"\"},\"large\":{\"Payload\":\"\"}},\"added\":true,\"blocked\":false,\"hasAddedUs\":false,\"localNickname\":\"\"}]" methodName=wakuext_saveContact
```
### Additional Information

- Status desktop version: 0.4.0 release, master
- Operating System: macOS

### PR DESCRIPTION
**Pull request by PascalPrecht**
This adjust the changes needed to have Status Desktop
talk to new contact related APIs that were introduced in status-lib
and status-go as of https://github.com/status-im/status-lib/pull/110

Closes #4147

### CODE REVIEW

**Comment by PascalPrecht** [comment]
This needs https://github.com/status-im/status-lib/pull/110

**Review by saledjenic — CHANGES_REQUESTED** [review]
@PascalPrecht I updated related code in the `base_bc` branch, actually entire contacts service is improved there and works properly with the old api. Maybe it we ought just to cherry pick that from there. 

But all in all have you run this code after applied changes?
As I see on the first sight this should not be compilable since the service refers to the new contacts (line 7 here) added to `statusgo_backend_new` and you added new methods to the old code?

**Comment by PascalPrecht** [comment]
> is improved there and works properly with the old api

Are you referring to status-go's old API? Because that one has been removed. 

> As I see on the first sight this should not be compilable since the service refers to the new contacts (line 7 here) added to statusgo_backend_new and you added new methods to the old code?

It is compiling and I tested this as well. I do have to update one of the APIs in status-lib though. Re:old code: I was surprised that some methods in desktop bypass status-lib's intermediary methods an call `status_contacts` directly instead. So to be sure that this works every where I've actually introduced the new APIs in both, the old and the new backend (as you can see here): https://github.com/status-im/status-lib/pull/110/files

**Comment by saledjenic** [comment]
> Are you referring to status-go's old API? Because that one has been removed.

Yes, I am referring to the old status-go API points

> It is compiling

Just to be clear not arguing, but that's not possible man based on what I see in files changed within this commit. So in [this line](https://github.com/status-im/status-desktop/blob/84e03962c5a6438468b8aa1a6ab76637b7f30bf3/src/app_service/service/contacts/service.nim#L7) we're referring to the contacts file from `statusgo_backend_new`, and [here](https://github.com/status-im/status-lib/blob/be61aa27364dd206913aa39459a2ed0741293fc7/status/statusgo_backend_new/contacts.nim) is how does it look for commit in `status-lib` we're pointing to from this branch. There are no methods you're calling like `rejectContactRequest`, `setContactLocalNickname`, `unblockContact`, `blockContact`, `removeContact`, you're actually calling them for `status_contacts` which refers to `status/statusgo_backend_new/contacts`, see line 7 [here](https://github.com/status-im/status-desktop/blob/84e03962c5a6438468b8aa1a6ab76637b7f30bf3/src/app_service/service/contacts/service.nim#L7)

> So to be sure that this works every where I've actually introduced the new APIs in both, the old and the new backend (as you can see here): https://github.com/status-im/status-lib/pull/110/files

That's the thing, files changed there are: `status/contacts.nim` and `status/statusgo_backend/contacts.nim`, but not `status/statusgo_backend_new/contacts.nim` which we're pointing from the changes applied in this commit, that's why I said this should be not compilable. Please try to build this branch.

**Comment by PascalPrecht** [comment]
All of the APIs have been added here: https://github.com/status-im/status-lib/pull/110

You're right that this commit doesn't explicitly point at that branch of `status-lib` but that's why I've mentioned in the PR message that it relies on that.

There's other work being done in status-lib which live in yet other branches. If I'd point to that one specific branch and later someone merges something that pointed at a different branch of status-lib, we might lose these changes again. 

So I rather wait until we know for sure that the changes have landed in status-lib.

> Please try to build this branch.

Please do it yourself cause I've been doing it plenty times to actually test the stuff.

**Comment by PascalPrecht** [comment]
Forgot to push changes of status-lib that I was sitting on. The PR branch is up-to-date now.

**Comment by saledjenic** [comment]
> Please do it yourself cause I've been doing it plenty times to actually to test the stuff.

I did and got this:
```
Building: bin/nim_status_client
/Users/sale/Status/desktop-app/src/app_service/service/contacts/service.nim(27, 1) template/generic instantiation of `QtObject` from here
/Users/sale/Status/desktop-app/src/app_service/service/contacts/service.nim(126, 21) Error: undeclared identifier: 'rejectContactRequest'
make: *** [bin/nim_status_client] Error 1
```

**Comment by saledjenic** [comment]
> Forgot to push changes of status-lib that I was sitting on. The PR branch is up-to-date now.

@PascalPrecht yes, all good now. Thanks.

**Review by saledjenic — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]

**Pull request merged**
