### PR TITLE
fix(Community): leave community from Community profile popup

### LINKED ISSUE #2403: leave community not working
clicking Manage Community and then Leave Community doesn't do anything

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #2403

### CODE REVIEW

**Review by iurimatias — CHANGES_REQUESTED** [review]
the leave works, but when I close and reopen the app the community is there again

**Comment by jrainville** [comment]
I think this is a status-go issue. I've seen it in master before.  
@cammellos have you ever seen this issue of a community you left that reappears when re-login in?
It seems to happen to me when I'm the admin and then after login, I wait a couple of seconds and sometimes the community reappears. It's a bit like I'm still subscribed to it for some reason.
Any idea?

**Comment by anastasiyaig** [comment]
@jrainville is it possible to add confirmation when leaving community (same when deleting chats)? So clicking Leave community will ask user to confirm the action (since this is likely the same action when leaving public chat or deleting 1x1 chat, so would be nice to have the pattern across the app)

**Comment by simonricoo** [comment]
I think the modal wont hurt :)

**Comment by anastasiyaig** [comment]
> I think this is a status-go issue. I've seen it in master before.
@cammellos have you ever seen this issue of a community you left that reappears when re-login in?

@jrainville  i am seeing the community in the UI after leaving it even without relogin, so I am somehow left it but i am still a member but i have join button at the same time, so quite confusing.

1. we need to understand what should happen when i leave the community and i am an admin
2. what should happen when i leave the community and i am not the admin
3. regarding possible status-go issue i am talking to @cammellos right now

**Comment by anastasiyaig** [comment]
@jrainville @cammellos there is an issue logged about leaving communities on mobile , maybe fixing this issue will fix appearing communities on desktop as well, please take a look and advise https://github.com/status-im/status-react/issues/12087

**Comment by cammellos** [comment]
that's a bit of a different issue, 
I would have to check, but basically we should be checking the `joined` flag, if that's true we should show the community (apart from the status community which we want to show always).

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias i suggest to merge this PR, since at least it makes Leave community button actionable and i will open another issue about the communities present in the list after leaving them

**Pull request merged**
