### PR TITLE
Add the xTwitter new logo

### PR DESCRIPTION
**Pull request by dicethedev**
Fix - [Profile Showcase] Wrong X (Twitter) icon #14300

### CODE REVIEW

**Review by caybro — COMMENTED** [review]
Nice trick :)

The problem here though is that we already have this new icon but under a different name. So the objective of the PR should also be to get rid of the other copy (`xtwitter.svg`) and adjust the QML code to just use this icon here.

Thanks for your contribution, can you pls update the PR according the above needs? Sorry if the issue wasn't explicit enough

**Comment by dicethedev** [comment]
> Nice trick :)
> 
> The problem here though is that we already have this new icon but under a different name. So the objective of the PR should also be to get rid of the other copy (`xtwitter.svg`) and adjust the QML code to just use this icon here.
> 
> Thanks for your contribution, can you pls update the PR according the above needs? Sorry if the issue wasn't explicit enough

Alright. I will look into this!

**Comment by alexjba** [comment]
@dicethedev Have a look here
https://github.com/status-im/status-desktop/blob/master/ui/imports/utils/ProfileUtils.qml#L82

This is where we map the icon to the link type

**Comment by alexjba** [comment]
@Seitseman I think you've already fixed this, right?

**Comment by Seitseman** [comment]
Already fixed in https://github.com/status-im/status-desktop/pull/15185

**Pull request closed without merging**
