### PR TITLE
chore(status-go): bump status-go to have the windows login fix

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-go/issues/5186

This is to test this status-go PR https://github.com/status-im/status-go/pull/5255

@anastasiyaig please have someone on every OS test creating an account and logging in to make sure all is good.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@jrainville update: i launched the PR on my windows 10 machine and i cant create account there

image

I restarted the app and was able to login afterwards.

I also talked to @Seitseman and i think we still need to merge some outstanding PR? https://github.com/status-im/status-go/pull/5255

I am happy to retest if needed later

**Comment by jrainville** [comment]
> @jrainville update: i launched the PR on my windows 10 machine and i cant create account there
> 
> I restarted the app and was able to login afterwards.
> 
> I also talked to @Seitseman and i think we still need to merge some outstanding PR? [status-im/status-go#5255](https://github.com/status-im/status-go/pull/5255)
> 
> I am happy to retest if needed later

Yes the outstanding PR si not merged yet. Sorry, I should have made it clearer in the description. I'll update it. 

I created this PR to test the status-go changes before merging to prevent issues like this haha.

So @Seitseman there seems to be some more fixes to be done?

**Comment by Seitseman** [comment]
@Jo, @anastasiyaig , From the 

> @jrainville update: i launched the PR on my windows 10 machine and i cant create account there

>image

>I restarted the app and was able to login afterwards.

>I also talked to @Seitseman and i think we still need to merge some outstanding PR? https://github.com/status-im/status-go/pull/5255

>I am happy to retest if needed later

From that printscreen I see you had some other unrelated error. Its not about status-go, but some other strange lib not loading in time (I have not looked into that yet)

That error happens sporadically on my windows as well for master and old releases (e.g. 2.28.1)

**Comment by Seitseman** [comment]
@jrainville I would say that this PR is ready for merging, as account was properly created.
@anastasiyaig , could you please create a ticket for that sporadic "Attempt to read from nil"?

**Comment by jrainville** [comment]
> @jrainville I would say that this PR is ready for merging, as account was properly created. @anastasiyaig , could you please create a ticket for that sporadic "Attempt to read from nil"?

@Seitseman can you check the mobile PR (linked on the status-go PR). It seems that mobile has issues too

**Comment by anastasiyaig** [comment]
i also saw the problem when creating a keycard account, then we miss identicon and public key rings on onboarding, but i wanted to retest it when everything is ready

**Comment by anastasiyaig** [comment]
to clarify i am not blocking the merge. if thats ready then ready

**Comment by Seitseman** [comment]
From https://github.com/status-im/status-mobile/pull/20296 it seems that the mkdir rightfully failed because that path is a top-level 'data' path. And app cannot create "root" for its data. Prior to the above fix problem was hidden because path was 'duplicated' (e.g. it was /var/mobile/Containers/Data/Application/3FEB...12D/var/mobile/Containers/Data/Application/3FEB...12D) and iOS allowed creating such path in Applications' Data dir. 
@jrainville , I would add in https://github.com/status-im/status-go/blob/3906fcb5fb1fe16d126b9154633ae1133a193cf4/services/ext/service.go#L145-L146 some logic and Mkdir only if needed path does not exist.

**Comment by jrainville** [comment]
@yqrashawn seems to be trying to help, so maybe you guys can collaborate

**Comment by jrainville** [comment]
@anastasiyaig can you test again. Igor made some fixes to it. Thanks @igor-sirotin for jumping on it! :muscle:

**Comment by igor-sirotin** [comment]
Updated to the latest fix version

**Comment by jrainville** [comment]
Closing this as the tests were ran succefully.

@igor-sirotin could you cherry-pick the fixes to develop/master. Thanks

**Comment by igor-sirotin** [comment]
> could you cherry-pick the fixes to develop/master. Thanks

@jrainville I did cherry-pick it to status-go release branch yesterday.
And I see you already made a new RC with the fix, thanks 🙂

**Pull request closed without merging**
