### PR TITLE
chore: bump status-go

### LINKED ISSUE #15122: Community permissions: Setting NFTs based permissions with count > 1 doesn’t work
# Bug Report

## Description

A channel with a permission of more than 1 NFT is not considering the correct amount and lets any user who holds at least 1 token in. 

## Steps to reproduce

1. As a Community owner or admin, set up a channel with the following permission: Anyone who holds 2 TOKEN is allowed to View and Post. 
2. Check the "Hide channel from members who don't have permissions to view channel"
3. Airdrop 1 TOKEN to member1, and 2 TOKENs to another member2.

#### Expected behavior
Member2 can see the channel because they met the channel permissions requirements.
Member1 cannot see the channel because they do not met the requirements. They need at least 1 more token.

#### Actual behavior
Member1 can see the channel even though they do not meet the requirements. They should hold at least 1 more token.

Test017 has 1 SIESTA token
Screenshot 2024-06-10 at 9 18 12 AM

Notice the channel permissions are set for users who hold 2 SIESTA tokens
Screenshot 2024-06-10 at 9 19 04 AM

Test017 can see channel and post. (Message sent June 10)
Screenshot 2024-06-10 at 9 27 51 AM

Tested with other user as well, using 2 and 3 required tokens.
3 tokens are required on this channel
Screenshot 2024-06-10 at 9 58 41 AM
VirDevTest user holds 1 token
Screenshot 2024-06-10 at 9 57 04 AM
How user sees channel
Screenshot 2024-06-10 at 10 00 58 AM

### Additional Information
This issue was discovered while testing https://github.com/status-im/status-desktop/pull/15038 

- Status desktop version: latest master version https://github.com/status-im/status-desktop/commit/54665ffba
- Operating System: Mac OS Sonoma

### LINKED ISSUE #15242: Test PR 15236
To test https://github.com/status-im/status-desktop/pull/15236

### PR DESCRIPTION
**Pull request by osmaczko**
fixes: #15122

### CODE REVIEW

**Comment by osmaczko** [comment]
@status-im/desktop-qa, could you please check issue https://github.com/status-im/status-desktop/issues/15122 itself and member reevaluation flows with various permission configurations? :pray: 

I touched a very critical part of check permissions code. The logic should remain the same, but still, there is a risk of regression.

**Comment by anastasiyaig** [comment]
@osmaczko pls rebase this one, so @lukaszso can proceed with testing (we need the fix for permissions)

**Comment by osmaczko** [comment]
> @osmaczko pls rebase this one, so @lukaszso can proceed with testing (we need the fix for permissions)

@anastasiyaig done :+1:

**Comment by osmaczko** [comment]
Tested, all fine, merged status-go PR. Closing this one, the bump will happen sooner or later.

**Pull request closed without merging**
