### PR TITLE
fix: ens details view

### LINKED ISSUE #6192: ENS Usernames
**Pending usernames are missing the `stateofus.eth` subtitle**
image

---

**Releasing username button is immediately available (unless it's been selected as a primary username). The release button should be disabled since the username is locked for 1Y**
image

---

**Release button is executing `setPubkey(bytes32 node, bytes32 x, bytes32 y)` . It should run the smart contract function that releases username instead**
See trx: https://ropsten.etherscan.io/address/0x42d63ae25990889e35f215bc95884039ba354115

---

**After selecting an ens username as primary name, the release date is calculated incorrectly. Should be 1Y after buy date.**
image

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #6192 

Requires:
- https://github.com/status-im/status-go/pull/2756

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]
LGTM

**Review by caybro — CHANGES_REQUESTED** [review]

**Review by saledjenic — APPROVED** [review]

**Comment by elina2015** [comment]
Cannot test because I don't have ETH to buy ENS. Look at https://discord.com/channels/624205794384281629/869581754858635314/1001673451880321074

**Comment by glitchminer** [comment]
Had a look at this just now @elina2015 but app is crashing on log in after entering password.

image


```
INFO [07-29|15:40:41.346] Status backend initialized               backend=geth version=0.102.4 commit=63c8931d
Traceback (most recent call last)
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/nim_status_client.nim(169) nim_status_client
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/nim_status_client.nim(166) mainProc
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(566) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/core/signals/signals_manager.nim(56) receiveSignal
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/core/signals/signals_manager.nim(53) processSignal
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/core/eventemitter.nim(46) emit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/modules/startup/controller.nim(35) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/modules/startup/io_interface.nim(16) userLoggedIn
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/modules/startup/module.nim(81) userLoggedIn
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/boot/app_controller.nim(345) userLoggedIn
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app/boot/app_controller.nim(317) load
/Users/jenkins/workspace/s-desktop_branches_macos_PR-6501/src/app_service/service/ens/service.nim(138) init
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by anastasiyaig** [comment]
@richard-ramos please reabase, perhaps it will help

**Comment by anastasiyaig** [comment]
Screenshot 2022-08-01 at 17 40 51

**Review by anastasiyaig — APPROVED** [review]

**Review by caybro — APPROVED** [review]

**Pull request merged**
