### PR TITLE
fix(@desktop): Persist application window state & geometry

### LINKED ISSUE #3073: Persist application window state / geometry
I have 4K screen with 250% scale factor set in display settings (Windows OS).
This makes the default window size to span beyond the desktop area. I had to resize the window (make it smaller) or maximize it.
In any case after I restart the app, it gets its initial size and centered position within the desktop.
I think we need to persist in settings:
- window state: Normal | Maximized
- window geometry

and restore these when launching the app.

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #3073

- [x] Add x/y to settings file & main.qml
- [x] Add state to settings file & main.qml

### Affected areas

Desktop

### Screenshot of functionality

https://user-images.githubusercontent.com/2522130/168570592-e8be70b0-c921-49e3-890b-a93977e2572d.mp4

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
Some questions:
- Do we really need to save window's geometry on every change. What if geometry and state will be saved on window close event?
- I want to chage x, y, width and height properties on QRect. Is is ok?
- If we exit app in minimized state, should i restore it in minimized state too?

**Comment by PascalPrecht** [comment]
> Do we really need to save window's geometry on every change. What if geometry and state will be saved on window close event?

Can do that as well, assuming that the window closed event is guaranteed to be emitted. Is that the case when the application is stopped using e.g SIGINT?

**Comment by PascalPrecht** [comment]
> If we exit app in minimized state, should i restore it in minimized state too?

I don't think so no. This is most likely unexpected by users.

**Comment by MishkaRogachev** [comment]
> Can do that as well, assuming that the window closed event is guaranteed to be emitted. Is that the case when the application is stopped using e.g SIGINT?

Oh, it's not [easy](https://gist.github.com/azadkuh/a2ac6869661ebd3f8588) to handle SIGINT, SIGKILL, SIGTERM and others. I'll leave it as is.

**Review by saledjenic — APPROVED** [review]

**Comment by saledjenic** [comment]
> Do we really need to save window's geometry on every change. What if geometry and state will be saved on window close event?

To save those values on app close sounds ok to me.

> I want to chage x, y, width and height properties on QRect. Is is ok?

Yes.

> If we exit app in minimized state, should i restore it in minimized state too?

No.

**Review by PascalPrecht — APPROVED** [review]

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
