### PR TITLE
chore: update icon for code text formatting

### LINKED ISSUE #1934: use SVG code icon
Please use SVG for this icon, its blurred

Screen_Shot_2021-02-26_at_10_44_05

### PR DESCRIPTION
**Pull request by PascalPrecht**
Closes #1934

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Not sure if this is a bug but Github says the new SVG is empty. I assume it's because the number of lines is the same? 🤷

**Comment by PascalPrecht** [comment]
That's weird indeed. Locally you can see that changes exist:

```
diff --git a/ui/app/img/format-text-code.svg b/ui/app/img/format-text-code.svg
index bfba8bf5..2967329e 100644
Binary files a/ui/app/img/format-text-code.svg and b/ui/app/img/format-text-code.svg differ
```

**Review by iurimatias — CHANGES_REQUESTED** [review]
Screen Shot 2021-03-04 at 5 29 14 PM

it actually looks more pixalized now, it might need one of the options like mipmap true or some of the previous qml svg tricks

**Comment by PascalPrecht** [comment]
It actually looked sharper on my machine, but it's smaller. Not really sure what else to do. The previous one was already an `svg` as well. How come we assume it was a `png` again? /cc @simonricoo

**Comment by iurimatias** [comment]
master
master

**Comment by iurimatias** [comment]
this branch
Screen Shot 2021-03-05 at 10 15 39 AM

**Comment by iurimatias** [comment]
@simonricoo at this point it looks better in master (due to recent changes), could you check the latest mater out when you get the chance and let me know if it still looks the same for you or not plz?

**Comment by simonricoo** [comment]
On latest master:
StatusIm-210305-153424-9fe925.dmg
--

Screenshot 2021-03-05 at 16 46 09

No change, it still looks blurred

**Comment by iurimatias** [comment]
closed in favour of #2499

**Pull request closed without merging**
