### PR TITLE
check the status-go PR changes that fix #17223 mobile issue against the desktop app

### LINKED ISSUE #17223: [Onboarding] Integrate the FactoryResetFlow
### Description

In https://github.com/status-im/status-desktop/pull/17167, we introduced the UI part of the Factory reset flow. This issue should cover the NIM integration. 

In a nutshell, should be as easy as:

Image

### PR DESCRIPTION
**Pull request by saledjenic**
Closes https://github.com/status-im/status-desktop/issues/12111

@QA please do check the syncing feature in this PR which points to the changes of the status-go that fix mobile issue:

- status-go PR: https://github.com/status-im/status-go/pull/4010
- mobile app issue: https://github.com/status-im/status-mobile/issues/17223

### CODE REVIEW

**Comment by saledjenic** [comment]
@churik @qfrank here is the desktop app PR that points to the status-go changes that fix the mobile app issue.

**Comment by anastasiyaig** [comment]
alright, i will take a look @saledjenic

**Comment by churik** [comment]
Thank you, results are https://github.com/status-im/status-mobile/pull/17226#issuecomment-1713594158

**Comment by anastasiyaig** [comment]
@saledjenic i noticed that the desktop app is stuck when u scan a QR code from mobile device. How to reproduce:

1. install the build on mobile app and create new account there
2. install the build on desktop app and select - I arelady use status -> Scan Sync code. Enable the camera access on your laptop and scan the QR displayed on mobile phone

Screenshot 2023-09-11 at 13 20 13

Console log:

```
Experimental support for Apple Silicon
INFO [09-11|13:18:10.960] Status backend initialized               backend=geth version=0.166.8 commit=46c0063be IpfsGatewayURL=https://ipfs.status.im/
INF 2023-09-11 13:18:11.285+03:00 Version: 0.9.90                            topics="status-app" tid=13320404 file=nim_status_client.nim:189
INF 2023-09-11 13:18:11.285+03:00 Commit: 2d84e2a13                          topics="status-app" tid=13320404 file=nim_status_client.nim:190
INF 2023-09-11 13:18:11.285+03:00 Current date:                              topics="status-app" tid=13320404 file=nim_status_client.nim:191 currentDateTime=2023-09-11T13:18:11+03:00
INF 2023-09-11 13:18:11.285+03:00 starting application controller...         topics="status-app" tid=13320404 file=nim_status_client.nim:193
INF 2023-09-11 13:18:11.853+03:00 starting application...                    topics="status-app" tid=13320404 file=nim_status_client.nim:196
WRN 2023-09-11 13:18:11.857+03:00 Error decoding signal                      topics="signals-manager" tid=13320404 file=signals_manager.nim:43 err="Unknown signal received: mediaserver.started"
Debug: StatusApplicationDelegate::applicationDidFinishLaunching (:0, )
Debug: needed to resize (:0, )
Debug: size:  0 , new size:  8294400 (:0, )
WARN [09-11|13:20:51.641] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.77.128.175:51086' failed: dial tcp 10.77.128.175:51086: connect: operation timed out; "
WARN [09-11|13:22:07.646] failed to connect to any of given addresses. Retrying... error="failed to connect to any of given addresses. connecting to 'https://10.77.128.175:51086' failed: dial tcp 10.77.128.175:51086: connect: operation timed out; "

```

**Comment by saledjenic** [comment]
@qfrank seems that the status-go changes are not compatible with the desktop app?
The desktop app doesn't work if it points to that status-go PR. Do we need to apply anything on the desktop app side or?

**Comment by saledjenic** [comment]
@alaibe we have a request from the mobile team ( @churik ) to include the related status-go PR to the 0.14. release once the issue @anastasiyaig found gets fixed.

**Comment by qfrank** [comment]
Hi @anastasiyaig , i guess the stuck will get through finally right, it just take seconds?

**Comment by saledjenic** [comment]
@qfrank @anastasiyaig I've just created another PR, here: https://github.com/status-im/status-desktop/pull/12121

it is made from desktop master `61f3d903ce437b97f7509e173dc18012b08e340e` and points to statusgo `e77fc59f5e13877c5d62e58213cd12ba88415939`

and this PR is updated and it's now made from `61f3d903ce437b97f7509e173dc18012b08e340e` and points to statusgo `9c6519c00218d3da8f0e9bfbaa53d539cb83d023`

**Comment by anastasiyaig** [comment]
I added a separate issue to the problem discussed https://github.com/status-im/status-desktop/issues/12126 to fix it later

**Comment by saledjenic** [comment]
@anastasiyaig @qfrank I wouldn't say that's an issue on the desktop app side, I would rather say that's something recently changed/updated on the status-go side.

**Comment by igor-sirotin** [comment]
@saledjenic I believe the base branch should be `release/0.14.x`, right?

**Comment by saledjenic** [comment]
@igor-sirotin have no idea, if the issue is reproducible in master I guess you can fix it there.

**Comment by igor-sirotin** [comment]
I'd say that this PR is simply an update to pick up status-go changes, i.e. https://github.com/status-im/status-desktop/issues/12111. If this PR is the reason for https://github.com/status-im/status-desktop/issues/12126, I will fix it first ofc, but the destination branch should be `0.14.x` anyway.

Let me know if you have any objections with that :)

**Comment by igor-sirotin** [comment]
Changed the base branch, will rebase soon.

**Comment by igor-sirotin** [comment]
Rebased.
Here's a status-go PR to cherry-pick the changes to desktop release: https://github.com/status-im/status-go/pull/4023

**Comment by igor-sirotin** [comment]
Closing, as status-go is already pointing above https://github.com/status-im/status-go/pull/4010.

**Pull request closed without merging**
