### PR TITLE
fix(@desktop/chat): Use different check icons in chat activity center

### LINKED ISSUE #5468: mark as read and mark as unread have same icon in the activity center
# Bug Report

Screen Shot 2022-04-08 at 5 36 39 PM

### PR DESCRIPTION
**Pull request by endulab**
Fix #5468

### What does the PR do

Use different icons for checkmarks in activity center

### Affected areas

Chat / Activity center

### Screenshot of functionality

image

### CODE REVIEW

**Comment by Khushboo-dev-cpp** [comment]
Hey does this icon already live in StatusQ, then in that case can we use that. Also there is only a difference of coloe we can use StatusIcon and change color through that instead?

**Review by Khushboo-dev-cpp — COMMENTED** [review]
Hey added a comment about the icon

**Comment by endulab** [comment]
@Khushboo-dev-cpp , unfortunately this icon is different than the one from StatusQ.
But I made one change: 1. I added only one icon and named it "check-activity", so it is related to activity panel 2. I am changing a color when clicking (according to your suggestion)

**Review by noeliaSD — APPROVED** [review]
LGTM!

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
