### PR TITLE
General: Add StatusQ qml tests to CI tests

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

The setup for `StatusQ` was already present, however the tests were not maintained because of no integration with CI. This PR is intended to add that integration and enforce checks on CI.

- exposes `TestStatusQ` to `Makefile`
- adds step to `ci/Jenkinsfile.tests-imports` for building and running unit tests (import sanity checker and unit tests in a single check)
- renames `ci/Jenkinsfile.tests-imports` to `ci/Jenkinsfile.tests-statusq`
- disables failing test in `tst_test-StatusInput`

Closes: #12081

### Affected areas
`Makefile`, `ci` dir

### CODE REVIEW

**Review by jakubgs — CHANGES_REQUESTED** [review]
I really don't think we need yet another separate job for tests.

Couldn't we just add those to `imports` tests?
Maybe we could rename that job to `statusq` tests to match both types better.

**Comment by micieslak** [comment]
> I really don't think we need yet another separate job for tests.
> 
> Couldn't we just add those to `imports` tests? Maybe we could rename that job to `statusq` tests to match both types better.

I agreed. Fixed - now it's combined with import sanity checker.

**Review by jakubgs — COMMENTED** [review]
Please never use absolute paths in symlinks, ever.
```
 > readlink Jenkinsfile.tests-imports
/home/michalc/workspace/status-desktop/ci/Jenkinsfile.tests-statusq
```
Unless you know exactly that's what you want.

**Comment by jakubgs** [comment]
Look good:

image

**Review by jakubgs — APPROVED** [review]

**Review by alexjba — APPROVED** [review]
Great addition!
Thank you 👍

**Pull request merged**
