### PR TITLE
fix(Storybook): linking WebEngine causes errors on Linux

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

For linux the linker is set to gold which fixes the problem with linking described in the ticket.

Closes: #8454

### Affected areas
`Storybook`

### CODE REVIEW

**Review by caybro — COMMENTED** [review]
I'm using mold myself 😬

**Comment by caybro** [comment]
Why do we even have to link against webenginge in the first place?

**Review by jrainville — APPROVED** [review]

**Review by caybro — CHANGES_REQUESTED** [review]
Just remove the WebEngine dependency as we discussed

**Comment by micieslak** [comment]
> Just remove the WebEngine dependency as we discussed

Thanks! That's the best option for sure!

**Review by caybro — APPROVED** [review]

**Review by alexjba — APPROVED** [review]

**Pull request merged**
