### PR TITLE
fix(@desktop/notifications): move notifications settings to `status-go`

### LINKED ISSUE #5649: Move notifications settings to `status-go`
Next step for Notifications settings section should be moving those setting from the local .ini file to the settings on the `status-go` side. Initially as part of the PR #5334 notifications settings values are stored in the .ini file.

Having those settings on the status-go side is needed for the app synchronization across devices.

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/2669

Fixes #5649

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]

**Comment by osmaczko** [comment]
Considering the current n-layer architecture, exposing service instance directly to QML looked suspicious at first glance. After a second look, it's just convenient to do that, because settings are global to the app :+1:

**Comment by saledjenic** [comment]
> Considering the current n-layer architecture, exposing service instance directly to QML looked suspicious at first glance. After a second look, it's just convenient to do that, because settings are global to the app 👍

Yes, I was thinking the same, form one side considering our architecture `Settings` class is a service (since it communicates with `status-go` and it's the only point on the desktop app side responsible for that) from the other side, settings is something what need to be globally accessible in the app (from all parts of the app) in an easy way. Other solution I had on my mind was to add new class which will be used only for dealing with setting from the `status-go` but in that case if someone missed it and used settings service directly we will have inconsistency, and that's why I decided to expose settings service as QObject class and register it as context property.

**Review by richard-ramos — APPROVED** [review]

**Comment by saledjenic** [comment]
@all since I updated `status-go` part and moved notifications related settings to a new table what has required a lot of new changes here, I am kindly asking if you can give another round of review here.

**Review by borismelnik — APPROVED** [review]
Tested!

**Pull request merged**
