### PR TITLE
Fix(@desktop): Resolve scrolling twitches

### LINKED ISSUE #6187: Chat scrolling twitches
Might be related to https://github.com/status-im/status-desktop/issues/5781
But actually behaves differently.

## Description

https://user-images.githubusercontent.com/25482501/174867379-5efdf04d-4ea7-4fa3-86c2-03b692831122.mov

## Steps to reproduce

1. Open chat
2. Scroll

#### Expected behavior

Smooth scrolling

#### Actual behavior

Unbearable twitching

### Additional Information

- Status desktop version: 0.5.0
- Operating System: MacOS 12.4

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #6187
Depends https://github.com/status-im/StatusQ/pull/784

### What does the PR do

Replace ListView/ScrollView with StatusListView/StatusScrollView and fix/clean use cases.
Some improvements:
- No more twitches while scrolling. (There is only one special case in chat and reason is not in scrolling)
- No need to decorate ListView with ScrollView,, StatusListView already has ScrollBar
- No need to manually hide/show scrollbars if content is smaller/bigger than container
- New ScrollBars that fit theme

### Affected areas

Desktop

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/2522130/179478525-b2c174be-8c39-4a4b-b5b4-1714b63cac78.mov

### CODE REVIEW

**Review by alexandraB99 — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Comment by glitchminer** [comment]
### **Issues found**

**Settings**:
RESOLVED: Not possible to scroll. Noted on: Messaging; Appearance; Notifications; Advanced; About

**Welcome bar (public chats):**
RESOLVED: Not possible to use scroll wheel on mouse but can click and drag scrollbar.
RESOLVED: Some horizontal movement

**Back up seed phrase dialog**
RESOLVED: text and elements are out of alignment
RESOLVED: It is not possible to scroll using scroll wheel but the scroll bar appears and can be dragged.
RESOLVED: It is possible to use the trackpad to scroll vertically only, meaning some elements are unreachable.

**Gif selector:**
RESOLVED: Text out of alignment

**Manage/Edit community page:**
OPEN: Alignment of elements have changed, some clipped on right hand side
image

**Wallet**
OPEN: Master has activity tab / build under test has history
OPEN: Alignment of send dialog elements has changed (see advanced and custom tabs as well)
image
OPEN: Alignment of receive dialog for you address has changed
image

Build: StatusIm-Desktop-220719-173632-9488c5-pr6456
OS: Mac

**Comment by MishkaRogachev** [comment]
Screenshot 2022-07-20 at 14 51 45
Screenshot 2022-07-20 at 14 51 23

@Khushboo-dev-cpp can I kindly ask you to re-review, i've made separated commit with new changes: https://github.com/status-im/status-desktop/pull/6456/commits/1d7d6518a6d7fc87713f10ce43b28a95849f10c7

**Review by saledjenic — APPROVED** [review]

**Review by Khushboo-dev-cpp — CHANGES_REQUESTED** [review]
I see some issues in the sendModal

https://user-images.githubusercontent.com/60327365/180029379-37632328-e21f-41be-88b0-43a5b2b27da7.mov

**Comment by MishkaRogachev** [comment]
> I see some issues in the sendModal
> 
>  Screen.Recording.2022-07-20.at.6.01.53.PM.mov

Thanks for testing, i'll fix that

**Comment by MishkaRogachev** [comment]
> I see some issues in the sendModal
> 
>  Screen.Recording.2022-07-20.at.6.01.53.PM.mov

Fixed, the reason was in explicit sizes. But i noticed that scrolling does not work over StatusTabBar and StatusListItem, and same in the master branch

https://user-images.githubusercontent.com/2522130/180200966-13d5f49c-03cd-4742-93e9-fb1a72564541.mov

I'd prefer to open new issue for that

**Comment by glitchminer** [comment]
Issues in previous build resolved: https://github.com/status-im/status-desktop/pull/6456#issuecomment-1190452232

Alignment issues on send dialog also resolved.

**Review by glitchminer — APPROVED** [review]
Tested and passed.

**Review by Khushboo-dev-cpp — APPROVED** [review]
rechecked wallet parts and it looks okay now.

**Pull request merged**
