### PR TITLE
Truncate long 3 words name

### LINKED ISSUE #1830: Enable ellipsis on long names in chat detail
This is an edge case for random name but there are still Nicknames where user can set long names, better to have it covered. 

### Current
Screen_Shot_2021-02-11_at_14_58_06

Screen_Shot_2021-02-11_at_15_04_12

### PR DESCRIPTION
**Pull request by ace-smart**
Fixes #1830

### CODE REVIEW

**Review by jrainville — CHANGES_REQUESTED** [review]
No need to create a custom `trancate` function. QML already has support for it with `elide` https://doc.qt.io/qt-5/qml-qtquick-text.html#elide-prop

You can use `elide: Text.ElideRight` and it will elide at the wanted size.
To make sure it works correctly, you just need to set a `width` or a left and right anchor

**Comment by ace-smart** [comment]
I am not sure why contact name is using `StyledTextEdit` based on `TextEdit`.
Actually, `TextEdit` doesn't support `elide` property.
May I update it to normal `StyledText` ?

**Comment by jrainville** [comment]
> I am not sure why ProfilePopup's contact name is using StyledTextEdit based on TextEdit.

I assume it's because we wanted to support selecting and copying that text, but I think it's better to have it elide correctly, so yes you can change it to StyledText

**Comment by ace-smart** [comment]
Ok, I see.
And then, there is another problem in message context menu. `Elide` and `wordWrap` attribute couldn't exist together.
In this case, it seems to use the custom function to truncate name.
image

**Comment by jrainville** [comment]
Ah, that's an interesting case. Maybe instead of `Text.WordWrap`, we could try `Text.Wrap`. It would truncate the word in the middle if it is too long

**Comment by ace-smart** [comment]
Done. Please review and merge this PR. :)

**Review by jrainville — APPROVED** [review]

**Pull request merged**
