### PR TITLE
fix: create community and channel name validation

### LINKED ISSUE #2050: Follow the same name limitation principles in community channels as on public chats
Screen_Shot_2021-03-16_at_14_38_31

Public chat formation example:
Screen Shot 2021-03-16 at 14 38 36

### PR DESCRIPTION
**Pull request by emizzle**
Fixes #2050.

This PR contains changes to fix the name validation for new communities and new channels in communities. In the process of updating this, better validation was also added to both popups (create community and create channel), including the prevention of the "Create" button from being enabled until all form fields were valid.

During this process, it was noticed that the community image cropper was not actually cropping the image *in the preview*. Once the community was created, status-go was successfully cropping the image as the user intended. However, the preview thumbnail prior to creation was not accurately showing the cropped image preview and showing the entire image centred instead. *This is still yet to be fixed.* One solution is to upgrade Qt to `5.15` to take advantage of Image QML's `sourceClipRect`.

~~This was quite a mind-bending task because there is a thumbnail image which is 128x128px, the original image, and a scaled version of the original image used in the ImageCropper component. Shrinking and moving the portion that is cropped should result in the thumbnail version being enlarged and moved to match. The enlargement should be an inverse proportion of the image cropper rectangle to image size, and the x/y movements should be the inverse of the x/y movement of the image cropper rectangle, also in the same proportion.~~

~~I got *very very* close to getting this work, but i'm the point where need to get some help (maybe @jrainville? @PascalPrecht?), or we upgrade to Qt 5.15 to take advantage of Image QML's `sourceClipRect` which is exactly we need. An alternative solution is to just leave it as it was because it wasn't working in the first place.~~

~~Please try not to get angry at the very dirty state it's in! It needs a massive cleanup!~~

~~Any help here would be greatly appreciated!~~

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
this didn't work for me, see video


https://user-images.githubusercontent.com/176720/114603351-9f1c6400-9c65-11eb-83c2-076ec9398144.mov

**Comment by emizzle** [comment]
@iurimatias the validation had been added for the community name, not the channel name. I have now added it to the channel name *as well*. Do we know if the community name is meant to have this validation? Maybe @simonricoo can guide me here? If not, I can revert that change.

**Comment by anastasiyaig** [comment]
@emizzle please merge to master

**Comment by emizzle** [comment]
> @emizzle please merge to master

Done.

**Pull request merged**
