### PR TITLE
fix(@desktop/onboarding): it's impossible to delete a profile image on the onboarding page

### LINKED ISSUE #5240: It's impossible to delete a profile image on the onboarding page
# Bug Report

## Description

It's impossible to delete a profile image on the onboarding page

## Steps to reproduce

1. Launch the app
2. Hit "I'm new to Status" - "Generate new keys"
3. Hit "+" and upload a photo for the profile image
4. Try to delete the profile picture

#### Expected behavior
It's possible to delete the profile picture
image

#### Actual behavior
There is no button for deleting the profile picture
image

### Additional Information

- Status desktop version: commit dcab50fe0944f65a1fafef3fdb9e7abe66277b6c
- Operating System: MacOS Big Sur 11.6.5 (20G526)

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #5240

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Changes LGTM but all of CI is failing

**Review by jrainville — APPROVED** [review]

**Comment by saledjenic** [comment]
> Changes LGTM but all of CI is failing

@PascalPrecht yes I see, not sure why, it will be fixed when it gets fixed in the `master` cause CI for the `master` branch failed as well.

**Comment by elina2015** [comment]
@saledjenic hey, could you kindly help with the build for testing?

**Review by stefandunca — APPROVED** [review]
It looks good for the intended functionality. However, providing a link to the design document will help to trace the reasoning behind the work.

**Review by borismelnik — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]

**Review by elina2015 — COMMENTED** [review]
@saledjenic hey, the button for deleting the uploaded picture is still not shown.
Also, if I click on the 'x' icon for closing the dialogue after uploading the profile image, and finish the onboarding, the uploaded image is shown (but it shouldn't). Could you check it?

**Review by elina2015 — APPROVED** [review]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9103&group_by=tests:status_id&group_order=asc

**Pull request merged**
