### PR TITLE
fix: Add close button to seed backup warning

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2248.

Add a close button to the seed backup warning banner in the wallet. The banner will reappear upon application restart as long as the seed hasn’t already been backed up (`profileModel.mnemonic.isBackedUp`).

A new .svg with a white outline needed to be added as well because the original “close.svg” had a purple outline, which would show up when the ColorOverlay applied to the close button had an opacity less than 1.0.

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@simonricoo can you please assist with the icon needed?

**Comment by simonricoo** [comment]
[Close - Circle.svg.zip](https://github.com/status-im/status-desktop/files/6348976/Close.-.Circle.svg.zip)
or here https://www.figma.com/file/Iz6vZHRiA1j08VbUZi7ySa/%F0%9F%92%B0-Wallet%E2%8E%9CDesktop?node-id=2339%3A11309

**Review by jrainville — APPROVED** [review]
Nice animation!

**Comment by anastasiyaig** [comment]
https://images.zenhubusercontent.com/261270348/1226f966-7684-4f52-8731-686b7826e0f4/______________2021_04_21___17_31_48.mov

Looks amazing, please merge it

**Pull request merged**
