### PR TITLE
refactor(section_details): simplify section_details to only contain needed props

### PR DESCRIPTION
**Pull request by jrainville**
I merged https://github.com/status-im/status-desktop/pull/12069 too soon. Just reopening it so it can be QA tested

For testers, check that the sections work fine.
From the code, the parts that use that section_details object are: the gifs, the permissions, the section changes and the message context menu.

### CODE REVIEW

**Comment by jrainville** [comment]
@igor-sirotin @MishkaRogachev can you give the thumbs up again. It's the same changes, just a new PR because I messed up.

@anastasiyaig can you get a QA to check this one out. There was no issue for it, because I did this in the context of cleaning up when looking for the crashes.

**Review by MishkaRogachev — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@glitchminer can u please check it out?

**Comment by glitchminer** [comment]
Hey @jrainville ,

A few of these are definitely known issues, but here's a few things noted if you want to take a look

---
1. “Loading chats” spinning indefinitely until you navigate away from community and back again
image

---
2. Pending members contains an existing member
Have seen this where it's waiting on owner node, even though it is the control node, and also where accept button is present.

https://github.com/status-im/status-desktop/assets/50769329/013d1218-7a99-4d61-a4bf-0e098c615a01

---
3. Banning a user gives that user a blank screen (could not reproduce after it first happened)
image

---
known: https://github.com/status-im/status-desktop/issues/12125
4. Crash on pinning a message
5. Crash on clicking on community link (also related to pinning a msg)

**Comment by jrainville** [comment]
@glitchminer I tried reproducing 1 and 3. I wasn't able to sadly.

I think I've seen 1 before, so maybe it's not related to this PR.

Both issues seem very rare. We'd probably need logs next time they happen.

The other issues are known like you linked.

I think I'd be ok merging this if you agree.

**Review by glitchminer — APPROVED** [review]
@jrainville, that's fine, thanks for checking. Hopefully can get the logs if we see them again.

**Pull request merged**
