### PR TITLE
feat: Version Updating

### LINKED ISSUE #1290: Version Updating (Temporary solution)
Based on the conversation from the last week I made this proposal for the version updating @jrainville @michaelsbradleyjr @iurimatias @hesterbruikman 

Something we haven't discussed is that we need to show a "Make sure you have your account password and seed phrase stored." before downloading as it may cause loosing funds and the account access. On MacOS it works fine  when you hit "Replace" when you are dropping the new dmg into the application folder (It remembers the seed credentials on the start). But I assume users will also uninstall first so credentials are lost or just it works differently on Linux / Windows or some error occurred during the installation or something else, thats why I would suggest to show this modal on all platforms.

Figma: https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1847%3A12524

Screenshot 2020-11-11 at 10 57 28

Screenshot 2020-11-11 at 11 01 15

Screenshot 2020-11-11 at 11 03 36

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #1290

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Do you want us to review yet? I see that this is more a placeholder for now since it doesn't seem to actually have the version fetch yet

**Comment by richard-ramos** [comment]
> Do you want us to review yet? 

Not yet!

**Comment by richard-ramos** [comment]
I guess it can be reviewed now. The only thing missing is the proper ens address

**Comment by iurimatias** [comment]
tested and it works but we need to review the ipfs page

**Pull request merged**
