### PR TITLE
feat(@desktop/communities): Add burning state logic

### PR DESCRIPTION
**Pull request by endulab**
Expose burningState in the model.
Update burningState when burning operation changes its status.

Issue #11076

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/61889657/fff2d108-f349-45ba-b509-fa050c6e82dc

### CODE REVIEW

**Review by noeliaSD — APPROVED** [review]
LGTM!! 
It looks nice! :)

**Review by micieslak — COMMENTED** [review]
Looks nice!

However, to have it visible in UI, small change needs to be done in `MintTokensSettingsPanel.qml`, line 521. `token.burnState: model.burnState` binding should be added.

It's needed after the recent refactor, now using non-existing roles would cause an error or warning.

**Comment by endulab** [comment]
> Looks nice!
> 
> However, to have it visible in UI, small change needs to be done in `MintTokensSettingsPanel.qml`, line 521. `token.burnState: model.burnState` binding should be added.
> 
> It's needed after the recent refactor, now using non-existing roles would cause an error or warning.

@micieslak I added missing binding

**Review by micieslak — APPROVED** [review]
lgtm!

**Comment by glitchminer** [comment]
Hi @endulab , please see notes below. 

---
1. OPEN Burning state does not persist after app restart
Restarting the app while the tx is pending and the burning spinner is present appears to clear the state. The burn icon and spinner do not load again after restart and the transaction is still pending.

---
2. OPEN  The burning state did not update after transaction updated to success
The burning icon and spinner persisted even after the transaction appears complete.

---
Note: Test was using goreli

**Comment by endulab** [comment]
@glitchminer I rebased the pr. Pending transactions are fixed.

**Review by glitchminer — APPROVED** [review]
Tested, approved.

Note this is impacted by https://github.com/status-im/status-desktop/issues/11139 where killing the app before the transaction is complete will result in an incorrect Total count and crash on next launch.

**Pull request merged**
