### PR TITLE
[Settings/Wallet] Fixed scroll bar position

### LINKED ISSUE #13365: Settings/Wallet/Manage tokens: Implement scroll bar positioning
# Bug Report

## Description

The scroll bar overlaps with the content, should be positioned outside, on the right border of the window as in designs.

Initially reported in: https://github.com/status-im/status-desktop/pull/13318#pullrequestreview-1853370526

image

Design for scrollbar behavior [here](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=3525-224510&mode=design&t=8rkDYBFqP0mierHI-0).

**Things to consider:**
With side-by-side preview, the scrollbar should stay in the same position (inside the setting page, not the preview area) when the side-by-side preview is visible. And the scroll should work if the cursor somewhere between delegates and scrollbar

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #13365

### What does the PR do
Settings/Wallet: Fixed scroll bar position

### Affected areas
Settings/Wallet

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/31625338/ce4172f1-e491-493f-87e8-a778fe4f5c2a

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM!

**Review by noeliaSD — COMMENTED** [review]
Could we do it differently to avoid reducing the delegate width?

Screenshot 2024-02-13 at 13 53 00

**Review by micieslak — COMMENTED** [review]
Changing the list view's width by scrollbar's width breaks the general width established many layers above: https://github.com/status-im/status-desktop/blob/0a0466a7a3a0f64edd4fddba67ed1cf17474e795/ui/app/AppLayouts/Profile/ProfileLayout.qml#L78

And this one is compliant with the design:

Screenshot from 2024-02-13 14-00-15

So the scrollbar should be moved right, without shrinking the list itself.

**Comment by alexandraB99** [comment]
@noeliaSD @micieslak with `clip: true` your suggestion doesn't work, proposals? can I remove `clip: true`?

**Comment by alexandraB99** [comment]
@micieslak @noeliaSD with `clip: true` your suggestions won't work

**Comment by micieslak** [comment]
> @micieslak @noeliaSD with `clip: true` your suggestion won't work

but I didn't suggest anything, just pointing design mismatch :upside_down_face:

**Comment by micieslak** [comment]
> @micieslak @noeliaSD with `clip: true` your suggestion won't work

Please play a bit with `ClippingWrapper`. This simple utility should help here :)

**Comment by alexandraB99** [comment]
not relevant after design definitions, description in [original issue](https://github.com/status-im/status-desktop/issues/13365) updated.

**Pull request closed without merging**
