### PR TITLE
feat(@desktop/wallet): Transactions values

### LINKED ISSUE #10792: Activity Details Values (fee + gas)
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12310-258079&t=KdYIzdn0ahxB48oq-4

### PR DESCRIPTION
**Pull request by Cuteivist**
closes #10792 

### What does the PR do

* Updated values section to new design.
* Extended storybook TransactionDetailsView logic
* Fixed transaction menu tx hash link

### Affected areas

* Wallet activity view

### Screenshot of functionality (including design for comparison)

Design:
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12310-258079&t=KdYIzdn0ahxB48oq-4

Sent:

sent

Bridge

bridge

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Comment by glitchminer** [comment]
Hey @Cuteivist , results of QA below.

1. OPEN Fees are not appearing in the total of transactions when receiving
image

**Comment by Cuteivist** [comment]
@glitchminer According to design
https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=12307-260481&t=346hjRhWiEYxI6Dd-4

Receive is has only `Total` field where total amount is displayed. Fees are not displayed.

**Comment by Cuteivist** [comment]
@glitchminer There are multiple types of transactions (Send, Receive, Swap, Bridge, Destroy, etc) so the first link is just an example  how it would look. 

The second link points to pages where are real life examples like Receive on Mainnet, Receive on Arb/Opti, Swap, Bridge, etc.

I always assumed that the first is just generic example and for specific use case I look at those pages I linked.
If you want I can get 100% confirmation from design on this.

**Comment by glitchminer** [comment]
Thanks @Cuteivist, when I think about it now it actually makes more sense the way it's currently implemented - we don't show the breakdown of fee when receiving anyway and also it would be amount - fee.

**Pull request merged**
