### PR TITLE
chore: script for creating local test fleet

### PR DESCRIPTION
**Pull request by richard-ramos**
Allows creating local test fleets with custom number of static nodes and mailserver nodes.
This has been only tested on linux

Requires
- https://github.com/status-im/status-go/pull/2821

Fixes: #7068

### CODE REVIEW

**Comment by alaibe** [comment]
If i understand correctly, this PR: https://github.com/status-im/status-desktop/pull/7001 will connect to the local bootnote being created here?

Also should this code not be on status-go? It is not desktop specific right?

**Comment by PascalPrecht** [comment]
As mentioned in the meeting, really cool stuff.
One thing I'd like to see if we get to configure names for fleets as well so that desktop can understand it and show them accordingly (instead of defaulting to for example `eth.prod`)

Other than that, I agree with @alaibe that this should probably live in status-go.

**Comment by richard-ramos** [comment]
The reason why I made it part of desktop is because the script modifies the fleets.json file read by desktop.

**Comment by richard-ramos** [comment]
This separate from #7001. In this PR we create a local fleet for use in your machine, and with software like Comcast affect the network conditions of the fleet so you can test different scenarios, and is not meant to be used in a CI environment (for now)

**Comment by PascalPrecht** [comment]
> The reason why I made it part of desktop is because the script modifies the fleets.json file read by desktop.

Actually this makes sense. I think it's fine then to keep it here.

**Review by alaibe — APPROVED** [review]

**Pull request merged**
