### PR TITLE
fix(StatusQ): Remove debug postfix

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-desktop/issues/10331

I removed `d` debug postfix for StatusQ binary.

Tested SanityChecker and Storybook on MacOS debug/release builds.
Also tested status-desktop binaries on MacOS and Windows.

### CODE REVIEW

**Comment by igor-sirotin** [comment]
@caybro @micieslak 
If you have linux, could you please check that status-desktop AppImage works fine?

**Review by caybro — APPROVED** [review]
LGTM

I'll test tomorrow :)

**Comment by caybro** [comment]
Tested, worked fine in both `storybook` and `sandbox`

**Review by noeliaSD — APPROVED** [review]
Same here! Tested and it works fine!

**Comment by caybro** [comment]
Oh, gonna test the produced AppImage too :)

**Review by micieslak — APPROVED** [review]
LGTM!

**Pull request merged**
