### PR TITLE
feat: edit communities

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2566.
Fixes: #2582.

Allow editing of Community name, description, image, colour, and access.

## Note
1. This PR relies on a [PR for status-go](https://github.com/status-im/status-go/pull/2229) that is currently not merged. It should be merged *first*, after which this PR can be updated with the new commit hash and then merged.
2. The PR for status-go is based on top of `develop` which may have some consequences for our use of `status-go`.

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Nice job!

**Comment by anastasiyaig** [comment]
@emizzle @iurimatias since we are planning to use only Requires Approval community type, i suggest to lock the option to change community type when editing community. Also , this opportunity is a potential source of issues we can avoid easily by locking it.

**Comment by vkjr** [comment]
+1 to @anastasiyaig 
same already done for mobile PR and editing community type removed from [status-go PR](https://github.com/status-im/status-go/pull/2229).

**Comment by anastasiyaig** [comment]
when updating the name and description of community and sharing it as a link, old name and description of community is shown:

1. create a community on desktop with some name on desktop , like 12345
2. make this community as Require Approval
3. change the name of the community, for example UPDATED
4. add any contact on mobile to your list of contacts
5. go to community -> profile -> share and copy link
6. paste the link to 1x1 chat with a contact on mobile device, but remove 1 c inside the url , for example
 https://join.status.im/**c**/0x0216739caca1a30f9ba984c7bff007a52f35ff060719f7300a1804109a2784b144 (otherwise u will run into https://github.com/status-im/status-desktop/issues/2501)
7. check the invitation preview on mobile

As a result, the invitation contains old (initial) data, not updated name / description



@vkjr is it something related to mobile maybe? not sure

**Comment by anastasiyaig** [comment]
@vkjr @emizzle 

so basically, when community is created and administrated on desktop and mobile device is added by tapping invitation (and approved) -> changing community data does not reflect on mobile. Could you please take a look? 
Please use community that requires approval, we dont need other ones

**Comment by vkjr** [comment]
@anastasiyaig, yes mobile has same issue, so it is something on `status-go` side I believe. I'll check.

**Comment by guylouis** [comment]
fixes #2582

**Comment by emizzle** [comment]
> @emizzle @iurimatias since we are planning to use only Requires Approval community type, i suggest to lock the option to change community type when editing community. Also , this opportunity is a potential source of issues we can avoid easily by locking it.

@anastasiyaig the membership requirement setting for communities has been locked to `Require Approval` in https://github.com/status-im/status-desktop/commit/0cd72cab6d3037e470c79814be95e9f2bca5c3a4. Note that this does not affect the value of the membership requirement for existing communities, even when they are being edited. @iurimatias @cammellos is this something that we should consider changing (updating the "membership requirement" value of existing communities)?

**Comment by cammellos** [comment]
@emizzle I'd say no, we can keep the backend as it is for now, just lock the UI to create that kind of communities only, and once things are a bit clearer we can drop the code from the backend.
Thanks

**Comment by anastasiyaig** [comment]
@emizzle i found that members list of community is throwing error and does not show members, it does not happen in nightly, could you please check?

1. create a community
2. manage community -> members

`DBG 2021-05-24 17:50:56+03:00 callPrivateRPC                             topics="rpc" tid=189388 file=core.nim:20 rpc_method=wakuext_contacts
qrc:/app/AppLayouts/Chat/CommunityComponents/CommunityProfilePopupMembersList.qml:77: ReferenceError: community is not defined`

**Comment by emizzle** [comment]
@anastasiyaig both issues reported above have been handled in this PR. Could you please retest?

**Comment by anastasiyaig** [comment]
thank you @emizzle , looks amazing!

**Pull request merged**
