### PR TITLE
fix: wakuv2 mailserver cycle

### PR DESCRIPTION
**Pull request by richard-ramos**
Requires
- https://github.com/status-im/status-go/pull/2926
Fixes: #7732

### CODE REVIEW

**Comment by richard-ramos** [comment]
Should fix #7732. Just keep in mind that data before October 6 is not guaranteed to be retrieved due to an issue existing with the history nodes back then

**Comment by richard-ramos** [comment]
@PascalPrecht would you mind checking if this PR also fixes https://github.com/status-im/status-desktop/issues/8021  
I managed to retrieve history from a community i joined following the steps from that issue

**Review by alaibe — APPROVED** [review]

**Comment by PascalPrecht** [comment]
@richard-ramos I tried, but I don't see this even trying to fetch history messages..

**Review by glitchminer — COMMENTED** [review]
On restoring account from seed phrase to a fresh instance (StatusIm-Desktop-221026-195428-8f599c-pr8059.dmg)

Todays date: Oct 28
On initial restoration of account, messages between dates are shown in General but are out of order: Oct 19 - Oct 28 

Top to bottom in chat
- Oct 28 (1 msg from 9:59UK )
- Oct 19
- Oct 20
- Oct 28 (rest of todays messages - 10:58UK - 11:10 )
- Oct 25
- Oct 26

Fetch more messages shows “Fetch more messages, Before Friday, Oct 28 2022”, which should already be loaded.

Clicking on Fetch Before Oct 28th returned messages from Oct 13 only (none between oct 13 - 19), but did not show a heading of Oct 13 so may not be full day.

Clicking on Fetch again “Before Oct 13” returned messages for rest of Oct 13 back to Oct 10th.

In all the fetch behaviour is improved from before when it did nothing but may need further investigation regarding reliability/consistency.

**Comment by PascalPrecht** [comment]
I think this can be closed. Desktop already depends on a newer status-go version

**Comment by jrainville** [comment]
Closing this as the status-go version was updated already in Master.
@glitchminer the issue you found seems to be related to the message ordering. That should be fixed by Patryk's work

**Pull request closed without merging**
