### PR TITLE
fix(JoinCommunityView): Enable activity centre and start chat button

### PR DESCRIPTION
**Pull request by alexjba**
### What does the PR do
Closing #9932 
Enable activity centre and start chat button functionality.

### Affected areas
Join Community View

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://user-images.githubusercontent.com/47811206/226602539-c0d5a5f7-5721-42a6-8702-8acf139c81f3.mov

### Cool Spaceship Picture

<!-- optional but cool ->

### CODE REVIEW

**Review by noeliaSD — CHANGES_REQUESTED** [review]
Not sure why but I see the `Start Chat` button blurred and disabled (I guess it needs some parameter to be set up in `JoinCommunityView`). 

Notifications are working fine!

See screenshot:
Screenshot 2023-03-21 at 13 31 17

**Comment by alexjba** [comment]
> Not sure why but I see the `Start Chat` button blurred and disabled (I guess it needs some parameter to be set up in `JoinCommunityView`).
> 
> Notifications are working fine!
> 
> See screenshot: Screenshot 2023-03-21 at 13 31 17

That was the first implementation, but changed it based on our discussions. Can you please check if it also happens after pulling latest code?

**Comment by noeliaSD** [comment]
> > Not sure why but I see the `Start Chat` button blurred and disabled (I guess it needs some parameter to be set up in `JoinCommunityView`).
> > Notifications are working fine!
> > See screenshot: Screenshot 2023-03-21 at 13 31 17
> 
> That was the first implementation, but changed it based on our discussions. Can you please check if it also happens after pulling latest code?

Ok, I see it correctly now after pulling your new changes! 

2 more comments:
1. The `Start Chat` button keeps its blue color after it is pressed the first time and the blue circle is not working the same way than in other views. Here a video for better understanding:

https://user-images.githubusercontent.com/97019400/226614620-cbf209dc-9339-4400-b493-1e3fea3ddb04.mov

2. This is more of a question... Does it make sense to switch to 1:1 view once the new chat is created?

**Comment by alexjba** [comment]
> 1. The `Start Chat` button keeps its blue color after it is pressed the first time and the blue circle is not working the same way than in other views. Here a video for better understanding:

Good catch! Fixed



> 2\. This is more a question... Does it make sense to switch to 1:1 view once the new chat is created?
Yes, at least to me! Looks like we're missing a handler on this action. And it's the same app wide.

**Comment by alexjba** [comment]
@John-44 @benjthayer Should we switch from `Community` view to the newly created chat when it is created from `Start chat` button? Currently if we're in `Community` view and the user creates a new chat, the view is not changed and there is no feedback.

Here is an example:

https://user-images.githubusercontent.com/47811206/226629390-02ea7ccd-fca7-4d67-8337-c1bcd14ecace.mov

**Review by noeliaSD — APPROVED** [review]
`Start Chat` button works fine now!! :) Thanks for the fixes!

Regarding the navigation to the 1:1 chat, since the issue is global, if you prefer, you can open a new task for it after knowing design team feedback!

**Comment by John-44** [comment]
> `Start Chat` button works fine now!! :) Thanks for the fixes!
> 
> Regarding the navigation to the 1:1 chat, since the issue is global, if you prefer, you can open a new task for it after knowing design team feedback!

@noeliaSD a task to fix the view not switching to the Messaging section is already open here https://github.com/status-im/status-desktop/issues/9880

**Review by alexandraB99 — APPROVED** [review]

**Review by caybro — APPROVED** [review]
Why is this not merged yet? ;)

**Pull request merged**
