### PR TITLE
fix(Windows): unbreak Windows build

### PR DESCRIPTION
**Pull request by caybro**
a feeble attempt to make M$ compiler grok otherwise valid C++17 code

### What does the PR do

Unbreaks Windows build

### CODE REVIEW

**Review by micieslak — APPROVED** [review]
LGTM, but it would be nice to force msvc to accept it somehow if possible :)

**Comment by caybro** [comment]
> LGTM, but it would be nice to force msvc to accept it somehow if possible :)

Yeah, feel free to experiment with the cmake options/switches... I failed :/ Maybe the MSVC compiler version is simply too old, dunno. What version are we using here @jakubgs ?

**Review by anastasiyaig — APPROVED** [review]

**Comment by jakubgs** [comment]
@caybro you can look those things up yourself in:
https://github.com/status-im/status-desktop/blob/master/scripts/windows_build_setup.ps1

**Comment by caybro** [comment]
> @caybro you can look those things up yourself in: https://github.com/status-im/status-desktop/blob/master/scripts/windows_build_setup.ps1

Thanks, seems to be "14.29.30133"

**Pull request merged**
