### PR TITLE
fix(@desktop/chat): after unblocking a user, messages are still not received until app is restarted

### LINKED ISSUE #5198: after unblocking a user, messages are still not received until app is restarted
# Bug Report

## Steps to reproduce

1. aadd a mutual contact request
2. after send messages to each other
3. block the user A
4. have user A send messages -> nothing is displayed as expected
5. unblock user A
6. have user A send messages

#### Expected behavior

new messages from user A since the unblocking should be displayed

#### Actual behavior

new messages are not displayed

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/2612

Fixes #5198

### CODE REVIEW

**Comment by abhi-status** [comment]
Not tested for blocked contacts in group chats.
Dependant on -> https://github.com/status-im/status-desktop/issues/5199

**Review by abhi-status — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]

**Comment by elina2015** [comment]
@abhi-status Could you kindly add a link to the test run for this PR?

**Comment by abhi-status** [comment]
I have generated one, as I had not done one before. https://ethstatus.testrail.net/index.php?/runs/view/8958&group_by=cases:section_id&group_order=asc

**Comment by saledjenic** [comment]
Closing this cause temporary solution is in (until we have appropriately introduced flags on the `status-go` side):
- https://github.com/status-im/status-desktop/pull/5457

**Pull request closed without merging**
