### PR TITLE
fix(chat): only add active chats (fixes chats reappearing after leaving)

### LINKED ISSUE #4903: A left channel re-appears if new messages are received
# Bug Report

## Steps to reproduce

1. right click on a channel and leave it
2. on another device send a message to that channel

#### Expected behavior

that message does not re-appear

#### Actual behavior

The channel re-appears in the chat list

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4903

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]
Nice!

**Review by borismelnik — APPROVED** [review]

**Comment by abhi-status** [comment]
@jrainville  The chat does not appear any more. 

But whenever the user is mentioned in a public chat (after having left it), I can hear the OS notification ping in the background.

**Comment by jrainville** [comment]
Good find @abhi-status . It is fixed now

**Review by abhi-status — APPROVED** [review]

**Comment by abhi-status** [comment]
Cheers @jrainville!
this is good to go !

**Pull request merged**
