### PR TITLE
feat(@desktop/wallet): Implement loading state for Send/Bridge Modal

### LINKED ISSUE #9107: Implement loading state for Send/Bridge Modal
### Acceptance Criteria

Design: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=9592%3A126633&t=AoPiPCjz9jJLUYZE-4
Implement design as per design for the send modal, each time values are being calculated it should be viewed as per design

[comment]: # (Rules for the future PR to be accepted.)

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #9107 
#9348 

### What does the PR do

Implements loading state for Send and. Bridge Modal, however there is a bug on the bridge modal that the routes are not loaded.  Bug raised https://github.com/status-im/status-desktop/issues/9348

### Affected areas

Wallet 

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://user-images.githubusercontent.com/60327365/215406859-d3a67d42-5991-4667-8dd0-0bc60f4f0d43.mov

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Review by stefandunca — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@alaibe @Khushboo-dev-cpp hey guys, i am constantly receiving `no route found` for bridging, is this PR fixing the bridge bug too? Or the issue will be fixed later? Thank you!

**Comment by anastasiyaig** [comment]
oh ya, i can see that i was working indeed, on the video attached, i thought it is not working because of my local issues though, thank you for checking on that @Khushboo-dev-cpp 🙌

**Comment by Khushboo-dev-cpp** [comment]
> oh ya, i can see that i was working indeed, on the video attached, i thought it is not working because of my local issues though, thank you for checking on that @Khushboo-dev-cpp 🙌

I checked for me send is also not working via a bridge :(

**Comment by Khushboo-dev-cpp** [comment]
@anastasiyaig I wasnt use my own key before and hence wasnt able to do it :(

Anyway it works for me, see video below 


https://user-images.githubusercontent.com/60327365/217298484-6b23d667-aecd-4774-b762-8e05d9abbea8.mov

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp thank you very much for trying again!

1. bridging through Send modal is working today 
2. bridging with Bridge modal - does not (tried for both Opt and Arb).

```
ERR 2023-02-08 10:08:40.993+03:00 rpc response error                         topics="rpc" tid=9467557 file=core.nim:36 err="\nstatus-go error [methodName:wallet_createMultiTransaction, code:-32000, message:not available for chainID ]\n"
```


https://user-images.githubusercontent.com/82375995/217459534-efddc284-31df-480f-8ac9-b28d1e63336d.mov

Should it be logged as separate ticket?

**Comment by anastasiyaig** [comment]
okay i logged it separately bcoz it is in master too https://github.com/status-im/status-desktop/issues/9483

**Review by anastasiyaig — APPROVED** [review]

**Comment by Khushboo-dev-cpp** [comment]
> okay i logged it separately bcoz it is in master too #9483

thanks for raising it @anastasiyaig :)

**Pull request merged**
