### PR TITLE
Fixed an issue that doesn't update one2one chatview name when unassign nickname from the contact

### LINKED ISSUE #1840: Doesn't update one2one chat view name when removed nickname from the profile view.
Doesn't update one2one chat view name when removed nickname from the profile view.
image

Please assign to me to fix

### PR DESCRIPTION
**Pull request by ace-smart**
Fixes #1840

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
I just tested your PR and removing the Nickname didn't update the topbar. Changing it to something else does work though

**Comment by ace-smart** [comment]
> I just tested your PR and removing the Nickname didn't update the topbar. Changing it to something else does work though

It is also strange. I repeated to test several times

**Comment by ace-smart** [comment]
https://user-images.githubusercontent.com/76216456/107817972-4aa55700-6d90-11eb-9dea-56d34ed17516.mp4

**Review by jrainville — APPROVED** [review]
My bad, I had checked out the wrong branch of yours. I tested again with the right branch and it's all good

**Pull request merged**
