### PR TITLE
fix(@desktop/profile): Fix slider controls in appearance settings

### LINKED ISSUE #5809: Slider controls in appearance settings overlap with labels
This seems to be new and most likely needs to be fixed in StatusQ.
The labels attached to the slider control conflict with the slider handle.

Screenshot from 2022-05-18 11-49-43

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #5809

### What does the PR do

Replaced StatusSlider with StatusLabeledSlider

### Affected areas

Profile

### Screenshot of functionality

image

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
This is a tiny fix. But maybe we need some generic slider with controls in StatusQ?

**Comment by PascalPrecht** [comment]
Not sure what you mean, we do have `StatusSlider`.

**Review by PascalPrecht — APPROVED** [review]

**Review by alexandraB99 — APPROVED** [review]

**Comment by MishkaRogachev** [comment]
> Not sure what you mean, we do have `StatusSlider`.

Slider with labels like on figma designs: https://github.com/status-im/status-desktop/issues/5809#issuecomment-1132959559

**Comment by anastasiyaig** [comment]
Moving back to `In progress` until the PR is finalised (we need to know wether implement new designs here or not)

**Comment by MishkaRogachev** [comment]
> Moving back to `In progress` until the PR is finalised (we need to know wether implement new designs here or not)

Ready

**Review by anastasiyaig — APPROVED** [review]

**Review by alexandraB99 — APPROVED** [review]

**Comment by alexandraB99** [comment]
please rebase

**Pull request merged**
