### PR TITLE
Fix link preview

### PR DESCRIPTION
**Pull request by Valentina1133**
### What does the PR do

Fix for link preview test, old link doesn't work again

CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2438/

### CODE REVIEW

**Comment by anastasiyaig** [comment]
do we know why it is happening?

**Review by anastasiyaig — APPROVED** [review]

**Comment by Valentina1133** [comment]
> do we know why it is happening?

No... We need to investigate, maybe it's a bug?

**Comment by anastasiyaig** [comment]
ya, for sure, we need to check out why profile links are not resolving after some time

**Comment by Valentina1133** [comment]
> ya, for sure, we need to check out why profile links are not resolving after some time

I will report it

**Review by antdanchenko — APPROVED** [review]

**Pull request merged**
