### PR TITLE
fix(StatusActivityCenterButton): fixed actvity icon position

### LINKED ISSUE #6350: Notification icon is shown far from the Activity Center icon
# Bug Report

## Steps to reproduce
1. Sign in and get a few notifications (mentions, added contact, was added to a group chat)
2. Check the Activity icon in the right top corner of any chat page

#### Expected behavior
image
Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=112%3A26519
#### Actual behavior
The icon with a number of notifications is shown far from the Activity Center icon
image

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/master/2275/
- Operating System: macOS Monterey, 12.3 Beta (21E5227a)

### PR DESCRIPTION
**Pull request by alexandraB99**
Depends on https://github.com/status-im/StatusQ/pull/780
Closes #6350

### What does the PR do
fixed actvity icon position

### Affected areas
Activity button

### Screenshot of functionality (including design for comparison)
act

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Review by caybro — APPROVED** [review]

**Comment by elina2015** [comment]
@alexandraB99 thank you for fixes! I have only one thing here - the icon and the notifications number are a little bit smaller than it's on the Design. Could you kindly check? 
image

**Comment by alexandraB99** [comment]
> @alexandraB99 thank you for fixes! I have only one thing here - the icon and the notifications number are a little bit smaller than it's on the Design. Could you kindly check?
> image

@elina2015 I did some minor updates, the sizes look correct
```
qml: ~~~~~~~~~~~~~ badge width:  20
qml: ~~~~~~~~~~~~~ badge height:  20
qml: ============= font.pixelSize:  12  
```
icon
g">

**Comment by alexandraB99** [comment]
@elina2015 all changes are in master, closing this PR as it doesn't make any sense. Please check master and let me know if you still see issues.

**Pull request closed without merging**
