### PR TITLE
fix: remove group labels for 'today' and 'yesterday'

### LINKED ISSUE #8377: Message gaps are not renewed without restart
### Description

When the app is not restarted , TODAY message gap is not renewed and shows all messages under Today, even they were sent yesterday. As result, when new messages are coming in - there will be 2 Today labels.

Screenshot 2022-11-22 at 12 35 48

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
Closes #8377

### CODE REVIEW

**Comment by caybro** [comment]
added @alexjba since he's working on this atm as well :)

**Review by alexjba — APPROVED** [review]

**Comment by anastasiyaig** [comment]
any additional testing is required here or it was checked by reviewing the code and can be merged? @alexjba @jrainville

**Comment by 0x-r4bbit** [comment]
@anastasiyaig I don't think any more testing is required here. In fact, testing this is a bit hard because you'll have to keep an instance running from one day to another.

This change really just removes the two labels, so I think this is gtg

**Comment by anastasiyaig** [comment]
Please, merge @0x-r4bbit :)

**Comment by 0x-r4bbit** [comment]
Restarting e2e task. Possible that there's changes in e2e tests needed.

**Pull request merged**
