### PR TITLE
feat(@desktop/onbiarding): Show Allow Notification page during first run

### PR DESCRIPTION
**Pull request by endulab**
Issue #5583

### What does the PR do

During the first run Allow Notification page is shown.
The page is only visible for Mac system.

Design: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1075%3A312335

Testing steps:
1. Remove Status directory (create a backup before)
2. Run application
3. The 1st page should be "Allow Notification" page

### Affected areas

Onboarding

### Screenshot of functionality

image

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]
@endulab you could use layouts (sooner or latter we will move to layouts everywhere).

**Review by iurimatias — CHANGES_REQUESTED** [review]
I don't see the image, is there anything I need to do? Here is the error in the console, the image is not found

`qrc:/app/AppLayouts/Onboarding/views/AllowNotificationsView.qml:27:5: QML Image: Cannot open: qrc:/imports/assets/png/onboarding/notifications.png`

Screen Shot 2022-05-25 at 5 57 17 PM

**Comment by endulab** [comment]
> I don't see the image, is there anything I need to do? Here is the error in the console, the image is not found
> 
> `qrc:/app/AppLayouts/Onboarding/views/AllowNotificationsView.qml:27:5: QML Image: Cannot open: qrc:/imports/assets/png/onboarding/notifications.png`
> 
> Screen Shot 2022-05-25 at 5 57 17 PM

I ran a package from CI and I see it, hmm, not sure what is going on:
image

**Comment by endulab** [comment]
@iurimatias please retest. I've made a small fix. Maybe it will help.

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
