### PR TITLE
fix(@desktop/chat): enable transactions over chat

### LINKED ISSUE #4610: [base_bc] can't request or send transaction in chat
### Description

Screenshot 2022-01-28 at 09 43 00

image

`qrc:/app/AppLayouts/Chat/popups/ChatCommandModal.qml:34:18: QML QQuickItem: Binding loop detected for property "height"`

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
fixes #4610

### Cool Spaceship Picture

<!-- optional but cool ->

### CODE REVIEW

**Comment by jrainville** [comment]
@Khushboo-dev-cpp do you think your PR fixes this issue as well? https://github.com/status-im/status-desktop/issues/4680

**Comment by Khushboo-dev-cpp** [comment]
Hey @jrainville ! the changes included in that commit will be a part of this commit

**Comment by jrainville** [comment]
Perfect. I'll link the issue with that PR then

**Comment by anastasiyaig** [comment]
@Khushboo-dev-cpp i noticed that signing phrase is empty when sending the transaction, can we fix it?

Screenshot 2022-02-10 at 16 57 34

**Comment by Khushboo-dev-cpp** [comment]
> @Khushboo-dev-cpp i noticed that signing phrase is empty when sending the transaction, can we fix it?
> 
> Screenshot 2022-02-10 at 16 57 34

Hey its done :)

**Comment by anastasiyaig** [comment]
would u mind to check why i cant receive STT in browser?

```
qrc:/imports/shared/popups/SignTransactionModal.qml:350:9: Unable to assign [undefined] to QObject*
qrc:/app/AppLayouts/Browser/views/WebProviderObj.qml:61: TypeError: Cannot assign to read-only property "sendTransaction"
```

maybe rebase will help or it is something broken here since master is okay

**Comment by Khushboo-dev-cpp** [comment]
> would u mind to check why i cant receive STT in browser?
> 
> ```
> qrc:/imports/shared/popups/SignTransactionModal.qml:350:9: Unable to assign [undefined] to QObject*
> qrc:/app/AppLayouts/Browser/views/WebProviderObj.qml:61: TypeError: Cannot assign to read-only property "sendTransaction"
> ```
> 
> maybe rebase will help or it is something broken here since master is okay

Hey fixed it now. thanks for funding it :)

https://user-images.githubusercontent.com/60327365/153572168-bd033ff9-ad77-4e85-ace9-e8f7cb2ce51a.mov

**Review by anastasiyaig — APPROVED** [review]

**Review by noeliaSD — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Nice work

**Pull request merged**
