### PR TITLE
fix: use correct ticker for all peers ping

### PR DESCRIPTION
**Pull request by iurimatias**
### Description

PR to trigger build to test https://github.com/status-im/status-go/pull/5798

### CODE REVIEW

**Comment by anastasiyaig** [comment]
status go cant be built

```
17:07:59  + make status-go
17:07:59  [92mBuilding:[39m status-go
17:07:59  ln: /Users/jenkins/workspace/s_macos_aarch64_package_PR-16268/vendor/status-go//.git/hooks: Not a directory
17:07:59  go: inconsistent vendoring in /Users/jenkins/workspace/s_macos_aarch64_package_PR-16268/vendor/status-go:
17:07:59  	github.com/waku-org/go-waku@v0.8.1-0.20240904134226-49eb64a27dc4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
17:07:59  	github.com/waku-org/go-waku@v0.8.1-0.20240808103513-b96582a30bc5: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
17:07:59  
17:07:59  	To ignore the vendor directory, use -mod=readonly or -mod=mod.
17:07:59  	To sync the vendor directory, run:
17:07:59  		go mod vendor
17:07:59  make[1]: *** [statusgo-shared-library] Error 1
17:07:59  make: *** [vendor/status-go/build/bin/libstatus.dylib] Error 2
```
@iurimatias

**Comment by iurimatias** [comment]
@anastasiyaig yeah I need to update, will do shortly

**Comment by chaitanyaprem** [comment]
> status go cant be built
> 
> ```
> 17:07:59  + make status-go
> 17:07:59  �[92mBuilding:�[39m status-go
> 17:07:59  ln: /Users/jenkins/workspace/s_macos_aarch64_package_PR-16268/vendor/status-go//.git/hooks: Not a directory
> 17:07:59  go: inconsistent vendoring in /Users/jenkins/workspace/s_macos_aarch64_package_PR-16268/vendor/status-go:
> 17:07:59  	github.com/waku-org/go-waku@v0.8.1-0.20240904134226-49eb64a27dc4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
> 17:07:59  	github.com/waku-org/go-waku@v0.8.1-0.20240808103513-b96582a30bc5: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
> 17:07:59  
> 17:07:59  	To ignore the vendor directory, use -mod=readonly or -mod=mod.
> 17:07:59  	To sync the vendor directory, run:
> 17:07:59  		go mod vendor
> 17:07:59  make[1]: *** [statusgo-shared-library] Error 1
> 17:07:59  make: *** [vendor/status-go/build/bin/libstatus.dylib] Error 2
> ```
> 
> @iurimatias

i have pushed updates to status-go PR. can you take in the new version?
https://github.com/status-im/status-go/commit/b2886effbe7bd38f4c9097e7b208353ee251d3cd

**Comment by iurimatias** [comment]
@anastasiyaig now it's updated

**Comment by anastasiyaig** [comment]
it works to me, no reconnections within 30 minutes, peers count is around 19-28 , stable

**Review by anastasiyaig — APPROVED** [review]

**Review by virginiabalducci — APPROVED** [review]
Looks good to me, peer count has been increasing until reaching 21-23 and remaining stable during the 30 minutes of testing

**Comment by jrainville** [comment]
I'm currently running this build as my main account to check if maybe this issue was related to the memory issue discussed here: https://github.com/status-im/status-desktop/issues/16214

I've been running the build for almost an hour and the memory used is around 1.9GB, which is standard.

I have seen spikes where it went up to 4GB, but it went back down.

I'll keep monitoring, but this is promising. It would make sense that the memory problem was related, because each time peers are reset, we do a new store node fetch, and considering we have a hundred channels, that's a lot of data being received and parsed.

**Comment by jrainville** [comment]
It's now been running for about 4 hours and the memory is stable around 3.4GB. It's still pretty high, but it used to be "stable" around 5GB before.
It has spiked once when I came back from lunch, but that's because the laptop went to sleep.
Before, it could get up to 7GB and more

I would then recommmend to **ship it**!!!

**Pull request merged**
