### PR TITLE
fix(CreatePassword): evaluation added on text changed

### LINKED ISSUE #5734: "Password must be at least 10 characters long" appears only after re-focus
https://user-images.githubusercontent.com/33099791/168293593-3365c0b3-7d2c-4482-801d-36b277b1915f.mp4

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #5734

### What does the PR do
Fixes password evaluation when text is changed

### Affected areas
Create password view

### Screenshot of functionality
https://user-images.githubusercontent.com/31625338/169550978-037907ef-da21-4127-a4f0-116d2e53fa7f.mov

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]

**Review by noeliaSD — COMMENTED** [review]
- Watching your video I can see that the strength progress bar is black and does not behaves as expected. I've tested the branch and it doesn't happen to me but, please, can you review it to ensure there is no errors there? Thanks!
- Just one use case: when the user removes all characters from the second input, the error message is not displayed. Please watch the video for a better understanding:

https://user-images.githubusercontent.com/97019400/169249987-e99397a8-157c-4468-8feb-1b1209cf68b2.mov

**Comment by alexandraB99** [comment]
> * Watching your video I can see that the strength progress bar is black and does not behaves as expected. I've tested the branch and it doesn't happen to me but, please, can you review it to ensure there are no errors there? Thanks!
> * Just one use case: when the user removes all characters from the second input, the error message is not displayed. Please watch the video for a better understanding:
> 
>  Screen.Recording.2022-05-19.at.10.31.19.mov

@noeliaSD it's black because I ran the single file with qmlscene so it missed colors I guess...all is good when running the desktop app.

As about showing the message when the text edit is empty, the bug report was only about when typing some text, is this also a requirement that it appears when the text field is empty?

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9238

**Review by elina2015 — APPROVED** [review]

**Comment by noeliaSD** [comment]
> > * Watching your video I can see that the strength progress bar is black and does not behaves as expected. I've tested the branch and it doesn't happen to me but, please, can you review it to ensure there are no errors there? Thanks!
> > * Just one use case: when the user removes all characters from the second input, the error message is not displayed. Please watch the video for a better understanding:
> > 
> > Screen.Recording.2022-05-19.at.10.31.19.mov
> 
> @noeliaSD it's black because I ran the single file with qmlscene so it missed colors I guess...all is good when running the desktop app.
> 
> As about showing the message when the text edit is empty, the bug report was only about when typing some text, is this also a requirement that it appears when the text field is empty?

The requirement for this message error is: "Once the input 2 is focused, trigger the validation". Let me share the [figma](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1965%3A219867).

**Comment by alexandraB99** [comment]
> > > * Watching your video I can see that the strength progress bar is black and does not behaves as expected. I've tested the branch and it doesn't happen to me but, please, can you review it to ensure there are no errors there? Thanks!
> > > * Just one use case: when the user removes all characters from the second input, the error message is not displayed. Please watch the video for a better understanding:
> > > 
> > > Screen.Recording.2022-05-19.at.10.31.19.mov
> > 
> > 
> > @noeliaSD it's black because I ran the single file with qmlscene so it missed colors I guess...all is good when running the desktop app.
> > As about showing the message when the text edit is empty, the bug report was only about when typing some text, is this also a requirement that it appears when the text field is empty?
> 
> The requirement for this message error is: "Once the input 2 is focused, trigger the validation". Let me share the [figma](https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1965%3A219867).

thanks @noeliaSD please check once more!

**Review by noeliaSD — APPROVED** [review]
Perfect!! :)

**Comment by anastasiyaig** [comment]
@alexandraB99 please take a look

**Comment by alexandraB99** [comment]
@anastasiyaig @Hbouaz I could have a look, however the ticket assigned to this PR is clearly a different thing and fixed ""Password must be at least 10 characters long" appears only after re-focus", so either create a new ticket so that we don't keep this PR so many days open since it's fixed, or update the description of the existing one. Please let me know!

**Comment by Hbouaz** [comment]
@alexandraB99, happy to do that, the PR is now labelled as tested and the other issue will be raised in its own issue https://github.com/status-im/status-desktop/issues/5822

**Pull request merged**
