### PR TITLE
feat(desktop/chat): Updated create new chat/group flow

### LINKED ISSUE #4781: new direct chat / group chat functionality
### Description

as per design https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop-(rolled-back-version-to-recover-a-screen%2C-ignore)?node-id=112%3A26519

should use the `StatusTagSelector` component from statusQ https://github.com/status-im/StatusQ/pull/537
to be done after new `startGroupChat `API introduced by https://github.com/status-im/status-desktop/issues/4735
should use status-go PR https://github.com/status-im/status-go/pull/2531

Screen Shot 2022-02-10 at 5 30 54 PM

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #4781

### What does the PR do
Updated create new chat flow based as per new designs in Figma.

### Affected areas
chat section

### Screenshot of functionality

https://user-images.githubusercontent.com/31625338/154775475-a8407728-7a69-4a31-966d-7f4426fbeb3e.mov
https://user-images.githubusercontent.com/31625338/154775480-2c58cf27-0b55-4055-9639-79306760cc34.mov

### CODE REVIEW

**Comment by alexandraB99** [comment]
*notes

1. I didn't implement the new chat content menus functionality, as I see it as a different task
2. Groups seem to have some issues on updating the info when creating it or adding/removing members. Need to check whether this is a general bug.

**Review by richard-ramos — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
the megaphone icon does not do anything, it should open what is the current `+` menu but excluding group chats and 1 on 1 chats

PR needs to be rebased and point to latest https://github.com/status-im/status-go/pull/2525

**Comment by alexandraB99** [comment]
> the megaphone icon does not do anything, it should open what is the current `+` menu but excluding group chats and 1 on 1 chats
> 
> PR needs to be rebased and point to latest [status-im/status-go#2525](https://github.com/status-im/status-go/pull/2525)


I don't see anything related to the megaphone [here](https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba⎜Desktop-(rolled-back-version-to-recover-a-screen%2C-ignore)), am I missing something? Will rebase tomorrow.

**Comment by alexandraB99** [comment]
Rebased

**Review by iurimatias — APPROVED** [review]
tested

**Comment by abhi-status** [comment]
Hi @alexandraB99 
I think this might have introduced a new [issue](https://drive.google.com/file/d/11X7G2szvfZE2-FlagH4R0h8ZexS4UjvX/view?usp=drivesdk)
Basically, clicking on a newly-added contact (from the Contacts screen), takes one to an incorrect chat window.

**Comment by iurimatias** [comment]
> Hi @alexandraB99 I think this might have introduced a new issue where, clicking on a newly-added contact (from the Contacts screen), takes one to an incorrect chat window. This issue is only rectified once the user starts a chat with this new contact via the new chat flow.
> 
>  2022-03-03_12-50-42.mp4

I can confirm the issue Abhi reported, it's not that it takes the wrong chat but rather does not open one, this the error

```
qrc:/app/AppLayouts/Profile/stores/ContactsStore.qml:27: Error: Insufficient arguments
```

**Review by iurimatias — CHANGES_REQUESTED** [review]
requesting changes due to issue above

**Comment by alexandraB99** [comment]
@iurimatias , @abhi-status rebased and updated. Issue should be fixed now, please check again!

**Comment by abhi-status** [comment]
**Use case :** When there are lots of contacts on the Chat panel (left of chat window), it could get difficult to find a contact. 
In this situation, if the user uses the new chatflow to find the required contact, the entered chat text does not appear in the 1 to 1 chat window.

https://user-images.githubusercontent.com/95302135/156755688-ef515079-d65d-4b69-8b25-f6537ee978c2.mp4

**Comment by abhi-status** [comment]
As a follow up to the above comment, the missing text appears in the chat group that the user creates next

https://user-images.githubusercontent.com/95302135/156757358-f7706aff-79cf-4e36-bbe0-1414f06615c6.mp4

.

**Comment by alexandraB99** [comment]
> As a follow up to the above comment, the missing text appears in the chat group that the user creates next
> 
>  2022-03-04_11-41-24.mp4 
> 
> .

@abhi-status pushed an update, please check again!

**Review by iurimatias — CHANGES_REQUESTED** [review]
can't join a public channel currently

https://user-images.githubusercontent.com/176720/156856576-4914f234-3118-4e25-8c94-bee2c8a9e726.mov

**Comment by abhi-status** [comment]
**Group Chats** - I can confirm the Group chat issue is now resolved. 

**Public Chats** - The public chat modal does not close and the user is not taken to the selected public chat after selecting one from the list. 
_expected_ : I think it'd be good to close this modal and take the user to the selected Public chat window.

https://user-images.githubusercontent.com/95302135/157085831-eda65bb1-c647-4d71-b4c9-88ae1be4842c.mp4

**Review by abhi-status — APPROVED** [review]

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
