### PR TITLE
fix(@desktop/chat): no identicon/profile picture shown and wrong time stamp format in search results

### PR DESCRIPTION
**Pull request by saledjenic**
PR: `StatusQ` [here](https://github.com/status-im/StatusQ/pull/361)

Icons added for messages senders in the search result, also community and chat
icons are colorized now.

Fixes: #3259

### CODE REVIEW

**Comment by saledjenic** [comment]
@richard-ramos timestamps in the search result is left like that cause that should be handled properly on the side of `StatusQ`, discussed that with @PascalPrecht while we were working on the search result development, there is a comment [here](https://app.zenhub.com/workspaces/nim-status-client--nim-status-5ea70d29c12ee928df5ae848/issues/status-im/status-desktop/2934) about that.

The issue with no icon is fixed, also colors for communities and chats without image is taken in to account now.

In order to use an image (for senders who set an image) instead of an icon in the search result, we need to refactor some part. Actually I see that image for sender is stored in the profile model > contacts > contactList, we should move that part from the view to the backend logic and serve any interested party for that info from there.

**Review by pinebit — APPROVED** [review]

**Comment by saledjenic** [comment]
@PascalPrecht if you ask me, that should be done on the nim side definitely, but currently there is a component `DateGroup` in the project which is used to correctly display readable time based on provided timestamp value and I thought that you will develop something similar in the StatusQ and we will just use it here. But anyway, we can now discuss this and agreed on how to proceed?

**Review by alaibe — APPROVED** [review]

**Comment by PascalPrecht** [comment]
> but currently there is a component DateGroup in the project which is used to correctly display readable time based on provided timestamp value and I thought that you will develop something similar in the StatusQ and we will just use it here

@saledjenic okay, not sure from the top of my head what this is DateGroup thing is about.

Either way, from StatusQ's perspective you're just rendering a `StatusListItem` with a `titleAsideText`. It doesn't know what the text is about so whoever supplies that information should makes sure it's the value they'd like to be rendered:

```
StatusListItem {
  ...
  titleAsideText: someFormattedDateString
}
```

Now in our case, we're rendering this information inside the search results, which is a component in StatusQ. So it would indeed make sense to have some date formatting logic there, which then means the result model has to provide just the timestamp. Alternatively the value is already formatted correctly as soon as it arrives in QML.

I'm fine either way.

Would you mind opening an issue for that in StatusQ in case you decide to not supply already formatted data?

**Comment by PascalPrecht** [comment]
As further discussed offline with @saledjenic, we've concluded that, for now StatusQ will provide a hook in `StatusSearchPopup` so Status Desktop can leverage it to perform locale based timestamp formatting.

Here's a corresponding issue in StatusQ: https://github.com/status-im/StatusQ/issues/363

**Comment by saledjenic** [comment]
Messages' time in the search result is converted from a timestamp to human readable format. So that is also handled within this change as the ticket requested.

**Pull request merged**
