### PR TITLE
feat: add wallet token integration

### LINKED ISSUE #7390: Wallet: improve the number of requests so assets list is updated faster
### Description

**Scenario**: open wallet and disable any network. As result, the asset list is updated with visible delay

https://user-images.githubusercontent.com/82375995/190394939-e9953d1e-ccfa-483a-8dd8-ce1ce5e6f7e3.mov

### PR DESCRIPTION
**Pull request by alaibe**
status-go pr: https://github.com/status-im/status-go/pull/2949
fixes #7390
* Speed up token calculation
* Changing network is immediate
* Remove extra call that aren't necessary

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Delete all the code!!! :smiling_imp:

**Review by caybro — COMMENTED** [review]
Wow, what a cleanup day :)

**Review by stefandunca — APPROVED** [review]
Awesome work! It looks so simple now. Have to unlearn what I have previously learned :)

**Review by glitchminer — APPROVED** [review]
Tested, approved. Speed of changing network is improved.

**Pull request merged**
