### PR TITLE
desktop(DOtherSide): Set env var before creating gui app

### LINKED ISSUE #6930: The app UI doesn't load with many `RangeError: Maximum call stack size exceeded` errors in log
# Bug Report

This is pretty much it in the title.
The problem is somewhere around `StatusPopupMenu`.

The problem arises before loading the UI. So it doesn't matter if you put the "problem origin component" into the `Loader` and create it dynanically.
It seems that while loading the engine processes whole code tree and gets into some recursive loop at this step.

### PR DESCRIPTION
**Pull request by Cuteivist**
fixes #6930 

### What does the PR do

Fixes environment variables not being applied correctly on Windows during runtime.

### Affected areas

Whole application during runtime.

### CODE REVIEW

**Comment by Cuteivist** [comment]
Tested on Windows and Mac.

Waiting for @jrainville to test it on his Windows and also on Linux.

**Review by caybro — APPROVED** [review]
;)

**Comment by Cuteivist** [comment]
> ;)

;)

**Review by osmaczko — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Tested on Windows 10 and on Ubuntu 20 and both work!

**Review by jrainville — APPROVED** [review]
Tested on Windows 10 and on Ubuntu 20 and both work!

**Review by jrainville — APPROVED** [review]
Tested on Windows 10 and on Ubuntu 20 and both work!

**Review by jrainville — APPROVED** [review]
Tested on Windows 10 and on Ubuntu 20 and both work!

**Pull request merged**
