### PR TITLE
release 0.14: update status-go

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-desktop/issues/12126
Closes https://github.com/status-im/status-desktop/issues/12114

Brings:
- https://github.com/status-im/status-go/pull/4036
- https://github.com/status-im/status-go/pull/4038
- https://github.com/status-im/status-go/pull/4039

### CODE REVIEW

**Comment by anastasiyaig** [comment]
I tested that and it works fine to me, the initial problem was caused by my current network configuration (default one), seems a pretty random stuff

**Review by anastasiyaig — APPROVED** [review]

**Comment by igor-sirotin** [comment]
@anastasiyaig it seems that I accidentally re-requested review from you. The code didn't change 🙂

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@igor-sirotin having a PR approval from QA means the PR is tested and it is fine. We are doing that for quite a while, so there is nothing really wrong. U need to request someone else's approval from Dev team , so the rule to have 2 devs approvals before merge is not broken

**Comment by igor-sirotin** [comment]
@anastasiyaig sure. I just wanted to shortcut this, because the code was already reviewed in status-go PR and you tested it in desktop.
Though now it's not possible anyway, because we're not authorized to merge to release branches anymore 😄

**Comment by anastasiyaig** [comment]
i think we have different process, we merge to master and then cherry pick needed commits to release. So I guess u need to change the base branch and just merge @igor-sirotin

**Comment by igor-sirotin** [comment]
Can't go this way really, as it's just a status-go update. And desktop `release/*` branch points to `desktop/release/*` status-go branch. So the order of merges doesn't really matter here. And I really wanted to test things for release first. 

Though I agree it'd be better to merge to master first in general 🙂

**Comment by igor-sirotin** [comment]
@jrainville I udpated status-go to `0d0f96ddf0a1f2ffb77ea3c259f121761a83c060`, so that we take https://github.com/status-im/status-go/pull/4039 in this PR as well.

cc @MishkaRogachev

**Comment by igor-sirotin** [comment]
tests and builds didn't finish yet :(

image

**Pull request merged**
