### PR TITLE
chore(macos): add entitlements required for squish

### PR DESCRIPTION
**Pull request by igor-sirotin**
And CI parameter to override the default entitlements.

### CODE REVIEW

**Comment by jakubgs** [comment]
Are we sure we don't want to make these conditional on type of build? We probably shouldn't use those for releases.

**Comment by igor-sirotin** [comment]
@jakubgs sure, I'm planning to add it. That's why it's a draft for now, just tested that adding entitlements fixes the problem.
We definitely don't want these to be in release build.

**Comment by jakubgs** [comment]
Thanks man. Just checking =].

**Comment by anastasiyaig** [comment]
@igor-sirotin even this branch is not complaining about rebase, would u mind to rebase? we are using this macOS build for our tests (now locally) and the app is changing , would be nice to have fresher version

cc @StateOf-Vlado

**Comment by StateOf-Vlado** [comment]
Please verify that you have one empty line at the end of added files. We will get fewer issues in rebasing or merging branches then.

**Comment by jakubgs** [comment]
I took the liberty of making this parametrizeable: https://github.com/status-im/status-desktop/commit/7620a907

**Comment by igor-sirotin** [comment]
@jakubgs thanks for the change!
I'd approve it, but can't approve own PR 😄

**Review by jakubgs — APPROVED** [review]
But I can :D.

**Review by anastasiyaig — APPROVED** [review]

**Comment by jakubgs** [comment]
I'll squash it then.

**Comment by igor-sirotin** [comment]
@jakubgs I usually squash with github. 
I find it better to keep commits separated in PR for readability reasons. 
image

**Comment by jakubgs** [comment]
That's fair, though in this case my change subsumes yours, so I don't see any info being lost. But sure.

I prefer squashing manually because then the commit is signed by me, and not by github =].

**Pull request merged**
