### PR TITLE
feat: speedup/slowdown archives import based on window state

### PR DESCRIPTION
**Pull request by osmaczko**
### What does the PR do

closes: #10815 

- speedups/slowdowns archives import based on window state

status-go PR: https://github.com/status-im/status-go/pull/3568

### Affected areas

- importing archives

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/33099791/9ed94887-306b-4ef7-81af-d108193d69b2

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
This is very cool. Good job!

Does this do the delay of 5 minutes before starting the import? If not, we can open a new issue and do that then

**Review by jrainville — APPROVED** [review]
This is very cool. Good job!

Does this do the delay of 5 minutes before starting the import? If not, we can open a new issue and do that then

**Comment by osmaczko** [comment]
> This is very cool. Good job!
> 
> Does this do the delay of 5 minutes before starting the import? If not, we can open a new issue and do that then

I have it on my todo-list. I will create an issue and implement it as followup

**Comment by jrainville** [comment]
> I have it on my todo-list. I will create an issue and implement it as followup

Great thanks

**Comment by osmaczko** [comment]
> > I have it on my todo-list. I will create an issue and implement it as followup
> 
> Great thanks

https://github.com/status-im/status-desktop/issues/10937

**Review by 0x-r4bbit — APPROVED** [review]
One of the coolest changes that'll land in Desktop :D

**Pull request merged**
