### PR TITLE
chore: improvements of the sending route generated by the router process

### LINKED ISSUE #14636: [EPIC] Sending transaction - improvements
This issue depends on #14635 

Apart from the things stated below, sending logic should know, based on the route, which transactions should be placed in parallel (immediately) and which of them should wait for execution of previously placed transaction/s.

- [x] https://github.com/status-im/status-go/issues/5140:
- [x] #16335 
- [ ] #16336
- [ ] #16337
- [ ] #16338

### LINKED ISSUE #16335: Unify the sending process after the best route is generated by the router
The Flow:
- a client requests from statusgo to build transactions for the best route that was displayed
- statusgo:
  -  builds all transactions and sends signal to the client asking for signing transactions or 
  - builds transactions one by one and sends to the client for signing, in the order which is determined by the router
- the client:
  -  signs transactions and calls statusgo to send built transactions providing signatures for all of them or
  - signs transactions one by one and calls statusgo to send built transaction providing signature for it 
- statusgo:
  - sends built transactions with received signatures
  - sends built transaction with received signature and waits for its execution before asking the client to sign next transaction
- once all transactions from the bundle are sent statusgo notifies client via signal that the multitransaction is sent

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/5807

This PR is the first step in the improvement planned for the desktop app. Next steps:
- move buying/releasing ens name and stickers to the same flow as sending transactions (statusgo part is already ready to support that) and that change will remove a big portion of code from the desktop app
- improve the notification mechanism in the desktop app (transaction sent, transaction confirmed/pending/failed)
- improve swap to sing the swap a single time only regardless of whether approval is needed or not (for this some more tuning will be needed on the statusgo side)

_Note_: minimal changes are done in the swap modal part on the qml side just to support new sending transaction flow, further improvements are necessary there

Closes #16335

Affected areas by this change are Send, Bridge and Swap modal, would be good to test the following:
- Send:
  - eth
  - erc20
  - erc721
  - erc1155
- Bridge:
  - eth -> eth
  - erc20 -> erc20
- Swap:
  - eth -> erc20
  - erc20 -> eth
  - erc20 -> erc20

### CODE REVIEW

**Comment by virginiabalducci** [comment]
Send:

Test user's geth.log [geth.log.zip](https://github.com/user-attachments/files/16998445/geth.log.zip)

- [ ] - eth OK
- [ ] - erc20 OK
- [ ] - erc721 OK
- [ ] - erc1155 OK

Swap:

- [ ] - eth -> erc20 OK

- [ ] erc20 -> eth -> I see an error message "Something went wrong. Change amount, token or try again later."
Screenshot 2024-09-13 at 4 03 01 PM

```
WRN 2024-09-13 16:00:22.612-03:00 qt warning                                 topics="qt" tid=31777056 text="qrc:/app/AppLayouts/Wallet/WalletUtils.qml:125: TypeError: Cannot call method 'split' of undefined \n             const chainIdsArray = chainIds.split(\":\")" file=:0 category=default
WRN 2024-09-13 16:00:22.612-03:00 qt warning                                 topics="qt" tid=31777056 text="qrc:/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml:71: TypeError: Cannot read property 'amount' of undefined \n                     expression: model.currencyBalance.amount" file=:0 category=default
```
[app_20240913_120139.log](https://github.com/user-attachments/files/16998392/app_20240913_120139.log)


- [ ] erc20 -> erc20

Screenshot 2024-09-13 at 4 06 43 PM

[app_20240913_120139.log](https://github.com/user-attachments/files/16998431/app_20240913_120139.log)

```
WRN 2024-09-13 16:06:22.956-03:00 qt warning                                 topics="qt" tid=31777056 text="qrc:/app/AppLayouts/Wallet/popups/swap/SwapModalAdaptor.qml:71: TypeError: Cannot read property 'amount' of undefined \n                     expression: model.currencyBalance.amount" file=:0 category=default
DBG 2024-09-13 16:06:32.992-03:00 NewBE_callPrivateRPC                       topics="rpc" tid=31777056 file=core.nim:27 rpc_method=wallet_getSuggestedRoutesAsync
```


In progress:

Bridge:
- [ ] eth -> eth
- [ ] erc20 -> erc20

**Comment by virginiabalducci** [comment]
testing this PR is blocked due to https://github.com/status-im/status-desktop/issues/16352 because I need to send some funds to bridge and get them to L2, to test the Bridge functionality in the desktop app, and to test swap on L2 networks.

**Review by alaibe — APPROVED** [review]

**Comment by saledjenic** [comment]
> testing this PR is blocked due to #16352 because I need to send some funds to bridge and get them to L2, to test the Bridge functionality in the desktop app, and to test swap on L2 networks.

@virginiabalducci I added a comment to the issue you logged, also rebased this PR on top of Dario's change for the disabled send button, could you try it out again?

**Comment by anastasiyaig** [comment]
@saledjenic i was able to do the remaining part of transactions (swap and bridge). it looks fine
cc @virginiabalducci

**Review by virginiabalducci — APPROVED** [review]

**Pull request merged**
