### PR TITLE
fix(dektop/profile) Back up seed was gone

### LINKED ISSUE #3433: Backup seed phrase indicator (blue dot) is gone when opening a profile
Nevertheless the fix is minor (looks to me like that) the indication for the seed phrase back up is really important to have, otherwise we don't remind a user in any other way that this should be done

1. install an app 
2. create account
3. notice that there is a blue dot at the left pane
4. click settings
5. notice that blue dot is gone and there is only counter at Backup seed phrase

https://user-images.githubusercontent.com/82375995/132529827-2dd9f8ce-ace1-4d81-9f16-e6e8080e9108.mov

image

https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/👤-Profile⎜Desktop?node-id=1432%3A6693

### PR DESCRIPTION
**Pull request by alexandraB99**
Brought back back up seed phrase indicator in profile
menu "Privacy and security"

Closes #3433

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Comment by anastasiyaig** [comment]
i dont see it @alexandraB99 

Screenshot 2021-09-09 at 16 13 04

**Comment by anastasiyaig** [comment]
@alexandraB99 please check the design -> there is a counter in a blue circle for the Privacy and Security option

image

**Comment by alexandraB99** [comment]
> @alexandraB99 please check the design -> there is a counter in a blue circle for the Privacy and Security option
> 
> image

done!

**Comment by anastasiyaig** [comment]
@iurimatias please cherry-pick to `0.3.0`

**Comment by iurimatias** [comment]
cherry-picked into `release/0.3.0`

**Pull request merged**
