### PR TITLE
fix(@desktop/general): the default profile picture and profile emojis are blurred on the Profile page

### LINKED ISSUE #5109: The default profile picture and profile emojis are blurred on the Profile page
# Bug Report

The default avatar and profile emojis are shown blurred on the Profile page

## Steps to reproduce
1. Sign in with the user without a profile picture
2. Go to Settings - Profile
3. Check the emojis under the default profile picture
4. Click on the pencil icon for editing profile picture
5. Check the appeared default profile picture

#### Expected behavior
The emojis and the profile picture are shown correctly and not blurred
#### Actual behavior
The emojis and the profile picture are shown incorrectly (they are blurred).
image
image

### Additional Information

- Status desktop version: commit 803cc77e9578be1d1f906a3fe10e742ff49af925
- Operating System: MacOS Monterey, v. 12.3 Beta (21E5227a)

### PR DESCRIPTION
**Pull request by saledjenic**
@elina2015 I think that emojis rendering in are slightly better now.

As of profile image... I checked what's happening and I could do literally nothing cause by default identicons are generated in size of 50x50 pixels and in that "change profile picture" popup we display them in size of 160x160 pixels, and that's the reason of poor quality in that view. For comparison if you check the same identicon on the login screen you will see that it is displayed far better, but that's because we display it there in 40x40 pixels.

To check that, just open any identicon and download that image from your browser, for example open this in your browser:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAjUlEQVR4nOzWwQmAMAxAURV30QEdwwF1Gr0Xi8mh8An/nUvhEwhZpiIMoTGExhAaQ2jKhKzRh+d9PZmPj22fR/7TKjMRQ2gMoTGExhAaQ2jCt1ZP9Bb6e5+9wVplJmIIjSE0qY3zpbdtstspu/1aZSZiCI0hGqTMRAyhMYTGEBpDaAyhMYTGEJo3AAD//4uOFSpUpwuKAAAAAElFTkSuQmCC`

Fixes #5109

### CODE REVIEW

**Comment by stefandunca** [comment]
@saledjenic I had a quick look over the rendering method and tried this experiment that seems to work and sharpen the images. I didn't look into whether the SVG indirect rendering can provide the same result without a workaround.

**Review by stefandunca — APPROVED** [review]

**Comment by elina2015** [comment]
@saledjenic thank you for the detailed information about the profile image! 
I'm just curious about could we try to find the way the profile image will look better? Maybe we can display it in the size 50x50 in the 'Change profile picture' popup or change the size of the default generated identicons?

**Review by elina2015 — APPROVED** [review]
The profile image is still blurred, but the icons look much better. So, I'll add the blurred profile image as a separate bug.

**Comment by saledjenic** [comment]
> @saledjenic thank you for the detailed information about the profile image! I'm just curious about could we try to find the way the profile image will look better? Maybe we can display it in the size 50x50 in the 'Change profile picture' popup or change the size of the default generated identicons?

@richard-ramos do you know is there a way to have identicons generated in a bigger size?

**Comment by saledjenic** [comment]
@elina2015 the only we can do now, is maybe to display the image in its native size (50x50) that way it won't be blurry, instead of scaling it to fill container as it's now.

**Comment by richard-ramos** [comment]
> @richard-ramos do you know is there a way to have identicons generated in a bigger size?

The magic happens here: https://github.com/status-im/status-go/blob/develop/protocol/identity/identicon/renderer.go#L41

If you want to generate a bigger image, probably `func drawRect(rgba *image.RGBA, i int, c color.Color)` needs to be modified as well. Just keep in mind that Identicon is used by mobile as well so a change in `Identicon` function needs to be coordinated. Another option could be to simply replace all the code to generate SVG instead of PNG. That way it wouldnt matter what size the image is.

**Comment by iurimatias** [comment]
merging., was marked as a tested in original issue

**Comment by osmaczko** [comment]
> @saledjenic thank you for the detailed information about the profile image! I'm just curious about could we try to find the way the profile image will look better? Maybe we can display it in the size 50x50 in the 'Change profile picture' popup or change the size of the default generated identicons?

@saledjenic @elina2015 I am not sure if we should use identicons at all in any place. The one that is visible when changing the profile image is leftover (I missed) and should be removed. Instead, we should use 2 letters + identicon ring there.

Identicon images are deprecated and all the leftovers should be removed from status-desktop, @John-44 @iurimatias please confirm.

**Pull request merged**
