### PR TITLE
fix(settings): Fix click on settings items

### PR DESCRIPTION
**Pull request by borismelnik**
Closes: #5872

### What does the PR do

Fix navigation in settings

### Affected areas

StatusNavigationListItem

### CODE REVIEW

**Comment by elina2015** [comment]
@borismelnik the app is not launched and the error appears in the logs:
image

Could you kindly check?

**Comment by PascalPrecht** [comment]
@borismelnik The reason this isn't working on desktop in this version is because the StatusQ version you're pointing to is not the latest and greatest (which introduces the `StatusEmoji`).

Also, there's already a fix in latest StatusQ for the navigation items as mentioned here: https://github.com/status-im/StatusQ/pull/689#issuecomment-1136872236

**Comment by borismelnik** [comment]
Already done by @PascalPrecht

**Comment by PascalPrecht** [comment]
@borismelnik Stop! :D

We still need this update to StatusQ here in desktop.

**Review by elina2015 — APPROVED** [review]
Tested on https://ethstatus.testrail.net/index.php?/runs/view/9278&group_by=tests:status_id&group_order=asc

**Comment by iurimatias** [comment]
statusq updated already

**Pull request closed without merging**
