### PR TITLE
chore(status-go): up status-go to get fix for sqlcipher

### PR DESCRIPTION
**Pull request by jrainville**
testing if https://github.com/status-im/status-go/pull/5844 builds fine on desktop

### CODE REVIEW

**Comment by siddarthkay** [comment]
@status-im/desktop-qa : good to merge the status-go side? I hope there are no issues on desktop side with this change ?

**Comment by anastasiyaig** [comment]
@siddarthkay i was hoping to check this PR with smoke test by autotests but squish was down. Tests are running now, lets see. I think you can merge if they pass

**Comment by anastasiyaig** [comment]
@siddarthkay it looks okay

**Comment by siddarthkay** [comment]
@anastasiyaig : Thanks for confirming, I'll go ahead and merge the updates on status-go side.

**Pull request closed without merging**
