### PR TITLE
chore: bump status-go

### PR DESCRIPTION
**Pull request by osmaczko**
Fixes always visible "sending..." message annotation.

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
What was the issue in the end? I'm curious as it was a weird issue.

**Comment by osmaczko** [comment]
> What was the issue in the end? I'm curious as it was a weird issue.

https://github.com/status-im/status-go/pull/4346

Message tracking wasn't working due to my oversight. Instead of allocating space for message hashes, I created them in place and then appended them, resulting in slices like `0, 0x1234`. Evidently, the first element in the slice is invalid, which caused the message tracking to fail.

**Comment by osmaczko** [comment]
@jrainville is there an issue I can link this PR to?

**Comment by jrainville** [comment]
I don't think we opened one for that. There was this in mobile :smile: https://github.com/status-im/status-mobile/issues/16873#issuecomment-1816315345

**Review by mprakhov — APPROVED** [review]

**Pull request merged**
