### PR TITLE
chore: add qtlottie to aqtinstall parameters

### PR DESCRIPTION
**Pull request by richard-ramos**
closes https://github.com/status-im/status-desktop/issues/4998

### CODE REVIEW

**Review by borismelnik — APPROVED** [review]

**Comment by abhi-status** [comment]
Richard ahs confirmed that this PR contains the Lottie code.

Which means using the PR build here must help launch the app.

But the app doesn't launch. 
(tested after removing Qt Lottie on my system)

**Comment by iurimatias** [comment]
@jrainville could you give a look at this one please

**Comment by jakubgs** [comment]
Look at this amazing naming consistency:
```
admin@windows-01 MINGW64 ~
$ aqt list-qt windows desktop --modules 5.14.2 win64_msvc2017_64
debug_info qtcharts qtdatavis3d qtlottie qtnetworkauth qtpurchasing qtquick3d qtquicktimeline qtscript qtvirtualkeyboard qtwebengine qtwebglplugin

admin@windows-01 MINGW64 ~
$ find /c/Qt/5.14.2 -iname '*lottieqt*.dll'
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugin.dll
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugind.dll

admin@windows-01 MINGW64 ~
$ find /c/Qt/5.14.2 -iname 'qtbodymovin'
/c/Qt/5.14.2/msvc2017_64/include/QtBodymovin
/c/Qt/5.14.2/msvc2017_64/include/QtBodymovin/5.14.2/QtBodymovin
/c/Qt/5.14.2/msvc2017_64/include/QtBodymovin/QtBodymovin
```
So:

* The module is called `qtlottie`
* The library is called `lottieqt`
* The headers are called `qtbodymovin`

Which makes perfect sense and causes no confusion whatsoever, and I totally didn't waste 30 minutes trying to find the DLL files and failing while thinking I'm going crazy.

**Comment by jakubgs** [comment]
I deployed the update to QT on CI hosts:
```
 > a ci-slave-windows -m win_shell -a 'find /c/Qt/5.14.2/msvc2017_64/ -iname "lottieqt*.dll"'
windows-01.he-eu-hel1.slave.ci | CHANGED | rc=0 >>
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugin.dll
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugind.dll

windows-02.he-eu-hel1.slave.ci | CHANGED | rc=0 >>
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugin.dll
/c/Qt/5.14.2/msvc2017_64/qml/Qt/labs/lottieqt/lottieqtplugind.dll
```
Ping me when this is merged so I can update the pinned commit in the Ansible role.

**Review by jrainville — APPROVED** [review]
Tested the new build containing Lottie and it worked.
I also tested the PS script locally on my PC and it also worked

**Pull request merged**
