### PR TITLE
feat(new-links-format): Adds new links to UI

### PR DESCRIPTION
**Pull request by borismelnik**
Part of: #11448

### What does the PR do

Adds usage of new links generators

### Affected areas

Contacts, Communities 

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

Снимок экрана 2023-07-06 в 14 28 59

Снимок экрана 2023-07-06 в 14 29 30

Снимок экрана 2023-07-06 в 14 29 54

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
LGTM.

It might be worth to split the original issue in two, so QAs can test this one and then they can test the other part while knowing the right acceptance criterias

**Comment by borismelnik** [comment]
> LGTM.
> 
> It might be worth to split the original issue in two, so QAs can test this one and then they can test the other part while knowing the right acceptance criterias

I agree. :)

**Review by caybro — APPROVED** [review]
LGTM

**Review by igor-sirotin — APPROVED** [review]
👍

**Review by lukaszso — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@borismelnik can u please resolve conflicts and get it merged? :)

**Comment by borismelnik** [comment]
> @borismelnik can u please resolve conflicts and get it merged? :)

yes :)

**Pull request merged**
