### PR TITLE
chore: switch wakuv2 fleet to waku

### PR DESCRIPTION
**Pull request by yakimant**
See status-im/infra-nim-waku#91 for details

Mostly done automatically. Some parts manually.

### CODE REVIEW

**Comment by yakimant** [comment]
@caybro, @richard-ramos, can you help with review?

**Review by richard-ramos — APPROVED** [review]

**Comment by caybro** [comment]
> @caybro, @richard-ramos, can you help with review?

I guess the review shall be done by someone else more knowledgeable in the domain :)

**Review by jrainville — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@yakimant how urgent is that? we are trying to get release out of the door, is it for 2.28?

**Comment by yakimant** [comment]
@anastasiyaig, not urgent, please do after 2.28

**Pull request merged**
