### PR TITLE
Fix various problems with link messages not showing

### LINKED ISSUE #4131: Gifs are not being displayed even all settings are enabled
# Bug Report

## Description

GIFs are not shown in chat

## Steps to reproduce

1. enable GIF widget
2. enable pictures preview in chat
3. enable unfurling for Tenor

#### Expected behavior

GIF is shown (as in Beta 0.3.0)

Screenshot 2021-11-18 at 12 53 29

#### Actual behavior

GIF is not shown

Screenshot 2021-11-18 at 12 53 23

Screenshot 2021-11-18 at 12 55 10

Screenshot 2021-11-18 at 12 55 15

### Additional Information

- Status desktop version: master from 18-nov-2021, commit `da28629ffc2f2aac313bcff1eeaab2fbfe8d85ec` 

- Operating System: macOS, BigSur

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4131

Fixes:
- never ask again not hiding the box
- the box not showing for non-images
- the gif not showing when changing the display image setting (until changing channel)

### CODE REVIEW

**Review by alexandraB99 — COMMENTED** [review]
Just tested this and I can't see the gif
gif
s

**Comment by anastasiyaig** [comment]
it does work partially to me:

1. youtube links are fine (shown) 
2. tenor is not resolved
3. giphy is asking for permissions (even i enabled all 3 flags and gif widget)

Is it something that could be improved @jrainville ?


https://user-images.githubusercontent.com/82375995/142985071-5f8ba71a-78c2-40d3-8bd3-a8b306d3e8c6.mov

**Comment by jrainville** [comment]
@anastasiyaig I updated status-go to remove tenor since sadly they updated the API and we no longer get an image url.

Otherwise, I can't reproduce the issue you're having. I wonder if it's OS specific. Or maybe you do something special? 
I tried with a new and old account. In #test and my own channel. With gifs I posted and gifs posted by others.

**Comment by anastasiyaig** [comment]
@jrainville please remove tenor in GIF widget too


Screenshot 2021-11-24 at 12 13 40

**Comment by borismelnik** [comment]
@jrainville i found  where is a problem
`            function getSourceComponent() {
                // Reset the height in case we set it to 0 below. See note below
                // for more information
                this.height = undefined
                if (Utils.hasImageExtension(link)) {
                    if (localAccountSensitiveSettings.displayChatImages) {
                        linkData = {
                            thumbnailUrl: link
                        }
                        return unfurledImageComponent
                    } else {
                        if (localAccountSensitiveSettings.neverAskAboutUnfurlingAgain || (isImageLink && index > 0)) {
                            return
                        }

                        isImageLink = true
                        return enableLinkComponent
                    }
                }`
               
               here `localAccountSensitiveSettings.displayChatImages` always `false` even if you checked it in settings

**Comment by jrainville** [comment]
> @jrainville please remove tenor in GIF widget too, or maybe replace with Giphy, which could be even better

@anastasiyaig so turns out the Gif widget has access to the URLs and sends the gifs using a special type of message that sends that URL, so they are still valid. In other words, the widget does NOT use the API that has been changed. It's another API that gives us good urls.

So that means that we can keep using the widget and also removing the other tenor whitelist setting doesn't change much, since the widget is the best way to send gifs

**Comment by anastasiyaig** [comment]
@jrainville why disabling the setting to have chat link previews does not make effect for gifs posted with Giphy?

Screenshot 2021-11-25 at 11 04 57

Screenshot 2021-11-25 at 11 04 44

Screenshot 2021-11-25 at 11 03 59

**Comment by PascalPrecht** [comment]
> why disabling the setting to have chat link previews does not make effect for gifs posted with Giphy?

Would have to verify, but it's prolly because we're using actual images for rendering those, while chat link previews are metadata from websites.

**Comment by anastasiyaig** [comment]
@PascalPrecht the reason i am asking is beacause the same scenario (enabling disabling links preview) works correctly for github links, so once it is switched off, i dont see the GH link posted, when i turn it on - i see the link. But it is not working for Giphy

**Comment by anastasiyaig** [comment]
@PascalPrecht @jrainville turned out this is already in beta3, so no need to fix it right now, i will investigate more and log separate issue for it to be fixed in master and delivered in any of newer versions

**Review by PascalPrecht — APPROVED** [review]
Changes LGTM, but I'm wondering why there's a change in status-lib/status-go in this PR

**Comment by PascalPrecht** [comment]
@jrainville FYI: I've merged the corresponding `status-lib` PR and updated this one to point at the newer status-lib version.

**Comment by jrainville** [comment]
> Changes LGTM, but I'm wondering why there's a change in status-lib/status-go in this PR

For posterity: that change is to remove Tenor from the whitelist. The reason being that the Tenor API has been changed and no longer returns a url, but instead returns an Iframe, which is not good for us.
I also explained it here: https://github.com/status-im/status-desktop/pull/4137#issuecomment-977111269

**Pull request merged**
