### PR TITLE
fix(TokenSelector): Duplicate plain token entries

### PR DESCRIPTION
**Pull request by caybro**
### What does the PR do
- filter out plain tokens from the adaptor if already present in the output model
- add a corresponding regression test
- hardcode the TokenSelector's popup height and increase margins
- fix sections in search mode
- add a placeholder for no search results

Fixes https://github.com/status-im/status-desktop/issues/15412

### Affected areas

TokenSelector[ViewAdaptor]

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

### CODE REVIEW

**Comment by Khushboo-dev-cpp** [comment]
image

In design there is a fixed height for it https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3406-231495&t=dlm3FaxR05MRt7xX-4

@caybro can you fix the popup height in this PR?

**Comment by caybro** [comment]
> image
> 
> In design there is a fixed height for it https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK/Swap---Milestone-1?node-id=3406-231495&t=dlm3FaxR05MRt7xX-4
> 
> @caybro can you fix the popup height in this PR?

Fixed (in a separate commit) together with some other minor tweaks based on design's feedback

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Comment by dlipicar** [comment]
I see one additional issue with the list of tokens. When searching the sections are supposed to become a single list: https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK?node-id=3504-426138#800162972
image

If we feel the current implementation is better/simpler, we should raise it with Alisher

**Comment by caybro** [comment]
> I see one additional issue with the list of tokens. When searching the sections are supposed to become a single list. Moreover, if no matches are found we should display some text: https://www.notion.so/Select-input-asset-8286c7cb617d43f195bce8de1c95a952?pvs=4#6683aba4992247c28ba7db8eb7a2a751
> 
> https://www.figma.com/design/TS0eQX9dAZXqZtELiwKIoK?node-id=3504-426138#800162972 image
> 
> If we feel the current implementation is better/simpler, we should raise it with Alisher

OK, can you pls raise a separate issue for the search/sections? I'll take it tomorrow

**Review by dlipicar — APPROVED** [review]

**Pull request merged**
