### PR TITLE
fix(mute-till): Fix migration problem

### PR DESCRIPTION
**Pull request by borismelnik**
Fixes: #11202

### What does the PR do

Fix the login problem because of migration issue

[STATUS-GO CHANGES](https://github.com/status-im/status-go/pull/3653)

### Affected areas

Communities

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### CODE REVIEW

**Review by noeliaSD — COMMENTED** [review]
Tested and I have this issue now: 
Screenshot 2023-06-22 at 09 23 18

**Comment by borismelnik** [comment]
> Tested and I have this issue now:
> Screenshot 2023-06-22 at 09 23 18

Very interesting... did you rebuild `status-go`?

**Review by noeliaSD — APPROVED** [review]
After last changes I can log in!

**Comment by borismelnik** [comment]
@caybro @alexjba pls :)

**Review by caybro — APPROVED** [review]
Unable to repro now but code LGTM

**Comment by borismelnik** [comment]
changes was there https://github.com/status-im/status-desktop/pull/10968

**Pull request closed without merging**
