### PR TITLE
feat(@contacts): close modal on accept/decline all

### LINKED ISSUE #5273: Nice to have: Close contact request modal when all requests were accepted
Imagine you get a contact request and you open the modal which looks like this:

Screenshot from 2022-03-30 16-03-39

Two options here:

1. Hit accept all
2. Accept individual requests

When I do 2) I end up with a modal that's empty:
Screenshot from 2022-03-30 16-06-16

Since there are no more requests, it'd be cool if the modal closes automatically

### PR DESCRIPTION
**Pull request by alaibe**
fixes status-im/feature-specs#69

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Review by saledjenic — APPROVED** [review]

**Comment by saledjenic** [comment]
@jrainville I think the changes are good, cause he is calling "close" in case accept all or reject all button is clicked, but if you accept/reject contacts one by one we should not close the popup automatically after last accepted/rejected contact, but let user to close it automatically (unless that is a request).

**Comment by jrainville** [comment]
I'm going with what @PascalPrecht wrote in his spec:
> Two options here:

> 1) Hit accept all
> 2) Accept individual requests

> When I do 2) I end up with a modal that's empty:
> Since there are no more requests, it'd be cool if the modal closes automatically

**Comment by iurimatias** [comment]
merging close it's already an improvement

**Comment by iurimatias** [comment]
merging because it's already an improvement

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
