### PR TITLE
StatusModal -> StatusDialog (first iteration)

### PR DESCRIPTION
**Pull request by osmaczko**
iterates: status-im/StatusQ#760

Adapted:
- rename-group dialog
- community-intro dialog
- mailserver-connection-issue dialog

### CODE REVIEW

**Comment by osmaczko** [comment]
> I want a screenshot :)
> 
> LGTM, code looks good

Wait, this is a work in progress :P Changed to draft.

**Comment by osmaczko** [comment]
@caybro could you please test the changes?

**Comment by caybro** [comment]
> @caybro could you please test the changes?

@osmaczko sure but still would like the screenshots here ;)

**Comment by osmaczko** [comment]
> > @caybro could you please test the changes?
> 
> @osmaczko sure but still would like the screenshots here ;)

@caybro sure (popups should look exactly the same as before :sweat_smile: )

- rename-group dialog
image

- community-intro dialog
image

- mailserver-connection-issue dialog
image

**Review by caybro — APPROVED** [review]
Tested, works fine

**Pull request merged**
