### PR TITLE
fix: The text entry box shouldn't highlight invalid @mentions

### LINKED ISSUE #3542: The text entry box shouldn't highlight invalid @mentions
See 
2021-09-15 07_33_56-Status Desktop

The @mention function shouldn't let a user @mention and highlight a name that isn't a member of the community

------------------------
Desired resolution: Inside a community it should only be possible for a user to at mention people who are members of that community.

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #3542

### What does the PR do
The text input in chat was highlighting whatever was starting
with @. Fixed to highlight only valid user mentions.

### Affected areas
Chat

### Screenshot of functionality 
https://user-images.githubusercontent.com/31625338/147973493-7f133ef5-0ddd-4bb2-8baa-b8b62cd72e27.mov

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Nice!!

**Review by PascalPrecht — APPROVED** [review]

**Comment by noeliaSD** [comment]
There are 2 use cases where text entry is still highlighting invalid mentions. When a mention is already highlighted: 
1. If it is modified and it is no longer valid, it should be disabled. 
2. Space disables mentions only in the first alias word.

Attached video.
https://user-images.githubusercontent.com/97019400/148207025-e3ddb602-fa5a-477d-9b5f-12a5a2ab4c03.mp4

**Comment by alexandraB99** [comment]
> There are 2 use cases where text entry is still highlighting invalid mentions. When a mention is already highlighted:
> 
> 1. If it is modified and it is no longer valid, it should be disabled.
> 2. Space disables mentions only in the first alias word.
> 
> Attached video. https://user-images.githubusercontent.com/97019400/148207025-e3ddb602-fa5a-477d-9b5f-12a5a2ab4c03.mp4

@noeliaSD I can't see the video, however you are right about your comments and I also discovered more issues like this when for example more than one mentions are in a single edit..I am working to provide a solution, marking the PR as "do not merge" for now.

**Comment by alexandraB99** [comment]
@noeliaSD just pushed an update, please check again!

**Review by noeliaSD — APPROVED** [review]

**Comment by noeliaSD** [comment]
Good improvement! Only something else not so relevant... after mention has been highlighted it is not possible to remove characters from the established mention directly using the backspace key but if you go back with back arrow then you can.

**Comment by alexandraB99** [comment]
> Good improvement! Only something else not so relevant... after mention has been highlighted it is not possible to remove characters from the established mention directly using the backspace key but if you go back with back arrow then you can.

thanks @noeliaSD, fixed

**Review by abhi-status — APPROVED** [review]

**Pull request merged**
