### PR TITLE
feat: check for updates (using status-go)

### PR DESCRIPTION
**Pull request by richard-ramos**
Requires
- https://github.com/status-im/status-go/pull/2552

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Nice job!

**Review by noeliaSD — APPROVED** [review]
LGTM!! :)

**Comment by richard-ramos** [comment]
To test this, in src/app/modules/main/profile_section/about/view.nim,  line 40 add:
```nim
    self.versionFetched(true, "3.0.0", "https://status.im")

```

**Comment by noeliaSD** [comment]
> To test this, in src/app/modules/main/profile_section/about/view.nim, line 40 add:
> 
> ```nim
>     self.versionFetched(true, "3.0.0", "https://status.im")
> ```

Tested by adding code line as @richard-ramos indicated above:

https://user-images.githubusercontent.com/97019400/170188864-96b71810-7a3e-4e8b-8a4f-ebd7022d62be.mov

**Comment by iurimatias** [comment]
closing since original PR has been merged

**Pull request closed without merging**
