### PR TITLE
[createCommunity]: added wrap mode in community key

### LINKED ISSUE #10325: Keys and Community URLs don't wrap on to the next line in the "Import Community" dialogue
Version 0.11, Windows 10

To reproduce:

1. Open the "Import Community" dialogue 

2. Try pasting a string like "0x0234c5803989ea37637e0c108376db184f927c9e413a894254e35738c25d4c5813" into the community key field

--- What currently incorrectly happens ---

3. The string that is too long to fit in the available horizontal space doesn't wrap on to the next line, see screenshot below:

2023-04-15 16_13_55-Status Desktop

In this example, the string "0x0234c5803989ea37637e0c108376db184f927c9e413a894254e35738c25d4c5813" was pasted into the field, and the last three characters in this string ("813") are missing.

--- Desired behaviour ---

3. If a string that is too long to fit on a single line (like for example a 'Community URL' or 'Channel inside a Community URL') is pasted into the 'Community  key' field, it should wrap onto the next lines so that the entire string is visible in the field.

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #10325

### What does the PR do
ImportCommunityPopup: added wrap mode in community key text area

### Affected areas
ImportCommunityPopup 

### Screenshot of functionality (including design for comparison)
https://user-images.githubusercontent.com/31625338/236808588-a122d722-1377-448e-ad19-148fc89d4181.mov

### CODE REVIEW

**Review by caybro — COMMENTED** [review]
Probably nothing but why does the pasted key show as invalid in your video?

**Review by alexjba — APPROVED** [review]

**Comment by alexandraB99** [comment]
> Probably nothing but why does the pasted key show as invalid in your video?

because it is, it's just a random long text :) the real key to a community was fitting the width so there was no way to demonstrate text wrapping

**Comment by alexandraB99** [comment]
@caybro updated video to show a valid key use case

**Review by noeliaSD — APPROVED** [review]
LGTM!

**Review by caybro — APPROVED** [review]

**Pull request merged**
