### PR TITLE
fix(ui): visually remove splitview handle

### PR DESCRIPTION
**Pull request by PascalPrecht**

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
I assume it's no longer clickable? Maybe it's what we want, but then maybe we can remove the old code that handles the sizes and such

**Comment by PascalPrecht** [comment]
Very good point. Will remove resize logic

**Comment by PascalPrecht** [comment]
@jrainville actually realized that resizing seems to be built-in to `SplitView`? Couldn't find any code for that otherwise. Or have you been referring to something completely different. What do you mean by "sizes"?

**Comment by jrainville** [comment]
BTW, the WalletLayout and ProfileLayout have the resize code as well:
https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Wallet/WalletLayout.qml#L30-L44
https://github.com/status-im/status-desktop/blob/master/ui/app/AppLayouts/Profile/ProfileLayout.qml#L20-L34

**Comment by PascalPrecht** [comment]
Ah good catch. Will send another PR. To be clear though, we still need to set the widths though for the panes to have a size. We don't need to restore any tho

**Comment by jrainville** [comment]
Yeah for sure. Though, maybe only the preferred width is necessary?
Also, I saw you fixed a typo in `leftTabPreferredSize`, but you didn't change the Style name (the typo is everywhere basically)

**Comment by PascalPrecht** [comment]
> Also, I saw you fixed a typo in leftTabPreferredSize, but you didn't change the Style name (the typo is everywhere basically)
Oh damn, didn't expect that, okay fix in the making :D

**Pull request merged**
