### PR TITLE
feat(@community): Add tags to communities

### LINKED ISSUE #5680: Creating community tags
### Description

see https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2759%3A388620

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #5680
Depends https://github.com/status-im/StatusQ/pull/734 and https://github.com/status-im/status-go/pull/2708

### What does the PR do

Support tags for creating communities

### Affected areas

Chat, Communities

### Screenshot of functionality

https://user-images.githubusercontent.com/2522130/173097250-9ef1fe55-6dfe-456f-81d8-542fa1ee53ff.mov

### CODE REVIEW

**Comment by iurimatias** [comment]
[status-go](https://github.com/status-im/status-go/pull/2708)

**Comment by elina2015** [comment]
@MishkaRogachev hey, I found some issues. Could you kindly check?
1. If user clicked the button 'Confirm Community Tags' without selection any tag, the placeholder text disappears from the 'Create New community' dialog:
image
2. The icon for 'Crypto' tag is not shown:
image
3. After hover over the tags the pointer doesn't change its view (it doesn't look like a hand) and for user it's not clear that it's possible to click on the tags (selected and not selected:
image
4. I selected some tags and clicked on the arrow in the left bottom corner for going back without clicking 'Confirm Community Tags'. But the selected tags are saved. Expected result: the selected tags are not saved.

**Comment by elina2015** [comment]
For QA: test run https://ethstatus.testrail.net/index.php?/runs/view/9488&group_by=tests:status_id&group_order=asc

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev hey, I found some issues. Could you kindly check?
> 
> 1. If user clicked the button 'Confirm Community Tags' without selection any tag, the placeholder text disappears from the 'Create New community' dialog:
> 
> image
> 
> 2. The icon for 'Crypto' tag is not shown:
> image
> 
> 3. After hovering over the tags the pointer doesn't change its view (it doesn't look like a hand) and for the user, it's not clear that it's possible to click on the tags (selected and not selected:
> image
> 
> 4. I selected some tags and clicked on the arrow in the left bottom corner for going back without clicking 'Confirm Community Tags'. But the selected tags are saved. Expected result: the selected tags are not saved. 
> 5. I selected some tags for a new community and saved them. After saving, I'm going to change the settings of the created community. Actual result: the tags are not shown Expected Result: The selected tags while creating a community are saved and can be seen in the edit community dialog.
>  tags.are.not.saved.mov 
> 6. Open community for editing and add some tags, save. Open the community for editing again.
>    Actual Result: the tags are not saved
>    Expected Result: the tags are saved

1. Fixed
2. In progress
3. Fixed
4. Fixed
5. Moved to https://github.com/status-im/status-desktop/issues/6089
6. Moved to https://github.com/status-im/status-desktop/issues/6089

**Review by elina2015 — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Good job!

**Comment by jrainville** [comment]
Needs a rebase

**Pull request merged**
