### PR TITLE
chore: decreased limits for concurrent requests and rps

### PR DESCRIPTION
**Pull request by saledjenic**
Corresponding `status-go` PR:
- https://github.com/status-im/status-go/pull/5253

### CODE REVIEW

**Comment by Valentina1133** [comment]
I'm going to run all tests for this branch - just to make sure that all good with other tests

**Comment by anastasiyaig** [comment]
started full run again one more time here https://ci.status.im/job/status-desktop/job/e2e/job/manual/1966/

**Comment by anastasiyaig** [comment]
UPD: no new failures it seems , results are the same as for master build @Valentina1133

**Comment by saledjenic** [comment]
@anastasiyaig  what does that mean, should we merge this pr or reject it?

**Comment by anastasiyaig** [comment]
> @anastasiyaig what does that mean, should we merge this pr or reject it?

i mean testing wise there are not problems found . we can merge

**Comment by saledjenic** [comment]
Closing cause it's not relevant anymore.

**Pull request closed without merging**
