### PR TITLE
chore: upgrade status-go

### PR DESCRIPTION
**Pull request by igor-sirotin**
Test this status-go breaking change: https://github.com/status-im/status-go/pull/5810

### CODE REVIEW

**Comment by igor-sirotin** [comment]
@pavloburykh can you please give it a quick test? We need to ensure that URL unfurling is working fine.
I removed an old deprecated `urls` package and it's a breaking change. According to the code, it's not used in mobile and desktop already, but worth testing just in case.

And https://github.com/status-im/status-go/pull/5810 needs to merged ASAP, as all tests in status-go are failing now 🫠

**Comment by anastasiyaig** [comment]
on it

**Comment by anastasiyaig** [comment]
https://ci.status.im/job/status-desktop/job/e2e/job/manual/2505/allure/#suites/215203023ddd57f8394707e3607851be/31a89fe7ca5f49fb/ it works @igor-sirotin

**Comment by igor-sirotin** [comment]
The fix will be merged to status-desktop at some point 👌

**Pull request closed without merging**
