### PR TITLE
feat(CommunitiesPortal): Communities Portal first UI approach

### LINKED ISSUE #4936: Communities Portal
### Description

Designs: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=2244%3A246844

Screen Shot 2022-02-28 at 5 44 47 PM

Scope:
- UI/QML only

Out of scope:
- **Tags row** component `StatusListItemTagRow` --> https://github.com/status-im/StatusQ/issues/690
- **Searcher** (just only add the control and keep it disabled)
- **Import** and **Create** buttons  (just only add the controls and keep them disabled)
- **Community Card**: neither tags nor community requirements and it will be clickable but the navigation action will be pending to implement.

Subtasks:
* [x] General `Community Portal` layout
* [x] Page API (needed property models and signals)
* [x] Create `StatusQ` component: `StatusCommunityCard` as it is in desktop desing. --> Second iteration here: https://github.com/status-im/StatusQ/issues/692

### PR DESCRIPTION
**Pull request by noeliaSD**
Closes #4936. Check that issue to see the scope!

Requires:
- https://github.com/status-im/status-go/pull/2685
- https://github.com/status-im/StatusQ/pull/693

### What does the PR do
- Added new item section `CommunitiesPortal`.
- First `CommunitiesPortalLayout` approach.
- Added some community logos.
- Added Store and Test models in store.
- Added disabled buttons and community cards navigation function.
- Added loading card.
- Modified `StatusQ` link.

### Affected areas
New section --> `Communities Portal`

### Screenshot of functionality
Here are the steps to follow to load the `Communities` that are retrieved from the backend:
1. Create new account
2. Advanced `multinetwork`
3. Advanced `wallet` and then, testnet
4. Advanced `community`
5. Logout

Then to enable the new section and the one to be tested here:

6. Advanced `communities portal`

**NOTE**: The way where now it is calculated the `Featured` or `Popular` clasification is out of scope, so do not pay attention to that result.

https://user-images.githubusercontent.com/97019400/170512109-149b6965-9b53-42c6-8116-31ef1212464c.mov

Here another video with a `mock` model to see the qml design:

https://user-images.githubusercontent.com/97019400/170515709-51afab72-d33b-4f6c-869e-9fce6b985362.mov

### CODE REVIEW

**Comment by iurimatias** [comment]
@noeliaSD can we make this visible only if the communities are enabled in the experimental settings? after that we can merge this

**Comment by noeliaSD** [comment]
> @noeliaSD can we make this visible only if the communities are enabled in the experimental settings? after that we can merge this

Yes! Since it is originally part of the @richard-ramos task here https://github.com/status-im/status-desktop/issues/5720 I've not implemented it yet. Let me coordinate with him!

**Comment by Hbouaz** [comment]
Will test when integrated with the B/E

**Comment by noeliaSD** [comment]
> @noeliaSD can we make this visible only if the communities are enabled in the experimental settings? after that we can merge this

Done!

**Comment by noeliaSD** [comment]
> Will test when integrated with the B/E

@Hbouaz you can now test it!

**Review by richard-ramos — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Comment by noeliaSD** [comment]
`Don't merge` tag still present bc of the dependence with PR https://github.com/status-im/StatusQ/pull/693

**Comment by Hbouaz** [comment]
@noeliaSD I am getting this error when trying to build:
`Undefined symbols for architecture x86_64:
  "_NSApp", referenced from:
      Status::OSNotification::showIconBadgeNotificationMacOs(int) in libDOtherSideStatic.a(OSNotification.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang  @nim_status_client_linkerArgs.txt'
make: *** [bin/nim_status_client] Error 1`
Not sure if it is related to the unfinished dependency, in anycase Iwill wait for the label `[wait-for-statusq-merge]` on 
(https://github.com/status-im/status-desktop/labels/wait-for-statusq-merge) to be removed

**Review by Hbouaz — APPROVED** [review]
Tested according to the PR instructions and attached screen recording

**Comment by Hbouaz** [comment]
image

**Pull request merged**
