### PR TITLE
fix(TabBar): fix community tab button color to match the community color

### LINKED ISSUE #4497: [base_bc] community color and active state messed up in left tool bar

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4497

Pretty! 
image

Needs https://github.com/status-im/StatusQ/pull/536

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Is this a new design requirement? Because this was done intentionally that all communities will have exactly the same hover color.

**Comment by jrainville** [comment]
Could be only me, but I remember the communities having their respective colors before.

I checked the designs and they only show the image icon, so I couldn't figure out what is the wanted behaviour.

I made the judgement that it's clearer to have the community reflect the color chosen, but if we find a design that contradicts that or if you guys prefer the single color, I don't mind closing.

**Comment by PascalPrecht** [comment]
For transparency's sake, here's what @simonricoo said:
Screenshot from 2022-01-19 19-36-18

**Comment by jrainville** [comment]
ok, got it. Too bad it isn't clear in the design

**Comment by jrainville** [comment]
Ah, so I see in his comment, he is only talking about the active and hover being blue. Does that mean the other part of this PR (putting the color of the community when not active) should stay?

**Comment by PascalPrecht** [comment]
As you can see in the screenshot, I'd would've also expected the hover color to change based on community color.
One reason I could see why this isn't done this way is because community colors can be arbitrarily chosen and there are many colors that won't work well in light+darkmode.

Happy to revisit this, but we should probably get @davholik 's opinion on that as well.

**Comment by PascalPrecht** [comment]
> Ah, so I see in his comment, he is only talking about the active and hover being blue. Does that mean the other part of this PR (putting the color of the community when not active) should stay?

Good question! I'd let @davholik chime in on that

**Comment by davholik** [comment]
Hey, a late response, but I will leave it in here just as a reference. Pretty much as @PascalPrecht mentioned. The user customization is always a bit tricky, with the colors especially. We are unable to ensure that their pick of color will work with the theming of the UI. In that regard, it is much more versatile to have the "state" (active, hover) universally defined in the design system as a pattern. A great example is Slack or Discord. The "highlight" of the element should be universal and versatile so we can assure that it will work in every scenario.

**Pull request closed without merging**
