### PR TITLE
fix: blurry icons in Network Filter combobox

### LINKED ISSUE #9853: Icons are slighlty displayed differently in `NetworkFilter`combobox
5. Tiny detail - icon in the combobox on the top is not anti-aliased:
Screenshot from 2023-03-07 09-56-08

_Originally posted by @micieslak in https://github.com/status-im/status-desktop/pull/9748#pullrequestreview-1327943865_

### PR DESCRIPTION
**Pull request by caybro**
Do not load a lowres image, breaks on hires displays. Also make sure we treat any SVG image the same way we do with icons, that is set the `sourceSize` to the required displayed size.

Fixes #9853

### Affected areas

NetworkFilter combobox

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

Snímek obrazovky z 2023-05-29 13-54-40

### CODE REVIEW

**Comment by micieslak** [comment]
From what I see this change doesn't fix the problem that I observed.

Before the change it was as follows:

Screenshot from 2023-05-29 14-44-12

The row of icons on top is smooth, and there are proper icons, visually optimized for small size

After the change:

Screenshot from 2023-05-29 14-47-51

The icons on top are ragged on edges and just miniatures of the full size versions.

**Review by micieslak — CHANGES_REQUESTED** [review]
As already posted in the comment - the problems for ragged edges still appears for me. Probably 500x500 images are rasterized and down-scaled drastically to 24x24

**Comment by caybro** [comment]
> As already posted in the comment - the problems for ragged edges still appears for me. Probably 500x500 images are rasterized and down-scaled drastically to 24x24

Alright, I used a different approach, pls give it a second try; on my side it's still good (High DPI) display, this should also make it work on a normal one

**Review by micieslak — APPROVED** [review]
Works like a charm. Nice work!

**Review by stefandunca — APPROVED** [review]
Good catch

**Pull request merged**
