### PR TITLE
fix(invitation): fix community invite not showing in 1-1 chats

### LINKED ISSUE #4851: Community invitation is not shown in chat
### Description

1. create an account on mobile
2. create an account on desktop
3. add each other to contacts
4. on mobile, create a community that is free membership
5. on mobile, add desktop account to this community
6. on desktop, check 1x1 chat with mobile

Expected: invitation to community is shown and resolved with appropriate button View / Join

**Actual:**  invitation is not shown

Screenshot 2022-02-21 at 16 14 41

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4851

### CODE REVIEW

**Review by iurimatias — CHANGES_REQUESTED** [review]
the fix didn't work for me

Screen Shot 2022-02-23 at 4 02 03 PM

**Comment by jrainville** [comment]
@iurimatias it's fixed now. The problem was that on new community invite, we didn't save the community in the community list model, so the fetch to get the data didn't work. Now we do

**Review by saledjenic — APPROVED** [review]
@jrainville code looks good, also checked and it works. 

Just one UI thing we should update within this or in some of the next tasks is the position of "Join"/"View" labels in community invitation bubble. For me it's somehow too up and left, but I guess it should have vertical and horizontal center position (checked on mobile it's centered tehre).

**Comment by anastasiyaig** [comment]
@jrainville please fix the button `Join` alignment if possible, otherwise looks good!

**Comment by jrainville** [comment]
@anastasiyaig and @saledjenic all the invite bubbles are kinda messed up. I didn't touch them because I didn't know if we had new designs for them or maybe a new StatusQ component for them.
If we don't, I can do the quick fix now

**Comment by anastasiyaig** [comment]
@jrainville no need then, indeed we need to check designs

**Review by anastasiyaig — APPROVED** [review]

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
