### PR TITLE
fix(onboarding): fixing onboarding layout ctx positioning issues

### LINKED ISSUE #5832: make all onboarding screens layout consistent
### Description

see figma

Currently some onboarding screens the buttons jump location, some header titles are not on the same position as others etc.. all of this needs to be made consistent

### Acceptance Criteria

- All onboarding screens have header text, images, action buttons at the same height

### PR DESCRIPTION
**Pull request by alexandraB99**
Closes #5832

### What does the PR do
Fixed onboarding layout context positioning issues

### Affected areas
Onboarding screens

### Screenshot of functionality
keysmain
userdetails

### CODE REVIEW

**Review by iurimatias — CHANGES_REQUESTED** [review]
I still see the tile jumping around in all screens, there is also a blank button

https://user-images.githubusercontent.com/176720/170376729-8c4b3743-e7b0-41b5-9ce3-5c70e01574d8.mov

**Comment by alexandraB99** [comment]
all fixed now

Uploading onb.mov…

**Comment by alexandraB99** [comment]
> I still see the tile jumping around in all screens, there is also a blank button
> 
>  Screen.Recording.2022-05-25.at.6.14.25.PM.mov

@iurimatias the "your profile" text is anyway at the top, since it's above the image, but all the rest should be fixed now.
gg

**Review by borismelnik — APPROVED** [review]

**Comment by elina2015** [comment]
@alexandraB99 could you kindly check the issue with a hidden button?
On the 'Connect your keys' screen, the hidden button is shown that lead to the 'Your profile' screen

https://user-images.githubusercontent.com/14942081/170891878-ad71001c-822a-4e26-a645-4779a65829a0.mov
Details: macOS Monterey 12.3 Beta (21E5227a)

**Pull request merged**
