### PR TITLE
feat: add DockClicker event filter

### PR DESCRIPTION
**Pull request by emizzle**
Fixes: #2311.

Add an event filter to `qApp` that can detect a dock icon click (in macos) when the main window is hidden or closed.

When the event has been triggered, the main window will be shown again.

Co-authored-by: Boris Melnik <82511785+borismelnik@users.noreply.github.com>

fix: support closing login window using native buttons
After closing the login window using the native "X" button, the application window would not restore correctly when clicking the dock icon. It was putting the application in to an unresponsive state. This PR fixes issue by handling the application window's `onClosing` event and hides the window manually.

### NOTE
~~Both the dependencies `status-im/nimqml` and `status-im/DOtherSide` have versions that are sitting on branches. Their respective PRs (linked below) should be merged in to their master branches *first* before merging this PR. Once merged, this PR should be updated with the bumped commit hashes.~~
~~1. https://github.com/status-im/dotherside/pull/24~~
~~2. https://github.com/status-im/nimqml/pull/20~~

### CODE REVIEW

**Comment by iurimatias** [comment]
@emizzle this can be updated now

**Comment by jakubgs** [comment]
Interesting failure:
```
cd /home/jenkins/workspace/s-desktop_branches_linux_PR-2485/vendor/DOtherSide/build/lib && /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -I/home/jenkins/workspace/s-desktop_branches_linux_PR-2485/vendor/DOtherSide/lib/include -I/home/jenkins/workspace/s-desktop_branches_linux_PR-2485/vendor/DOtherSide/lib/include/Qt -isystem /opt/qt/5.14.0/gcc_64/include -isystem /opt/qt/5.14.0/gcc_64/include/QtCore -isystem /opt/qt/5.14.0/gcc_64/./mkspecs/linux-g++ -isystem /opt/qt/5.14.0/gcc_64/include/QtGui -isystem /opt/qt/5.14.0/gcc_64/include/QtWidgets -isystem /opt/qt/5.14.0/gcc_64/include/QtQml -isystem /opt/qt/5.14.0/gcc_64/include/QtNetwork -isystem /opt/qt/5.14.0/gcc_64/include/QtQuick -isystem /opt/qt/5.14.0/gcc_64/include/QtQmlModels -isystem /opt/qt/5.14.0/gcc_64/include/QtQuickControls2  -O3 -DNDEBUG   -Wall -Wno-long-long -pedantic -fPIC -std=gnu++11 -o CMakeFiles/DOtherSideStatic.dir/src/DOtherSide.cpp.o -c /home/jenkins/workspace/s-desktop_branches_linux_PR-2485/vendor/DOtherSide/lib/src/DOtherSide.cpp
/home/jenkins/workspace/s-desktop_branches_linux_PR-2485/vendor/DOtherSide/lib/src/DOtherSide.cpp:1322:26: fatal error: DOtherSide.moc: No such file or directory
compilation terminated.
lib/CMakeFiles/DOtherSideStatic.dir/build.make:62: recipe for target 'lib/CMakeFiles/DOtherSideStatic.dir/src/DOtherSide.cpp.o' failed
make[3]: *** [lib/CMakeFiles/DOtherSideStatic.dir/src/DOtherSide.cpp.o] Error 1
```
I don't think this error is caused by CI host setup:
```
...../DOtherSide.cpp:1322:26: fatal error: DOtherSide.moc: No such file or directory
```

**Comment by jakubgs** [comment]
MOC files appear to be a QT thing: https://doc.qt.io/archives/qt-4.8/moc.html

**Comment by borismelnik** [comment]
MOC files generated by `qmake` step.
Sometimes rebuild fix it.

**Review by borismelnik — APPROVED** [review]

**Comment by anastasiyaig** [comment]
> MOC files generated by qmake step.
Sometimes rebuild fix it.

indeed, rebuild helped :D

**Comment by anastasiyaig** [comment]
for Linux it is not that optimistic:

`Makefile:168: recipe for target 'vendor/DOtherSide/build/lib/libDOtherSideStatic.a' failed
15:30:35  make: *** [vendor/DOtherSide/build/lib/libDOtherSideStatic.a] Error 2`

**Comment by anastasiyaig** [comment]
@emizzle it works nicely when i am logged in, but when i try to minimize to dock from login screen (enter password screen) -> the app is not responsive after clicking cross button:

`anastasiya@MacBook-Pro-Anastasiya /Applications % cd /Applications
Status.app/Contents/MacOS/nim_status_client
Network Cache Dir:  "/Users/anastasiya/Library/Application Support/Status/tmp/netcache"
qml: Unknown theme. Valid themes are "light" and "dark"
INF 2021-05-05 15:45:20+03:00 Starting application...                    topics="main" tid=153234 file=nim_status_client.nim:216
Network Cache Dir:  "/Users/anastasiya/Library/Application Support/Status/tmp/netcache"
ERR 2021-05-05 15:45:41+03:00 TODO: if user is logged in, logout         topics="main" tid=153234 file=nim_status_client.nim:160
`

https://images.zenhubusercontent.com/261270348/125d208d-71f9-4b34-a6c0-02332efaa9e1/screen_recording_2021_05_05_at_15_47_37.mov


is it something we can fix as well?

**Comment by emizzle** [comment]
> MOC files generated by `qmake` step.
> Sometimes rebuild fix it.

@borismelnik, I added `#include "DOtherSide.moc"` manually to the bottom of `DOtherSide.cpp`: https://github.com/status-im/DOtherSide/compare/25e70373f8558a20132cd3a344c2c2ab5ea041a3...4e3964099892410a986ffe5be2304fcad32d1060#diff-78b5ff497d785fbddb8bf59fd940a02e98143a24b215c4692663f10beb7e988fR1322.

Without it, building `DOtherSide` produces the following error:
```
"SRC:/lib/src/DOtherSide.cpp"
contains a "Q_OBJECT" macro, but does not include "DOtherSide.moc"!
Consider to
  - add #include "DOtherSide.moc"
  - enable SKIP_AUTOMOC for this file
```

**Comment by emizzle** [comment]
> @emizzle it works nicely when i am logged in, but when i try to minimize to dock from login screen (enter password screen) -> the app is not responsive after clicking cross button:
> 
> `anastasiya@MacBook-Pro-Anastasiya /Applications % cd /Applications Status.app/Contents/MacOS/nim_status_client Network Cache Dir: "/Users/anastasiya/Library/Application Support/Status/tmp/netcache" qml: Unknown theme. Valid themes are "light" and "dark" INF 2021-05-05 15:45:20+03:00 Starting application... topics="main" tid=153234 file=nim_status_client.nim:216 Network Cache Dir: "/Users/anastasiya/Library/Application Support/Status/tmp/netcache" ERR 2021-05-05 15:45:41+03:00 TODO: if user is logged in, logout topics="main" tid=153234 file=nim_status_client.nim:160 `
> 
> https://images.zenhubusercontent.com/261270348/125d208d-71f9-4b34-a6c0-02332efaa9e1/screen_recording_2021_05_05_at_15_47_37.mov
> 
> is it something we can fix as well?

@anastasiyaig, I've fixed this in this PR (commit https://github.com/status-im/status-desktop/pull/2485/commits/c3e404ba39f898c09f7fc60b64d6ef205bab385a).

**Comment by anastasiyaig** [comment]
for some reason i can reproduce it in latest build -> clicking Close button makes the app not responding when being on Login screen @emizzle

**Comment by emizzle** [comment]
> for some reason i can reproduce it in latest build -> clicking Close button makes the app not responding when being on Login screen @emizzle

I just tried with the release in the PR (https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2485/7/artifact/pkg/StatusIm-210510-063016-c3e404-pr.dmg) and was not able to reproduce.

**Comment by anastasiyaig** [comment]
It is working on 11.0.1, not working on 11.3 and not working on 10.15.6 which is super weird

**Comment by emizzle** [comment]
Confirmed working on `10.15.7`.

**Pull request merged**
