### PR TITLE
Fix/11409/high ram usage on linux

### PR DESCRIPTION
**Pull request by osmaczko**
potentially fixes: #11409

status-go PR: https://github.com/status-im/status-go/pull/3742

### CODE REVIEW

**Comment by jrainville** [comment]
Let me know when running this build if you ever see the spike again. If it seems like you don't we'll merge this

**Comment by osmaczko** [comment]
> Let me know when running this build if you ever see the spike again. If it seems like you don't we'll merge this

So far so good.

**Comment by osmaczko** [comment]
> > Let me know when running this build if you ever see the spike again. If it seems like you don't we'll merge this
> 
> So far so good.

Still all good. I also have an impression that the RAM usage is much lower than before, in idle mode ~700MB vs 1.2GB.

**Comment by jrainville** [comment]
Great, I restarted the e2e. When it's green I'll merge

**Pull request merged**
