### PR TITLE
fix(@desktop/wallet): show all tokens in wallet that have balance > 0

### LINKED ISSUE #5859: Show all tokens in wallet that have balance > 0
From the UI meeting (section Wallet Settings, issue 10):
https://docs.google.com/document/d/1Nd7YQOYVPR-KMz5qdU1AIGpL7vwBAZs-efifnZ0IkO8/edit#

### PR DESCRIPTION
**Pull request by saledjenic**
Fixes #5859

### CODE REVIEW

**Review by alaibe — CHANGES_REQUESTED** [review]
Requesting change as I think this is not enough, the wallet account dto are being populated based on the list that has been hidden by the previous PR, It will then always return the default couple: ETH + SNT. As a test you can add an account which own other token and they should appear. I think you probably need a new status-go endpoint e.g: discover token, which for all token we have in token store, check the balance and returns it.

wdyt?

**Comment by alaibe** [comment]
> I cannot cause I am getting all the time this error, even for the new status accounts (if you can, please test it):

This is a known bug! if you generate a new account, you also need to change the path index.
But for the purpose of this feature, you can simply add watch only account, if you go to advance section then Add a watch-only address, you can for example add this address: 0x7dac3ea4b99b15ec53cfa0f37510dd828b27895d (https://etherscan.io/address/0x7dac3ea4b99b15ec53cfa0f37510dd828b27895d)

As u can see this address own eth and USDC for example. But when I load the wallet here is what I see:
image

The reason is because of the message above, the wallet account dto is only populated based visible account token.

Also a question for this feature is, should we always display native chain token?

**Comment by saledjenic** [comment]
@all I updated code here a bit more. Now we don't rely on selected tokens any more, but for all wallet accounts we're checking periodically (on every `CheckBalanceIntervalInMilliseconds` milliseconds, currently I set that to 15 mins) balances for all known tokens and display tokens which have balances greater than 0. Also we're checking that on user's action and in that case time event check is postponed for another `CheckBalanceIntervalInMilliseconds` milliseconds. All that is done in a separate thread in a loop. That way adding new accounts or sending tokens to wallet address should be visible without app restart.

At the moment there is some other issue with the `status-go` and I am getting this error:
```
rpc response error                         topics="rpc" tid=69636654 file=core.nim:29 err="\nstatus-go error [methodName:wallet_fetchPrices, code:-32000, message:json: cannot unmarshal string into Go value of type map[string]float64 ]\n"
```
once that is fixed in the latest master I will rebase this branch and all should be good.

**Comment by anastasiyaig** [comment]
NOTE: goerli tokens are not displayed because it was not yet implemented https://github.com/status-im/status-go/blob/develop/services/wallet/tokenstore.go

**Review by anastasiyaig — APPROVED** [review]

**Comment by alaibe** [comment]
In the browser, i can see token where my balance is > 0, see screenshot:
image

I think WNG should not be displayed.

Also what about:
> Also a question for this feature is, should we always display native chain token?

**Comment by saledjenic** [comment]
> In the browser, i can see token where my balance is > 0, see screenshot:

Yes, I forgot about the wallet in the browser section, it's updated now as well.

> Also a question for this feature is, should we always display native chain token?

I agree with this but this is more a question for @John-44 (but if needed we can add it via new ticket, want to merge this now). When I checked some other wallets they display the entire list of all tokens they support, not only those where balance is greater than 0, so now when we have checking in a separate thread without UI blocking maybe we can do the same, and for example those with balance > 0 to keep always on top, maybe is more natural that way, not sure. 

> This seems that this logic should be on status-go side => this problem is shared between mobile and desktop and could be solve once there

And yes and no, depends what we want. If we move that to `stauts-go` side then we will need new signal notifying clients (desktop, mobile apps) about the change, this way we have some endpoints there (on the `stauts-go` side) and clients are allowed to implement the way they want or is more suitable to appropriate technology using exposed endpoints from the `stauts-go`. I am perfectly fine with both ways.

**Review by borismelnik — APPROVED** [review]

**Review by alaibe — APPROVED** [review]
Thanks for fixing browser, the 2 other point don t block the merge

**Comment by alaibe** [comment]
> I agree with this but this is more a question for @John-44 (but if needed we can add it via new ticket, want to merge this now). When I checked some other wallets they display the entire list of all tokens they support, not only those where balance is greater than 0, so now when we have checking in a separate thread without UI blocking maybe we can do the same, and for example those with balance > 0 to keep always on top, maybe is more natural that way, not sure.

I agree with you, it would be good to have @John-44 feedback

> And yes and no, depends what we want. If we move that to stauts-go side then we will need new signal notifying clients (desktop, mobile apps) about the change, this way we have some endpoints there (on the stauts-go side) and clients are allowed to implement the way they want or is more suitable to appropriate technology using exposed endpoints from the stauts-go. I am perfectly fine with both ways.

Why do we need a new signal, cannot status-go make multiple request on its own to the price provider and that be transparent for the client?

**Comment by saledjenic** [comment]
> Why do we need a new signal, cannot status-go make multiple request on its own to the price provider and that be transparent for the client?

Not sure (didn't check) how price provider works. If it sends balances for all accounts/tokens periodically that's great.

**Pull request merged**
