### PR TITLE
feat/cached-eth-client

### PR DESCRIPTION
**Pull request by dlipicar**
Bump status-go to get https://github.com/status-im/status-go/pull/5907

No functional changes are expected from this build. For regression testing:
- Proper fetch of balances
- Proper detection of transfers

### CODE REVIEW

**Comment by siddarthkay** [comment]
the core issue on failing windows builds seems to be -> `'protoc-gen-go' is not recognized as an internal or external command,`

**Comment by siddarthkay** [comment]
CI issues will be fixed after https://github.com/status-im/status-desktop/pull/16488 is merged

**Comment by anastasiyaig** [comment]
gonna see what is happening with tests, all of them are failing

**Comment by anastasiyaig** [comment]
i tested that today, did not see any issues so far

**Review by anastasiyaig — APPROVED** [review]

**Pull request closed without merging**
