### PR TITLE
fix(pins): only enable jump to and unpin buttons from the pinned popup

### LINKED ISSUE #4540: [base_bc] cant edit pinned messages
### Description

1. create community
2. create a channel
3. send some messages there
4. pin some
5. edit message in pin modal

Screenshot 2022-01-24 at 16 22 28

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #4540

This fits the design on Figma (at least the old one that we still have)

image

### CODE REVIEW

**Review by saledjenic — APPROVED** [review]
@jrainville from the code perspective this looks good.

**Comment by anastasiyaig** [comment]
@jrainville i think we need to leave reactions as well (per mobile)?  As well as delete and copy

Screenshot 2022-02-02 at 11 38 33

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Comment by jrainville** [comment]
@anastasiyaig as discussed with John here https://discord.com/channels/624205794384281629/730410574428504166/938845308069220412, we only want the "go to message" and "unpin" option in that dialog.

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
