### PR TITLE
chore: remove wakuv2 store config in advanced settings

### PR DESCRIPTION
**Pull request by kaichaosun**
### What does the PR do

Fix https://github.com/status-im/status-go/issues/4399

Remove the wakuv2 store config option in advanced settings page

cc @richard-ramos @cammellos @chaitanyaprem 

### StatusQ checklist

- [x] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

image

### Cool Spaceship Picture

<!-- optional but cool ->

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

if that's indeed the desired thing :)

**Comment by John-44** [comment]
> @John-44 can you help confirm if this is desired?

I think so, but the better people to check this with are @iurimatias and @cammellos

**Review by cammellos — APPROVED** [review]
(only approving the feature removal, not the code, as that's not for me :) )

**Review by iurimatias — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]
LGTM, cograts with first desktop PR! 🎉

**Comment by igor-sirotin** [comment]
Why are CI checks not running? 🤔  Is it because it's a PR from a fork?

cc @iurimatias @jakubgs 

image

**Pull request merged**
