### PR TITLE
feat: use a higher kdf number for DB encryption

### PR DESCRIPTION
**Pull request by richard-ramos**
The following scenarios must be tested:

Login with an existing account
Login after changing the password
Exporting a database
New account creation
Creating an account with seed phrase
Creating an account with keycard
Login with keycard

Requires
- https://github.com/status-im/status-go/pull/2796

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Do we plan of doing further work to accept an ENV variable to change it for tests or you think putting it even lower than the default is useless?

**Comment by richard-ramos** [comment]
I will try adding the environment variable, although I think that it wont make much difference

**Comment by richard-ramos** [comment]
@jrainville done!  in the makefile, you can use `make KDF_ITERATIONS=___` with a value greater than 0 to set a custom number of iterations.  I tried with a value of `1` and didn't notice a change in the time to login. Altho maybe it will make a difference in a machine with fewer resources?

**Review by jrainville — APPROVED** [review]

**Review by stefandunca — APPROVED** [review]

**Review by osmaczko — APPROVED** [review]

**Comment by richard-ramos** [comment]
Rebased

**Review by endulab — APPROVED** [review]

**Comment by anastasiyaig** [comment]
@richard-ramos i can't login with keycard:

```
terPin
DBG 2022-09-13 12:15:00.932+03:00 Account logged in succesfully              topics="accounts-service" tid=3731251 file=service.nim:520
ERROR[09-13|12:15:01.010] failed to initialize db                  package=status-go/api.GethStatusBackend err="file is not a database"
ERROR[09-13|12:15:01.013] failed to start a node                   key-uid=0xddf93726305d204916b4804f30b45d86f59d87e1166bd16004cb4e431564be71 error="file is not a database"
ERR 2022-09-13 12:15:01.013+03:00 node.login                                 topics="signals-manager" tid=3731251 file=signals_manager.nim:48 error="file is not a database"
ERR 2022-09-13 12:15:01.017+03:00 login error                                topics="app-controller" tid=3731251 file=module.nim:254 methodName=onNodeLogin errDesription="file is not a database"
```

**Review by alaibe — APPROVED** [review]

**Review by anastasiyaig — APPROVED** [review]

**Comment by anastasiyaig** [comment]
it works finally! Thank u @richard-ramos :)

**Pull request merged**
