### PR TITLE
chore(chat/MembersSelector): display "no results" when not found

### PR DESCRIPTION
**Pull request by osmaczko**
fixes: #7495

### Affected areas

- create chat
- edit group members

### Screenshot of functionality (including design for comparison)

- [ ] ~~I've checked the design and this PR matches it~~
There is no design for this yet

https://user-images.githubusercontent.com/33099791/200281789-450e8219-938b-48ae-82fd-9ca0899e6235.mp4

### CODE REVIEW

**Review by caybro — APPROVED** [review]

**Review by jrainville — APPROVED** [review]
Looks good. I think we might have said that if there are no contacts, we say `no contacts` or something, but if you want, we can wait for the designs

**Review by micieslak — CHANGES_REQUESTED** [review]
The current behavior of the popup is probably not what we expect. When the list is long, it's not scrollable, just trimmed. When there are several results, the popup seems to be too long.

[Kazam_screencast_00079.webm](https://user-images.githubusercontent.com/20650004/200337144-2136e0b6-4bf3-4a1a-811f-9054580c335c.webm)

**Comment by micieslak** [comment]
It would be nice to use `Storybook`. Testing on large number of contacts would be easier :)

**Comment by PascalPrecht** [comment]
@micieslak I think these things are worth creating issues for. This PR seems to be merely about adding the "no results found" case.

Unless these changes introduce the bugs you're mentioning, we should not pursue them as part of this PR

**Comment by PascalPrecht** [comment]
@micieslak is off today but to get this unblocked, I've discussed with him to dismiss his review as it blocks this PR from merging.
The things he's mentioning seem to be unrelated to the changes of this PR

**Comment by PascalPrecht** [comment]
Also chances are, the things mentioned in @micieslak comment will be addressed in #7668

**Comment by alexandraB99** [comment]
> Also chances are, the things mentioned in @micieslak comment will be addressed in #7668

@PascalPrecht if you're referring to [this](https://github.com/status-im/status-desktop/pull/8143#pullrequestreview-1170521117), not it's not. [This](https://github.com/status-im/status-desktop/pull/7668) PR is only addressing issues in the input field, we'd need a new issue for the mentioned bug.

**Comment by PascalPrecht** [comment]
@alexandraB99 done https://github.com/status-im/status-desktop/issues/8210

**Pull request merged**
