### PR TITLE
fix(@desktop): Fix icons regressions

### LINKED ISSUE #7284: Icons regressions - loginview and Community members list
image

image

### PR DESCRIPTION
**Pull request by endulab**
Fixes #7284

Fix icons on lists: 
1. LoginView accounts 
2. Community members list.

### Screenshot of functionality (including design for comparison)

image

image

🍺

### CODE REVIEW

**Comment by endulab** [comment]
@alexandraB99 please test :)

**Review by alexandraB99 — APPROVED** [review]
tested

**Comment by caybro** [comment]
@endulab does this also fix https://github.com/status-im/status-desktop/issues/7323?

**Review by caybro — APPROVED** [review]
LGTM

**Comment by endulab** [comment]
> #7323

@caybro yes.

**Pull request merged**
