### PR TITLE
fix(community): Tabs don't look clickable on the Members community page

### LINKED ISSUE #6787: Tabs don't look clickable on the Members community page
# Bug Report

## Steps to reproduce
1. Create a community with some members
2. Open the community
3. Click 'Manage community'
4. Ban any member
5. Hover over the tab 'Banned' and click it
6. Hover over the 'All Members' tab

#### Expected behavior
The cursor is changing its view to a hand (as it's hovering a clickable element)
#### Actual behavior
The cursor is not changing its view to a hand (as it's hovering over a clickable element)
image

### Additional Information

- Status desktop version: https://github.com/status-im/status-desktop/pull/6280
- Operating System: macOS Monterey

### PR DESCRIPTION
**Pull request by micieslak**
### What does the PR do

Fixes #6787
Updated StatusQ fixes problem with cursor in StatusTabButton

### Affected areas

StatusQ

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://user-images.githubusercontent.com/20650004/185142344-f1941464-f475-4d1b-8ff2-9358bdbe3cf1.mp4

### CODE REVIEW

**Review by caybro — APPROVED** [review]
LGTM

...but they still look "disabled" if you ask me :) Are you sure the inactive tab button color is the correct one? I can't tell much difference between disabled and inactive

**Comment by micieslak** [comment]
> LGTM
> 
> ...but they still look "disabled" if you ask me :) Are you sure the inactive tab button color is the correct one? I can't tell much difference between disabled and inactive

**Comment by micieslak** [comment]
> LGTM
> 
> ...but they still look "disabled" if you ask me :) Are you sure the inactive tab button color is the correct one? I can't tell much difference between disabled and inactive

The issue from the ticket is solved, cursor changes works as expected. When it comes to other ui adjustments I think could be handled separately if sth is wrong. Btw, I cannot find figma designs for that.

**Comment by caybro** [comment]
> > LGTM
> > ...but they still look "disabled" if you ask me :) Are you sure the inactive tab button color is the correct one? I can't tell much difference between disabled and inactive
> 
> The issue from the ticket is solved, cursor changes works as expected. When it comes to other ui adjustments I think could be handled separately if sth is wrong. Btw, I cannot find figma designs for that.

Yeah sure, I know it's unrelated

**Pull request merged**
