### PR TITLE
fix:  Don't quit the app when clicking on "x" and Enable closing the app with CMD + W

### LINKED ISSUE #1694: Don't quit the app when clicking on "x" and Enable closing the app with CMD + W
Currently we quit the app when clicking on the "x" we should just close it and let it run. This is the expected behaviour on MacOS.
Screen_Shot_2021-01-19_at_13_49_46

CMD + W (Close window) shortcut is not working on MacOS. The expected behaviour is to close the app (not quit)

So when I click on "x" or hit CMD + W the app should close but still "live" the the app bar
Screen Shot 2021-01-19 at 13 49 53

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #1694

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Doesn't that mean that the app can never be terminated apart from shutting down the process?

Either way, I think this needs to be a setting. I personally hate when apps don't shut down when clicking the `X` and I know I'm not alone

**Comment by iurimatias** [comment]
shouldn't it be Q instead of W?

**Comment by simonricoo** [comment]
So this is only for MacOS. Here is the expacted behaviour:
Window icons:
"X" = is closing the app (not quitting)
Minimalize icon = minimalizing the app
https://user-images.githubusercontent.com/52249767/107642560-56502b00-6c75-11eb-864f-1f14ea736255.mov

Shortcuts:
CMD+W = close app
CMD+H= hide the app
CMD+Q = Quit the app

https://user-images.githubusercontent.com/52249767/107642878-bba41c00-6c75-11eb-9c8d-970283fbb20b.mov

**Comment by simonricoo** [comment]
Tested the latest master, the app can't be opened after I close it with "x"


https://user-images.githubusercontent.com/52249767/108838278-b8912000-75d3-11eb-824f-5aecb45c7381.mov

**Pull request merged**
