### PR TITLE
feat(@desktop/chat): editing message in markdown mode

### LINKED ISSUE #3270: UI: editing a message to deal with original markdown input, not rich text
Needed by https://github.com/status-im/status-desktop/issues/1368

### PR DESCRIPTION
**Pull request by pinebit**
Fixes #3270 as a new feature and implements #1368

Requires DOtherSide: https://github.com/status-im/dotherside/pull/46

Previously: when a user was editing a sent message, it dealt with styled (html) text, so it was impossible to fix MD tags.
Now: when the user is editing a message, the source markdown markup is brought to the editor.
Also I fixed `code` styling.

### CODE REVIEW

**Review by richard-ramos — CHANGES_REQUESTED** [review]
Syntax highlighting seems to not be working and "<", ">" are being translated to html entities:
image

**Comment by pinebit** [comment]
> Syntax highlighting seems to not be working and "<", ">" are being translated to html entities:
> image

It is working, but in a different way. Because it is language-agnostic, it slightly improves the code appearance. Look at your screenshot: you may notice the literals have different font style as well as operators. Also, if you add a comment, you will also notice the difference.
Also, the language specified after ``` does not make any effect, so it can not be specified.
As for < and > characters - I will fix this next.

**Comment by pinebit** [comment]
Fixed handling of <, >, & symbols.

**Comment by anastasiyaig** [comment]
@pinebit is it possible to address the representation of the message in ` code ` to push notification? So it wont be displayed like this? 

Screenshot 2021-09-07 at 13 55 58

**Comment by pinebit** [comment]
> @pinebit is it possible to address the representation of the message in `code` to push notification? So it wont be displayed like this?
> 
> Screenshot 2021-09-07 at 13 55 58

I think this is impossible, because if every app will be making it rich-text, then all notifications area will become a visual mess.

**Pull request merged**
