### PR TITLE
fix(StoreKeyChainConfirmationPopup): Show dialog after successful login

### PR DESCRIPTION
**Pull request by borismelnik**
Closes: #3638

### CODE REVIEW

**Comment by iurimatias** [comment]
@saledjenic @anastasiyaig @borismelnik what shall we do with this PR?

**Comment by anastasiyaig** [comment]
lets close it and re-introduce again if needed when we are finish refactoring completely.

**Comment by saledjenic** [comment]
@iurimatias since we completely changed the logic behind login/onboarding part (which also includes "store to Keychain" feature), during refactor of that part, this is not a relevant issue any more. You can freely close/delete it.

**Comment by borismelnik** [comment]
Done in `base_bc`

**Pull request closed without merging**
