### PR TITLE
fix(gif/emoji popup): pre-focus the search field

### LINKED ISSUE #6165: selecting the emoji or gif selector should automatically focus on the text input
### Description

Screen Shot 2022-06-20 at 3 15 00 PM

### Acceptance Criteria

- [x] opening the emoji selector should automatically focus cursor on the text input
- [x] opening the gif selector should automatically focus cursor on the text input

### PR DESCRIPTION
**Pull request by caybro**
Close #6165 

### What does the PR do

Automatically pre-focus the search field in the gif and emoji popups upon opening them

### Affected areas

Chat

### Screenshot of functionality
[Záznam obrazovky z 5.7.2022 09:37:17.webm](https://user-images.githubusercontent.com/5377645/177275436-7b9bae5b-2243-4603-83b1-b260d5d76bf9.webm)

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]
LFTM :)

**Review by noeliaSD — APPROVED** [review]
Nice!!

**Comment by caybro** [comment]
@Khushboo-dev-cpp can you pls give it a test? :) thanks in advance

**Comment by noeliaSD** [comment]
> @Khushboo-dev-cpp can you pls give it a test? :) thanks in advance

And tested!!

**Pull request merged**
