### PR TITLE
fix(Profile): Added menu to remove profile image

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/status-im/status-desktop/issues/5921

### What does the PR do

1. Removed old unused files
2. Added menu to remove profile image

### Affected areas

Profile settings

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it
This doesn't actually have designs. I discuess with John to first implement it the way I see it, then decide if it's ok.
But I was reffering to this design: https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=1116%3A108254

Снимок экрана 2022-08-08 в 00 00 11

https://user-images.githubusercontent.com/25482501/183359849-a07bf978-0a18-4ef7-b169-63a50c825967.mov

### CODE REVIEW

**Review by stefandunca — APPROVED** [review]
Looks great. Nice that you also cleaned up the old code.

**Review by caybro — APPROVED** [review]
Nice

**Comment by anastasiyaig** [comment]
@igor-sirotin  I set up a profile image during onboarding and it did not appear in the settings, did u see that as well?

Screenshot 2022-08-08 at 17 48 40

**Review by osmaczko — APPROVED** [review]

**Comment by saledjenic** [comment]
> @igor-sirotin I set up a profile image during onboarding and it did not appear in the settings, did u see that as well?

Just to jump in, it was working after I introduced keycard flow, so must be something recently changed.

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
