### PR TITLE
fix(general): Ignore invalid HTML user input

### PR DESCRIPTION
**Pull request by stefandunca**
### Fixes: #4961

Fix malformed user input for:
- [x] Browser favorite entries
- [x] Browser Tabs
- [x] Nickname entry; filters the available characters
  - [x] depends on merging [StatusQ PR #576](https://github.com/status-im/StatusQ/pull/576)
- [x] Sanitize browser home page input and refactor the dialog using StatusQ controls
  - Migrate to StatusQ
  - Partial redesign of browser settings (layout can be reused in the final implementation)
- [x] Sanitize Favorites list in the default homepage
- Avoiding length limitation by enter key is not reproducible anymore
- Add contact option is not available anymore
- [x] Saved Addresses
- [x] Wallet Account Names
- [x] Communities name and description

### Affected areas
Browser, contacts

### Screenshot of functionality

Nickname editor popup simplified with the new StatusQ.StatusInput
image

Browser with limited and sanitized input
fix_malformed_favorite_entries

image

Tab with sanitized HTM content
image

Homepage StatusQ
image

Homepage with new designs layout and validation
image

Wallet Account Names

Screenshot 2022-03-24 164326
Screenshot 2022-03-24 164507
Screenshot 2022-03-24 164556

Screenshot 2022-03-24 164642
Screenshot 2022-03-24 164725
Screenshot 2022-03-24 165229

Saved Address

image

### CODE REVIEW

**Review by Khushboo-dev-cpp — APPROVED** [review]
LGTM :)

**Comment by elina2015** [comment]
@stefandunca Could you kindly ping me when the issue can be tested?

**Comment by stefandunca** [comment]
> @stefandunca Could you kindly ping me when the issue can be tested?

I fixed all the leftovers, please have a look

**Comment by iurimatias** [comment]
@stefandunca @elina2015 is this still WIP? can it be tested/merged?

**Comment by stefandunca** [comment]
> @stefandunca @elina2015 is this still WIP? can it be tested/merged?

It is ready to be tested. @elina2015 please have a look

**Comment by elina2015** [comment]
@stefandunca hey, I tested it in the test run https://ethstatus.testrail.net/index.php?/runs/view/8825&group_by=cases:section_id&group_order=asc, but see the reviewer in the curremt PR is @abhi-status.

**Review by elina2015 — APPROVED** [review]

**Pull request merged**
