### PR TITLE
feat(@desktop/wallet): Adapt to new SendModal Design

### PR DESCRIPTION
**Pull request by Khushboo-dev-cpp**
StatusQ PR :https://github.com/status-im/StatusQ/pull/595

fixes https://github.com/status-im/status-desktop/issues/5040

### What does the PR do

This PR aims at adapting the SendModal to the new design  https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?node-id=3014%3A175789

However many things are not exactly as the design for example -
1. Modal look
2. Floating buttons behaviour for account selection
3. The saved address look and feel in design are not supported yet and need to check if this support should be added in StatusQ
4. The recent addresses list look and feel not exactly like design
5. There is a new asset selector design and if its final needs to adapted in StatusQ first
6. The Simple/Advanced/Custom parts are not implemented yet
7. Suggested fees functionality needs to be implemented before we can show Slow, Optimal and Fast modes
8. The send to ENS flow is now clear, for that reason we are using "RecepientSelector" and not the new StatusInput. Need to use StatusInput after flow is finalized.

### Affected areas

Wallet, Browser (sendModal related parts)

### Screenshot of functionality
https://user-images.githubusercontent.com/60327365/159554772-178d3b87-d765-4c24-9fb9-b95220f0ec3a.mov

### CODE REVIEW

**Review by alaibe — COMMENTED** [review]
Code LGTM, a question regarding the feature, do we lost the way to set the gas ?

**Comment by Khushboo-dev-cpp** [comment]
> Code LGTM, a question regarding the feature, do we lost the way to set the gas ?

Hey no if you scroll further you will the see the same old gas option. Attaching it in a new video here.


https://user-images.githubusercontent.com/60327365/159666535-cfb6b994-834c-4f16-98de-eabc173788a8.mov

**Review by alaibe — APPROVED** [review]

**Review by iurimatias — CHANGES_REQUESTED** [review]
I get this in my monitor

Screen Shot 2022-03-23 at 5 36 34 PM

**Comment by Khushboo-dev-cpp** [comment]
> I get this in my monitor
> 
> Screen Shot 2022-03-23 at 5 36 34 PM

Woaaah, let me check why

**Comment by Khushboo-dev-cpp** [comment]
> > I get this in my monitor
> > Screen Shot 2022-03-23 at 5 36 34 PM
> 
> Woaaah!

Fixed now :)

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
