### PR TITLE
fix(LoginView): add button to navigate to import existing key screen

### PR DESCRIPTION
**Pull request by PascalPrecht**
Screenshot from 2022-05-11 16-44-29

### CODE REVIEW

**Review by jrainville — CHANGES_REQUESTED** [review]
Nice. The only thing is we discussed that the "Generate new account" button should be renamed to something like "Add new account" and go to this screen https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1194%3A319706

**Comment by PascalPrecht** [comment]
@jrainville updated the button label. The "add existing" button already takes you to that screen. It doesn't offer keycard options though (I assume those aren't implemented yet)

**Comment by jrainville** [comment]
@PascalPrecht thanks for changing the label. The navigation should change to this page however: https://www.figma.com/file/17fc13UBFvInrLgNUKJJg5/Kuba%E2%8E%9CDesktop?node-id=1042%3A300545

**Comment by John-44** [comment]
Following our discussion of these options at the desktop UI meeting today:

- How about adjusting the copy for these two options to be "Add a new user" and "Add existing Status user"

- If a user clicks on "Add a new user" they should be taken to this screen 
2022-05-11 18_23_24-Kuba⎜Desktop – Figma
 
- If a user clicks on "Add existing Status user" they should be taken to this screen 
2022-05-11 18_24_09-Kuba⎜Desktop – Figma

Thoughts?

**Comment by PascalPrecht** [comment]
@John-44 @jrainville addressed all comments!

**Review by jrainville — APPROVED** [review]

**Review by iurimatias — APPROVED** [review]
Screen Shot 2022-05-12 at 12 18 44 PM

**Pull request merged**
