### PR TITLE
feat: SortFilterProxyModel

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Great work dude.

I'll add a QA label so we can test it first to make sure the list still behave well

**Comment by anastasiyaig** [comment]
what i've noticed in comparison to master from yesterday is when u are sending messages in a chat real quick , they seem to appear very slow , especially in the sender ui. In order to reproduce this, just send random messages in a group chat real quick and check how do they appear on another status instance -> as a result, the UI does show only a few first inputs and they stops showing the messages at all, like it is still in a queue

**this PR:**


https://user-images.githubusercontent.com/82375995/122576909-e276c280-d05a-11eb-9d86-f6196cd5bff6.mov

**master:** 


https://user-images.githubusercontent.com/82375995/122577033-01755480-d05b-11eb-88ae-70d9bb8f6b86.mov

@richard-ramos do u think the changes could impact the performance?

**Comment by richard-ramos** [comment]
hmmm this is weird. I do not see a noticieable difference between both this PR and master. Both seem to have the same slow behavior for group messages

master:

https://user-images.githubusercontent.com/1106587/122583916-bdb52780-d027-11eb-90be-8fc4274966a4.mp4

this PR:

https://user-images.githubusercontent.com/1106587/122583952-c86fbc80-d027-11eb-9288-946794355853.mp4

**Comment by anastasiyaig** [comment]
i double checked that and indeed, there is something wrong with master, which i still should reproduce . Thanks @richard-ramos 

there was no regression noticed in chats functionality

**Pull request merged**
