### PR TITLE
fix(AppNavBar): make navbar buttons render correctly again

### LINKED ISSUE #5949: No icons for settings, wallet, etc.
image

### PR DESCRIPTION
**Pull request by PascalPrecht**
We've introduced a regression in
https://github.com/status-im/status-desktop/commit/9f633f0fcce234dcda9968c71a614d60a9cd55f2
where model data for navbar buttons are malformed, which results in them being rendered
incorrectly (as letter identicons, instead of icon buttons)

The reason this was happening was because the model data for the
navbar buttons was not properly initialized due to a mixed usage of
positioned and named arguments of the `initItem()` APIs in `SectionItem`
models.

Fixes #5949

### CODE REVIEW

**Review by noeliaSD — COMMENTED** [review]
Did you branch from current master? There was another section introduced recently that I cannot see in this `module.nim` file that I think it should also need the fix. It is the `Communities Portal` section --> `conf.COMMUNITIESPORTAL_SECTION_ICON`

**Comment by PascalPrecht** [comment]
Wow good catch @noeliaSD !! Will update

**Review by osmaczko — APPROVED** [review]
What a nasty bug... Maybe we should agree to use named parameters on the caller side to avoid it in the future?

**Review by alaibe — APPROVED** [review]

**Comment by PascalPrecht** [comment]
> What a nasty bug... Maybe we should agree to use named parameters on the caller side to avoid it in the future?

@osmaczko I agree! Either that or not mixing named and unnamed arguments. If those were all unnamed nim wouldn't have compiled because of missing arguments.

**Review by noeliaSD — APPROVED** [review]
Tested!! Great fix!

**Pull request merged**
