### PR TITLE
Feat/group chat adjustments

### PR DESCRIPTION
**Pull request by osmaczko**
closes: https://github.com/status-im/status-desktop/issues/7154
closes: https://github.com/status-im/status-desktop/issues/7155

fixes: https://github.com/status-im/status-desktop/issues/5941
fixes: https://github.com/status-im/status-desktop/issues/7234
fixes: https://github.com/status-im/status-desktop/issues/7235
fixes: https://github.com/status-im/status-desktop/issues/7236
fixes: https://github.com/status-im/status-desktop/issues/7237
fixes: https://github.com/status-im/status-desktop/issues/7238
fixes: https://github.com/status-im/status-desktop/issues/7239
fixes: https://github.com/status-im/status-desktop/issues/7240

### Testing notes:
Now:
- only mutual contacts can be added to the group (either on group creation or later)
- any member has the ability to add its mutual contact to the group
- any member has the ability to change the name, image, and color of the group

Please note there is ongoing work on the same area:
- ~~[images support](https://github.com/status-im/status-desktop/pull/6993)~~
- [tags selector issues](https://github.com/status-im/status-desktop/pull/7057)

If in any doubts please refer to the specs: https://github.com/status-im/feature-specs/blob/3bcd4909d730bea213ad94412ed8e0077a32e7ba/content/raw/chat/group_chat.md

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@osmaczko sorry for delay in testing. I would like to discuss the following scenario here:

1. we have 3 users, user1 , user2 and user3
2. user 1 adds user2 and user3 to contacts of himself (mutual)
3. user2 and user3 are not contacts
4. user1 creates group chat with himself + user2 + user3
5. for user3 the group chat is not shown in chats screen. It will be shown only when i add user2 and user3 to contacts to each other and re-add user3 to group again

Screenshot 2022-09-01 at 14 22 20

is it a bug or any functionality limitation? 

Also (not related probably to current changes) when removing a user from group -> there is no any wording about it (when i add a user, the admin is seeing that such user is added to a group)

**Review by endulab — APPROVED** [review]

**Comment by osmaczko** [comment]
> @osmaczko sorry for delay in testing. I would like to discuss the following scenario here:
> 
> 1. we have 3 users, user1 , user2 and user3
> 2. user 1 adds user2 and user3 to contacts of himself (mutual)
> 3. user2 and user3 are not contacts
> 4. user1 creates group chat with himself + user2 + user3
> 5. for user3 the group chat is not shown in chats screen. It will be shown only when i add user2 and user3 to contacts to each other and re-add user3 to group again

I can't reproduce it. It looks more like mailserver failure - seems the message about group creation was not distributed to user3. Could you please retry?

**Comment by osmaczko** [comment]
@glitchminer I've assigned you directly because I fixed a lot of issues you have recently created related to members selector. Could you please verify the fixes?

**Comment by glitchminer** [comment]
## Issues found

### Bug 7237

#### 1. OPEN Display names not shown when non-admin enters edit mode
Actual

image

---
### Bug 7237

#### 2. OPEN [OBSERVATION] After resizing, horizontal scrollbar on members bar does not adjust until bar is in focus
Actual


#### 3. OPEN [OBSERVATION] Can no longer scroll horizontally using trackpad or horizontal (secondary) scrollwheel
While it is now possible to reach all members of the group, it is no longer possible to do so except for via the new scrollbar.

#### 4. OPEN [OBSERVATION] Not possible to use arrow keys to navigate between members
While it is now possible to reach all members of the group, it is not possible to do so using the keyboard

---
### Bug 7240

#### 5. OPEN [OBSERVATION] When the 20th user is added the user limit message overlaps the remove button of the final pill
Actual


---

@osmaczko, issue 1 appears to need another look. Issues 2 - 5 are observations that I don't have specific requirements on but you may want to see if improvements are needed for them.

**Comment by osmaczko** [comment]
> Issues found

@glitchminer thank you for testing and triggering issues.

AD.1 Fixed, details:
This is a more serious issue that requires significant changes in status-go. Currently, each user advertises its details (display name, image, etc) in certain intervals, that's why one must sometimes wait to see the display name instead of 3 words name. Members selector is not the only place lacking data in that case, see members list on the right and also system message "user A has added...":
image

The fix, for now, is to use 3 words name if the display name is not provided (yet advertised):

image


Clarification: member's pubkey is the only information propagated when adding/removing group members. 3 words name is generated from pubkey, that's why it is always available.
FYI: It is technically possible to make it work as expected, but it requires changes in how we distribute information about group membership in status-go, I've triggered [status-go issue](https://github.com/status-im/status-go/issues/2851) for that.

AD. 6 Good catch, fixed!


Regarding 2 - 5: none of them is trivial to fix and at the same time non of them is critical, I will leave them for priority evaluation.
AD.3 This may be a global issue. I've noticed mouse scroll stopped working for most scroll views in our UI.

**Comment by alexandraB99** [comment]
@osmaczko is https://github.com/status-im/status-desktop/pull/7057 still relevant?

**Comment by glitchminer** [comment]
@osmaczko, 1 and 6 now resolved thanks! 2-5 will be addressed separately. There is 1 outstanding issue ported over from https://github.com/status-im/status-desktop/pull/7057

Added as issue 7: The admin pill should be visible when starting the chat
image

**Comment by alexandraB99** [comment]
> @osmaczko is #7057 still relevant?

@osmaczko sorry wrong link, I meant this one https://github.com/status-im/StatusQ/pull/860

**Comment by osmaczko** [comment]
> > @osmaczko is #7057 still relevant?
> 
> @osmaczko sorry wrong link, I meant this one [status-im/StatusQ#860](https://github.com/status-im/StatusQ/pull/860)

Not relevant, can be closed.

**Comment by osmaczko** [comment]
> @osmaczko, 1 and 6 now resolved thanks! 2-5 will be addressed separately. There is 1 outstanding issue ported over from #7057
> 
> Added as issue 7: The admin pill should be visible when starting the chat image

I can't see how issue 7 resulted from #7057. [This comment](https://github.com/status-im/status-desktop/pull/7057#issuecomment-1240687625) is only clarifying the edit mode of the members selector. Additionally, according to designs, we(ourselves) should not be on the list when creating a new chat (and it makes a lot of sense to me).

CCing: @John-44

**Review by glitchminer — APPROVED** [review]
Tested and approved

**Pull request merged**
