### PR TITLE
fix: ensure Nim recompile after make update

### LINKED ISSUE #3639: Running make after changing status-lib doesn't recompile
After making a change in status-lib, doing a make doesn't recompile the app

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
These changes are a follow-up to #3582.

Also support `REBUILD_NIM=true` and `REBUILD_UI=true` variables so that it's possible to ensure a rebuild for the next invocation of `make` or `make run`.

Dev docs have been updated: https://hackmd.io/OtFjDnH6QtOl3K65fKKEGg?view#3-Build-and-run-the-app

Also adjust run targets so that e.g. `make -j16 run` works correctly.

Closes #3639.

### CODE REVIEW

**Comment by emizzle** [comment]
Continuing on from https://github.com/status-im/status-desktop/issues/3639#issuecomment-924233420 in #3639, would we maybe be able to add a `--submodules` option for `make`, ie `make --submodules` that touches the `.update.timestamp` file? I also modify files directly inside of `vendor/` (and `ui/StatusQ` and now `spellchecking/`).

Just double-checking, if no `status-desktop/../*.nim` files are modified, running `make run` won't recompile any nim files, correct? I'm asking because when modifying only QML files, any compilation of nim files could slow down `make run`.

**Comment by michaelsbradleyjr** [comment]
> Continuing on from [#3639 (comment)](https://github.com/status-im/status-desktop/issues/3639#issuecomment-924233420), would we maybe be able to add a `--submodules` option for `make`, ie `make --submodules` that touches the `.update.timestamp` file? I also modify files directly inside of `vendor/` (and `ui/StatusQ` and now `spellchecking/`).

Ah, very nice idea! While adding a `--submodules` option isn't doable (to my understanding), we could have a `REBUILD_NIM` variable that works in conjunction with `.update.timestamps` being added to `NIM_SOURCES`.

So if you're making changes to `.nim` sources in *any* submodule, you would do:
```
$ make REBUILD_NIM=true run
```
And a Nim recompile would be ensured, whether you've made changes to `status-desktop/src/*.nim` or `status-desktop/vendor/*.nim`, or both.

When using ctrl+r or up-arrow to replay command history, that shouldn't impose much burden. Of course, it should be documented in a comment in the Makefile and in dev docs for status-desktop.

Thoughts?

> Just double-checking, if no `status-desktop/../*.nim` files are modified, running `make run` won't recompile any nim files, correct? I'm asking because when modifying only QML files, any compilation of nim files could slow down `make run`.

That's correct.

**Comment by emizzle** [comment]
> So if you're making changes to `.nim` sources in *any* submodule, you would do:
> ```
> $ make REBUILD_NIM=true run
> ```
Yes, i like this idea!

**Review by pinebit — APPROVED** [review]

**Comment by michaelsbradleyjr** [comment]
I added *don't merge yet* label because I'm in the process of adding the `REBUILD_NIM` variable as proposed in https://github.com/status-im/status-desktop/pull/3652#issuecomment-924506408.

**Comment by michaelsbradleyjr** [comment]
I've implemented support for `REBUILD_NIM=true` and `REBUILD_UI=true`. I left explanatory comments in the Makefile and updated dev docs (see link in the updated PR description).

**Review by alaibe — APPROVED** [review]
Well done!

**Review by emizzle — APPROVED** [review]

**Pull request merged**
