### PR TITLE
Make the getENSName calls async

### LINKED ISSUE #16086: Login to the app takes forever in master
# Bug Report

## Description

image

## Steps to reproduce

Found with autotests. new accounts could not be created because clicking Start using status button hangs the app for more than 15 seconds

https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/496/allure/#suites/db36b027265858e30e3f42c2f7edffa8/52a4187c811bcc96/

#### Expected behavior

Login is smooth

#### Actual behavior

Cant basically create new account with autotests

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/nightly/468/, commit 3c18ac0f7a3061f74e3de6b8a991fad29d2cf561
- Operating System: Linux
- Geth log 
[data_attachments_f3e8c3cd44694d20.txt](https://github.com/user-attachments/files/16595862/data_attachments_f3e8c3cd44694d20.txt)
- Application log 
[data_attachments_476e2afed4a0f555.txt](https://github.com/user-attachments/files/16595869/data_attachments_476e2afed4a0f555.txt)

**NOTE 1:** it was not the case for build on 10-Aug-2024 https://ci.status.im/job/status-desktop/job/nightly/466/ which was the commit `9acf723ddcec770956d173d8f01a5da38c95e7d8`
**NOTE 2:** it is not the case for release branch of 2.30.x , tests are smooth there https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F2.30.x/48/

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #16086

Work by me and @saledjenic

### CODE REVIEW

**Comment by saledjenic** [comment]
@jrainville I updated a bit this PR, the first commit on top of your changes is about resolving the ens name on the app start in an async way. The second commit is about resolving the ens name when adding new accounts in an async way, which speeds up adding new accounts process.

Once you guys review the changes, we can squash all that in a single commit before merging it.

**Review by alaibe — APPROVED** [review]

**Review by Khushboo-dev-cpp — APPROVED** [review]

**Comment by jrainville** [comment]
I'll merge when @anastasiyaig confirms that it fixed the issue (either in the tests or manually)

**Comment by anastasiyaig** [comment]
i am trying to figure why tests are failing :/

**Comment by jrainville** [comment]
> i am trying to figure why tests are failing :/

It's on top of release, so maybe something missing in the release branch?

**Comment by anastasiyaig** [comment]
@jrainville no its actually not related to that. there are some known issues we did not yet fix. One looks to be unfixable :D (we need to move tests to docker) and one is i am trying to understand why the heck second check box on login is not being checked from time to time. You can force merge. 
i also ran full run for this branch here https://ci.status.im/job/status-desktop/job/e2e/job/manual/2461/allure/#suites/c903afa10bc80eef63bd789fadecf5ad/2a53daaf282020b8/ , even tests failed i dont really see the initial issue with application stuck on login

**Pull request merged**
