### PR TITLE
fix(keycard): unable to import account from keycard

### PR DESCRIPTION
**Pull request by saledjenic**
Handling for recovering Status profile for Linux updated since we don't use biometrics for Linux and that requires slightly different flow.

Closes: #14673

### CODE REVIEW

**Comment by saledjenic** [comment]
@iurimatias it would be good for this one to get into the next release, cause it unblocks users on Linux to recover the Status profile using a keycard.

**Review by jakubgs — APPROVED** [review]
I can't really review the code changes as I know almost nothing about the Nim codebase.

I tried the PR build and the `Login with Keycard` button appears to do nothing right now. But `Enter a seed phrase` below it works fine.

**Comment by saledjenic** [comment]
This is how it looks for me when running this PR on Mac, while setting `const IS_MACOS* = false` to simulate Linux behavior:

https://github.com/status-im/status-desktop/assets/86303051/456e4185-c8f7-4144-94cc-65cd346adb59

**Comment by saledjenic** [comment]
> I can't really review the code changes as I know almost nothing about the Nim codebase.
> 
> I tried the PR build and the `Login with Keycard` button appears to do nothing right now. But `Enter a seed phrase` below it works fine.

@jakubgs I am pretty sure that on your side because of something keycard lib doesn't respond on the recovering flow and we cannot move further without getting a response. Why that's happening I am not sure, it's up to low-level communication between keycard lib and the reader (keycard) itself.

**Comment by saledjenic** [comment]
@anastasiyaig @glitchminer could you somehow test this PR on Linux, please?

**Comment by jakubgs** [comment]
>I am pretty sure that on your side because of something keycard lib doesn't respond on the recovering flow and we cannot move further without getting a response.

I just just tested current build of `master`(https://github.com/status-im/status-desktop/commit/d70f2dcf238ef442100fb2dcf1da69c9db86b271) and it gets blocked at PIN entry, but I re-tested the [PR build](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/package/job/PR-14721/1/) and it works, I got past the PIN entry screen and successfully logged into the app:

image

Not sure what that issue with `Login with Keycard` button before was about. Bit flaky.

Thanks for the fix.

**Pull request merged**
