### PR TITLE
chore: bump status-go

### LINKED ISSUE #14047: Crash on editing display name field
# Bug Report

## Description

Entering a new character in the display name field causes the app to crash.

```
DBG 2024-03-19 22:33:02.383+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-03-19 22:33:04.693+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_speedupArchivesImport
DBG 2024-03-19 22:33:14.383+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_slowdownArchivesImport
DBG 2024-03-19 22:33:17.374+00:00 NewBE_callPrivateRPC                       topics="rpc" tid=65807806 file=core.nim:27 rpc_method=wakuext_isDisplayNameDupeOfCommunityMember
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Segmentation fault: 11
```

## Steps to reproduce

Open profile settings, attempt to add a character to the display name.

App crashes.

Notes: As it seems relevant to `wakuext_isDisplayNameDupeOfCommunityMember`, the account is a member of 6 communities (previously could have been ~20+ but they didn't show up after restore). 

### Additional Information

- Status desktop version: Master
- Operating System: Mac

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #14047
Waits https://github.com/status-im/status-go/pull/4956

Fix crash if it's not possible to fetch community member as a contact

https://github.com/status-im/status-desktop/assets/2522130/ef4e503b-b29f-46e0-bf75-ee4030d5f6a1

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
@glitchminer can you please try this brach, i can't reproduce this crash locally

**Review by jrainville — APPROVED** [review]

**Review by kounkou — APPROVED** [review]

**Comment by anastasiyaig** [comment]
we need to resolve conflicts here and cherry pick to release branch @jrainville

**Comment by jrainville** [comment]
@MishkaRogachev can you do it please.

I think Mishka also had issues reproducing. Can @glitchminer test it to see if it worked for him

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev can you do it please.
> 
> I think Mishka also had issues reproducing. Can @glitchminer test it to see if it worked for him

sure, i'll do it after testing if it works

**Comment by glitchminer** [comment]
Tested OK, bug is no longer reproducible.

**Pull request merged**
