### PR TITLE
fix(@desktop/timeline): render message age instead of message time

### LINKED ISSUE #2918: Message date in 'status updates'
In 'status updates', messages are shown with today's date rather than the date the message was sent https://www.loom.com/share/e654a670a0a44802b99a03c42284fb7c

### Current
Message shows today's date

### Expected
~~Message shows date when message was sent~~ EDIT: Message is shown with `Age` as in [design file](https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1918%3A13058) (thanks @pinebit )

### PR DESCRIPTION
**Pull request by pinebit**
In according with Figma, we need to render messages' age instead of time/date.
https://www.figma.com/file/Zz6KMBxwrB0l2NPgsjnPjq/%F0%9F%91%A4-Profile%E2%8E%9CDesktop?node-id=1918%3A13058

Fixes #2918

### CODE REVIEW

**Comment by alaibe** [comment]
A question regarding this feature: if I leave a chat open for a long time, imagine 24h, would the date being displayed change or I will always say: `Now` ?

**Review by jrainville — APPROVED** [review]

**Comment by jrainville** [comment]
> A question regarding this feature: if I leave a chat open for a long time, imagine 24h, would the date being displayed change or It will always say: Now ?

I think it will stay on Now, but changing "page" and coming back should re-calculate

**Comment by pinebit** [comment]
> > A question regarding this feature: if I leave a chat open for a long time, imagine 24h, would the date being displayed change or It will always say: Now ?
> 
> I think it will stay on Now, but changing "page" and coming back should re-calculate

correct... I think we need a timer attached to each delegate to update the values. I will do this next.

**Comment by jrainville** [comment]
>  I think we need a timer attached to each delegate to update the values

Would that be overkill? I fear it might consume too much memory if we have a lot of messages

**Comment by pinebit** [comment]
> > I think we need a timer attached to each delegate to update the values
> 
> Would that be overkill? I fear it might consume too much memory if we have a lot of messages

A good way to do this is to update items in QAbstractListModel. Given that most of the items are rendered as Days/Hours, they won't trigger `update()` signal. Only the fresh items will be triggering updates - those are <1H.
However, I will be thinking first if it is possible to implement this in pure QML with a single time.

**Comment by pinebit** [comment]
@jrainville @alaibe please check the latest commit. It works.

**Review by alaibe — APPROVED** [review]
If I understand it correctly, that looks quite cool! no idea you could do that that way :)

**Review by jrainville — APPROVED** [review]

**Comment by iurimatias** [comment]
@pinebit nice catch verifying the real intended behaviour

**Pull request merged**
