### PR TITLE
10987 assets deployment

### PR DESCRIPTION
**Pull request by endulab**
### What does the PR do

Handling assets deployment (w/o burn and mint functionality)

Related status-go pr: https://github.com/status-im/status-go/pull/3636/files

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/61889657/442fa0e3-a28e-4d91-8e38-14f8f2147967

### CODE REVIEW

**Review by noeliaSD — APPROVED** [review]
LGTM!

**Comment by anastasiyaig** [comment]
@endulab so far there are 2 observations (discussed in DM):
- no `Mining in progress` status when transaction is actually in progress
- Decimal points value is always 2 on UI no matter of value entered when minting asset 

Screenshot 2023-06-22 at 17 21 13

**Comment by endulab** [comment]
@anastasiyaig I fixed the problem with decimals.
Mining in progress status works correctly. I am attaching a demo.

https://github.com/status-im/status-desktop/assets/61889657/d6ab6784-064d-48b7-99d9-5d4d244d560e

**Comment by anastasiyaig** [comment]
@endulab today i found this weird error on Optimism Goerli:

```
ERR 2023-06-26 11:51:18.738+03:00 rpc response error                         topics="rpc" tid=2173099 file=core.nim:36 err="\nstatus-go error [methodName:collectibles_estimateMintTo, code:-32000, message:execution reverted ]\n"
```

Screenshot 2023-06-26 at 11 43 28

the error does not make a lot of sense because it says execution reverted  which is usually means out of gas , but the transaction for airdropping was not initiated yet (it appeared on the stage of getting txn fees). Mind checking that for me? This is the token contract i tried to interact with https://goerli-optimism.etherscan.io/address/0xd70820204d5b7183ba0da739aee1fcc1b67474c7

**Comment by anastasiyaig** [comment]
turned out that airdrop and remote destruct will be done in another tickets for Assets . Then lets merge this one!

**Review by anastasiyaig — APPROVED** [review]

**Pull request merged**
