### PR TITLE
Inform about missing encryption key

### PR DESCRIPTION
**Pull request by osmaczko**
closes: https://github.com/status-im/status-desktop/issues/15064
status-go PR: https://github.com/status-im/status-go/pull/5438

https://github.com/status-im/status-desktop/assets/33099791/e1dc84b4-14b6-4a78-b34b-af501016411c

**NOTE**
I simulated missing encryption key by modifying control node client to send encryption keys with 30s delay.

### CODE REVIEW

**Comment by osmaczko** [comment]
> Nice work!
> 
> I think we can open a new issue now so that we can still show the channel, but disable the input and put a message on top of the member list. The reasoning is that this missing encryption keys issue can happen when there are already messages in a channel and you might want to see them (you do have access, you just are missing the encryption keys)

That makes sense, yes. The only problem is that members will not be able to receive new messages, and this may be confusing.

**Comment by jrainville** [comment]
> That makes sense, yes. The only problem is that members will not be able to receive new messages, and this may be confusing.

Yeah, that's why we must make the message as clear as possible. So in the Input, we can disable it and say "Waiting for encryption keys"
and in the member list we can say "waiting for encryption keys. Until you receive them, you will not receive new messages (but they can be fetched later on)" or  something like that

**Review by endulab — APPROVED** [review]

**Review by MishkaRogachev — APPROVED** [review]

**Comment by osmaczko** [comment]
@status-im/desktop-qa "May I kindly ask for regression tests covering scenarios involving the community members list?

**Comment by anastasiyaig** [comment]
yes sure @osmaczko , maybe for a test you could temporarily commit a hack for the store node to send updates with delay?

**Comment by osmaczko** [comment]
> yes sure @osmaczko , maybe for a test you could temporarily commit a hack for the store node to send updates with delay?

Thanks. I would just opt for regression tests. Don't want to commit the hack as it may affect other areas, if that's ok.

**Comment by anastasiyaig** [comment]
understood, sure, no problem

**Review by lukaszso — APPROVED** [review]
Tested, results are available in this report: https://ethstatus.testrail.net/index.php?/reports/view/46

In my experience changes were visible in control node first, the regular member had to wait for 1-3 minutes to see them.

**Pull request merged**
