### PR TITLE
Implement redesign of empty chat

### LINKED ISSUE #2384: redesign empty state for a first time chat
see design at https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=70%3A0

the profile picture and message should be on the top, font is different etc..

current:

desired:

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #2384

Adds the "Add to Contact" banner at the top if it's a 1 to 1 chat and the user is not a contact. You can hide it. The banner will come back if you close the app and reopen. It can be changed to be in the settings if wanted.

Positions the chat identifier at the top of the screen when it's empty (or not enough content). We used to have it like that before too, but when we changed the ListView to BottomToTop, we lost it. 
To fake that behaviour, I added a `header` that is invisible and just adds a spacer. I added a big comment in the ChatMessages file to explain how and why it works.

image

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@jrainville 

can we somehow fix the margin at the top (a lot of space under the name and name) and message appearance?

**Comment by jrainville** [comment]
For the top margin, I followed the design. Maybe @simonricoo has an idea or an opinion?

As for the bottom margin, I don't think we want to fix that? Because it was already like on your right screenshot, but the design seems to want it to come from the top now

**Comment by anastasiyaig** [comment]
@simonricoo could you please take a look? If it is matching our expectations - then okay )

**Comment by simonricoo** [comment]
Looks good to me, @jrainville is right in both cases so please merge it :)

**Pull request merged**
