### PR TITLE
test(suite_settings): Feature review

### PR DESCRIPTION
**Pull request by glitchminer**
### What does the PR do
Feature review

### Affected areas
`suite_settings`

### CODE REVIEW

**Comment by iurimatias** [comment]
@glitchminer @noeliaSD is this PR still applicable?

**Comment by iurimatias** [comment]
cc: @anastasiyaig

**Review by noeliaSD — CHANGES_REQUESTED** [review]
Suggestion:
- Since this is open for long, I suggest to firstly do a rebase, and then address the comments.
- As a general comment, if we want to integrate it, we need to update the corresponding `steps.py`.

**Comment by glitchminer** [comment]
I've discussed with @noeliaSD and will close this PR due to age. If the changes are still required it will be simpler to apply them starting from the current state.

**Pull request closed without merging**
