### PR TITLE
feat(@desktop/wallet): implement detection of ETH Bridge transactions

### PR DESCRIPTION
**Pull request by dlipicar**
Part of #10791
status-go part: https://github.com/status-im/status-go/pull/3706

### What does the PR do

Bumps status-go to include ETH Bridge transaction detection.

Nim and UI work is pending, this only ensures Bridge transactions are added to the DB.

### CODE REVIEW

**Comment by anastasiyaig** [comment]
@dlipicar i tried to launch the build and i am getting this when i try to login with new account:

```
anastasiya@Anastasiyas-MacBook-Pro MacOS % ./nim_status_client -d:~/data/PR1
Experimental support for Apple Silicon
INFO [07-10|10:48:05.590] Status backend initialized               backend=geth version=0.161.2 commit=069ab16c4 IpfsGatewayURL=https://ipfs.status.im/
INF 2023-07-10 10:48:05.973+03:00 Version: 0.9.90                            topics="status-app" tid=1085039 file=nim_status_client.nim:182
INF 2023-07-10 10:48:05.974+03:00 Commit: 375bd9073                          topics="status-app" tid=1085039 file=nim_status_client.nim:183
INF 2023-07-10 10:48:05.974+03:00 Current date:                              topics="status-app" tid=1085039 file=nim_status_client.nim:184 currentDateTime=2023-07-10T10:48:05+03:00
INF 2023-07-10 10:48:05.974+03:00 starting application controller...         topics="status-app" tid=1085039 file=nim_status_client.nim:186
INF 2023-07-10 10:48:07.389+03:00 starting application...                    topics="status-app" tid=1085039 file=nim_status_client.nim:189
WRN 2023-07-10 10:48:07.395+03:00 Error decoding signal                      topics="signals-manager" tid=1085039 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
ERR 2023-07-10 10:48:43.088+03:00 unsupported waku version                   topics="node-config-service" tid=1085039 file=service.nim:95
Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:32: ReferenceError: userProfile is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:32, )
Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:23: ReferenceError: walletSectionAssets is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:23, )
Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:21: ReferenceError: walletSectionOverview is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:21, )
Warning: qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12: ReferenceError: mainModule is not defined (qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12, )
Warning: Populating font family aliases took 90 ms. Replace uses of missing font family "Inter" with one that exists to avoid this cost.  (:0, )
```

I tried the same in master and i was able to create new account. Could u please check on this and rebase if needed? Thank u!

**Comment by dlipicar** [comment]
> @dlipicar i tried to launch the build and i am getting this when i try to login with new account:
> 
> ```
> anastasiya@Anastasiyas-MacBook-Pro MacOS % ./nim_status_client -d:~/data/PR1
> Experimental support for Apple Silicon
> INFO [07-10|10:48:05.590] Status backend initialized               backend=geth version=0.161.2 commit=069ab16c4 IpfsGatewayURL=https://ipfs.status.im/
> INF 2023-07-10 10:48:05.973+03:00 Version: 0.9.90                            topics="status-app" tid=1085039 file=nim_status_client.nim:182
> INF 2023-07-10 10:48:05.974+03:00 Commit: 375bd9073                          topics="status-app" tid=1085039 file=nim_status_client.nim:183
> INF 2023-07-10 10:48:05.974+03:00 Current date:                              topics="status-app" tid=1085039 file=nim_status_client.nim:184 currentDateTime=2023-07-10T10:48:05+03:00
> INF 2023-07-10 10:48:05.974+03:00 starting application controller...         topics="status-app" tid=1085039 file=nim_status_client.nim:186
> INF 2023-07-10 10:48:07.389+03:00 starting application...                    topics="status-app" tid=1085039 file=nim_status_client.nim:189
> WRN 2023-07-10 10:48:07.395+03:00 Error decoding signal                      topics="signals-manager" tid=1085039 file=signals_manager.nim:48 err="Unknown signal received: mediaserver.started"
> ERR 2023-07-10 10:48:43.088+03:00 unsupported waku version                   topics="node-config-service" tid=1085039 file=service.nim:95
> Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:32: ReferenceError: userProfile is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:32, )
> Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:23: ReferenceError: walletSectionAssets is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:23, )
> Warning: qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:21: ReferenceError: walletSectionOverview is not defined (qrc:/app/AppLayouts/Profile/stores/WalletStore.qml:21, )
> Warning: qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12: ReferenceError: mainModule is not defined (qrc:/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:12, )
> Warning: Populating font family aliases took 90 ms. Replace uses of missing font family "Inter" with one that exists to avoid this cost.  (:0, )
> ```
> 
> I tried the same in master and i was able to create new account. Could u please check on this and rebase if needed? Thank u!

wth, did 0 changes to client-side files. Rebasing, will give it a quick try when the build's ready.

**Comment by anastasiyaig** [comment]
Screenshot 2023-07-10 at 15 33 29

https://explorer.hop.exchange/?transferId=0x3ba3ff43e19333e1cc7a5f83ded54bb97ce0a1d41e71b342c27a32eeeaa03f91

**Review by anastasiyaig — APPROVED** [review]

**Comment by dlipicar** [comment]
Closing, status-go was bumped in `master` already

**Pull request closed without merging**
