### PR TITLE
fix(@desktop): Fix scrolling twitches using ScrollView and Flickable items

### LINKED ISSUE #5781: ScrollView twitches
# Bug Report

## Description

All ScrollViews in the app twitches when flicking over bounds with trackpad (doesn't happen with mouse).

https://user-images.githubusercontent.com/25482501/168774202-b8263f70-8aae-4ac6-9d74-9c3fd33ada40.mov

- Status desktop version: 0.4.0 - 54e2217c9
- Operating System: MacOS 12.3.1

### PR DESCRIPTION
**Pull request by MishkaRogachev**
Close #5781
Depends https://github.com/status-im/StatusQ/pull/766

### What does the PR do

Replace ScrollView and Flickable usages with StatusScrollView 

### Affected areas

Desktop, almost in the all places 

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/2522130/178734565-7b31dd01-40c7-4fe6-a696-683de0508f46.mov

### CODE REVIEW

**Review by caybro — APPROVED** [review]
Nice!

**Comment by MishkaRogachev** [comment]
For QA: for this PR scrolling fixed just in some places, others using ListView should be implemented here: https://github.com/status-im/status-desktop/pull/6456
So here i think we should test that nothing was broken

**Comment by glitchminer** [comment]
### Issues found

#### 
#### Scrolling broken in multiple components

**Settings**
In setting screen, scroll bar is missing and not possible to scroll at all on multiple screens via either trackpad or mouse. Noted on: Messaging; Appearance; Notifications; Advanced; About

**Invite / Public chat side bar**
On the sidebar with invite and public chats, it is not possible to use scrollwheel on mouse but can click and drag scrollbar. 
When using the trackpad, the bounce is removed but there also appears to be some horizontal movement

**Back up seed phrase dialog**
On the back up seed phrase dialog, the text and elements are out of alignment
It is not possible to scroll using scroll wheel but the scroll bar appears and can be dragged.
It is possible to use the trackpad to scroll vertically only, meaning some elements are unreachable.

image

image


#### Test info
Build: StatusIm-Desktop-220714-114245-886358-pr6440
OS: Mac

**Comment by MishkaRogachev** [comment]
@glitchminer thanks, that's very helpful! I'm going to work on it tomorrow.

**Comment by MishkaRogachev** [comment]
@glitchminer we decided to unite this PR with https://github.com/status-im/status-desktop/pull/6456, results would be there

**Comment by MishkaRogachev** [comment]
Continue here: https://github.com/status-im/status-desktop/pull/6456

**Comment by MishkaRogachev** [comment]
@glitchminer issues you have found I resolved here:  https://github.com/status-im/status-desktop/pull/6456

**Pull request closed without merging**
