### PR TITLE
Cherry picks for small fixes to crashes

### PR DESCRIPTION
**Pull request by jrainville**
Just cherry picks of https://github.com/status-im/status-desktop/pull/11999 and https://github.com/status-im/status-desktop/pull/12022

### CODE REVIEW

**Comment by caybro** [comment]
@jrainville https://github.com/status-im/status-desktop/pull/11999 also contained some status-go changes, all up to date?

**Comment by dlipicar** [comment]
> 

I think that's these changes https://github.com/status-im/status-go/pull/3936
They've been in status-go/develop for a while now

**Comment by jrainville** [comment]
Yup like Dario said, the status-go changes were part of master even before they were in the release branch

**Review by caybro — APPROVED** [review]

**Comment by jrainville** [comment]
Not sure why the builds are not triggering :thinking:

**Comment by jrainville** [comment]
Ah there it is! Not sure what took so long

**Comment by jrainville** [comment]
Sorry about that. I'm fixing on the release and cherry-picking here after

**Comment by jrainville** [comment]
Fixed

**Pull request merged**
